### ISSUE TITLE
Any user can grant a role.

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#3772]
Date: 2015-07-20 00:18:55 +0200
From: vera &lt;<vera.matei>&gt;
To:   SQL devs &lt;<bugs-sql>&gt;
Version: 11.19.15 (Oct2014-SP4)
CC:   @njnes

Last updated: 2015-08-28 13:42:07 +0200

## Comment 21027
Date: 2015-07-20 00:18:55 +0200
From: vera &lt;<vera.matei>&gt;

User-Agent:       Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
 Build Identifier: 
 
 A user can grant any role, even if that role was not assigned to him. The user can even grant the role to itself, which gives the user permissions that was not having previously.
 
 Reproducible: Always

## Comment 21029
Date: 2015-07-20 21:41:57 +0200
From: MonetDB Mercurial Repository &lt;<hg>&gt;

Changeset [2b167d2b527d](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=2b167d2b527d)  made by Vera Matei <vera.matei@monetdbsolutions.com> in the MonetDB repo, refers to this bug.
 
 For complete details, see [http//devmonetdborg/hg/MonetDB?cmd=changeset;node=2b167d2b527d](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=http//devmonetdborg/hg/MonetDB?cmd=changeset;node=2b167d2b527d) 
 
 Changeset description:
 
 	Test for bug #3772.

## Comment 21046
Date: 2015-07-22 22:24:01 +0200
From: @njnes

fixed, ie now only monetdb user or role owner, or granted with admin can grant roles

## Comment 21202
Date: 2015-08-28 13:42:07 +0200
From: @sjoerdmullender

Jul2015 has been released.

**Comment by yzchang** [comment]
Reopened this ancient issue, because now the role owner can't grant the role to someone else. See the newly extended test for this Issue [grantRole.Bug-3772.SQL.py](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=b9246c2e6964) @njnes

**Comment by yzchang** [comment]
Fixed in [https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=f0c84cb94a0e](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=f0c84cb94a0e)
