### ISSUE TITLE
Cannot connect to local or networked server with this version - Tableau/Alteryx - but can via earlier version

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#4042]
Date: 2016-07-27 19:02:33 +0200
From: l.beischer
To:   clients devs &lt;<bugs-clients>&gt;
Version: 11.23.7 (Jun2016-SP1)

Last updated: 2016-07-27 19:02:33 +0200

## Comment 22264
Date: 2016-07-27 19:02:33 +0200
From: l.beischer

User-Agent:       Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
 Build Identifier: 
 
 When trying to connect to the latest version of MonetDB programs that use the ODBC drivers to connect cannot find the server - even if running locally (i.e. localhost:50000)
 
 A default message that the ODBC driver cannot find the server specified is given. This problem crashes BOTH: Alteryx (10.6) and Tableau (9.3). However when connecting via dBVisualizer (via java driver) this worked as expected and queries execute.
 
 Un-installing all components of MonetDB and installing Jun2015-SP2 fixes the issue (connections can now be made).
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 1.Install Jun2016-SP1 MonetDB Server + Drivers (Geo doesn't have to be installed but also is part of issue)
 2.Can create tables etc. but not necessary
 3.Install Tableau/Alteryx if necessary
 4.Connect via ODBC Drivers - either using MonetDB DSN (system-created) or via user-defined
 5.Usually crashes Tableau/Alteryx but also gives the error that server cannot be found.
 ### Actual Results:  
 Usually crashes Tableau/Alteryx but also gives the error that server cannot be found.
 
 ### Expected Results:  
 Connected to the database and allowed queries of tables

**Comment by NancyOwens** [comment]
All the identifications of the maxilla are done for the use of the instruments. For sure, the utility of [topcvwritersuk.com/increase-your-competitive-value-in-the-job-market](https://topcvwritersuk.com/increase-your-competitive-value-in-the-job-market/) is increasing day by day for all girls. The boys are fully involved in the market for the attainment of the proficient slots for success.
