### ISSUE TITLE
Prepared statements lost after any error, also in auto commit mode

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6351]
Date: 2017-07-12 11:01:02 +0200
From: @swingbit
To:   SQL devs &lt;<bugs-sql>&gt;
Version: 11.25.23 (Dec2016-SP5)
CC:   martin.van.dinther, @mlkersten, @njnes, @PedroTadim

Last updated: 2020-06-16 09:55:07 +0200

## Comment 25453
Date: 2017-07-12 11:01:02 +0200
From: @swingbit

User-Agent:       Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
 Build Identifier: 
 
 The following behaviour seems not right to me:
 
 sql>prepare select 1;
 execute prepared statement using: EXEC 7(...)
 +---------+--------+-------+--------+-------+--------+
 | type    | digits | scale | schema | table | column |
 +=========+========+=======+========+=======+========+
 | tinyint |      1 |     0 |        | L2    | L2     |
 +---------+--------+-------+--------+-------+--------+
 1 tuple (0.560ms)
 sql>exec 7();
 +------+
 | L2   |
 +======+
 |    1 |
 +------+
 1 tuple (0.301ms)
 sql>exec 7();
 +------+
 | L2   |
 +======+
 |    1 |
 +------+
 1 tuple (0.332ms)
 sql>some error;
 syntax error, unexpected SOME in: "some"
 sql>exec 7();
 EXEC: no prepared statement with id: 7
 sql>
 
 The error discarded the prepared statement.
 I see no reason for that, especially in auto-commit mode. 
 
 
 
 Reproducible: Always
 
 
 
 
 $ mserver5 --version
 MonetDB 5 server v11.25.24 (64-bit, 128-bit integers)
 This is an unreleased version
 Copyright (c) 1993-July 2008 CWI
 Copyright (c) August 2008-2017 MonetDB B.V., all rights reserved
 Visit http://www.monetdb.org/ for further information
 Found 15.6GiB available memory, 8 available cpu cores
 Libraries:
   libpcre: 8.40 2017-01-11 (compiled with 8.40)
   openssl: OpenSSL 1.0.2j  26 Sep 2016 (compiled with OpenSSL 1.0.2j-fips  26 Sep 2016)
   libxml2: 2.9.3 (compiled with 2.9.3)
 Compiled by: roberto@photon.hq.spinque.com (x86_64-unknown-linux-gnu)
 Compilation: gcc -O3 -fomit-frame-pointer -pipe -Werror -Wall -Wextra -W -Werror-implicit-function-declaration -Wpointer-arith -Wdeclaration-after-statement -Wundef -Wformat=2 -Wno-format-nonliteral -Winit-self -Winvalid-pch -Wmissing-declarations -Wmissing-format-attribute -Wmissing-prototypes -Wold-style-definition -Wpacked -Wunknown-pragmas -Wvariadic-macros -fstack-protector-all -Wstack-protector -Wpacked-bitfield-compat -Wsync-nand -Wjump-misses-init -Wmissing-include-dirs -Wlogical-op -Wunreachable-code -D_FORTIFY_SOURCE=2
 Linking    : /usr/bin/ld -m elf_x86_64

## Comment 25514
Date: 2017-07-28 13:05:06 +0200
From: @njnes

on errors we cleanup, ie we also cleanup any prepared statements. We basically reset the connection to a known previous state.

## Comment 25517
Date: 2017-07-28 13:17:23 +0200
From: @swingbit

Thanks Niels.
 
 Just to be sure, you don't think this behaviour is odd from a user point of view?
 
 I do understand the reason behind it, but it still surprises me much.

## Comment 25605
Date: 2017-08-31 19:00:16 +0200
From: Martin van Dinther &lt;<martin.van.dinther>&gt;

MonetDB should not destroy the prepared statement when an error occurs, for exmaple in the calling of exec (<args>) where <args> contains some invalid value. It produces unexpected and annoying problems in mclient but also in JDBC and ODBC drivers.
 Just return the error msg and keep the prepared statement(s) active.

## Comment 25636
Date: 2017-09-15 09:01:09 +0200
From: @njnes

again each error is the moment to cleanup, which is similar to a session reset.
 I do not think this is very strange. Users should handle errors properly.

## Comment 27106
Date: 2019-07-04 11:54:50 +0200
From: @swingbit

I must reopen this bug, because I just don't agree with how it was closed.
 
 1) cleaning up (resetting the connection) after any error sounds like an arbitrary and questionable choice, not like a proper reason
 
 2) it is not even true/consistently done, because variables are still there after an error:
 
 auto commit mode: on
 sql>declare a int;
 operation successful
 sql>set a = 2;
 operation successful
 sql>select a;
 +------+
 | L2   |
 +======+
 |    2 |
 +------+
 1 tuple
 sql>some error;
 syntax error, unexpected IDENT in: "some"
 sql>select a;
 +------+
 | L2   |
 +======+
 |    2 |
 +------+
 1 tuple

## Comment 27492
Date: 2019-12-18 16:32:43 +0100
From: MonetDB Mercurial Repository &lt;<hg>&gt;

Changeset [cfcedd05281b](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=cfcedd05281b)  made by Pedro Ferreira <pedro.ferreira@monetdbsolutions.com> in the MonetDB repo, refers to this bug.
 
 For complete details, see [https//devmonetdborg/hg/MonetDB?cmd=changeset;node=cfcedd05281b](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=https//devmonetdborg/hg/MonetDB?cmd=changeset;node=cfcedd05281b) 
 
 Changeset description:
 
 	Delete session declared variables at an error, rollback or commit.
 
 	I'm against this too, but as requested on bug #6351, we have to keep it consistent with the deletion of prepared statements.

## Comment 27596
Date: 2020-03-15 11:10:55 +0100
From: @mlkersten

Follow up in BUG #6832

## Comment 27856
Date: 2020-06-16 09:55:07 +0200
From: @PedroTadim

Discussing continues on bug #6832.

**Comment by njnes** [comment]
in the default support for prepared statements after errors is added.
