### ISSUE TITLE
Cannot compile with GCC 8.1 and --enable-debug=no

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6611]
Date: 2018-06-11 12:56:48 +0200
From: Ingo Müller &lt;<bugzilla.monetdb.org>&gt;
To:   GDK devs &lt;<bugs-common>&gt;
Version: 11.29.7 (Mar2018-SP1)
CC:   arkr17997, daryt, fosema4365, hexaba9787, merijo9251, pirat, vypal

Last updated: 2020-11-05 14:25:35 +0100

## Comment 26481
Date: 2018-06-11 12:56:48 +0200
From: Ingo Müller &lt;<bugzilla.monetdb.org>&gt;

I am trying to compile the Mar2018_SP1_release branch like so:
 
 ./bootstrap && rm -rf build && mkdir build && cd build && CC=gcc-8.1 ../configure --enable-debug=no && make
 
 With:
 
 $ gcc-8.1 --version
 gcc-8.1 (GCC) 8.1.0
 Copyright (C) 2018 Free Software Foundation, Inc.
 This is free software; see the source for copying conditions.  There is NO
 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 But fail with the following error:
 
 libtool: compile:  gcc-8.1 -DHAVE_CONFIG_H -I. -I../../gdk -I.. -I../../gdk -I../common/options -I../../gdk/../common/options -I../common/stream -I../../gdk/../common/stream -I../common/utils -I../../gdk/../common/utils -DLIBGDK -g -O2 -Werror -Wall -Wextra -W -Werror-implicit-function-declaration -Wpointer-arith -Wundef -Wformat=2 -Wformat-overflow=1 -Wno-format-truncation -Wno-format-nonliteral -Wno-cast-function-type -Winit-self -Winvalid-pch -Wmissing-declarations -Wmissing-format-attribute -Wmissing-prototypes -Wold-style-definition -Wpacked -Wunknown-pragmas -Wvariadic-macros -fstack-protector-all -Wstack-protector -Wpacked-bitfield-compat -Wsync-nand -Wjump-misses-init -Wmissing-include-dirs -Wlogical-op -Wduplicated-cond -Wduplicated-branches -Wrestrict -Wnested-externs -Wno-char-subscripts -Wunreachable-code -D_REENTRANT -c ../../gdk/gdk_calc.c  -fPIC -DPIC -o .libs/libbat_la-gdk_calc.o
 In file included from ../../gdk/gdk.h:2271,
                  from ../../gdk/gdk_calc.c:10:
 ../../gdk/gdk_calc.c: In function 'addstr_loop':
 ../../gdk/gdk_atoms.h:266:4: error: 'memcpy' forming offset [3, 65535] is out of the bounds [0, 2] of object 'str_nil' with type 'const char[2]' [-Werror=array-bounds]
     memcpy(d_, s_, ATOMsize(t_)); \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ../../gdk/gdk.h:1050:4: note: in expansion of macro 'ATOMputFIX'
     ATOMputFIX((b)->ttype, (p), v);   \
     ^~~~~~~~~~
 ../../gdk/gdk.h:1173:3: note: in expansion of macro 'Tputvalue'
    Tputvalue((b), Tloc((b), (p)), (v), 0); \
    ^~~~~~~~~
 ../../gdk/gdk_calc.c:3415:3: note: in expansion of macro 'tfastins_nocheck'
    tfastins_nocheck(bn, i, str_nil, Tsize(bn));
    ^~~~~~~~~~~~~~~~
 In file included from ../../gdk/gdk.h:2271,
                  from ../../gdk/gdk_calc.c:10:
 ../../gdk/gdk_atoms.h:132:23: note: 'str_nil' declared here
  gdk_export const char str_nil[2];
                        ^~~~~~~
 In file included from ../../gdk/gdk.h:2271,
                  from ../../gdk/gdk_calc.c:10:
 
 (A similar error repeats a couple of times more.)
 
 Compiling with --enable-debug=yes (or no option set) works fine. The only difference in the failing command is "-O2" (and the commands succeed/fail if I manually remove/add that option). Compiling with clang 5.0 works fine with an otherwise unchanged setup.

## Comment 26499
Date: 2018-06-26 13:07:28 +0200
From: @sjoerdmullender

Configure using --disable-strict and it will compile (although you will get warnings).
 
 This is actually fixed in the default branch.  I don't think this will be fixed in the Mar2018 branch since there are too many changes for a release branch.

## Comment 26754
Date: 2018-12-25 07:24:27 +0100
From: Thanos &lt;<arkr17997>&gt;

Must be thanks for the share this nice post here it is amazing way to look here http://passwordsinmicrosoftedge.com/ and access the all windows setting to see remembered passwords in microsoft edge to secure data.

**Comment by anansahasal** [comment]
Hood cleaning services brooklyn is an outstanding service for those who want to keep their homes and businesses clean, safe, and functional. Professional cleaners know how to use the proper techniques when it comes to keeping your home and http://www.brooklynhoodcleaningpros.com about business professionally cleaned. They also know about using chemical-free products for the best results.

**Comment by anansahasal** [comment]
Hood cleaning services brooklyn is an outstanding service for those who want to keep their homes and businesses clean, safe, and functional. Professional cleaners know how to use the proper techniques when it comes to keeping your home and http://www.brooklynhoodcleaningpros.com about business professionally cleaned. They also know about using chemical-free products for the best results.
--
