### ISSUE TITLE
Feature request: make code more extension-friendly

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6682]
Date: 2019-02-18 15:54:26 +0100
From: @swingbit
To:   MonetDB5 devs &lt;<bugs-monetdb5>&gt;
Version: 11.31.13 (Aug2018-SP2)
CC:   @mlkersten

Last updated: 2020-03-15 09:52:34 +0100

## Comment 26887
Date: 2019-02-18 15:54:26 +0100
From: @swingbit

User-Agent:       Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
 Build Identifier: 
 
 On the one hand, the codebase and the documentation encourage to write custom code in separate modules, which makes much sense to me. 
 
 On the other hand, modularity seems to be explicitly discouraged, probably by early designs that became legacy.
 
 I will make one example:
 
 I'm maintaining a set of extra functionalities on strings, like tokenization, similarity, etc.
 
 If I were a MonetDB developer, these functionalities would mainly be spread over str.c and batstr.c. Because I'm not, I'm maintaining these extensions under monetdb5/extras/myfancystringmodule.
 
 In my code I need to use many basic string functions / macros like:
 UTF8_strlen(), UTF8_strpos(), UTF8_GETCHAR(), UTF8_PUTCHAR(), etc.
 
 These are defined statically inside str.c and batstr.c. It's like saying: whatever code concerns strings should be in str.c and batstr.c. Which makes sense if your code is not meant to be extended by external developers, but is a pain otherwise. 
 Currently, because I value modularity and do want to keep our extensions in a separate module, I have to resort to copying the code I need into my modules, which is bad for many reasons.
 
 Long story short: please put macros and exports in .h files.
 
 Reproducible: Always

## Comment 26889
Date: 2019-02-18 16:51:25 +0100
From: @sjoerdmullender

Are you familiar with the repository [1]?  Useful for extending MonetDB.  No need for in-tree extensions.
 
 Having said that, it is indeed a good idea to make available macros and functions that might be useful for extension writers.
 
 [1] https://dev.monetdb.org/hg/MonetDB-extend/

## Comment 26891
Date: 2019-02-18 17:46:23 +0100
From: @swingbit

I haven't used the MonetDB-extend repository yet, but I plan to.
 
 I will still need the mentioned changes in the core modules of course.

## Comment 27590
Date: 2020-03-15 09:28:17 +0100
From: @mlkersten

No further information obtained. Changes foreseen in the string handling will address some of the issues mentioned.

## Comment 27592
Date: 2020-03-15 09:52:34 +0100
From: @swingbit

I wasn't aware that more information was needed from me, I thought the issue was clear.

**Comment by swingbit** [comment]
I am not allowed to reopen this issue (which was closed without any resolution), but if possible things got even worse.
Now functions exported from `str.h `are marked with
```
__attribute__((__visibility__("hidden")));
```
which explicitly forbids to use them from a different shared library.
Now I need to copy basically the whole module.

**Comment by sjoerdmullender** [comment]
I think we need to have a proper think about this one.

**Comment by njnes** [comment]
there is a fine ballance in keeping functions exported vs extern vs static. We do agree some functions could very well be used in extention modules, which would mean we need to open up some of those. I think with some discussion (emails) we could open some of those, where need is very clear.
