### ISSUE TITLE
MonetDB unaware of resource limitations

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6710]
Date: 2019-06-07 15:38:40 +0200
From: @yzchang
To:   GDK devs &lt;<bugs-common>&gt;
Version: 11.33.3 (Apr2019)
CC:   @PedroTadim, @swingbit

Last updated: 2019-11-28 10:01:13 +0100

## Comment 27038
Date: 2019-06-07 15:38:40 +0200
From: @yzchang

When tools such as numactl (and probably cgroups as well) are used to limit the hardware resources (e.g. cpu, mem) available to MonetDB, MonetDB is not aware of these limitations.  As a result of this, MonetDB would think that it has more cpu/mem to use than what it will actually gets.
 
 We should extend MonetDB to not only check the resources of the whole system, but also the limitations which might have been set.

**Comment by ThanKarab** [comment]
Hello @PedroTadim , was this actually fixed? 

If multiple docker containers running monet are started on the same machine, will they all use the maximum available memory? Is there a way to limit each container to use specific amount of memory?

**Comment by PedroTadim** [comment]
I am not sure, but there were improvements in the cgroup area from MonetDB.

**Comment by swingbit** [comment]
@ThanKarab I use this often. Docker's limits `memory` and `memory-reservation` map to cgroups  memory limits, which in turn map to MonetDB's hard and soft memory limits: `gdk_vm_maxsize` and `gdk_mem_maxsize`.

In practice: 
- use Docker's `memory` as a hard limit: the container will be killed when this is reached
- use Docker's `memory-reservation` as a soft limit: MonetDB will try to stay below this, but no guarantee

I tend to  set `memory-reservation` at a reasonable value and `memory` quite a bit higher, to be used only as a last resort to protect the system

**Comment by ThanKarab** [comment]
Thanks a lot @swingbit!

**Comment by ThanKarab** [comment]
One last thing, @swingbit , have you tried with k8s? Any idea how to set the `memory-reservation` there?

**Comment by swingbit** [comment]
@ThanKarab no, I have no experience with it.
