### ISSUE TITLE
mserver5: crashes under update_table() when calling lib_sql.so ( max_clients = 2048)

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6862]
Date: 2020-05-11 10:45:03 +0200
From: Arshad &lt;<arshad.super>&gt;
To:   GDK devs &lt;<bugs-common>&gt;
Version: 11.35.19 (Nov2019-SP3)
CC:   @mlkersten, @njnes, renalkoclok

Last updated: 2020-07-27 09:09:13 +0200

## Comment 27701
Date: 2020-05-11 10:45:03 +0200
From: Arshad &lt;<arshad.super>&gt;

User-Agent:       Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
 Build Identifier: 
 
 Hi,
 
 While executing our test-case where max_clients is set to 2048. mserver5 segfaults while executing update_table(). Our reproducer is very lengthy forking more than thousands of threads where there is great number of table create/update. We are trying to narrow down the reproducer and strip it to bare minimal so we can share it later or provide more info on this.
 
 I have not seen this under Bug history either. Does this call to mind anything which we are missing. ? What scenario update_table() will fault which executing lib_sql.so ?
 
 merovingian.log
 ===============
 <snip>
 2020-05-09 05:38:27 ERR control[432623]: !monetdbd: an internal error has occurred 'could not receive initial byte: Connection reset by peer'
 2020-05-09 05:38:27 ERR control[432623]: !monetdbd: an internal error has occurred 'could not receive initial byte: Connection reset by peer'
 2020-05-09 05:38:27 MSG merovingian[432623]: database 'TSV_PROD_2_DB' has crashed after start on 2020-05-08 10:49:50, attempting restart, up min/avg/max: 1s/2h/17h, crash average: 1.00 0.30 0.13 (12-8=4)'
 <snip>
 
 
 (gdb) bt
 0  0x00007f4cf8f09b9b in update_table () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 1  0x00007f4cf8ef20c2 in rollforward_changeset_updates () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 2  0x00007f4cf8f02f6d in rollforward_update_schema () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 3  0x00007f4cf8ef20c2 in rollforward_changeset_updates () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 4  0x00007f4cf8ef244a in rollforward_trans () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 5  0x00007f4cf8ef7ca9 in sql_trans_commit () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 6  0x00007f4cf8e948e3 in mvc_commit () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 7  0x00007f4cf8e12d81 in SQLreader () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/monetdb5/lib_sql.so
 8  0x00007f4d0ada7720 in runScenario () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/libmonetdb5.so.28
 9  0x00007f4d0ada7d6c in MSserveClient () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/libmonetdb5.so.28
 10 0x00007f4d0ada8336 in MSscheduleClient () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/libmonetdb5.so.28
 11 0x00007f4d0ae1559d in doChallenge () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/libmonetdb5.so.28
 12 0x00007f4d0aa2ce37 in THRstarter () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/libbat.so.19
 13 0x00007f4d0aa5ad89 in thread_starter () from /monet_binaries/MonetDB-11.35.19_DEBUG/lib/libbat.so.19
 14 0x00007f4d084d2e25 in start_thread (arg=0x7f475940f700) at pthread_create.c:308
 15 0x00007f4d0820034d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
 (gdb)
 
 dmesg
 ======
 This is not from the present run. We do not have any fault registered yet. But we do see this on our previous run.
 Fri May  8 10:43:42 2020] mserver5[5693]: segfault at 50 ip 00007f4cf8f09b9b sp 00007f475940c960 error 4 in lib_sql.so[7f4cf8ddf000+19e000]
 
 $ mserver5 --version
 MonetDB 5 server 11.35.19 (Nov2019-SP3) (64-bit)
 Copyright (c) 1993 - July 2008 CWI
 Copyright (c) August 2008 - 2020 MonetDB B.V., all rights reserved
 Visit https://www.monetdb.org/ for further information
 Found 1007.3GiB available memory, 128 available cpu cores
 Libraries:
   libpcre: 8.32 2012-11-30
   openssl: OpenSSL 1.0.2k-fips  26 Jan 2017
   libxml2: 2.9.1
 Compiled by: monet@localhost (x86_64-pc-linux-gnu)
 Compilation: gcc -std=gnu99 -g -O2 -g3
 Linking    : /usr/bin/ld -m elf_x86_64  -Wl,-Bsymbolic-functions
 
 
 
 $ /monet_binaries/MonetDB-11.35.19_DEBUG/bin/monetdbd --version
 MonetDB Database Server v11.35.19 (Nov2019-SP3)
 
 
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 1. Run Reproducer (Will upload or provide info)
 
 
 ### Actual Results:  
 mserver5 crashes.
 
 ### Expected Results:  
 Reproducer should work (create/update) table should work as designed.

## Comment 27702
Date: 2020-05-11 11:34:44 +0200
From: Arshad &lt;<arshad.super>&gt;

Log from /var/log/message at time of crash
 ===========================================
 May  9 05:37:37 lnx1538 kernel: mserver5[5693]: segfault at 50 ip 00007f4cf8f09b9b sp 00007f475940c960 error 4 in lib_sql.so[7f4cf8ddf000+19e000]
 May  9 05:37:37 lnx1538 abrt-hook-ccpp: Process 432632 (mserver5) of user 9998 killed by SIGSEGV - dumping core

## Comment 27735
Date: 2020-06-02 16:14:11 +0200
From: Arshad &lt;<arshad.super>&gt;

Update 2:
 =========
 
 We compiled with no optimization and assert switch on to catch any assertion early if any. The crash was a abort due to trans_init: Assertion `0' failed. I am not sure if this is the same cause. https://www.monetdb.org/pipermail/users-list/2018-June/010260.html.  Below are the details. We see this fairly consistently any help on this one.
 
 Our core generated is is almost 3.5 GB. I do not know if uploading is feasible. here.
 
 Let us know if you require more input from us.
 
 $ ls -alih core.287457
 46932408 -rw------- 1 monetadmin monetadmin 3.4G Jun  2 06:27 core.287457
 
 
 mserver5 --version
 MonetDB 5 server 11.35.19 (Nov2019-SP3) (64-bit)
 Copyright (c) 1993 - July 2008 CWI
 Copyright (c) August 2008 - 2020 MonetDB B.V., all rights reserved
 Visit https://www.monetdb.org/ for further information
 Found 1007.3GiB available memory, 128 available cpu cores
 Libraries:
   libpcre: 8.32 2012-11-30
   openssl: OpenSSL 1.0.2k-fips  26 Jan 2017
   libxml2: 2.9.1
 Compiled by: monetadmin@lnx1490.ch3.prod.i.com (x86_64-pc-linux-gnu)
 Compilation: gcc -std=gnu99 -g -g3
 Linking    : /bin/ld -m elf_x86_64  -Wl,-Bsymbolic-functions
 
 
 Log
 ===
 <snip>
 2020-06-02 05:34:46 ERR TSV_PROD_2_DB[287457]: client4:!ERROR:MALException:mal.interpreter:prematurely stopped client
 2020-06-02 05:35:52 ERR TSV_PROD_2_DB[287457]: client3:!ERROR:SQLException:sql.resultset:45000!Result set construction failed
 2020-06-02 06:27:52 ERR TSV_PROD_2_DB[287457]: mserver5: store.c:3281: trans_init: Assertion `0' failed.
 <snip>
 2020-06-02 06:27:59 MSG merovingian[287426]: starting a proxy failed: could not receive initial byte: Connection reset by peer
 2020-06-02 06:27:59 ERR merovingian[287426]: client error: could not receive initial byte: Connection reset by peer
 2020-06-02 06:27:59 ERR merovingian[287426]: client error: could not receive initial byte: Connection reset by peer
 2020-06-02 06:27:59 MSG merovingian[287426]: database 'TSV_PROD_2_DB' (287457) has crashed (dumped core)
 2020-06-02 06:27:59 MSG merovingian[287426]: database 'TSV_PROD_2_DB' has crashed after start on 2020-06-01 02:00:13, attempting restart, up mi      n/avg/max: 1s/2d/3w, crash average: 1.00 0.40 0.17 (14-9=5)
 76845 2020-06-02 06:28:00 MSG merovingian[287426]: proxying client 10.106.68.48:47636 for database 'TSV_PROD_2_DB' to mapi:monetdb:///monet_data01/DB      FARM_TSV_PROD_2/TSV_PROD_2_DB/.mapi.sock?database=TSV_PROD_2_DB
 76846 2020-06-02 06:28:00 MSG TSV_PROD_2_DB[346819]: arguments: /monet_binaries/MonetDB-11.35.19_ARSHAD/bin/mserver5 --dbpath=/monet_data01/DBFARM_TS      V_PROD_2/TSV_PROD_2_DB --set merovingian_uri=mapi:monetdb://lnx1538.ch3.qa.i.com:50900/TSV_PROD_2_DB --set mapi_open=false --set mapi_ipv6=fals      e --set mapi_port=0 --set mapi_usock=/monet_data01/DBFARM_TSV_PROD_2/TSV_PROD_2_DB/.mapi.sock --set monet_vault_key=/monet_data01/DBFARM_TSV_PR      OD_2/TSV_PROD_2_DB/.vaultkey --set gdk_nr_threads=128 --set max_clients=2048 --set sql_optimizer=sequential_pipe --set embedded_py=2
 2020-06-02 06:28:00 ERR control[287426]: !monetdbd: an internal error has occurred 'cannot connect: Connection refused'
 <snip-end>
 
 Here is the back-trace.
 
 (gdb) bt
 0  0x00007f3ad12bd1f7 in __GI_raise (sig=sig@entry=6)
     at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
 1  0x00007f3ad12be8e8 in __GI_abort () at abort.c:90
 2  0x00007f3ad12b6266 in __assert_fail_base (
     fmt=0x7f3ad1408e68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
     assertion=assertion@entry=0x7f3ac1e45ba8 "0",
     file=file@entry=0x7f3ac1e45914 "store.c", line=line@entry=3281,
     function=function@entry=0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606> "trans_init")
     at assert.c:92
 3  0x00007f3ad12b6312 in __GI___assert_fail (assertion=0x7f3ac1e45ba8 "0",
     file=0x7f3ac1e45914 "store.c", line=3281,
     function=0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606> "trans_init") at assert.c:101
 4  0x00007f3ac1dc3fa5 in trans_init (tr=0x7f39c00018d0, stk=0, otr=0x5d6be30)
     at store.c:3281
 5  0x00007f3ac1dd417e in sql_trans_begin (s=0x7f3980140f30) at store.c:6923
 6  0x00007f3ac1d154a1 in mvc_trans (m=0x7f39802d7940) at sql_mvc.c:357
 7  0x00007f3ac1c58ec0 in SQLtrans (m=0x7f39802d7940) at sql_scenario.c:674
 8  0x00007f3ac1c59e79 in SQLparser (c=0x7f3ac25b1cc8) at sql_scenario.c:1076
 9  0x00007f3ad4195acf in runPhase (c=0x7f3ac25b1cc8, phase=1) at mal_scenario.c:517
 10 0x00007f3ad4195b80 in runScenarioBody (c=0x7f3ac25b1cc8, once=0)
     at mal_scenario.c:537
 11 0x00007f3ad4195dfb in runScenario (c=0x7f3ac25b1cc8, once=0) at mal_scenario.c:575
 12 0x00007f3ad4197847 in MSserveClient (c=0x7f3ac25b1cc8) at mal_session.c:504
 13 0x00007f3ad41973b4 in MSscheduleClient (
     command=0x7f3980130fd0 '\333' <repeats 199 times>, <incomplete sequence \333>...,
     challenge=0x7f39bddedc90 "mckG7kNhAh", fin=0x7f3980142a70, fout=0x7f3ab8042330,
     protocol=PROTOCOL_9, blocksize=8190) at mal_session.c:382
 14 0x00007f3ad423a0cb in doChallenge (data=0x7f3ab8001f90) at mal_mapi.c:267
 15 0x00007f3ad3d3bb97 in THRstarter (a=0x7f3ab8077440) at gdk_utils.c:1558
 16 0x00007f3ad3da2c0f in thread_starter (arg=0x7f3ab80016f0) at gdk_system.c:657
 17 0x00007f3ad1652e25 in start_thread (arg=0x7f39bddee700) at pthread_create.c:308
 18 0x00007f3ad138034d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
 (gdb) frame 5
 5  0x00007f3ac1dd417e in sql_trans_begin (s=0x7f3980140f30) at store.c:6923
 6923    store.c: No such file or directory.
 (gdb) bt
 0  0x00007f3ad12bd1f7 in __GI_raise (sig=sig@entry=6)
     at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
 1  0x00007f3ad12be8e8 in __GI_abort () at abort.c:90
 2  0x00007f3ad12b6266 in __assert_fail_base (
     fmt=0x7f3ad1408e68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
     assertion=assertion@entry=0x7f3ac1e45ba8 "0",
     file=file@entry=0x7f3ac1e45914 "store.c", line=line@entry=3281,
     function=function@entry=0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606> "trans_init")
     at assert.c:92
 3  0x00007f3ad12b6312 in __GI___assert_fail (assertion=0x7f3ac1e45ba8 "0",
     file=0x7f3ac1e45914 "store.c", line=3281,
     function=0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606> "trans_init") at assert.c:101
 4  0x00007f3ac1dc3fa5 in trans_init (tr=0x7f39c00018d0, stk=0, otr=0x5d6be30)
     at store.c:3281
 5  0x00007f3ac1dd417e in sql_trans_begin (s=0x7f3980140f30) at store.c:6923
 6  0x00007f3ac1d154a1 in mvc_trans (m=0x7f39802d7940) at sql_mvc.c:357
 7  0x00007f3ac1c58ec0 in SQLtrans (m=0x7f39802d7940) at sql_scenario.c:674
 8  0x00007f3ac1c59e79 in SQLparser (c=0x7f3ac25b1cc8) at sql_scenario.c:1076
 9  0x00007f3ad4195acf in runPhase (c=0x7f3ac25b1cc8, phase=1) at mal_scenario.c:517
 10 0x00007f3ad4195b80 in runScenarioBody (c=0x7f3ac25b1cc8, once=0)
     at mal_scenario.c:537
 11 0x00007f3ad4195dfb in runScenario (c=0x7f3ac25b1cc8, once=0) at mal_scenario.c:575
 12 0x00007f3ad4197847 in MSserveClient (c=0x7f3ac25b1cc8) at mal_session.c:504
 13 0x00007f3ad41973b4 in MSscheduleClient (
     command=0x7f3980130fd0 '\333' <repeats 199 times>, <incomplete sequence \333>...,
     challenge=0x7f39bddedc90 "mckG7kNhAh", fin=0x7f3980142a70, fout=0x7f3ab8042330,
     protocol=PROTOCOL_9, blocksize=8190) at mal_session.c:382
 14 0x00007f3ad423a0cb in doChallenge (data=0x7f3ab8001f90) at mal_mapi.c:267
 15 0x00007f3ad3d3bb97 in THRstarter (a=0x7f3ab8077440) at gdk_utils.c:1558
 16 0x00007f3ad3da2c0f in thread_starter (arg=0x7f3ab80016f0) at gdk_system.c:657
 17 0x00007f3ad1652e25 in start_thread (arg=0x7f39bddee700) at pthread_create.c:308
 18 0x00007f3ad138034d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
 
 (gdb) frame 5
 5  0x00007f3ac1dd417e in sql_trans_begin (s=0x7f3980140f30) at store.c:6923
 6923    in store.c
 (gdb) info locals
 tr = 0x7f39c00018d0
 snr = 191
 (gdb) ptype tr
 type = struct sql_trans {
     char *name;
     int stime;
     int wstime;
     int rtime;
     int wtime;
     int schema_number;
     int schema_updates;
     int active;
     int status;
     list *dropped;
     list *moved_tables;
     changeset schemas;
     sql_allocator *sa;
     struct sql_trans *parent;
     backend_stack stk;
 } *
 (gdb) p *tr
 $1 = {name = 0x0, stime = 1889, wstime = 1893, rtime = 0, wtime = 0,
   schema_number = 192, schema_updates = 0, active = 0, status = 0, dropped = 0x0,
   moved_tables = 0x0, schemas = {sa = 0x7f39c0001970,
     destroy = 0x7f3ac1db0bad <schema_destroy>, set = 0x7f39c014e5d0, dset = 0x0,
     nelm = 0x0}, sa = 0x7f39c0001970, parent = 0x5d6be30, stk = 0}
 (gdb) ptype snr
 type = int
 (gdb)
 
 
 (gdb) bt full
 0  0x00007f3ad12bd1f7 in __GI_raise (sig=sig@entry=6)
     at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
         resultvar = 0
         pid = 287457
         selftid = 346754
 1  0x00007f3ad12be8e8 in __GI_abort () at abort.c:90
         save_stage = 2
         act = {__sigaction_handler = {sa_handler = 0x7ffd5d8a6f5a,
             sa_sigaction = 0x7ffd5d8a6f5a}, sa_mask = {__val = {139890595487600,
               139890337798420, 3281, 139885975361280, 139890594118595, 4,
               139885975361216, 2149427392, 139884939385536, 139885975361392, 0, 0, 0,
               21474836480, 139890649300992, 139890595499624}},
           sa_flags = -1041998936,
           sa_restorer = 0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606>}
         sigs = {__val = {32, 0 <repeats 15 times>}}
 2  0x00007f3ad12b6266 in __assert_fail_base (
     fmt=0x7f3ad1408e68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
     assertion=assertion@entry=0x7f3ac1e45ba8 "0",
     file=file@entry=0x7f3ac1e45914 "store.c", line=line@entry=3281,
     function=function@entry=0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606> "trans_init")
     at assert.c:92
         str = 0x7f3980145080 " P\024\200\071\177"
         total = 4096
 3  0x00007f3ad12b6312 in __GI___assert_fail (assertion=0x7f3ac1e45ba8 "0",
     file=0x7f3ac1e45914 "store.c", line=3281,
     function=0x7f3ac1e46c1d <__PRETTY_FUNCTION__.12606> "trans_init") at assert.c:101
 No locals.
 4  0x00007f3ac1dc3fa5 in trans_init (tr=0x7f39c00018d0, stk=0, otr=0x5d6be30)
     at store.c:3281
         pt = 0x96f2bf0
         t = 0x7f39c1d75a00
         k = 0x96f3540
         l = 0x7f39c1d76350
         ps = 0x60c7220
         s = 0x7f39c01569c0
         istmp = 0
         m = 0x97badc0
         n = 0x7f39c1de6100
         __PRETTY_FUNCTION__ = "trans_init"
 5  0x00007f3ac1dd417e in sql_trans_begin (s=0x7f3980140f30) at store.c:6923
         tr = 0x7f39c00018d0
         snr = 191
 6  0x00007f3ac1d154a1 in mvc_trans (m=0x7f39802d7940) at sql_mvc.c:357
 ---Type <return> to continue, or q <return> to quit---
         schema_changed = 0
         err = 0
         __PRETTY_FUNCTION__ = "mvc_trans"
 7  0x00007f3ac1c58ec0 in SQLtrans (m=0x7f39802d7940) at sql_scenario.c:674
         s = 0x48
         __func__ = "SQLtrans"
         __PRETTY_FUNCTION__ = "SQLtrans"
 8  0x00007f3ac1c59e79 in SQLparser (c=0x7f3ac25b1cc8) at sql_scenario.c:1076
         in = 0x7f3980142a70
         out = 0x7f3ab8042330
         msg = 0x0
         be = 0x7f3980143900
         m = 0x7f39802d7940
         oldvtop = 1
         oldstop = 1
         pstatus = 0
         err = 0
         opt = 0
         q = 0x7f39801439f0 '\333' <repeats 72 times>, "A"
         __func__ = "SQLparser"
         __PRETTY_FUNCTION__ = "SQLparser"
 9  0x00007f3ad4195acf in runPhase (c=0x7f3ac25b1cc8, phase=1) at mal_scenario.c:517
         msg = 0x0
 10 0x00007f3ad4195b80 in runScenarioBody (c=0x7f3ac25b1cc8, once=0)
     at mal_scenario.c:537
         msg = 0x0
         __PRETTY_FUNCTION__ = "runScenarioBody"
 11 0x00007f3ad4195dfb in runScenario (c=0x7f3ac25b1cc8, once=0) at mal_scenario.c:575
         msg = 0x0
 12 0x00007f3ad4197847 in MSserveClient (c=0x7f3ac25b1cc8) at mal_session.c:504
         mb = 0x7f3980142d40
         msg = 0x0
         __PRETTY_FUNCTION__ = "MSserveClient"
 13 0x00007f3ad41973b4 in MSscheduleClient (
     command=0x7f3980130fd0 '\333' <repeats 199 times>, <incomplete sequence \333>...,
     challenge=0x7f39bddedc90 "mckG7kNhAh", fin=0x7f3980142a70, fout=0x7f3ab8042330,
     protocol=PROTOCOL_9, blocksize=8190) at mal_session.c:382
         user = 0x7f3980130fd4 '\333' <repeats 199 times>, <incomplete sequence \333>...
         algo = 0x7f3980130fe7 '\333' <repeats 199 times>, <incomplete sequence \333>...
         passwd = 0x7f3980130ff1 '\333' <repeats 199 times>, <incomplete sequence \333>...
 ---Type <return> to continue, or q <return> to quit---
         lang = 0x7f398013101a '\333' <repeats 199 times>, <incomplete sequence \333>...
         database = 0x7f398013101e '\333' <repeats 199 times>, <incomplete sequence \333>...
         s = 0x0
         dbname = 0x49d43e0 "TSV_PROD_2_DB"
         msg = 0x0
         filetrans = false
         c = 0x7f3ac25b1cc8
         __func__ = "MSscheduleClient"
 14 0x00007f3ad423a0cb in doChallenge (data=0x7f3ab8001f90) at mal_mapi.c:267
         buf = 0x7f3980130fd0 '\333' <repeats 199 times>, <incomplete sequence \333>...
         __func__ = "doChallenge"
         challenge = "mckG7kNhAh\000\275\275"
         fdin = 0x7f3ab8001ef0
         fdout = 0x7f3ab8042330
         bs = 0x7f3980142a70
         len = 93
         protocol = PROTOCOL_9
         buflen = 8190
 15 0x00007f3ad3d3bb97 in THRstarter (a=0x7f3ab8077440) at gdk_utils.c:1558
         t = 0x7f3ab8077440
         func = 0x7f3ad4239912 <doChallenge>
         arg = 0x7f3ab8001f90
         __func__ = "THRstarter"
 16 0x00007f3ad3da2c0f in thread_starter (arg=0x7f3ab80016f0) at gdk_system.c:657
         p = 0x7f3ab80016f0
         data = 0x7f3ab8077440
 17 0x00007f3ad1652e25 in start_thread (arg=0x7f39bddee700) at pthread_create.c:308
         __res = <optimized out>
         pd = 0x7f39bddee700
         now = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139885975365376,
                 6215938736664030108, 0, 139885975366080, 139885975365376, 37,
                 -6327547695679198308, -6325638198854079588}, mask_was_saved = 0}},
           priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0,
               canceltype = 0}}}
         not_first_call = <optimized out>
         pagesize_m1 = <optimized out>
         sp = <optimized out>
         freesize = <optimized out>
 18 0x00007f3ad138034d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
 (gdb)

## Comment 27769
Date: 2020-06-03 09:13:32 +0200
From: @sjoerdmullender

The content of attachment 670 has been deleted for the following reason:
 
 spam

## Comment 27793
Date: 2020-06-08 10:12:08 +0200
From: Arshad &lt;<arshad.super>&gt;

Hi Devs,
 
 We are running into this very often. Would like to know if there is any update on this ? Is the information I have supplied sufficient ? Is there anything else you want me to update. Please do let me know.
 
 Thanks
 Arshad

## Comment 27794
Date: 2020-06-08 11:43:05 +0200
From: @mlkersten

This overwhelming information is hard to assess, but the first line may give a hint
 
 2020-05-09 05:38:27 ERR control[432623]: !monetdbd: an internal error has occurred 'could not receive initial byte: Connection reset by peer'
 
 
 This indicates there are problems in you network environment, because mserver lost the connection. Whether it is broken hardware, hidden network timeouts, broken pipe, hitting an OS limit on processes, open files, ...  can not be determined.
 
 Resolving this requires a holistic view on your application setup.

## Comment 27797
Date: 2020-06-09 06:37:59 +0200
From: Arshad &lt;<arshad.super>&gt;

Comment 2: contains the more latest core and information. This server was compiled with assert on to catch any abnormality early. I can confirm that the network is stable and the "connection reset" is the effect of earlier crash. The early (first) crash however could not capture the debugging symbols so we got the latest crash with debugging symbols. Which starts with Comment 2.
 
 The setup is : Server running under Linux and clients (mclient) connecting to it. Clients however on certain parts of script can scale up-to 2048 count as I said earlier.
 
 The core is so large that it is next to impossible to uploaded; most of the information is dissection of core. This is the most I could do.
 
 The details of back-trace is given earlier. 
 
  This is where We hit assertion.
 
 client3:!ERROR:SQLException:sql.resultset:45000!Result set construction failed
 2020-06-02 06:27:52 ERR TSV_PROD_2_DB[287457]: mserver5: store.c:3281: trans_init: Assertion `0' failed.
 ...
 ...
 
  ..and as a result we abort.
 
 2020-06-02 06:27:59 ERR merovingian[287426]: client error: could not receive initial byte: Connection reset by peer
 2020-06-02 06:27:59 MSG merovingian[287426]: database 'TSV_PROD_2_DB' (287457) has crashed (dumped core)
 
  Here is the relevant frame information of store.c 
 
 (gdb) frame 5
 5  0x00007f3ac1dd417e in sql_trans_begin (s=0x7f3980140f30) at store.c:6923
 6923    in store.c
 (gdb) info locals
 tr = 0x7f39c00018d0
 snr = 191
 (gdb) ptype tr
 type = struct sql_trans {
     char *name;
     int stime;
     int wstime;
     int rtime;
     int wtime;
     int schema_number;
     int schema_updates;
     int active;
     int status;
     list *dropped;
     list *moved_tables;
     changeset schemas;
     sql_allocator *sa;
     struct sql_trans *parent;
     backend_stack stk;
 } *
 (gdb) p *tr
 $1 = {name = 0x0, stime = 1889, wstime = 1893, rtime = 0, wtime = 0,
   schema_number = 192, schema_updates = 0, active = 0, status = 0, dropped = 0x0,
   moved_tables = 0x0, schemas = {sa = 0x7f39c0001970,
     destroy = 0x7f3ac1db0bad <schema_destroy>, set = 0x7f39c014e5d0, dset = 0x0,
     nelm = 0x0}, sa = 0x7f39c0001970, parent = 0x5d6be30, stk = 0}
 (gdb) ptype snr
 type = int
 (gdb)

## Comment 27822
Date: 2020-06-11 11:07:19 +0200
From: @njnes

the assert is throw because there is a difference in the lists of tables of a schema. Any hints on what the application is doing may help narrowing down the issue.

## Comment 27945
Date: 2020-07-27 09:09:13 +0200
From: Arshad &lt;<arshad.super>&gt;

Hi Niels,
 
 >the assert is throw because there is a difference in the lists of tables of a schema. Any hints on what the application is doing may help narrowing down the issue.
 
 The data load is happening through a automatic application workflow creator (control-M) - Currently the prep time itself is almost half a day. What I meant is that the Test-case is huge!. We are still trying narrow down and bring it into small chunk so that is easily shared.  
 
 That said, what i could say is that the setup is  a Server running under Linux and clients (mclient) connecting to it (this is done via control-M). Clients however on certain parts of control-m script can scale up-to 2048 count. So concurrency is in play here. 
 
 Thanks
 Arshad

**Comment by njnes** [comment]
We fixed a couple of bugs related to the transaction handling recently. Could you verify if this has helped this case?
