### ISSUE TITLE
Could Mapilib have non-blocking functions to ask if the query is over for mapi_send?

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6961]
Date: 2020-09-03 10:13:42 +0200
From: xavier &lt;<wysunxavier>&gt;
To:   clients devs &lt;<bugs-clients>&gt;
Version: 11.37.11 (Jun2020-SP1)

Last updated: 2020-09-03 10:13:42 +0200

## Comment 28049
Date: 2020-09-03 10:13:42 +0200
From: xavier &lt;<wysunxavier>&gt;

I used the function mapi_send to execute 'SELECT' query, but i had to use function mapi_read_response to get query status.It seems that mapi_read_response is a blocking call.
 Could there be a non-blocking call function to get the query status? Or the function exists but I don't know.
 
 
 Thanks
 Xavier

**Comment by sjoerdmullender** [comment]
The actual answer to the question is: no, there is no such function.  And it is unlikely that such a function will be implemented any time soon.
