### ISSUE TITLE
Wrong constraint name in error message of constraint violation

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6982]
Date: 2020-10-05 07:28:57 +0200
From: Karl Seguin &lt;<no>&gt;
To:   SQL devs &lt;<bugs-sql>&gt;
Version: 11.37.11 (Jun2020-SP1)
CC:   @PedroTadim

Last updated: 2020-10-07 18:29:31 +0200

## Comment 28150
Date: 2020-10-05 07:28:57 +0200
From: Karl Seguin &lt;<no>&gt;

User-Agent:       Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
 Build Identifier: 
 
 Seems like when there's a failed foreign constraint, the MonetDB server returns the first defined foreign key, not the one the one that actually failed.
 
 
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 create table a (id int primary key);
 insert into a values (1);
 
 create table b (id int primary key);
 
 create table c (a int references a(id), b int references b(id));
 insert into c (a, b) values (1, 2);
 
 ### Actual Results:  
 40002!INSERT INTO: FOREIGN KEY constraint 'c.c_a_fkey' violated
 
 ### Expected Results:  
 40002!INSERT INTO: FOREIGN KEY constraint 'c.c_b_fkey' violated

## Comment 28158
Date: 2020-10-07 18:29:31 +0200
From: @PedroTadim

We noticed this, thanks for your report. We will fix it on a future release.

**Comment by karlseguin** [comment]
Any chance to get this fixed?  I often forget about this bug, so I spend a good 20 minutes trying to figure out why it's complaining about constaint X when everything looks (and is) fine. Then I need to go check each one manually.

**Comment by PedroTadim** [comment]
I am back at looking at this. It should have been fixed already. Apparently the SQL layer does something confusing to insert into join idxs, which foreign keys do use. I wanted to clean this, but maybe it requires a major change.

**Comment by PedroTadim** [comment]
Should be fixed on default branch.
