### ISSUE TITLE
Mserver5 crashes on start: debug info

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#6999]
Date: 2020-10-19 17:33:13 +0200
From: Manuel &lt;<manuel>&gt;
To:   SQL devs &lt;<bugs-sql>&gt;
Version: 11.29.7 (Mar2018-SP1)
CC:   @PedroTadim, @yzchang

Last updated: 2020-11-24 16:49:23 +0100

## Comment 28213
Date: 2020-10-19 17:33:13 +0200
From: Manuel &lt;<manuel>&gt;

User-Agent:       Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
 Build Identifier: 
 
 I have an instance of a db farm causing mserver5 to crash immediately with exit status -1073741819. As far as I can tell no information is logged anywhere. I tried adding --trace option, but that seems to have no effect. Anything else I can try to understand what the issue is ?
 
 
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 N/A DB farm contains client data.

## Comment 28214
Date: 2020-10-19 18:39:16 +0200
From: @PedroTadim

Hello Manuel,
 
 You are using a very old version of MonetDB, can you try to upgrade it first? If not, can you send a core dump? So we can analyze it?

## Comment 28215
Date: 2020-10-19 18:46:08 +0200
From: @yzchang

Hai Manuel,
 
 We no longer support Mar2018-SP1.  The best you can do is to upgrade to the most recent version Oct2020 and rebuild your database from scratch => for older versions like this, starting with a fresh database is safer than following the upgrade path.

## Comment 28216
Date: 2020-10-20 10:10:12 +0200
From: Manuel &lt;<manuel>&gt;

I understand I am using an older version of monetdb (updating monetdb is very expensive for us), I was wandering if there is a way I can get more information on what the cause of the issue is, and how the database got corrupted in the first place.

## Comment 28288
Date: 2020-11-24 16:49:23 +0100
From: @sjoerdmullender

This looks like an error from Windows.  Have you tried Google to find the error?  Try searching for "windows -1073741819".  That gave some intriguing hits.  And it points to problems that have nothing to do with MonetDB...

**Comment by njnes** [comment]
closing because it looks like an issue outside MonetDB's scope.
