### ISSUE TITLE
More flexible syntax for time intervals

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7014]
Is there a good reason for using an explicit string in interval syntax, like:
```
INTERVAL '3' DAY
```

My first question would be "why a string and not an integer / decimal" ?

My second question would be why not an expression?

Sometimes it would be useful to be able to write things like:
```
INTERVAL (3*24) HOUR
```

Or use it in a function:
```
CREATE FUNCTION f(d DATE, i integer) 
RETURN date
BEGIN
  RETURN d + INTERVAL i SECOND;
END;
```

One could argue that if you can write `INTERVAL (3*24) HOUR` then you can as well write `INTERVAL '3' DAY`, but I don't think this would be a fair assumption. Queries are often generated and amounts may come from procedures unable to make such conversions.

PS: Do I win something for the first issue reported on GitHub? :)

**Comment by njnes** [comment]
why not write 
select (3*24) * INTERVAL '1' HOUR

**Comment by swingbit** [comment]
Of course, you can do that. 
I really meant this as an enhancement proposal, not as a bug.

It just feels a bit of an unnecessary restriction to use a literal there. A _string_ literal feels even out of place.
I am aware that the string literal is used in other systems as well - not blaming MonetDB for it, but some other systems use generic expressions there, and it feels more natural.

So, my answer is: there is no reason for not using `select (3*24) * INTERVAL '1' HOUR`, but I also see no valid reason for this to be necessary (that's why I asked whether there was any good reason I might be missing).

**Comment by njnes** [comment]
Good reason is very generic ;-). But its more or less that the literals are handled in the parser which follows the sql specification. Allowing this is sort of similar to allowing casts like that, which we don't. I do agree the extra quotes aren't that natural.
