### ISSUE TITLE
Optimizers-pipeline as a global setting for a certain database

### ISSUE THREAD

**Issue by ghost** [MonetDB/MonetDB#7015]
**Is your feature request related to a problem? Please describe.**
The current setup allows a user to change the database optimizers-pipeline in a session-wide fashion using SQL statements.

**Describe the solution you'd like**
In MonetDB-Console we would like to introduce an option so that we make it possible for the user to set the optimizers pipeline for the database as a whole (a global setting).

**Comment by njnes** [comment]
you can pass a global (default) optimizer-pipeline using the mserver5 command line option sql_optimizer.
ie
mserver5 --set sql_optimize='what_ever_pipe'
Those global settings cannot be changed (at the moment) via sql statements.

**Comment by ghost** [comment]
That set's the optimizer pipeline for all databases within a farm right? This is not what we want to achieve in monetdb-console. At the time of the creation of a database, we would like to set the pipeline that would be used for every query.

**Comment by sjoerdmullender** [comment]
No.  --set options on mserver5 only work for that instance.

**Comment by ghost** [comment]
So, if I have db0, I can execute `monetdb set optpipe='volcano_pipe' db0` to set the optimizers pipeline for that particular database. In case I would like later to change the pipeline again, do I have to perform any restart?

**Comment by sjoerdmullender** [comment]
You are confusing monetdb and mserver5.  They are different programs.  This is about mserver5.

**Comment by ghost** [comment]
In monetdb-console we control the farm and the databases using `monetdbd` and `monetdb`. We do not use `mserver5` in any way. That's why I am interested in those programs and not mserver5 options.

**Comment by njnes** [comment]
indeed with monetdb you could pass the optimizer too the mserver5. You do need to restart the mserver5 for this global option to take effect.
