### ISSUE TITLE
STREAM TABLE not supported but has online documentation

### ISSUE THREAD

**Issue by aris-koning** [MonetDB/MonetDB#7019]
The SQLreference documentation describes the `STREAM TABLE` syntax [here](https://www.monetdb.org/index.php/Documentation/SQLreference/SQLSyntaxOverview#CREATE_STREAM_TABLE) and possible at other pages as well.

Since stream tables are not supported, it should be removed.

**Comment by PedroTadim** [comment]
I removed them on default branch, so it has not yet been released. This can't be considered a bug because it's not in production.

**Comment by ghost** [comment]
STREAM tables have a specific semantics relevant for any system that is either dealing with event streams (from Kafka) or an in-memory message queue.  One significant aspect is that it lives outside of the transaction manager and is heavily used in the TimeTrails branch. The branch that will become crucial in teh VesselAI project starting next month. So. It can not be removed from the source, nor the documentation, although the implementation is likely to change. 
Not even from the default branch.

**Comment by PedroTadim** [comment]
As I am aware timetrails is not in production and the stream tables don't do anything in default.

**Comment by arjenpdevries** [comment]
Exciting developments! Looking forward to the project results, any online information available already? At Spinque, there is definitely interest in the planned extension.

Would make sense to update the documentation so it is clear that this is experimental and you need a special branch :-)
Maybe just a flag "experimental".

**Comment by aris-koning** [comment]
Sounds like we should reopen this issue as a feature request.

**Comment by yzchang** [comment]
@arjenpdevries interesting to know Spinque is also interested in this topic. We'll be working on it the coming year. Might be a good idea to exchange some information in this area
