### ISSUE TITLE
Revoking a role from a logged-in user is not immediately effective

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7026]
**Describe the bug**
After `monetdb` has revoked a role from a user who is already logged in and has assumed the revoked role, the user can still use the rights associated with the revoked role.

**To Reproduce**
In connection1, log in as `monetdb` and run the following queries:
```
CREATE SCHEMA s1;
CREATE USER bruce WITH PASSWORD 'bruce' name 'willis' schema s1;
CREATE TABLE s1.test(d int);
CREATE ROLE role1;
GRANT ALL ON s1.test to role1;
GRANT role1 TO bruce;
```
In connection2, log in as `bruce` and stay logged in.  Check that `bruce` can assume the role `role1` and use all its rights:
```
SET role role1;
SELECT * FROM test;
INSERT INTO test VALUES (24), (42);
UPDATE test SET d = 42 WHERE d <> 42;
DELETE FROM test WHERE d = 42;
```
Back in connection1:
```
REVOKE role1 FROM bruce;`
```
Back in connection2, `bruce` still has all privileges on `test`, even though it no longer has `role1`:
```
SELECT * FROM test;
INSERT INTO test VALUES (24), (42);
UPDATE test SET d = 42 WHERE d <> 42;
DELETE FROM test WHERE d = 42;
SET role role1; --> Role (role1) missing
```

**Expected behavior**
`bruce` should not be able to access `test` after its `role1` has been revoked.

**Software versions**
 - MonetDB version number [v11.39.8 (hg id: 66645aea30c4)]
 - OS and version: [e.g. Ubuntu 20.04]
 - Mercurial source

**Comment by njnes** [comment]
this is not a bug. Only new sessions will have the new (revoked) role semantics.

**Comment by swingbit** [comment]
May I add my 2 cents to this? I am not really interested in the ROLE issue itself, but more in what is a bug or not.

As @njnes clarified, this is not a _programming_ bug, i.e. the feature does not behave differently from how it was designed.

There are however more levels of "bug".

This could be a _design_ bug, if one decides that waiting for the change to be active in the next session is not acceptable. 

If this design choice is the one accepted, the fact remains that from a user point of view this behaviour is confusing. I would certainly expect the same that @yzchang  expected.

At the very least, this may be considered a _documentation_ bug. If the REVOKE command clearly said "your change will be effective in the next session" then it would be fine. But without this information the user is bound to expect an immediate effect which is not there.

**Comment by yzchang** [comment]
I agree.  I was thinking that this can then also be seen as an unsupported feature.  But improving the documentation can also help.  Currently, a GRANT <role> statement only says "operation successful".  not sure if that can be changed easily...

**Comment by njnes** [comment]
Indeed the documentation should be clear.
