### ISSUE TITLE
levels of bugs?

### ISSUE THREAD

**Issue by njnes** [MonetDB/MonetDB#7027]
May I add my 2 cents to this? I am not really interested in the ROLE issue itself, but more in what is a bug or not.

As @njnes clarified, this is not a _programming_ bug, i.e. the feature does not behave differently from how it was designed.

There are however more levels of "bug".

This could be a _design_ bug, if one decides that waiting for the change to be active in the next session is not acceptable. 

If this design choice is the one accepted, the fact remains that from a user point of view this behaviour is confusing. I would certainly expect the same that @yzchang  expected.

At the very least, this may be considered a _documentation_ bug. If the REVOKE command clearly said "your change will be effective in the next session" then it would be fine. But without this information the user is bound to expect an immediate effect which is not there.

_Originally posted by @swingbit in https://github.com/MonetDB/MonetDB/issues/7026#issuecomment-743246044_

**Comment by njnes** [comment]
Moved too its own issue. Indeed this needs a proper description (and maybe we need more labels etc) and improved documentation.

**Comment by njnes** [comment]
I moved this also to have some more input on the current issues labels and other features we could/should use.

**Comment by swingbit** [comment]
I would suggest to start from the principle that a bug report can only be invalid in two cases:
- if the result is in fact not different from the user expectation (sometimes this may not be obvious to see)
- if the user expectation is not correct or not reasonable

In all other cases, a mismatch between a behaviour and a user expectation is always some type of issue.
It may be a coding mistake, a design flaw, or simply a miscommunication, but always something to address.

Perhaps the word "bug" is what can be misleading when used in a broad sense? Most code platforms (including this one) use the term "issue", which is more generic and is not necessarily a coding issue (which is normally what people mean with "bug").

You already have the labels "bug" and "documentation". Perhaps you only need to add one for design/logical issues?

**Comment by njnes** [comment]
Added the label Design for now. Later we could add more labels (or cleanup some old).
