### ISSUE TITLE
Role dropped while being used by a user

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7029]
**Describe the bug**
Is this a bug or expected behaviour?  I can drop a ROLE while it has been GRANTed to a USER, doesn't matter if the USER is currently logged in and has assumed the ROLE or not.

**To Reproduce**
--- role not assumed by a user
Log in as `monetdb`:
```
CREATE USER alice with password 'alice' name 'alice' schema sys;
CREATE ROLE role1;
GRANT role1 to alice;
DROP ROLE role1; -- operation successful
```
--- role assumed by a user
Log in as `monetdb`:
```
CREATE USER alice with password 'alice' name 'alice' schema sys;
CREATE ROLE role1;
GRANT role1 to alice;
```
Log in as `alice` and stay logged-in:
```
SET ROLE role1;
```
Back to `monetdb`
```
DROP ROLE role1;  -- operation successful
```

**Expected behavior**
Shouldn't the `DROP ROLE` be rejected?

**Software versions**
 - MonetDB version number [default]
 - OS and version: [e.g. Ubuntu 20.04]
 - Mercurial source

**Comment by PedroTadim** [comment]
From what I see from the source code, there's no dependency created between the role and the user. When the role is dropped, the connection between users and that role is dropped as well. So the next time the user logs in, it won't have the role anymore. This is similar to a previous bug where we don't propagate changes to live users.

**Comment by njnes** [comment]
indeed not a bug.
