### ISSUE TITLE
I cannot start MonetDB, because the installation path has Chinese.

### ISSUE THREAD

**Issue by GrapecityDuke** [MonetDB/MonetDB#7031]
**Describe the bug**
Use the M5Server.bat start MonetDb. Return error message.
![image](https://user-images.githubusercontent.com/76139677/102437011-bd29dd00-4054-11eb-8d56-1fd08cb4b152.png)

**To Reproduce**
If the installation path contains Chinese, the bug is reproduce.

**Expected behavior**
The MonetDb can started.

**Software versions**
 - MonetDB version number:11.37.7
 - OS and version: Windows 10

**Comment by PedroTadim** [comment]
We have started to look into this. We are missing an encoding conversion on Windows for sure.

**Comment by PedroTadim** [comment]
This is fixed on default and it will be available in the next feature release.
