### ISSUE TITLE
CREATE VIEW: duplicate column name v

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7032]
**Describe the bug**
When creating a view with multiple computed columns, it gives the error `CREATE VIEW: duplicate column name v`.

**To Reproduce**
```
create table t (i int);
-- one computed column gets the name 'v'
create view v1 as select i+1 from t;
select * from v1;
-- a second computed column triggers: CREATE VIEW: duplicate column name v
create view v2 as select i+1, i*10 from t;
-- while SELECT automatically creates unique names for the computed columns
select i+1, i*10 from t;

**Expected behavior**
Not sure if this is a bug or a feature.  Would be nice if `create view` also automatically generates unique names for the computed columns?

**Software versions**
 - MonetDB version number [v11.39.8 (hg id: 5a846c0ffc58)]
 - OS and version: [e.g. Ubuntu 20.04]
 - Mercurial source

**Comment by PedroTadim** [comment]
I stumbled upon this a few months back and I ignored it. I think this is expected behavior, because we can't evaluate what the column name sequence should be. PostgreSQL also gives a similar error:
demo=> create view v2 as select i+1, i*10 from t;
ERROR:  column "?column?" specified more than once

**Comment by yzchang** [comment]
what do you mean with "we can't evaluate what the column name sequence should be"?  I don't understand why we can't do the same thing for columns in a view as what we do for columns in a select?

**Comment by PedroTadim** [comment]
We could use a name sequence. So what do you want? Error a sequence of my own?

**Comment by yzchang** [comment]
sorry, I don't understand "Error a sequence of my own?"  Did you mean "Create a sequence of my own?"

**Comment by yzchang** [comment]
I don't have preferences or something but for consistency, maybe use the same type of generated column names as what SELECT does, i.e. '%1', '%2', etc?

**Comment by PedroTadim** [comment]
'%n' are our own internal identifiers. We don't allow column names (including in views) to start with the '%' character because of this reason.

**Comment by njnes** [comment]
the user should simply give each column a proper name.

**Comment by ghost** [comment]
A front-end not necessary can manipulate the query text to inject column aliases and has to rely on reflective analysis after the fact. Also from a puritan point of view, the creation of a table using an expression should ensure the same semantics as done manually.

**Comment by njnes** [comment]
but the query is simply incorrect, ie the user should fix this.

**Comment by swingbit** [comment]
I'm sure there is a reason, but I think what is not obvious to understand (not to me at least) is why is this incorrect:

```
create view v2 as select i+1, i*10 from t;
```

and this is instead correct (and generates automatic column names):

```
select i+1, i*10 from t;
```

They both project unnamed columns.

**Comment by njnes** [comment]
a view needs names and the table result doesn't.

**Comment by swingbit** [comment]
Of course. I see why, now. The select generates "names" only because it is the top-level statement, not because it is a select. These names are only used for display purposes but could not be used as identifiers. OK, I caught up with the world.

**Comment by ghost** [comment]
See also discussion in #7036
