### ISSUE TITLE
User with sysadmin role cannot create another user

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7034]
**Describe the bug**
Not sure if this is a bug or I did something wrong, but after a user has been granted and assumed the `sysadmin` role, this user still cannot create another user.

This question comes from the test `sql/test/Users/Tests/grantMonetdb.SQL.py`, in which the description says the user should then be able to create another user while the corresponding test is expected to fail.

The [documentation](https://www.monetdb.org/Documentation/SQLReference/DataDefinition/Privileges/GrantAndRevoke) says GRANT takes either `[WITH ADMIN OPTION]` or  `[WITH ADMIN grantor]`, but if I try `WITH ADMIN monetdb`, I just get an error.

**To Reproduce**
---- log in as `monetdb`
```
create user alice with password 'alice' name 'alice' schema sys;
grant sysadmin to alice with admin option;
-- using a granter fails with 'syntax error, unexpected IDENT, expecting OPTION in: "grant sysadmin to alice with admin monetdb" '
grant sysadmin to alice with admin monetdb;
```
---- log in as alice
```
sql>create user bob with password 'bo' name 'bob' schema sys;
CREATE USER: access denied for user 'alice'
```
**Expected behavior**
The `create user bob...` query should succeed.

**Software versions**
 - MonetDB version number [default]
 - OS and version: [e.g. Ubuntu 20.04]

**Comment by PedroTadim** [comment]
The documentation says:
grantor:
    CURRENT_USER | CURRENT_ROLE
so you cannot any user in the WITH ADMIN option

**Comment by yzchang** [comment]
But it's still not right:
```
sql>grant sysadmin to u with admin current_user;
syntax error, unexpected CURRENT_USER, expecting OPTION in: "grant sysadmin to u with admin current_user"
sql>grant sysadmin to u with admin current_role;
syntax error, unexpected CURRENT_ROLE, expecting OPTION in: "grant sysadmin to u with admin current_role"
sql>grant sysadmin to u with  current_role;
syntax error, unexpected CURRENT_ROLE, expecting ADMIN in: "grant sysadmin to u with  current_role"
sql>grant sysadmin to u with  current_user;
syntax error, unexpected CURRENT_USER, expecting ADMIN in: "grant sysadmin to u with  current_user"
```

Seems like the only syntax accepted is `WITH ADMIN OPTION`?

**Comment by sjoerdmullender** [comment]
Looks like it should be FROM CURRENT_USER etc.
The bison code says:
`GRANT privileges TO grantee_commalist opt_with_grant opt_from_grantor`
and opt_from_grantor has
`FROM grantor`.

**Comment by yzchang** [comment]
Seems only `monetdb` + `sysadmin` can create a user, so this is not a bug.
- documentation update
- [corrected the test instead](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=7b153446a92a)

**Comment by yzchang** [comment]
Reopen this issue: according to @njnes, a user who has assumed the `sysadmin` should be able to create (and drop) another user.  So this is a bug after all.  This is tested by `sql/test/Users/Tests/grantMonetdb.SQL.py`, which currently fails

**Comment by njnes** [comment]
this was fixed
