### ISSUE TITLE
UPDATE and SELECT column privileges

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7035]
**Describe the bug**
Not sure if this is a bug, but the error is a bit unexpected:

---- `usr` can SELECT column `a` and UPDATE column `b`:
```
create table t (a int, b int);
create user usr with password 'usr' name 'usr' schema sys;
grant select(a) on t to usr;
grant update (b) on t to usr;
```
---- log in as `usr`
```
select a from t; -- this works
update t set b = 23; -- this works
update t set b = 32 where a = 6; -- UPDATE: insufficient privileges for user 'usr' to update table 't'
```

**Expected behavior**
Since `usr` has SELECT right on `t(a)`, I'd expect the second UPDATE query to succeed.

**Software versions**
 - MonetDB version number [v11.39.8 (hg id: 20d5ae056058)]
 - OS and version: [e.g. Ubuntu 20.04]
 - Mercuria source

**Comment by PedroTadim** [comment]
Nice find, the column reduction based on privileges is missing for update queries. I'm adding them right now.

**Comment by yzchang** [comment]
for the record `update t set b = b + 1` currently works, which shouldn't, because usr has no SELECT right on column `b`.

All cases are tested in `sql/test/Users/Tests/columnRights.SQL.py`

**Comment by PedroTadim** [comment]
It's now fixed on Oct2020 branch.
