### ISSUE TITLE
Allow shell commands to be executed from within mclient

### ISSUE THREAD

**Issue by muhmud** [MonetDB/MonetDB#7039]
**Is your feature request related to a problem? Please describe.**
It should be possible to execute shell commands from within mclient.

**Describe the solution you'd like**
When supplied with a `\!`, for example, mclient should execute the rest of the line as a shell command

**Describe alternatives you've considered**
N/A

**Additional context**
This is a common feature of other SQL client tools.

**Comment by njnes** [comment]
shell commands is somewhat out of scope of the mclient
