### ISSUE TITLE
Variables changes

### ISSUE THREAD

**Issue by avo15** [MonetDB/MonetDB#7041]
Now that variables approach was changed existing declarations do not work. 
How can I create session/global variable in latest versions?
Would be nice to have web documentation updated with different examples

**To Reproduce**
DECLARE testvar integer;
SQL Error [42000]: Variables cannot be declared on the global scope

**Software versions**
 - MonetDB version number 11.39.7 (Oct2020-SP1)
 - OS and version: Fedora
 - Installed from release package 

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**

**Comment by PedroTadim** [comment]
We had to remove them from the global scope because it was not allowed by the standard. Use a procedure or the scripting language connecting the database for that.
