### ISSUE TITLE
Cannot build from source with R integration switched on trough brew for MacOS

### ISSUE THREAD

**Issue by amauryt** [MonetDB/MonetDB#7043]
I'm trying to enable embedded R for monetdb on MacOS 10.15.7 via homebrew. However the instructions on the official website seem to be outdated now that monetdb uses CMAKE. Therefore, I first made sure that I could successfully build from source with the default options from within homebrew after installing all dependencies, then I edited the brew formula to switch `RINTEGRATION` to `ON` but now the compilations fails at 72% with this error:

```
ld: can't map file, errno=22 file '/Library/Frameworks/R.framework' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [monetdb5/extras/rapi/lib_rapi.so] Error 1
make[1]: *** [monetdb5/extras/rapi/CMakeFiles/rapi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Perhaps my approach is not the most appropriate and there is another documented way to enable R integration that I missed?

By the way I have a working installation of R (v 4.0.2) on the directories that `FindLibR.cmake` seems to seek and the output of `R.home()` is `/Library/Frameworks/R.framework/Resources`.

**To Reproduce**

To edit the formula:

`brew edit monetdb`

Then change `DRINTEGRATION=OFF` to `DRINTEGRATION=ON`.

 Build (or rebuild) from source:

`brew [re]build -s monetdb`
 
**Expected behavior**
Successful compilation of monetdb with R integration enabled.

**Software versions**
 - MonetDB version number: Oct2020-SP1/MonetDB-11.39.7
 - OS and version: MacOS Catalina 10.15.7
 - Self-installed and compiled
 - R 4.0.2 from official package

**Comment by sjoerdmullender** [comment]
I just tried to reproduce, but failed.
I have R installed from homebrew, and I edited the monetdb formula like you said (just change OFF into ON on the appropriate line), and rebuilt.  No problems.  Afterwards, I see that it succeeded since the files that should be installed for R integration were indeed installed.
This is on Big Sur (11.1).  I don't have Catalina at my disposal.

**Comment by amauryt** [comment]
Thanks for the quick reply. I uninstalled my installation of R from the official CRAN MacOS package and then installed the R formula for homebrew `brew install r`. Now monetdb compiles with R integration without a problem.

However, installing the R brew formula and subsequent R packages is not as straightforward as with the official R MacOS package from CRAN. For instance, packages that already have binaries available will nevertheless be compiled with the brew formula installation (see [this discussion](https://community.rstudio.com/t/a-cran-extras-repository-for-the-hombrew-cask-version-of-r-experimental/9907/5)) and it is not recommended for most people [as stated by the maintainers of R](https://stat.ethz.ch/pipermail/r-sig-mac/2016-March/011890.html). Indeed, installing _tidiyverse_ by compilation took much much longer and gave many warnings compared to directly installing the binaries.

Unfortunately it appears that this is the easiest way on MacOS to integrate with other libraries and software, such as OpenBLAS, monetdb (seemingly), and until recently OpenMP.

It would be nice If there could be a way to compile monetdb with R integration while retaining the official CRAN R installation, but I'm not sure it is possible.

Anyhow, I realize that this would rather be an enhancement to the user experience as the R integration already works on MacOS with the brew R installation, so feel free to close this issue.
