### ISSUE TITLE
Improve error message regarding 3-level SQL names

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7044]
When a query (seems to) contain a 3-level SQL name, i.e. `foo.bar.baz`, it is rejected, with a message saying:

> TODO: column names of level >= 3

the line of code is in `sql/server/rel_select.c`:
```
		return sql_error(sql, 02, SQLSTATE(42000) "TODO: column names of level >= 3");
```
this bug is not about the missing feature, but about an error message. It should be clearer - as the query author may not realize what exactly they did wrong: They may not recognize the term "name level", or even not intended to have typed in one of the periods etc.

Please change it to something like:
> Use of 3-level SQL names (database_name.table_name.column_name) is not supported yet. You may only refer to tables within the database to which you have connected.

**Comment by njnes** [comment]
we have added 3 level naming. And hopefully for > 3 improved the error.
