### ISSUE TITLE
A value filtered in a subquery finds its way to a later filter in the outer query

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7045]
**Describe the bug**
A value filtered in a subquery finds its way to a later filter in the outer query.

**To Reproduce**

1. (Create and) connect to a MonetDB database 
2. Issue the following queries:
```
CREATE TEMPORARY TABLE delme AS SELECT '0-71' AS wheelsoff ON COMMIT PRESERVE ROWS;
INSERT INTO delme VALUES ('1550');
SELECT count(*)  FROM (SELECT wheelsoff FROM delme WHERE wheelsoff NOT LIKE '%-%') AS t WHERE cast(wheelsoff AS int) = 0;
CREATE TEMPORARY TABLE delme2 AS (SELECT wheelsoff FROM delme WHERE wheelsoff NOT LIKE '%-%') ON COMMIT PRESERVE ROWS;
SELECT count(*)  FROM delme2 WHERE cast(wheelsoff AS int) = 1550;
```
The first SELECT query fails with:
```
conversion of string '0-71' to type int failed.
```
even though the table `t` does not have such a value. And indeed, when we "split the work", using the last two commands, we do get the correct result in the last query.

**Expected behavior**
All queries should succeed. The last query should return 1.

**Software versions**
 - MonetDB 11.33.3
 - OS and version: Devuan Beowulf (~= Debian Buster without systemd)
 - Self-built with: `--enable-optimize --enable-rintegration` and extra compiler flags `-O3 -march=native`.

**Comment by PedroTadim** [comment]
I think someone issued this 1-2 years ago. We merge select relations without function calls then we reorder them according to a score which includes the type used in the comparison.What we can do is to attempt to disable the merging on more occasions.

**Comment by eyalroz** [comment]
You could also keep the merge, but notice the fact that something may be filtered out before triggering the error. Of course, that would be more of a coding effort.

**Comment by PedroTadim** [comment]
The issue is the conversion is performed first because it uses integers, while the like expression uses strings which is more expensive to compute. The candidate list is built on the integer comparison. As a declarative language, this is allowed in SQL.

**Comment by eyalroz** [comment]
In terms of SQL semantics, the query needs to succeed.

Now, execution-wise - it's fine to perform the conversion first - but it's wrong to consider the query to have failed if the conversion fails on elements which are actually filtered out. So, you would need to not "bail out" on an operator when encountering a conversion error, but rather convert everything you can, remembering which elements triggered an error; and if not all of those are filtered out, then you can complain to the user.

In order to avoid this overhead, I suppose you could first try an "optimistic" execution which bails out immediately and doesn't keep track of errors, and if it does bail out, you switch to an alternative plan.

Perhaps I would also put a question mark on whether the CAST should be considered all that cheaper than the LIKE. After all, it's also a string operation in this case - string parsing.
