### ISSUE TITLE
Current DockerImage

### ISSUE THREAD

**Issue by walter-weinmann** [MonetDB/MonetDB#7046]
Would it be possible to create a current docker image? The most current one seems to be https://hub.docker.com/layers/monetdb/monetdb/Jun2020-SP1/images/sha256-6599ebcdc4277ee0cc9755254c2c98c82f6520d67653b9acd51a4eb93e2f3cc5?context=explore

Thanks a lot.

**Comment by kutsurak** [comment]
Hi @walter-weinmann 

We pushed the latest release (Oct2020-SP2) on dockerhub. You should be able to get it using `docker pull monetdb/monetdb:Oct2020-SP2` We added this to our release process, so a new image should be pushed automatically every time we release a new version.

If you encounter issues let us know.
