### ISSUE TITLE
Syntax error indications should indicate where on the line the error occurred

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7047]
This is a requested feature.

In many parsers/compilers e.g. in C compilers, when a syntax error is found, its location indicated. 

Example: If you compile
```
int main()) {
    return 0;
}
```
with the GNU C Compiler, you get something like:
```
<source>:1:11: error: expected function body after function declarator
int main()) {
          ^
```
Now, in MonetDB we:

* Don't get the character index at which the error was encountered.
* Don't get a context with a caret indicating the location of therror (the last two lines in the example output.

I would think that information is available when MonetDB parses a command - and certainly it could be kept available. This would make life easier when typing in SQL commands manually.

**Software versions**
 - MonetDB 11.39.11 and earlier of course
 - OS and version: Devuan Beowulf
 - Built from source

**Issue labeling **
Something between a mis-feature and a feature request.

**Comment by PedroTadim** [comment]
This is something I have thought too, but at the moment we have to give low priority for this feature.
