### ISSUE TITLE
Implement an IF() builtin function

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7048]
Many DBMSes, including MySQL (and even Excel and LibreOffice Calc...) have a [function named IF()](https://www.w3schools.com/SQl/func_mysql_if.asp):
```
IF(condition, value_on_true, value_on_false)
```
This is a very useful function to have. It is basically syntactic sugar, since one can use:
```
CASE WHEN condition THEN value_on_true ELSE value_on_false END
```
except that the latter is more cumbersome to write and to read than the former, and doubly so when you want to nest these.

**Software versions**
 - MonetDB 11.39.11

**Comment by PedroTadim** [comment]
Hi Eyal, the MonetDB's equivalent for that function is "ifthenelse". Maybe we could add an alias for it.

**Comment by eyalroz** [comment]
@PedroTadim : Well, I don't see it here:

[Logical Functions and Operators](https://www.monetdb.org/Documentation/SQLReference/FunctionsAndOperators/LogicalFunctionsOperators)

... ah, ok, I found it here:

[Comparison functions and operators](https://www.monetdb.org/Documentation/SQLReference/FunctionsAndOperators/ComparisonFunctionsOperators)

but I would suggest maybe it should be mentioned under the first page as well.

An alias would be nice, but - apparently this function is not in the standard. In MS SQL server it's `IIF()`. I don't think PostgreSQL has such a function. So - up to you. (And you can decide to close this bug if you like.)
