### ISSUE TITLE
Implement DISTINCT for GROUP_CONCAT

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7049]
In MySQL, you can write:
```
SELECT GROUP_CONCAT(DISTINCT(c1)) AS c1_values FROM t1;
```
but MonetDB does not seem to allow the `DISTINCT` keyword within a GROUP_CONCAT.

It would be useful to have this feature.

**Comment by PedroTadim** [comment]
Hi Eyal! I try that statement in MonetDB and it runs fine. Am I doing something wrong?

**Comment by eyalroz** [comment]
@PedroTadim : I must have messed up my GROUP BY I guess. Sorry.
