### ISSUE TITLE
file descriptor leak when forward=redirect

### ISSUE THREAD

**Issue by karlseguin** [MonetDB/MonetDB#7050]
**Describe the bug**
When `forward=redirect`,a file descriptor leaks every time a connection is opened and then closed.

**To Reproduce**
./monetdbd create ./farm
./monetdbd set forward=redirect ./farm
./monetdbd set listenaddr=127.0.0.1 ./farm
./monetdbd start ./farm

./monetdb create test
./monetdb release test

lsof -p $(pidof monetdbd) | wc -l
40

./mclient -d test -s "select 1"
lsof -p $(pidof monetdbd) | wc -l
41

./mclient -d test -s "select 1"
lsof -p $(pidof monetdbd) | wc -l
42

./mclient -d test -s "select 1"
lsof -p $(pidof monetdbd) | wc -l
43

**Software versions**
 - 11.39.11 and 11.39.7
 - Ubuntu 20.04
 - self-installed

**Comment by PedroTadim** [comment]
Thanks for the report, I already found a culprit and just committed a fix for it.
