### ISSUE TITLE
monetdb "set role sysadmin": Role (sysadmin) missing

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7054]
**Describe the bug**
If I log in as the `monetdb` user and run `set role sysadmin;`, I get `... createExceptionInternal: !ERROR: SQLException:sql.update_var:42000!Role (sysadmin) missing'.

Is this expected?

**Software versions**
 - MonetDB version number [Oct2020, 0a258a97c2c0]
 - OS and version: Fedora 32
 - Mercurial source

**Comment by PedroTadim** [comment]
The mvc_set_role call expects a connection from the user to the role at the "user_role" for the set to succeed. I see there's no connection from the "monetdb" user and the "sysadmin" role. Now if this is expected I could say yes, but the discussion can proceed.

**Comment by yzchang** [comment]
Ah, I see.  Since the `monetdb` user can do all the admin type of work, I assumed it also has the `sysadmin` role. Not a bug then.
