### ISSUE TITLE
We are performing  DROP - CREATE - DELETE - INSERT - COMMIT on a table, All data in the table is lost

### ISSUE THREAD

**Issue by bharaththam** [MonetDB/MonetDB#7056]
**Describe the bug**
While running DROP - CREATE - DELETE - INSERT - COMMIT on a table, All data in the table getting lost. 

**To Reproduce**
Where seven jobs executed parallel at a time and  seven tables are created and data is inserted to table out of seven jobs five jobs are completed successfully and two of the jobs are failed and tables are empty in new verison ( MonetDB interactive terminal, version 11.39.11 (Oct2020-SP2))

When same seven set of jobs are executed in old version it is running fine and getting the expected results( MonetDB 5 server v11.27.13 "Jul2017-SP4")

**Expected behavior**
Table data should exists in all seven tables in New verison  ( MonetDB interactive terminal, version 11.39.11 (Oct2020-SP2))
 

**Software versions**
Versions:
MonetDB/SQL interactive terminal (Oct2020-SP2)
Database: MonetDB v11.39.11 (Oct2020-SP2), 
[monetadmin@lnx1538 ~]$ mclient -v
mclient, the MonetDB interactive terminal, version 11.39.11 (Oct2020-SP2)
support for command-line editing compiled-in
yum install https://dev.monetdb.org/downloads/epel/MonetDB-release-epel.noarch.rpm
yum install MonetDB-SQL-server5 MonetDB-client
-rwxrwxr-x 1 monetadmin monetadmin 1.6M Feb  2  2021 MonetDB-11.39.11-20210118.el7.x86_64.rpm
-rwxrwxr-x 1 monetadmin monetadmin 1.5M Feb  2  2021 MonetDB5-server-11.39.11-20210118.el7.x86_64.rpm
-rwxrwxr-x 1 monetadmin monetadmin 145K Feb  2  2021 MonetDB-client-11.39.11-20210118.el7.x86_64.rpm
-rwxrwxr-x 1 monetadmin monetadmin 145K Feb  2  2021 MonetDB-SQL-server5-11.39.11-20210118.el7.x86_64.rpm

let me know if you need any details

**Comment by bharaththam** [comment]
Can you please check and update on my bug

**Comment by PedroTadim** [comment]
Can you give a reproducible script? That's because with concurrent create and drop table statements, I would expect transaction conflicts.

**Comment by bharaththam** [comment]
please find the below detailed issue and script:
Issue Definition:
The scenario performed is for data loads where in - DROP - CREATE - DELETE - INSERT - COMMIT statements are run on a table. It is observed that data is lost #7056

Overview on issue:
Issue is observed while doing concurrency loads of two tables, as for example load1 as VN and Load2 as RL, concurrently run. The issue is observed in latest version of Monet 11.39.11 SP2 version.

The above same scenario has been working consistently well in the older version 11.27.13. 

Steps to replicate:
1.	Load1 - COPY INTO from file as below:
COPY INTO "DM_POS_TSV_MRT_P6"."VN_DSJ_TEST_8135" FROM ( '/nztoexa/tst/mdm_mig/crosscut_output/upgrade_testing/tsv23_eb_jr/output/vn_dsj_TEST_8135_tsv23_eb_jr_2021-01-25_16-42-53.dat' )
      USING DELIMITERS '|','\n','"' null as '';
Record count: 3887524 				Column count: 10

2.	Load2 - COPY INTO from file as below:
COPY INTO "VGRLSBL_STG_TEST_WB1702" FROM ( '/nztoexa/tst/mdm_mig/crosscut_output/upgrade_testing/tsv23_eb_jr/output/../rltnl_stage/rlsbl_tsv23_eb_2159.dat' )
      USING DELIMITERS '|','\n','\"' null as '';
Record count: 244727518					Column count: 6
3.	Log shows data got loaded to the VN table and it is printing correct number of records #3887524
4.	Post 2-3 min, when you check for record count, table shows zero records sometimes.

5.	When load1 and load2 are successful in DB (having records in DB).
6.	Immediate after load1 is completed, there is another script starts which keeps on dropping and creating almost 2882 tables
Below are the sample queries 

a.	DROP TABLE IF EXISTS "TEST_VN_S_49073_8135_O";
CREATE TABLE "TEST_VN_S_49073_8135_O" (ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER) AS SELECT ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER FROM "VN_DSJ_TEST_8135" WHERE COL_NAME='S_49073_KEY' AND SORT_TYPE='ORTH';

b.	DROP TABLE IF EXISTS "TEST_VN_S_49073_8135_C";
CREATE TABLE "TEST_VN_S_49073_8135_C" (ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER) AS SELECT ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER FROM "VN_DSJ_TEST_8135" WHERE COL_NAME='S_49073_KEY' AND SORT_TYPE='CATG';

7.	VN Table load is failing with reason as 0 records in DB, load2 (RL) table got loaded successfully

**Comment by bharaththam** [comment]
could  you please check and update us on the above issue

**Comment by PedroTadim** [comment]
Your reproduction script is not clear to me. I don;t see any delete statement there. Between points 3 and 4, are there concurrent writes on the database besides load1 and load2?

**Comment by bharaththam** [comment]
Point 6 queries are getting executed immediately once the “Load 1” is completed and this point 6 queries are execute in between point 3 and 4. Till the point 6 is complete, we see data in table. Not sure at that time whether the data for the table were in cache memory or not, because after few minutes we see 0 records in "VN_DSJ_TEST_8135" table but all the 2882 tables have data which taken  from "VN_DSJ_TEST_8135" table as below.

6.	Immediate after load1 is completed, there is another script starts which keeps on dropping and creating almost 2882 tables
Below are the sample queries 

a.	DROP TABLE IF EXISTS "TEST_VN_S_49073_8135_O";
CREATE TABLE "TEST_VN_S_49073_8135_O" (ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER) AS SELECT ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER FROM "VN_DSJ_TEST_8135" WHERE COL_NAME='S_49073_KEY' AND SORT_TYPE='ORTH';

b.	DROP TABLE IF EXISTS "TEST_VN_S_49073_8135_C";
CREATE TABLE "TEST_VN_S_49073_8135_C" (ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER) AS SELECT ATTR_NAME, COL_NAME, AVP_KEY, ATTR_VALUE, ATTR_LONG_VALUE, ATTR_SHORT_VALUE, ATTR_MEDIUM_VALUE, PARENT_AVP_KEY, SORT_ORDER FROM "VN_DSJ_TEST_8135" WHERE COL_NAME='S_49073_KEY' AND SORT_TYPE='CATG';

7.	Also after the Point 6 is completed, the next job executes with below queries on different tables.
drop table "DM_POS_TSV_MRT_P6"."VN_DIM_TEST_8135_TEMP" cascade;
create table "VN_DIM_TEST_8135_2158_BKP" as select * from "VN_DIM_TEST_8135";

create table "VN_DIM_TEST_8135_TEMP" as select * from "VN_DIM_TEST_8135" 
where venue_dim_key in (select distinct venue_dim_key from "VG_STORE");--Record count: 128063

delete from "VN_DIM_TEST_8135"; --Record count: 129219

insert into "VN_DIM_TEST_8135" select * from "VN_DIM_TEST_8135_TEMP"; --Record count:129219
DROP TABLE IF EXISTS "VN_DIM_TEST_8135_2158_BKP" CASCADE; --Record count: 129219

**Comment by bharaththam** [comment]
could you please update me on the above points

**Comment by bharaththam** [comment]
we are making an assessment  on upgrading to new verison, it would help us if you provide the quick re-solution

**Comment by PedroTadim** [comment]
Can you wrap up a reproducible python script? Then I can look into it.
