### ISSUE TITLE
MonetDBe: COPY INTO csv file does not produce any output

### ISSUE THREAD

**Issue by MitchellWeg** [MonetDB/MonetDB#7058]
**Describe the bug**
Within MonetDBe, `COPY SELECT * FROM foo INTO '/file/path.csv'"` does not fill the output csv file.

**To Reproduce**
Within MonetDBe (Python & C) `COPY SELECT * FROM foo INTO '/file/path.csv'"`. 
See newly created [Test](https://github.com/MonetDBSolutions/monetdbe-examples/blob/CI/C/copy_into.c)

**Expected behavior**
Resulting file contains query result.

**Software versions**
 - MonetDB V 11.40.0
 - Ubuntu 18.04
 - Built from source

**Comment by ghost** [comment]
Fixed in 2962a31752e51cd5146acd6557835a63316b030a Added also a test `example_copy.c`
