### ISSUE TITLE
MonetDBe: 'reverse' C UDF crashes

### ISSUE THREAD

**Issue by ankravch** [MonetDB/MonetDB#7059]
**Describe the bug**
'reverse' C UDF crashes when queried from within MonetDBe

**To Reproduce**
// MonetDBe C API,  getstarted.c example with the query
monetdbe_query(db, "SELECT reverse('abc');", NULL, NULL);

**Expected behavior**
It should produce the same result as MonetDB for "SELECT reverse('abc');" query.

**Software versions**
 - monetdb v11.39.5
 - centos 7
 - built from source

**Comment by PedroTadim** [comment]
On changeset https://dev.monetdb.org/hg/MonetDB/rev/9b1b9a581b1a I pushed a fix for this. Can you test it please? Thanks.

**Comment by ankravch** [comment]
It works as expected now.  Thanks.
