### ISSUE TITLE
Have bulk load support combined gzip files

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7061]
I'm using `monetdbe` on Ubuntu 18.04, but I assume the server version handles this similarly.

Sometimes I work with files that are concatenations of multiple runs of the `gzip` command. This functionality is documented in `man gzip`, i.e. `command1 | gzip > foo.gz; command2 | gzip >> foo.gz` leaves us with a file that can be read normally by tools like `zcat` or `gunzip`. Not sure if this is what every reader of gz data expects or not.

I was loading many tables from Postgres into Monet, and compressing them before upload. I found that parallelizing the compression with GNU Parallel sped up the pipeline significantly.

However, I later found that this change was silently giving me partial loads. Here is a Bash script to reproduce:

```
rm -f foo.gz foo.multiple.gz

# 1M long foos, gzipped
yes "fooooooooooooooooooooo" | head -n 1000000 | gzip > foo.gz

# 1M long foos, gzipped in parallel, with resulting chunks concatted
# "parallel" is GNU parallel
yes "fooooooooooooooooooooo" | head -n 1000000 |
    parallel --jobs 5 --keep-order --pipe --block 1M gzip >> foo.multiple.gz

# Show they are the same content when uncompressed
zcat foo.gz | sha1sum
zcat foo.multiple.gz | sha1sum

PLAIN_PATH=$PWD/foo.gz
MULTI_PATH=$PWD/foo.multiple.gz

python <<EOF
import monetdbe
conn = monetdbe.connect('foo.db')
cursor = conn.cursor()

cursor.execute("CREATE TABLE foo (bar TEXT)")
cursor.execute("CREATE TABLE foo_multiple (bar TEXT)")

cursor.execute("COPY 1000000 RECORDS INTO foo FROM '$PLAIN_PATH'")
cursor.execute("COPY 1000000 RECORDS INTO foo_multiple FROM '$MULTI_PATH'")

cursor.execute("SELECT count(1) FROM foo")
print(cursor.fetchall())
cursor.execute("SELECT count(1) FROM foo_multiple")
print(cursor.fetchall())
EOF
```

This prints:
```
b72c6df2ee74c49fa6dbc2cd51f1382defd6578d  -
b72c6df2ee74c49fa6dbc2cd51f1382defd6578d  -
[(1000000,)]
[(45590,)]
```

So, the copy stops after ~4.5% of the file, with no warning. Since my 1MB chunks were 4.5% of the 22MB uncompressed size, it must be stopping after one chunk.

This isn't a blocker for me at the moment, but it caused some confusion for a while, and could inconvenience some people who are given certain kinds of gz files. I spent about an hour checking for oddities in my CSV data/delimiters/escapes, and wondering if maybe the parser combined half of a file into one record.

PS: I've been using Monet for a few days and am very impressed so far!

**Comment by PedroTadim** [comment]
Once I get time I will look into this.

**Comment by kutsurak** [comment]
I have reproduced it on Oct2020 and I will take a look at it later today.

**Comment by joerivanruth** [comment]
Concatenated compressed files currently seem to work with lz4 and xz, and not with gzip and bz2. I'll see if I can fix this, I seem to recall that for some compression schemes there was a flag you could pass to the library to get this behavior.

**Comment by joerivanruth** [comment]
Fixed this, will be part of the next release.
