### ISSUE TITLE
ANALYZE MERGE TABLE is not persistent

### ISSUE THREAD

**Issue by ankravch** [MonetDB/MonetDB#7062]
**Describe the bug**
ANALYZE on merge table throws 'MERGE TABLE is not persistent'

**To Reproduce**
```
create table table t(v int);
insert into t values(1),(2),(3);

create merge table mt(v int);
alter table mt add table t;

analyze sys.mt;
```
**Expected behavior**
- merge table should exist in sys.storage table 
- ANALYZE should fill out sys.statistics for merge table

**Software versions**
 - monetdb v11.39.5
 - centos 7
 - built from source

**Comment by yzchang** [comment]
I'm not sure, but it makes sense to me that ANALYZE would only analyse a normal SQL table, i.e. persistent.  The error message is a bit funny though.

**Comment by ankravch** [comment]
I am following MonetDB tutorial at https://www.monetdb.org/Documentation/ServerAdministration/DistributedQueryProcessing/DataPartitioning.  And at the very bottom it says "To prepare these statistics, the user has to run the ANALYZE command over a MERGE TABLE".

**Comment by PedroTadim** [comment]
The analyze command throws error for merge tables for a long time (I found doing this as back as Mar2018 release). Also the error message has been the same before my changes (why is it funny?). This can be either a documentation mistake, because the analyze command should be applied to the children tables, or we can add support for merge tables, by applying it recursively.

**Comment by yzchang** [comment]
The error message is not straightforward, requires a second thought.

I was also thinking that translate an ANALYZE <merge table> into ANALYZE <each-child-table-of-the-merge-table> should be easy to do.  But
- how do you present the results?  merge all stats together and present them for one merge table? => this will require some additional calculations.
- the children tables can be updated, and children tables can be added to or removed from a merge table.
