### ISSUE TITLE
MonetDB crash after  (Oct2020-SP3)

### ISSUE THREAD

**Issue by warrenmaster** [MonetDB/MonetDB#7067]
[**Describe](url) the bug**

**To Reproduce**
Create a setting with minimal input for an external user to demonstrate him the buggy behavior.
This includes the relevant part of the database  schema description.
Performance trace of the roque query (using the TRACE command)

**Expected behavior**

**Screenshots**

**Software versions**
 - MonetDB version number [a milestone label]
 - OS and version: [e.g. Ubuntu 18.04]
 - Installed from release package or self-installed and compiled

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**
[log.txt](https://github.com/MonetDB/MonetDB/files/6029638/log.txt)

**Comment by warrenmaster** [comment]
log attached

**Comment by PedroTadim** [comment]
Hi! From the log, it's difficult to guess where the server crashed. Can you load the server with debug symbols and provide the stack trace? Thanks
