### ISSUE TITLE
Out of memory issue when performing large parallel data imports

### ISSUE THREAD

**Issue by muhmud** [MonetDB/MonetDB#7068]
**Describe the bug**
When performing a large data import from MySQL to MonetDB using Pentaho PDI (aka Kettle), all available memory will very often be completely consumed, causing MonetDB to error and the import to fail. The import job parallelizes its workload, so data for multiple tables will be ingested into MonetDB at the same time.

The following command can be used to view free and available memory slowly diminishing:

```bash
$ watch 'cat /proc/meminfo | grep Mem'
```

It is interesting to note that after several attempts at performing the import, without making any changes, memory usage will finally become more stable, and will be allocated and released in a continual cycle, thereby allowing the import to succeed. This was, however, on a previous version of MonetDB.

The machine used to host MonetDB in this scenario has 64 GB of physical memory and is not used for any other workloads.

**To Reproduce**
Perform a sizable data import into MonetDB using the Pentaho PDI framework, preferably for multiple tables in parallel, and monitor memory usage. The job should fail and messages such as the following should appear in the `merovingian.log` file:

* `MT_mmap: !ERROR: mmap(/var/monetdb5/dbfarm/olap/bat/37/75/377511.tail,393216) failed: Cannot allocate memory`
* `GDKmmap: !ERROR: requesting virtual memory failed; memory requested: 393216, memory in use: 41398916512, virtual memory in use: 98137560480`
* `HEAPalloc: !ERROR: Insufficient space for HEAP of 393216 bytes.`

**Expected behavior**
The MonetDB memory footprint during such imports should remain stable, with memory freed up as data is written to disk.

**Software versions**
 - MonetDB version number: Oct2020-SP3
 - OS and version: Amazon Linux 2
 - Installed using Docker

**Comment by PedroTadim** [comment]
We noticed a memory leak in Oct2020 at the logger level. However I haven't seen it appearing on default branch. Maybe what are you noticing is this leak.

**Comment by muhmud** [comment]
It could be.

To give further details, I amended my code to not parallelize the import and this appeared to successfully address the memory leak issue, however, after a while performance became completely unacceptable, with MonetDB taking minutes to write small batches of 50K rows.

In the end, I had to return to Jun2020-SP1.

I'm going to try to put together a self-contained test case so that you can reproduce the issue I'm having.

**Comment by PedroTadim** [comment]
Thanks for the report. We will look into the test case.

**Comment by PedroTadim** [comment]
We did a fix on a issue similar to this one on Oct2020 a while back.
