### ISSUE TITLE
double free error when running MonetDBe Example

### ISSUE THREAD

**Issue by arifsaeed** [MonetDB/MonetDB#7070]
**Describe the bug**
When I run the "getstarted" example code from https://github.com/MonetDBSolutions/monetdbe-examples on C++. I get the following error when the function monetdbe_close(&db) runs.
`free(): double free detected in tcache 2`

**To Reproduce**
To get the code to run on a C++ compiler I had to make a slight change to the SQL strings passed to the functions, i.e. I created char arrays as shown below that were passed to the functions.

     `char createTableSQL[46]="CREATE TABLE integers(i INTEGER, j INTEGER);"; `
     `char insertSQLChar[58]= "INSERT INTO integers VALUES (3, 4), (5, 6), (7, NULL);"; `
      `char selectSQL[23]="SELECT * FROM integers";`

---------------------------THE FULL CODE IS BELOW--------------------------------------------------------
#include "monetdbe.h"
#include <stdlib.h>
#include <stdio.h>
#include <inttypes.h>
#include <string.h>
#define error(msg) {fprintf(stderr, "Failure: %s\n", msg); return -1;}  

int main(){
   monetdbe_database db = NULL;
    monetdbe_result *result;
    monetdbe_column *cols[2];
    long int rows_affected = 0;
    char createTableSQL[46]="CREATE TABLE integers(i INTEGER, j INTEGER);";
    char insertSQLChar[58]= "INSERT INTO integers VALUES (3, 4), (5, 6), (7, NULL);";
    char selectSQL[23]="SELECT * FROM integers";

    if (monetdbe_open(&db, NULL /* inmemory database */, NULL /* no options */)) {
        fprintf(stderr, "Failed to open database\n");
        return -1;
    }
    if (monetdbe_query(db, createTableSQL, NULL, NULL) != NULL) {
        fprintf(stderr, "Failed to query database\n");
        goto cleanup;
    }   
    if (monetdbe_query(db, insertSQLChar, NULL, &rows_affected) != NULL) {
        fprintf(stderr, "Failed to query database\n");
        goto cleanup;
    }
    printf("inserted %d rows\n", (int)rows_affected);
    if (monetdbe_query(db, selectSQL, &result, NULL) != NULL) {
        fprintf(stderr, "Failed to query database\n");
        goto cleanup;
    }
    // print the names of the result
    for (size_t i = 0; i < result->ncols; i++) {
        monetdbe_result_fetch(result, &cols[i], i);
        printf("%s ", cols[i]->name);
    }
    printf("\n");
    // print the data of the result
    for (size_t row_idx = 0; row_idx < result->nrows; row_idx++) {
        for (size_t col_idx = 0; col_idx < result->ncols; col_idx++) {
            assert(cols[col_idx]->type == monetdbe_int32_t);
            monetdbe_column_int32_t *col = (monetdbe_column_int32_t *)cols[col_idx];
            int val = col->data[row_idx];
            if (val == col->null_value)
                printf("NULL ");
            else
                printf("%d ", val);
        }
        printf("\n");
    }

     
	cleanup:
    	monetdbe_cleanup_result(db, result);
    	monetdbe_close(&db);
}

---------------------------END OF FULL CODE SECTION--------------------------------------------------------

**Expected behavior**
I was expecting the monetdbe_close function to execute with no errors

**Software versions**
 - MonetDB-master from Github on 26th February 2021
 - Ubuntu 20.04
 - I downloaded the code from this link https://github.com/MonetDB/MonetDB.git and then ran
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
        I then added the following path to my target_link_libraries in my CMakeLists.txt file
              MonetDB-master/build/tools/monetdbe/libmonetdbe.so
        and added a path to the following two header files in  target_include_directories in my CMakeLists.txt file        
         monetdbe.h 
        monetdb_config.h
        

**Issue labeling **
bug 

**Additional context**

**Comment by ankravch** [comment]
You should replace 
```
monetdbe_close(&db);
```
with
```
monetdbe_close(db);
```
as expected by monetdbe_close signature at https://github.com/MonetDB/MonetDB/blob/c3910e2d9e75ab08f261efd22f86a060c112052b/tools/monetdbe/monetdbe.h

**Comment by njnes** [comment]
thanks for the fix. Also added this now to the build setup.
