### ISSUE TITLE
cgroups' hard/soft memory limits are considered in the wrong order

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7073]
This comes after a discussion in https://www.monetdb.org/pipermail/users-list/2021-March/010850.html (thanks Sjoerd for the feedback), triggered by MonetDB being unexpectedly killed.

GDK's `GDK_mem_maxsize` is a **soft** limit for committed memory, in practice for `malloc()`-like allocations. How it is exactly used in MonetDB is not very important here, what is important is that it can be regarded as a soft limit: MonetDB uses it to calibrate its memory management, but can in practice allocate more memory.

Its value is set this way:
- By default, `GDK_mem_maxsize = 0.815 * <system memory>`.
- If a limit is set via cgroups, then `GDK_mem_maxsize = 0.815 * <cgroups limit>`
- If it is set via cmdline, then `GDK_mem_maxsize = <cmdline value>`

The issue is in the setting via cgroups. I'll use cgroups v1 here, but the same holds for v2.

The current logic is `GDK_mem_maxsize = 0.815 * (memory.limit_in_bytes || memory.soft_limit_in_bytes)`,
meaning that if `memory.limit_in_bytes` is defined, then it has precedence over `memory.soft_limit_in_bytes`.

I don't think this is correct, because it is (preferably) assigning a hard limit to a soft limit. This can cause problems. Imagine a container (or any other way of settings cgroups limits) setting both a soft and a hard limit. The soft limit will be ignored, MonetDB will use the hard limit as a soft one, and will have a high chance of hitting it, causing an OOM.
This is in fact what is happening in my case.

I think the right logic should be: `GDK_mem_maxsize = 0.815 * (memory.soft_limit_in_bytes || memory.limit_in_bytes)`, i.e. the soft limit should have priority.

Even better, I think: `GDK_mem_maxsize = memory.soft_limit_in_bytes || 0.815 * memory.limit_in_bytes`. 
This would be more in line with the setting via cmdline, and would be more logical. It makes sense to say `soft = 80% hard`. It doesn't make sense to say `soft = 80% soft`. If a soft limit is given, it should be trusted.

I am not entirely sure whether the same holds for `GDK_vm_maxsize`, because that one can be more regarded as a hard limit from within MonetDB. My intuition though is that it still should be associated with the soft limit coming from cgroups, because cgroups' hard limits should be the last safety guard from the kernel point of view, not settings for applications.

**Comment by yzchang** [comment]
Hai Roberto,

I was just wondering, if your main goal is limiting MonetDB's memory consumption, how about only use the gdk_mem_maxsize and gdk_vm_maxsize settings without using cgroup?  In this way, MonetDB will try to stay within those limits and won't get (immediately) killed when it temporarily exceeds them.

Regards,
Jennie

**Comment by swingbit** [comment]
Hi Jennie,

Of course what you say makes sense.
I have 3 observations about this:

1. No matter how I solve my issue, I think there is a logic mistake in how those limits are handled.
2. Setting limits to a Docker container is much more convenient and makes more sense in a production environment. This should be the way to go.
3. Setting `gdk_vm_maxsize` and `gdk_vm_maxsize` can only be done via `monetdb set`. This is *extremely* inconvenient in a dockerized deployment. It means you have to execute the command, and the container is not instructed to do so. When it starts, `monetdbd` is executed. It doesn't know yet which databases are there and it shouldn't try to change the settings every time.
It would be a viable solution if I could set parameters via environment variables or via a configuration file. The best I could do is to overwrite `<dbfarm>/<db>/.merovingian_properties`. However, that is also not very convenient.

**Comment by yzchang** [comment]
Thanks for your detailed explanation.  Sorry that I don't have direct answer to your questions, but now I have better understand why simply setting those options is not sufficient for the type of production env. you're using.

**Comment by swingbit** [comment]
Jennie, thanks for your suggestion! 
For now, I have used docker option `oom_kill_disable` to at least prevent the kill.
The effect should be that the hard limit is used *only* as a soft limit by  MonetDB, but won't trigger OOM. 
This is nothing more than an ugly (and dangerous) workaround that completely abuses the role of those limits, but I hope it will do for now.
Hopefully I can remove it when the bug is fixed.

**Comment by swingbit** [comment]
**UPDATE**

I went through that piece of code again, and I now see that I had not read it correctly.

The current code does give priority to the soft limit before the hard limit. It fooled me because it looks at the hard limit first, but then it allows the soft limit to overwrite it.

The reason why it did not behave as expected was not due to a wrong order, but it is in fact related to #6882 (cgroups limits were not found). 
Sjoerd had made a fix for that in Oct2020, but I needed in Nov2019, so I backported it locally. However, I now see that my backport was incomplete: I had missed the `memory.soft_limit_in_bytes` case, so that one was still not found.

I will close this ticket, and open a different one on a related issue I noticed while testing all this.

**Comment by v-from-meiro** [comment]
Hi @swingbit 

Have you made any progress on the OOM running MonetDB in the cgroup? I may be facing the same issue, where MonetDB goes over the limit of memory.limit_in_bytes quite a lot, getting killed by OOM. 

In a try to prevent it from happening, I set mem_reservation in docker-compose v2, which translates to memroy.soft_limit_in_bytes, but MonetDB is still using quite a lot of memory over this limit (limit_in_bytes set to 21G, soft_limit_in_bytes set to 14G and I see spikes at 19G used, uncomfortably close to the hard limit of the container).

Anything I may do or set up to prevent the OOMs?
