### ISSUE TITLE
Inconsistent Results using CTEs in Large Queries

### ISSUE THREAD

**Issue by PeteMillington** [MonetDB/MonetDB#7075]
Hello MonetDB Team. We have a MonetDB query that makes use of three CTE steps within the query. The first two steps generate results over a million records each. The correct expected result should also yield millions of records.

However, the use of the first CTE results in the third CTE expression yields an incomplete result. Alternatively. when we save the interim result of the first two steps into stand-alone tables, the application of the third step (using these new table references) yields the proper result (millions of records).

Is it a know issue that CTE constructs can drop records during a query? We have provided a specific example below. The attached zip file contains three csv files that can be used to generate three tables (dummy_src_table, dummy_calendar_table & dummy_calendar_image) to perform the test queries below. Note that the csv file for the dummy_calendar_image table was generated from the intermediate result of QUERY #2's CTE (calendar_image).

Is this behavior with large CTE expression a known issue in MonetDB?

DETAILS FOLLOW...

------------------- START: QUERY #1 -------------------
-- THIS WORKS PROPERLY YIELDS 1,476,736 RECORDS ...

WITH x AS
(
    SELECT
          dummy_calendar_image."FX",
          dummy_calendar_image."Dates",
          dummy_calendar_image."Dates_no",
          dummy_src_table."Values_"

    FROM dummy_calendar_image
    LEFT JOIN dummy_src_table
         ON dummy_calendar_image."FX" = dummy_src_table."FX"
         AND dummy_calendar_image."Dates" = dummy_src_table."Dates"
)
SELECT COUNT(*) FROM x;
-------------------- END: QUERY #1 --------------------

------------------- START: QUERY #2 -------------------
-- THIS DOES NOT WORK PROPERLY...YIELDS 156,383 RECORDS
WITH range_table as
(

      SELECT
          dummy_src_table."FX",
          dummy_src_table."Dates",
          dummy_calendar_table."freq_idx" AS "min_Dates_no",
          dummy_calendar_table."freq_idx"+5 AS "max_Dates_no"
      FROM dummy_src_table
      JOIN dummy_calendar_table
        ON dummy_calendar_table."Dates" = dummy_src_table."Dates"
      WHERE dummy_calendar_table."freq" = 'WEEKDAY'
)
, calendar_image as (
      SELECT
         DISTINCT range_table."FX",
         dummy_calendar_table."Dates" AS "Dates",
         dummy_calendar_table."freq_idx" as "Dates_no"

      FROM range_table

      JOIN dummy_calendar_table ON dummy_calendar_table."freq_idx" >= range_table."min_Dates_no"
        AND dummy_calendar_table."freq_idx" <= range_table."max_Dates_no"

      WHERE dummy_calendar_table."freq" = 'WEEKDAY'
        AND dummy_calendar_table."Dates" <= '2021-03-10'
)
, x2 AS
(
    SELECT
          calendar_image."FX",
          calendar_image."Dates",
          calendar_image."Dates_no",
          dummy_src_table."Values_"

    FROM calendar_image
    LEFT JOIN dummy_src_table dummy_src_table
        ON calendar_image."FX" = dummy_src_table."FX"
        AND calendar_image."Dates" = dummy_src_table."Dates"
)
SELECT COUNT(*) FROM x2;
-------------------- END: QUERY #2 --------------------
[dummy_csv_files.zip](https://github.com/MonetDB/MonetDB/files/6126594/dummy_csv_files.zip)

**Comment by PedroTadim** [comment]
I'm looking into it, I can confirm the result for the second query is wrong.

**Comment by PeteMillington** [comment]
Hi Pedro,

Thanks for the response and for looking into the issue. In case it helps, we are using MonetDB Oct2020-SP3.

Thanks again,

Peter Millington


-------- Original message --------
From: Pedro Ferreira ***@***.***>
Date: 3/12/21 8:33 AM (GMT-05:00)
To: MonetDB/MonetDB ***@***.***>
Cc: Pete Millington ***@***.***>, Author ***@***.***>
Subject: Re: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)


I'm looking into it, I can confirm the result for the second query is wrong.

**Comment by PedroTadim** [comment]
We found and fixed two issues: range expressions with different sizes were not merged, which made the query much slower and the mergetable optimizer didn't split multi-assignments. Can you try to test it on default branch? It should be ready for the next feature release.

**Comment by PeteMillington** [comment]
Hello Pedro,

Thank you fir the message and for addressing this issue.

We will look to install and test using the default branch of MonetDB.

Much appreciated.

Have a good day.

Peter Millington
Scientific Financial Systems


-------- Original message --------
From: Pedro Ferreira ***@***.***>
Date: 3/18/21 9:28 AM (GMT-04:00)
To: MonetDB/MonetDB ***@***.***>
Cc: Pete Millington ***@***.***>, Author ***@***.***>
Subject: Re: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)


We found and fixed two issues: range expressions with different sizes were not merged, which made the query much slower and the mergetable optimizer didn't split multi-assignments. Can you try to test it on default branch? It should be ready for the next feature release.

**Comment by PeteMillington** [comment]
Hello Pedro,

Thank you again for addressing this issue. Your quick response is much appreciated.

Just wondering if/where I can find the (*.msi) Windows binary installers for the default branch with this code fix to bug #7075? Similarly for the Ubuntu Linux installation files for the latest default branch.

Best regards,

Pete Millington
Scientific Financial Systems

From: Pete Millington ***@***.***>
Sent: Thursday, March 18, 2021 11:38 AM
To: MonetDB/MonetDB ***@***.***>; MonetDB/MonetDB ***@***.***>
Cc: Author ***@***.***>; Marc ***@***.***>
Subject: RE: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)

Hello Pedro,

Thank you fir the message and for addressing this issue.

We will look to install and test using the default branch of MonetDB.

Much appreciated.

Have a good day.

Peter Millington
Scientific Financial Systems


-------- Original message --------
From: Pedro Ferreira ***@***.******@***.***>>
Date: 3/18/21 9:28 AM (GMT-04:00)
To: MonetDB/MonetDB ***@***.******@***.***>>
Cc: Pete Millington ***@***.******@***.***>>, Author ***@***.******@***.***>>
Subject: Re: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)


We found and fixed two issues: range expressions with different sizes were not merged, which made the query much slower and the mergetable optimizer didn't split multi-assignments. Can you try to test it on default branch? It should be ready for the next feature release.

-

**Comment by PedroTadim** [comment]
The fix is also available on Oct2020, so it should be available on the next release, but in default branch we addressed a related performance issue from the query.

We build Windows installers every night: http://monetdb.cwi.nl/testweb/web/status.php The latest builds can be found here: http://monetdb.cwi.nl/testweb/web/80633:2c1d23b89b05/ for default and here: http://monetdb.cwi.nl/testweb/web/80630:4cc759c56763/ for Oct2020.

However the default/master branch is very unstable, so I don't recommend to use it for a production environment at the moment. We have been doing many bug and performance fixes, including some I did today, plus there was a substantial storage renovation. We are planning to make a new feature release once it stabilises, but it will take some time still.

**Comment by PeteMillington** [comment]
Hi Pedro,

Thank you for the information. We will test our code using the updated Oct2020 build.

Thanks again for your efforts to address this issue.

Have a nice weekend.

Peter Millington


-------- Original message --------
From: Pedro Ferreira ***@***.***>
Date: 3/19/21 5:43 PM (GMT-05:00)
To: MonetDB/MonetDB ***@***.***>
Cc: Pete Millington ***@***.***>, Author ***@***.***>
Subject: Re: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)


The fix is also available on Oct2020, so it should be available on the next release, but in the default branch we addressed a related performance issue from the query.

We build Windows installers every night: http://monetdb.cwi.nl/testweb/web/status.php The latest builds can be found here: http://monetdb.cwi.nl/testweb/web/80633:2c1d23b89b05/ for default and here: http://monetdb.cwi.nl/testweb/web/80630:4cc759c56763/ for Oct2020.

However the default/master branch is very unstable, so I don't recommend to use it for a production environment at the moment. We have been doing many bug and performance fixes, including some I did today, plus there was a substantial storage renovation. We are planning to make a new feature release once it stabilises, but it will take some time still.

**Comment by PedroTadim** [comment]
May I close this issue?

**Comment by PeteMillington** [comment]
Hello Again Pedro,

Thanks you again for your help to address this matter in a timely manner.

We tried to test our system against the updated Oct2020 Windows build you mentioned which we downloaded from the link you provided namely:

http://monetdb.cwi.nl/testweb/web/80630:4cc759c56763/

However, we have been having trouble launching this version of MonetDB with the embedded Python feature. MonetDB is finding our installation of Python (v3.9.2) but is failing to load the api binary library: C:\Program Files\MonetDB\MonetDB5\lib\monetdb5\_pyapi3.dll (even though the path is correct, it is looking in the correct location and the pyapi library is present in the specified directory).

I have experienced this issue in the past, and the issue related to the specific version of Python that was present. To that point, is there a specific version of Python that latest build requires? Are you familiar with this issue and any solutions? So far we have not been able to test MonetDB with your latest fix to bug #7075.

Thank you again for your assistance and any guidance you can offer.

Pete Millington
Scientific Financial Systems

**Comment by sjoerdmullender** [comment]
The system this binary was built on still has Python 3.9.1.  Maybe that is the problem?
Actually, it's getting built on our Windows 7 box (not Internet accessible) so it has an even older Python.
I will need to move the building of the Windows installer over to a different system so that it is a bit more up-to-date.

**Comment by PeteMillington** [comment]
Hi Sjoerd,

Thanks for the reply. I will try to run the suggested MonetDB windows installation using Python 3.9.1.

It is interesting that the embedded python module of the Oct2020-SP3 windows build of MonetDB seems to work with Python 3.9.2 but Pedro’s recent fix to the Oct2020 branch (http://monetdb.cwi.nl/testweb/web/80630:4cc759c56763/) does not seem to work with Python 3.9.2 on Windows.

I will let you know if this suggestion corrects this pyapi loading issue.

On a related note, is there any documentation that would tell us which version of (embedded) Python is being used for a specific (Windows) build of MonetDB? In general, is there a hard requirement for (closely) matching the version of the native Python installation on a machine with that being used in the MonetDB build of the embedded pyapi binary library?

Thank you again,

Pete Millington
Scientific Financial Systems

**Comment by sjoerdmullender** [comment]
The builds Pedro pointed to are side effects of our nightly testing.  The process for creating a release is completely separate from that.

**Comment by PeteMillington** [comment]
Hello Sjoerd & Pedro,

I have been having trouble installing and running the recent builds of MonetDB (with fixes for bug #7075) on the Windows platform using the build links as recently suggested by Pedro. [I am trying to upgrade and test against a recent MonetDB build to help Pedro close the recent #7075 bug issue.]

Currently, I have installed Python 3.9.1 with numpy 1.20.1. This configuration is compatible (starts fine) with the official release Oct2020-SP3, but when I try to install and run the recent MonetDB builds for Windows, I get an error from the MonetDB server session when it tries to start the embedded Python service saying it cannot load the associated _pyapi3.dll library because a module is not available. [I assume the error message is referring to a Python module not being available.]

I have confirmed that the search path for the lib load is correct and the pyapi_locatepython3.bat is finding the correct Python installation and updating the environment variables (LOCALPYTHONHOME & LOCALPYTHONPATH) accordingly. Note that I tried reinstalling a few variants of numpy (namely 1.19.4 & 1.19.5) combined with Python 3.9.1 but still see the same issue. Also, I see the same issue using a Python 3.9.2 installation with the recent build. [This 3.9.2 configuration is compatible/works with the Oct2020-SP3 release.]

Any thoughts or suggestions on why my current Python 3.9.1 configuration on Windows works fine with the Oct2020-SP3 release but not these recent nightly builds?

Thank you for any thoughts you might have.

MonetDB is an awesome tool. We really appreciate your work and your help!

Kind regards,

Pete Millington
Scientific Financial Systems

From: Pete Millington
Sent: Friday, March 26, 2021 2:14 PM
To: 'MonetDB/MonetDB' ***@***.***>; MonetDB/MonetDB ***@***.***>
Cc: Author ***@***.***>; Marc ***@***.***>
Subject: RE: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)

Hi Sjoerd,

Thanks for the reply. I will try to run the suggested MonetDB windows installation using Python 3.9.1.

It is interesting that the embedded python module of the Oct2020-SP3 windows build of MonetDB seems to work with Python 3.9.2 but Pedro’s recent fix to the Oct2020 branch (http://monetdb.cwi.nl/testweb/web/80630:4cc759c56763/) does not seem to work with Python 3.9.2 on Windows.

I will let you know if this suggestion corrects this pyapi loading issue.

On a related note, is there any documentation that would tell us which version of (embedded) Python is being used for a specific (Windows) build of MonetDB? In general, is there a hard requirement for (closely) matching the version of the native Python installation on a machine with that being used in the MonetDB build of the embedded pyapi binary library?

Thank you again,

Pete Millington
Scientific Financial Systems

**Comment by sjoerdmullender** [comment]
I amended my comment, but I guess you saw the original.
The nightly build happens on a Window 7 box, so it has an older Python version (3.9 doesn't work on Windows 7).
From tonight, the nightly build should be done on a Windows 2k12R2 system, and the Python version there was updated to 3.9.2.

**Comment by PeteMillington** [comment]
Hi Sjoerd,

Thanks for the reply and the information on the nightly build processes. I will look to re-install for Windows using the latest build after tonight. I will let you know if this solves our Windows installation issue and our original #7075 bug fix issue.

Thank you again for all your help.

Pete Millington

**Comment by PedroTadim** [comment]
Oct2020-SP4 has been released.

**Comment by PeteMillington** [comment]
Hello Pedro,

Thank you for the heads-up on the latest release. Thank you also for all the great and thorough work on MonetDB.

Kind regards,

Pete Millington
Scientific Financial Systems


-------- Original message --------
From: Pedro Ferreira ***@***.***>
Date: 4/15/21 7:41 AM (GMT-05:00)
To: MonetDB/MonetDB ***@***.***>
Cc: Pete Millington ***@***.***>, Author ***@***.***>
Subject: Re: [MonetDB/MonetDB] Inconsistent Results using CTEs in Large Queries (#7075)


Oct2020-SP4 has been released.
