### ISSUE TITLE
mserver5 ignores memory.low from cgroups v2

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7076]
**Describe the bug**
Issue found while fighting #7073 (which was eventually invalid).

Cgroups v1 has 1 soft and 1 hard limits for memory:
- soft: `memory.soft_limit_in_bytes`
- hard: `memory.limit_in_bytes`

Cgroups v2 has [2 soft and 1 hard limits](https://git.kernel.org/pub/scm/linux/kernel/git/tj/cgroup.git/tree/Documentation/admin-guide/cgroup-v2.rst#n1128) for memory:
- soft: `memory.low`
- soft: `memory.high`  (harder than `memory.low`)
- hard: `memory.max`

Docker has [a soft and a hard limit](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory):
- soft: `memory-reservation`  maps to
  -  (v1) `memory.soft_limit_in_bytes`
  - (v2) `memory.low`
- hard: `memory` maps to
  - (v1) `memory.limit_in_bytes`
  - (v2) `memory.max`

The issue is that, for v2, MonetDB uses `memory.high || memory.max` as its soft limit. 
That is, it ignores `memory.low`, which is in fact the true soft limit. 

This is a bit of a problem, because when setting a soft limit in Docker, it will work with cgroups v1, but won't work with cgroups v2.

It should probably consider: `memory.low || memory.high || memory.max`

**Comment by swingbit** [comment]
This is the patch I'm currently using:

[bug7076.patch.gz](https://github.com/MonetDB/MonetDB/files/6130689/bug7076.patch.gz)

**Comment by sjoerdmullender** [comment]
Your patch opens the file low.low.  I take it that should be memory.low?

**Comment by swingbit** [comment]
Oops. Indeed, I must have fixed it after taking the diff.
