### ISSUE TITLE
Oct2020: new default privileges not effectively communicated

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7077]
Before Oct2020, non-monetdb users appeared to have more privileges by default.

For example, this used to work (as a user):
```
sql>select * from sys.storage();
SELECT: no such table returning function 'storage'
```

If this now requires an explicit grant (which indeed makes it work), that's fine. 
However:
- I don't see any mention on the release notes (it should be considered a breaking change)
- the error doesn't mention it is about privileges, it suggests that the function doesn't exist. I would have expected an error like "insufficient privileges".
- even more so, because the user can actually see the function:
   ```
   sql>select id,name from sys.functions where name='storage';
   +-------+---------+
   | id    | name    |
   +=======+=========+
   | 20767 | storage |
   | 20825 | storage |
   | 20845 | storage |
   | 20866 | storage |
   +-------+---------+
   4 tuples
   ```

**Comment by PedroTadim** [comment]
Hi Roberto, this was a bug that I found and fixed on Oct2020. I didn't report it because no one had done before, so it was irrelevant. It makes that it should always been like this since the beginning. I can make it to give a better message, though.

**Comment by swingbit** [comment]
Hi Pedro,
If it was a bug to give those privileges by default, it was right to fix it. Making the error message more telling would indeed help.
Unfortunately I had applications using that function as a non-privileged user, which now fail. Even fixing a bug can be a breaking change, sometimes. No drama, but knowing in advance can help. 
Thanks for your feedback.

**Comment by PedroTadim** [comment]
I already have a fix for the error message. Running tests.

**Comment by PedroTadim** [comment]
This should be fixed on Oct2020 branch now.
