### ISSUE TITLE
Wrong links in redirect from bugzilla to Github 

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7078]
If I open a link to an old bugzilla ticket, it gets redirected to github. However, the link is incorrect.

For example:
 
`https://www.monetdb.org/bugzilla/show_bug.cgi?id=6981`

redirects to:
`https://github.com/MonetDB/MonetDB/issues?id=6981`

but it should be:
`https://github.com/MonetDB/MonetDB/issues/6981`

**Comment by sjoerdmullender** [comment]
Seems to be working correctly now.
