### ISSUE TITLE
WITH table AS... UPDATE ignores the WHERE conditions on table

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7079]
The newly-introduced `WITH` clause for UPDATE queries should be subject to the WHERE clause constraints - but isn't, resulting in many overwriting updates.

**To Reproduce**

For setup, run these queries:
```
CREATE TEMPORARY TABLE t1 AS SELECT 123 AS c1 ON COMMIT PRESERVE ROWS;
INSERT INTO t1 VALUES (45);
CREATE TEMPORARY TABLE t2 AS SELECT 'AB' AS c3, 10 AS c4  ON COMMIT PRESERVE ROWS;
INSERT INTO t2 VALUES ('CD', 20);
```
Now let's make an update:
```
> WITH t1_ AS (SELECT * FROM t1)
UPDATE t2
SET c4 = t1_.c1
WHERE t1_.c1 = 123;
4 affected rows
```
It should be _2_ rows affected. 

And now:
```
>SELECT * FROM t2;
+------+------+
| c3   | c4   |
+======+======+
| AB   |   45 |
| CD   |   45 |
+------+------+
2 tuples
```
when we should be seeing 123's.

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux 3 (Beowulf) 
 - Built MonetDB from source

**Comment by PedroTadim** [comment]
I cannot run the "WITH t1 AS (t1) UPDATE t2 SET c4 = t1.c1 WHERE t1.c1 = 123;" query. The syxntax is wrong I think.

**Comment by eyalroz** [comment]
@PedroTadim : Sorry, I mis-copy pasted. Try it now.

**Comment by PedroTadim** [comment]
This was a mistake of mine Niels noticed back then. I'm going to fix it on default branch now, All the input tables for update/delete must appear in the from clause, which is not in this case, so your query won't work.

**Comment by eyalroz** [comment]
@PedroTadim : But if all the tables are in the from clause, then we're updating records via their Cartesian product, while I only want to update records in one table. In fact, generally, it seems much less likely for people to want to update records through a possibly-many-to-many Join result.

Alternatively, if I don't place t1_ in the FROM clause - how will I be able to use it?

If you can, will you specify what syntax I should use instead of the query I tried?

**Comment by PedroTadim** [comment]
Extra tables used in an update, must be specified in the FROM clause. Later you can specify in the WHERE clause the join condition, but if it still leads into a cartesian product, we have to change it into a semijoin. We already do it for some cases.
You should either do:
UPDATE t2 SET c4 = t1_.c1 FROM (SELECT * FROM t1) as t1_ WHERE t1_.c1 = 123;
or 
WITH t1_ AS (SELECT * FROM t1) UPDATE t2 SET c4 = t1_.c1 FROM t1_ WHERE t1_.c1 = 123;

**Comment by PedroTadim** [comment]
I just fixed the FROM issue, now I have to look in the count one.

**Comment by eyalroz** [comment]
I didn't realize UPDATE ... SET ... FROM was a possibility in MonetDB - the documentation suggests it is not supported.

Anyway, it seems to work (at least for a couple of simple cases). Anyway, if you've made my query get rejected, then the bug can be closed I guess.

**Comment by PedroTadim** [comment]
The count issue has been fixed.
