### ISSUE TITLE
Allow "WITH my_table UPDATE" and "WITH my_table DELETE"

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7080]
A recent syntax addition to MonetDB is the WITH clause for updates and deletions, as described [here](https://www.monetdb.org/Documentation/SQLReference/DataManipulation/TableUpdates). The WITH clause allows for an arbitrary SELECT query to be specified and given an alias. But - what about the simpler case, of just wanting to use an existing table?

At the moment, we have to write statements such as:
```
WITH my_alias AS (SELECT * FROM my_table)
UPDATE another_table
SET foo='bar';
```
which is redundant. It should not be problematic for MonetDB to accept:
```
WITH my_table
UPDATE another_table
SET foo='bar';
```
and make sure that `my_table` actually exists.

In case it matters - I'm using version 11.39.11

**Comment by PedroTadim** [comment]
This is not allowed by the standard so we won't implement it.

**Comment by eyalroz** [comment]
Now that I know I can use FROM _after_ the UPDATE clause, I'm fine with that. But please update the [documentation](https://www.monetdb.org/Documentation/SQLReference/DataManipulation/TableUpdates)!
