### ISSUE TITLE
Attempt to allocate too much space in UPDATE query

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7081]
Consider the following query:
```
UPDATE table_3 AS t3
SET c1 = t2.c1
FROM table_1 AS t1, table_2 AS t2
WHERE false;
```
in the case that:
* Table 1 is small (3 records).
* Table 2 is large (~60 Million records).
* Table 3 is small (less than 1000 records).
* c1 is a column of type `CHAR(3)`

On my system, this gets me:
```
GDK reported error: GDKmmap: requested too much virtual memory; memory requested: 2307734896640, memory in use: 387076736, virtual memory in use: 2308246491776
HEAPalloc: Insufficient space for HEAP of 2307734835200 bytes.
```
Clearly, too much memory is being allocated (even if we ignore the fact that the condition is never met).

**Software versions**
 - MonetDB 11.39.11
 - Built from source
 - Devuan GNU/Linux 3 Beowulf

**Comment by PedroTadim** [comment]
On default branch, we added optimizations for these trivial cases. You can try it there. It will be available on the next feature release.

**Comment by eyalroz** [comment]
@PedroTadim : You mean, the master branch here has it?

**Comment by yzchang** [comment]
yes, on github, it's the master branch
