### ISSUE TITLE
MonetDBe C++ Compiling Error 

### ISSUE THREAD

**Issue by arifsaeed** [MonetDB/MonetDB#7083]
**Describe the bug**
I am trying to integrate Monetdbe into a C++ application.  When I include the <String> header then i get the following compiling errors:
```
/usr/include/c++/9/bits/ptr_traits.h:120:71: error: macro "static_assert" passed 3 arguments, but takes just 2
[build]   120 |    "pointer type defines element_type or is like SomePointer<T, Args>"); 
```
However, if I remove the following macro from the monetdb_config.h file then the error goes away.  I this case Monetdbe seems to work fine.

#ifndef static_assert
/* static_assert is a C11 feature, defined in assert.h which also exists
 * in many other compilers we ignore it if the compiler doesn't support it */
#define static_assert(expr, mesg)	((void) 0)
#endif

Is it ok to remove this macro if compiling monetdbe in a C++ environment.
**To Reproduce**
Create a C++ application with CMAKE, I'm using compiler GCC 9.3.0
paste the code below code into the main.cpp file and try to compile the application
```
#include "monetdbe.h"
#include <string>

int main(){

  std::string   mystr="hello world";  
}
```

**Expected behavior**
I would expect the code to compile successfully

**Screenshots**

**Software versions**
 - I downloaded monetdb after October 2020 from the github page
 - Ubuntu 20.04
 - i followed the following instructions to install monetDB locally
                           git clone https://github.com/MonetDB/MonetDB MonetDB 
                           cd MonetDB
                          mkdir build && cd build
                          cmake -DCMAKE_BUILD_TYPE=Release ..
                           cmake --build .

**Issue labeling **
bug

**Additional context**

**Comment by PedroTadim** [comment]
We are not C++ people, so this is not entirely our fault :) However I just committed a fix here: https://dev.monetdb.org/hg/MonetDB/rev/0495ad7a8f9c
Is this enough? Thanks for your support.
