### ISSUE TITLE
Data consistency problem of query results in the latest release of Monetdb (Remote Table)

### ISSUE THREAD

**Issue by merqury7** [MonetDB/MonetDB#7089]
0. Overview

As a result of installing and testing version 11.39.13 of Monetdb as follows, there is a bug in which data is inconsistent when query conditions are applied to numeric columns in Remote Table. The following problem occurs in both conditional columns of type int and double type.
The same happens with Merge tables that contain remote tables. We present an example of a problem that occurred on two servers, beestore and beestore1.
And both the server installed in the binary method and in the compile method show the same symptoms. Below is a list of versions showing the same symptoms.

-MonetDB 11.39.13  (binary & Compiled)
-MonetDB 11.39.7 (binary)
-MonetDB 11.39.5 (binary)

1. Server environment and version
  
   1) beestore server (server accessing remote table)

		MonetDB 5 server 11.39.13 (64-bit, 128-bit integers)
		This is an unreleased version
		Copyright (c) 1993 - July 2008 CWI
		Copyright (c) August 2008 - 2021 MonetDB B.V., all rights reserved
		Visit https://www.monetdb.org/ for further information
		Found 31.2GiB available memory, 16 available cpu cores
		Libraries:
		  libpcre: 8.32 2012-11-30
		  openssl: OpenSSL 1.0.2k-fips  26 Jan 2017
		  libxml2: 2.9.1
		Compiled by: root@beestore (x86_64-pc-linux-gnu)
		Compilation: /usr/bin/cc  -DNDEBUG=1
		Linking    : /usr/bin/ld
   
   2) beestore1 server (server serving remote table)
		MonetDB 5 server 11.39.13 (64-bit, 128-bit integers)
		This is an unreleased version
		Copyright (c) 1993 - July 2008 CWI
		Copyright (c) August 2008 - 2021 MonetDB B.V., all rights reserved
		Visit https://www.monetdb.org/ for further information
		Found 15.5GiB available memory, 8 available cpu cores
		Libraries:
		  libpcre: 8.32 2012-11-30
		  openssl: OpenSSL 1.0.2k-fips  26 Jan 2017
		  libxml2: 2.9.1
		Compiled by: root@beestore1 (x86_64-pc-linux-gnu)
		Compilation: /usr/bin/cc  -DNDEBUG=1
		Linking    : /usr/bin/ld  
		
		
2. Data Creation

  1) DDL in beestore1 server
   
   sql>
       -- Create local table
	   CREATE TABLE AMI_test (
	    toc_no String null,
	     mesure_de int null
       );
	   
   sql>
     -- insert sample data
	 insert into AMI_test values('A000000009', 20201006);
	 insert into AMI_test values('A000000010', 20201007);
	 insert into AMI_test values('A000000011', 20201008);
	 insert into AMI_test values('A000000012', 20201009);
	 insert into AMI_test values('A000000013', 20201010);
	 insert into AMI_test values('A000000014', 20201011);
	 insert into AMI_test values('A000000015', 20201012);
	 insert into AMI_test values('A000000016', 20201013);
  
    -- Checking the inserted data
   sql> select * from AMI_test order by mesure_de;
		+------------+-----------+
		| toc_no     | mesure_de |
		+============+===========+
		| A000000009 |  20201006 |
		| A000000010 |  20201007 |
		| A000000011 |  20201008 |
		| A000000012 |  20201009 |
		| A000000013 |  20201010 |
		| A000000014 |  20201011 |
		| A000000015 |  20201012 |
		| A000000016 |  20201013 |
		+------------+-----------+
		
  2) DDL in beestore server
   sql>
       -- create remote table
	   CREATE REMOTE TABLE AMI_test (
		  toc_no String null,
		  mesure_de int null
		) on 'mapi:monetdb://beestore1:50000/bcsdb';

       -- Checking the inserted data from remote table (same as above)
	sql>select * from  AMI_test order by mesure_de;
	+------------+-----------+
	| toc_no     | mesure_de |
	+============+===========+
	| A000000009 |  20201006 |
	| A000000010 |  20201007 |
	| A000000011 |  20201008 |
	| A000000012 |  20201009 |
	| A000000013 |  20201010 |
	| A000000014 |  20201011 |
	| A000000015 |  20201012 |
	| A000000016 |  20201013 |
	+------------+-----------+			
	
	
3. Query on numeric column   (beestore server)

	-- Rows with mesure_de value less than 20201011 should be extracted, but it is not. (mesure_de==20201011)
	
	select * from  AMI_test 
	where mesure_de >= 20201001 and mesure_de < 20201011 
	order by mesure_de desc;
	
	+------------+-----------+
	| toc_no     | mesure_de |
	+============+===========+
	| A000000014 |  20201011 |
	| A000000013 |  20201010 |
	| A000000012 |  20201009 |
	| A000000011 |  20201008 |
	| A000000010 |  20201007 |
	| A000000009 |  20201006 |
	+------------+-----------+
	
	-- Create local table based on AMI_test table data
	sql>create table AMI_test_normal as select * from  AMI_test;
	operation successful
	
	-- Execute the same query on the created local table (Normal data with mesure_de < 20201011)
	
	select * from  AMI_test_normal
	where mesure_de >= 20201001 and mesure_de < 20201011 
	order by mesure_de desc;
	
	+------------+-----------+
	| toc_no     | mesure_de |
	+============+===========+
	| A000000013 |  20201010 |
	| A000000012 |  20201009 |
	| A000000011 |  20201008 |
	| A000000010 |  20201007 |
	| A000000009 |  20201006 |
	+------------+-----------+   

**Expected Output**
        -- Query from Remote Table
	select * from  AMI_test 
	where mesure_de >= 20201001 and mesure_de < 20201011 
	order by mesure_de desc;
	
	+------------+-----------+
	| toc_no     | mesure_de |
	+============+===========+
	| A000000013 |  20201010 |
	| A000000012 |  20201009 |
	| A000000011 |  20201008 |
	| A000000010 |  20201007 |
	| A000000009 |  20201006 |
	+------------+-----------+

**Additional context**
The above problem does not occur in MonetDB-11.31.13

**Software versions**
 - MonetDB version number : 
        MonetDB 11.39.13  (binary & Compiled)
        MonetDB 11.39.7 (binary)
       MonetDB 11.39.5 (binary)
 - OS and version:  
     CentOS Linux release 7.4.1708 
 - Installed from release package or self-installed and compiled : both

** Additional Tests**

We tested as follows from the recently released version. The problem seems to have occurred from version 11.37.7

MonetDB-SQL-server5-11.39.13 MonetDB-client-11.39.13    ->  fail
MonetDB-SQL-server5-11.39.11 MonetDB-client-11.39.11    ->  fail	
MonetDB-SQL-server5-11.39.7 MonetDB-client-11.39.7      -  >  fail
MonetDB-SQL-server5-11.39.5 MonetDB-client-11.39.5      ->  fail
MonetDB-SQL-server5-11.37.11 MonetDB-client-11.37.11   -> fail 
MonetDB-SQL-server5-11.37.7 MonetDB-client-11.37.7    -> fail

MonetDB-SQL-server5-11.35.19 MonetDB-client-11.35.19  -> OK

**Comment by PedroTadim** [comment]
Hello! I found the origin of the problem and I just pushed a fix here: https://dev.monetdb.org/hg/MonetDB/rev/9609c5232f7e If you can compile the sources you can test it out, otherwise just wait for the next release.

Thanks for the report
