### ISSUE TITLE
Performance issues using a window function

### ISSUE THREAD

**Issue by JohannesRahn** [MonetDB/MonetDB#7090]
**Describe the bug**
I am facing very slow performance using a sum() window function.

**To Reproduce**

The first table (t1 has 1.270.000 rows and around 600MB of data, t2 has 40.000.000 rows and around 10.3 GB).

Here’s the SQL-Query I am using (column and table names changed due to confidentiality):

SELECT
  t1.pk2,
  SUM(t2.amount) over (
    partition by t1.someColumn1
ORDER BY t1.pk3
  ) AS Sum_Amount
FROM
  table1 t1
LEFT JOIN table2 t2 on (t1.pk1 = t2.pk1
    AND t1.pk2 = t2.pk2
    AND t1.pk3 = t2.pk3);

You can find the performed actions in the text file in the attachments.

**Expected behavior**

**Software versions**
The problem occurred on a Windows 10 machine using the release package of MonetDB 10.5. 

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**
I had to kill this query after 5 hours of runtime in MonetDB. I also tried to run the query on a smaller subset of the data and it worked. 
The same query with the same test data runs on MariaDB in under 8 Minutes, therefore I don’t think it is an issue with the query or the data.

Is there anything I can do to speed up this window function or is this a problem MonetDB faces with window functions on big tables? 

[explain_windowFunction.txt](https://github.com/MonetDB/MonetDB/files/6220031/explain_windowFunction.txt)

**Comment by PedroTadim** [comment]
This seems to be a duplicate of this issue https://github.com/MonetDB/MonetDB/issues/6959 We improved the window functions performance on default/master branch and it will be available on the next feature release.

**Comment by JohannesRahn** [comment]
Oh I did see that one yet. Thanks for the fast reply!

Is there already a date for the next feature release?

**Comment by yzchang** [comment]
Not yet, but won't be in April.  It contains huge changes.

**Comment by JohannesRahn** [comment]
Okay, thanks for the information and all the work you do for MonetDB.
