### ISSUE TITLE
Drop remote tables in transactions and rollback

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7094]
We encounter a bug with remote tables as part of transactions:

sql>CREATE REMOTE TABLE rmt_tbl (id int, name varchar(20)) ON ‘mapi:monetdb://remote.host.url:50000/dbname/scm1/l_tbl’;
operation successful
sql>BEGIN TRANSACTION;
auto commit mode: off
sql>DROP TABLE  rmt_tbl;
operation successful
sql>ROLLBACK;
auto commit mode: on
sql>DROP TABLE if exists rmt_tbl;
no such table: ‘sys.rmt_tbl’
sql>

It seems that after rollback the table exists in the catalogue but it does not actually exists so that drop table fails even if we have ‘if exists’
This happens only with remote tables. (October2020-SP3)

**Comment by PedroTadim** [comment]
It seems the authorization component of remote tables is not transaction aware. I think this was done by a cleanup project some time ago. Back then I warned about this, so time to think about a solution.

**Comment by johnfouf** [comment]
Yes, it is necessary when you run concurrent requests from the application layer, so in case of conflicts during cleanups of remote tables, rollbacks and retries are required.

**Comment by ThanKarab** [comment]
Hello @PedroTadim , what's the status on this one?

**Comment by aris-koning** [comment]
Hi, the status is that we haven't forgotten about it.  But a solution is not straightforward and might require some architectural rethinking here and there and we currently have other priorities. We are keeping it open though. You can contact us via the commercial channels if your company project depends on this and you require more attention from us to this issue.

**Comment by njnes** [comment]
implemented in jun2023
