### ISSUE TITLE
Add an 'ANY' or 'ARBITRARY' aggregate function

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7097]
When grouping by certain columns in a table, we can only select other columns via an aggregate function. However, at times, one merely wants _some_ value in that column of records in the group - arbitrarily. See also this StackOverflow question:

[GROUP BY one column; pick arbitrary value for another](https://stackoverflow.com/q/15314892/1593077)

Some DBMSes have an aggregate function named `ANY` or `ARBITRARY` which does exactly this (although some only have it internally, see [here](https://www.sql.kiwi/2011/07/undocumented-query-plans-the-any-aggregate.html)). Now, it is possible to simulate this using a window function (row number over order by null, and taking the first element) - but it is _much_ more convenient to have this available in MonetDB directly:
```
SELECT user.id, ANY(file.path), ANY(file.size)
FROM user, file
WHERE files.user_id = user.id
GROUP BY user.id;
```
Note that the choice of record for the different uses of `ANY` needs to be the same (otherwise it is only useful for a single rather than multiple columns).

**Comment by njnes** [comment]
support for any_value() has been added to the aug2024 release
