### ISSUE TITLE
Feature request: nextafter() in SQL

### ISSUE THREAD

**Issue by drstmane** [MonetDB/MonetDB#7101]
**Is your feature request related to a problem? Please describe.**
Given a floating point value range (say, between min(C) and max(C) value of a column C), the IMHO easiest(?) way to divide that range into N ranges/partitions/clusters of equal width (e.g., to calculate an equi-width histogram with N bins) and easily determine the range/partition/cluster P(V) each value V belongs to, requires using C(99?) math library function nextafter[f]() (or C++(11?) std::nextafter()) to get a tight exclusive upper bound as follows: calculate width of each range/partition/cluster as W=(nextafter(max(C))-min(C))/N , then determine range/partition/cluster of value V as P(V) = floor((V-min(C))/W).
Doing so in SQL requires C/C++ function nextafter() to be made available in SQL.

**Describe the solution you'd like**
Please expose C/C++ function nextafter() (for floating point types) in SQL.

**Describe alternatives you've considered**
None.

**Additional context**
For convenience of (canonical) use, one could consider also adding nextafter() for integer and decimal types:
for integer, it would boil down to a simple +1 (or -1); for decimal type decimal(x,y) it would be a + (or -) 10^(-y).

Thanks!
Best,
Stefan

**Comment by PedroTadim** [comment]
Hello Stefan, this is something we can implement, but we have many other priorities right now.

**Comment by yzchang** [comment]
Hai Stefan, I added this to the MonetDB roadmap we're planning.
