### ISSUE TITLE
"Can not create object" error when adding primary key.

### ISSUE THREAD

**Issue by Pietro-PPC** [MonetDB/MonetDB#7102]
**Describe the bug**
I deleted a (3-column composite) primary key from my database table. When I tried to add it again, I got the error "Can not create object".

**To Reproduce**
I was not able to reproduce the error in a smaller scale. 

When I try to add a primary key that has repeated values for the specified primary key columns in a smaller table, I get the "Violated Constraint" error, so I do not think this is not the problem.

**Expected behavior**
The primary key is added successfully.

**Software versions**
 - MonetDB version: MonetDB Database Server Toolkit v11.33.11 (Apr2019-SP1)
 - OS and version: Debian GNU/Linux 10 (buster)
 - I do not know whether it was installed from release package or self-installed and compiled, probably the first option.

**Additional context**
The table has around 140 million rows and 200 columns, so the bug can be be related to the amount of data. The table was created around 4 years ago.

I have already searched for this error on the web, but found only one problem similar to mine [here](https://stackoverflow.com/questions/22142170/batproject-error-when-querying-monetdb-database), where there also was a huge amount of data.

I also found that "Can not create object" is the value of the INTERNAL_OBJ_CREATE macro, but I do not exactly know in which case it is returned.

**Comment by PedroTadim** [comment]
While running a SQL fuzzer I found this error. However my recent fixes for these errors went to the default/master branch. i would like to ask you to attempt to reproduce that error on that branch, however that branch is not stable at the moment.

**Comment by PedroTadim** [comment]
Also the Apr2019 version is very old, we made many bug fixes since that release.

**Comment by yzchang** [comment]
Hello Pietro, Apr2019 is no longer supported.  Please upgrade to the most recent release https://www.monetdb.org/Downloads/ReleaseNotes.

**Comment by Pietro-PPC** [comment]
Hello, sorry I took a long time to answer. Thank you for your fast answers. 

I copied the dbfarm and now i am running the database with the copy inside a docker container with version 11.39.17 (Oct2020-SP5). I was able to successfully add the primary key in the table I was having problems, but now when I try to add a primary key to a temporary table, it displays the error ALTER TABLE: can't alter temporary table. 

I tried to search for some other person that had the same error, but did not find anyone.

**Comment by PedroTadim** [comment]
Tomorrow I will confirm if we can add constraints on temporary tables.

**Comment by PedroTadim** [comment]
We have disallowed alter statements on temporary tables for a long time, and this won't change soon.

**Comment by Pietro-PPC** [comment]
Hello, I am having trouble,

**Comment by Pietro-PPC** [comment]
Ok, thank you. This problem was solved, but now I am facing a another problem. It is related to the "Column specified more than once" error. Do I have to create another issue?

**Comment by HenriqueVarellaEhrenfried** [comment]
Hello, I work with @Pietro-PPC and I have some question as well:

@PedroTadim could this error be concerned with the [commit](https://github.com/MonetDB/MonetDB/commit/b9b495aea2b20b834ff362af8f7ea065e4279ecf )? I mean, as I understood, @Pietro-PPC updated his database several versions at once ( Apr2019-SP1 -> Oct2020-SP5 ). 

Perhaps there is a bug in the database upgrade path that triggers this error "Column specified more than once". Is there something that can be done to fix this error? 

We tested creating the database from scratch and the error does not appear, but when we try to update this updated database, the error occurs. Unfortunately recreating our database is inviable since there are many data, and our project is leading to the end.

**Comment by yzchang** [comment]
Just FYI, (for the open-source community) we only support the automatic upgrade of one major release back, in this case, Jun2020* - Oct2020*.

We understand the difficulty of upgrading a big database.  Nevertheless, please keep in mind that jumping over such as lang chain of versions is extremely risky.  With older MonetDB versions (in particular before Jun2020), databases can get corrupted.  If you use the upgrade path, you'll never know if you carry over any old problems until you hit the problem in the new version.
