### ISSUE TITLE
Source compile install 

### ISSUE THREAD

**Issue by dnstlrsla** [MonetDB/MonetDB#7105]
CMake version = 3.20
but my centos is not installed python3

cmake -DCMAKE_INSTALL_PREFIX:PATH=/path/to/monetdb .
and 

make 

[ 70%] Generating 81_tracer.sql.c
/bin/sh: Python3_EXECUTABLE-NOTFOUND: command not found
make[2]: *** [sql/backends/monet5/81_tracer.sql.c] Error 127
make[1]: *** [sql/backends/monet5/CMakeFiles/sql.dir/all] Error 2
make: *** [all] Error 2

how to install no use python3 ??

why use python3?

**Comment by PedroTadim** [comment]
Python2 reached its end-of-life last year, so we dropped the support for it. MonetDB requires python3 to be compiled.
