### ISSUE TITLE
Monetdb crashes on query execution

### ISSUE THREAD

**Issue by manuelpagliaivisokio** [MonetDB/MonetDB#7108]
Hello.

I am using monetdb version Oct2020-SP4 Bugfix Release (11.39.15) on Windows 10.
I can get monetdb to crash when executing a query. I attached both the query and the SQL dump of the table.

The query is quite large, and non sensical as it is automatically generated by our testing tool, still I hope this can be helpful to spot the bug, as it is able to make monetdb crash every time it is executed.

** Problem description **
Monetdb crashes every time this this specific query is executed

**To reproduce**

- Create the table lineitem_denormalized_first1k_sanitised (attached)
- Execute the query (attached)

[Query.txt](https://github.com/MonetDB/MonetDB/files/6345176/Query.txt)
[lineitem_denormalized_first1k_sanitised.txt](https://github.com/MonetDB/MonetDB/files/6345178/lineitem_denormalized_first1k_sanitised.txt)

**Comment by PedroTadim** [comment]
Hi! We already found the culprit and we are trying to find out a solution.

**Comment by njnes** [comment]
Pushed a fix too the oct2020 branch
