### ISSUE TITLE
MERGE Statement incorrectly reports that input relation matches multiple rows

### ISSUE THREAD

**Issue by v-from-meiro** [MonetDB/MonetDB#7109]
**Describe the bug**
There is a bug in MERGE statement, incorrectly reporting "Multiple rows in the input relation 'ce' match the same row in the target relation 'attr", which is not the case.

**To Reproduce**
```drop table if exists ce;
drop table if exists attr;
create table ce (id bigint);
insert into ce values (1), (2);
create table attr (id bigint, value text);
insert into attr values (1,'a'),(1,'b'),(2,'a'),(2,'a'),(3,'a'),(3,'b');

merge into attr
using ce on ce.id = attr.id
when matched then delete;
```

**Expected behavior**
Only rows with id `3` are left in `attr` table.

**Software versions**
 - MonetDB version number: MonetDB v11.39.13
 - OS and version: Ubuntu 20.04
 - Installed from release package into Docker

**Comment by PedroTadim** [comment]
Thanks for the report, I made a wrong check for the update and delete components on a merge statements. This is now fixed on the Oct2020 branch and it will be available in the next release.
