### ISSUE TITLE
Monetdb Query parsing consistency issues in the latest release (Remote Table)

### ISSUE THREAD

**Issue by merqury7** [MonetDB/MonetDB#7110]
**Describe the bug**
   The check method for the identifier used in the GROUPBY clause is inconsistent between the Remote Table and the Local Table.

**To Reproduce**

1. Environment and Version
  
  1) beestore Server : MonetDB 5 server 11.39.15 (Oct2020-SP4)
  2) beestore1 Server : MonetDB 5 server 11.39.15 (Oct2020-SP4)

2. Data Creation 

  1) DDL in beestore1 Server 
   
   sql>
       -- Create a Local Table 
	   CREATE TABLE keyword_test (
	    toc_no String null,
	     name String null
       );
	   
   sql>
     -- Insert Sample Data
	 insert into keyword_test values('A000000009', 'AAAA');
	 insert into keyword_test values('A000000010', 'BBBB');
	 insert into keyword_test values('A000000011', 'CCCC');
	 insert into keyword_test values('A000000012', 'DDDD');
	 insert into keyword_test values('A000000013', 'EEEE');
	 insert into keyword_test values('A000000014', 'AAAA');
	 insert into keyword_test values('A000000015', 'DDDD');
	 insert into keyword_test values('A000000016', 'AAAA');
  
    -- Checking the inserted data
   sql> select * from keyword_test order by name;
		+------------+------+
		| toc_no     | name |
		+============+======+
		| A000000009 | AAAA |
		| A000000014 | AAAA |
		| A000000016 | AAAA |
		| A000000010 | BBBB |
		| A000000011 | CCCC |
		| A000000012 | DDDD |
		| A000000015 | DDDD |
		| A000000013 | EEEE |
		+------------+------+

	- Check the GROUPBY result
	sql>select '*' as category, count(*) as cnt from keyword_test group by category;
		+----------+------+
		| category | cnt  |
		+==========+======+
		| *        |    8 |
		+----------+------+

  2) DDL in beestore Server
   sql>
       -- Create a Remote Table
	   CREATE REMOTE TABLE keyword_test (
	    toc_no String null,
	     name String null
		) on 'mapi:monetdb://beestore1:50000/bcsdb';

       -- Check Remote Table
	sql>select * from keyword_test order by name;
	+------------+------+
	| toc_no     | name |
	+============+======+
	| A000000009 | AAAA |
	| A000000014 | AAAA |
	| A000000016 | AAAA |
	| A000000010 | BBBB |
	| A000000011 | CCCC |
	| A000000012 | DDDD |
	| A000000015 | DDDD |
	| A000000013 | EEEE |
	+------------+------+
	
3. Data Query Task (beestore Server)

   --  In a normal situation, the same result as the beestore 1 execution result should be displayed
   --  When I run the same query as the beestore1 server, I get the following error.
   
  sql>select '*' as category, count(*) as cnt from keyword_test group by category;
(mapi:monetdb://monetdb@beestore1/bcsdb) Identifier category doesn't exist

**Expected behavior**
       --  In a normal situation, the same result as the beestore 1 execution result should be displayed  (From Remote Table)
	sql>select '*' as category, count(*) as cnt from keyword_test group by category;
		+----------+------+
		| category | cnt  |
		+==========+======+
		| *        |    8 |
		+----------+------+

**Screenshots**

**Software versions**
 - MonetDB version number [a milestone label] :  MonetDB 5 server 11.39.15 (Oct2020-SP4)
 - OS and version: [e.g. Ubuntu 18.04] CentOS 7.4 
 - Installed from release package or self-installed and compiled   :   Installed from release package

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**

**Comment by PedroTadim** [comment]
Hi! There was an issue parsing grouping queries with aliases. I just fixed the issue this morning. It should be available in the next release.
