### ISSUE TITLE
ORDER BY ... LIMIT support in inner queries

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7111]
If I enter the following commands:
```
CREATE TEMPORARY TABLE table1 AS (SELECT 1 AS col1, 'foo' AS col2)  ON COMMIT PRESERVE ROWS;
INSERT INTO table1 VALUES (1, 'bar'), (2, 'baz');
SELECT (SELECT col2 FROM table1 ORDER BY col1 LIMIT 1);
```
I should get `1`, but I get a syntax error:
```
syntax error, unexpected ORDER, expecting UNION or EXCEPT or INTERSECT or ')' in: "select (select col2 from table1 order"
```
as MonetDB does not accept ORDER BY ... LIMIT in inner queries. I'm not expert on the standard, but I do believe this needs to be supported; if not, it definitely should be IMHO.

**Software versions**
 - MonetDB 11.39.11
 - OS and version: Devuan GNU/Linux Beowulf
 - Built from source

**Comment by PedroTadim** [comment]
This was a decision made several years ago. The ORDER BY clause is rather cosmetic, so using it in a subquery won't give benefit. As for LIMIT, it can lead into undefined results as only a subset of the results are returned from the subquery.

**Comment by eyalroz** [comment]
@PedroTadim :

> The ORDER BY clause is rather cosmetic, so using it in a subquery won't give benefit.

That is not true if you use ORDER BY with LIMIT.

> As for LIMIT, it can lead into undefined results as only a subset of the results are returned from the subquery.

I don't understand. Are you saying that there is a known bug in MonetDB which is avoided by preventing LIMIT? If not - how are the results of LIMIT in an inner query less defined than LIMIT in an outer query?

**Comment by njnes** [comment]
order by limit in subqueries isn't in the sql spec
