### ISSUE TITLE
Need keyboard shortcut to interrupt query execution rather than session

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7112]
Currently, if you want to interrupt the execution of a long-running query you've input in an mclient session, you can press Ctrl+C - but this won't get you back to the prompt; rather, it will terminate both query execution and the connection. Thus, if you have uncommitted changes, or temporary tables - they'll be lost. 

It would be nice if Ctrl+C could just go back to the command prompt (and a Ctrl+C without a query running would break the connection). But any shortcut key combination would be some improvement.

**Software versions**
 - MonetDB 11.39.11
 - OS and version: Devuan GNU/Linux Beowulf
 - Built from source

**Comment by sstalin** [comment]
Recently we've extended query timeout functionality such as timeout propagates further down in GDK layer. User should have better control of timing queries now via `call sys.setquerytimeout(seconds)`.

**Comment by eyalroz** [comment]
Hello Svetlin :-)  It's been a while...

So, call `sys.setquerytimeout(seconds)` is useful, but it doesn't replace the functionality of wanting to interrupt the current query/statement on the current connection, immediately. No reason not to have both, I would think.

**Comment by njnes** [comment]
this was added to the mclient.
