### ISSUE TITLE
Table name completion mishandles underscores

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7113]
**Describe the bug / Reproduction instructions**
If, in an mclient session, you:

1. Create a table named `foo`.
2. Create a table named `foo_bar`.
3. Type `SELECT COUNT(*) FROM foo_` (without pressing Enter)
4. Press Tab

the underscore gets deleted, and you're back with `foo`.

**Expected behavior**
The completion should produce `foo_bar`.

**Software versions**
 - MonetDB 11.39.11
 - OS and version: Devuan GNU/Linux Beowulf
 - Built from source

**Comment by ghost** [comment]
Can not reproduce on Fedora. Most likely incompatibility in readline library, beyond the realm of MonetDB.
