### ISSUE TITLE
false concurrency concern prevents commit

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7117]
I've just run a query taking a few minutes of a DBMS, and which creates a new table t2 from data in table t1.

During the run of this query, I ran another query, which is merely a SELECT, and which only regards table t1. This query takes a lot less time and concludes successfully.

After a while, I come to check on the long query, only to find the message:
```
> operation successful
> COMMIT: transaction is aborted because of concurrency conflicts, will ROLLBACK instead
```
but - there were no concurrency conflicts; and I mean that in two ways:

* The only changes are in a new table.
* Even if the changes had been to the old table, it wouldn't have been a problem to commit them, since by the time the question of whether to commit came up, no other query was running.

Unfortunately I don't have easy reproduction instructions.

**Expected behavior**
The new table should have been created.

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from source.

**Comment by PedroTadim** [comment]
We made a storage renovation for the upcoming Jul2021 release. So we won't look for this on Oct2020 for sure. Can you try to reproduce it on that branch? However it's not stable yet.

**Comment by eyalroz** [comment]
How unstable is it?

**Comment by PedroTadim** [comment]
There are some transaction isolation issues in the storage. We hope it will get fixed soon.

**Comment by eyalroz** [comment]
Well, if you can comment here when it's sort-of stable again, I'll try to reproduce with the main branch (or whatever other branch you suggest).

**Comment by njnes** [comment]
its been a while since the storage revamp.
