### ISSUE TITLE
Unnecessary heap allocation fails simple query

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7118]
Suppose I have two large tables, the product of whose sizes is beyond the heap allocation capacity. If I write:
```
SELECT COUNT(*) 
FROM t1, t2
WHERE false;
```
I get the error:
```
GDK reported error: GDKextendf: could not extend file: File too large
HEAPalloc: Insufficient space for HEAP of 40577078061056 bytes.
```
Clearly, no large allocation is needed here. This situation can probably be generalized somewhat, but I'm not sure exactly how.

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from source

**Comment by PedroTadim** [comment]
I know we can improve this, but it's rather tricky because we have to delay the projections coming from joins. Probably adding a SQL optimizer would be an easier solution. However we have many other priorities right now

**Comment by eyalroz** [comment]
@PedroTadim : I'm not filing these bugs because I need them fixed right now. I need to settle for workarounds anyway... this is just a community service. So fix it whenever you like.

**Comment by njnes** [comment]
should be fixed by optimizers by now.
