### ISSUE TITLE
Add option to have the tag ID printed when execution starts

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7119]
MonetDB offers (?) the `sys.pause()` and `sys.stop()` procedures which apply to running statements. These procedures take a statement "tag id"; but when you issue a statement either interactively or with `mclient -s`, you don't get told what the new "tag id" is. While you can query it using the `sys.queue` table, it would be convenient if you could just be told what the query tag is - if a message could be printed on execution start, e.g.
```
Executing statement 1234.
```

Obviously, this should be printed by default; users don't expect to get this, and certainly in non-interactive mode you might want just the raw results. But there should be an option to enable it being printed IMHO.

**Software versions**
 - MonetDB 11.39.11
 - Debuan GNU/Linux Beowulf
 - Built from source

**Comment by lrpereira** [comment]
Hi @eyalroz,
From our experience, the id's are only needed in a few cases, for long running queries. Querying sys.queue is the way to go.

**Comment by eyalroz** [comment]
@lrpereira : "long running queries" _are_ what takes up most of the time - because they're long running. Querying `sys.queue` is cumbersome and inconvenient, plus, it requires one additional piece of knowledge which could easily be avoided. Why not just print the statement ID? It's not like there's an excess of information printed right now.

It seems like you closed this arbitrarily.

**Comment by lrpereira** [comment]
Hi @eyalroz,
At the time I closed this issue, I discussed this with my other colleagues and it did not seemed reasonable to implement this as default behavior in MonetDB.
The only functions/procedures that take TAG ID's as arguments are the procedures that you mentioned - pause(), resume() and stop() - so having the knowledge of the running statement ID would be useful for only these 3 procedures.
Furthermore, these procedures are useful when the user is aware of long-running queries, either using mclient session interactively or with "-s" option.
So, printing by default (or as an option) the running statement ID for 3 procedures that are useful on long-running queries does not seem reasonable.
Also the implications for implementing this in the MAPI protocol are estimated to be not that trivial. However if you can cook up a code patch yourself that implements this feature in a backwards-compatible non-intrusive way, with all the proper mapi protocol extension, we can promise you to review it and if it is good we will merge into our main, with all the proper credits to you of course.
If you want to go down that path, we can reopen this issue knowingly that you are working on it.
