### ISSUE TITLE
MonetDB website search shows result links to localhost:8080

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7120]
If I search monetdb.org, for, say, ["functions"](https://www.monetdb.org/index.php/search/node?keys=functions), all the results I get have links to localhost:8080/whatever . I don't remember search being busted like this when I last used it...

**Comment by yzchang** [comment]
This is the same problem as reported in #7072.  It was fixed several times, but once in a while, it comes back again.  I'm closing this ticket but keeping #7072 open until we find a better solution.
