### ISSUE TITLE
Enable grouping sets in Mondrian for MonetDB

### ISSUE THREAD

**Issue by llorieb** [MonetDB/MonetDB#7121]
I'm using MonetDB with Pentaho to analyze a very large fact table (around 200 millons rows and more than 50 columns). MonetDB Jun2020 release implemented grouping sets, and I think this feature would increase aggregates performance noticeably.

Today, using grouping sets in Pentaho Mondrian is a feature limited to a couple of databases (Oracle, DB2 and Greenplum), and it'd be great having MonetDB in such a selected group.

**Comment by PedroTadim** [comment]
Hello! Adding MonetDB support on Pentaho Mondrian is something we should do, or Pentaho?

**Comment by llorieb** [comment]
Hi, Pedro!

I don't know! If there's nothing to do in MonetDB in order to dialog with Mondrian, it's OK. I'm going to ask Pentaho if it's possible to support this functionality.

I truly appreciate your comment.

**Comment by yzchang** [comment]
One of our colleagues has started looking into if there's anything we need to do on the MonetDB side about this.  We'll come back to this ticket once we know more.

**Comment by njnes** [comment]
grouping sets has been part of MonetDB for some time now.
