### ISSUE TITLE
Stopping a statement keeps its session locked up

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7123]
When you start a long-running statement on one connection, then, in a second connection, get its tag and issue `call sys.stop(the_tag_of_the_other_statement)` - the statement disappears from the `sys.queue` table, but - the first connection behaves as though it's still running the statement: It doesn't print a prompt, doesn't echo entered characters and won't execute additional statements.

**Expected behavior**
After the stop has been issued, the first connection should print a message about this having happened, and display a prompt for taking the next statement.

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from source

Note: This happened to me with a SELECT-only query, not a query which changes any data.

**Comment by PedroTadim** [comment]
We have improved this on default.
