### ISSUE TITLE
MonetDB Round Function issues in the latest release

### ISSUE THREAD

**Issue by dnstlrsla** [MonetDB/MonetDB#7125]
**Describe the bug**
 - When using round function inside case statement, an error of division by zero occurs

**To Reproduce**
1. Environment and Version
    1.1 MonetDB 5 Server 11.39.17 (Oct2020-SP5)
2. Data Creation
    2.1 DDL
        sql > 
        -- Create Table 
        create table round_test(
            category String null,
            colorby String null,
            stddev_dep_delay double null,
            usl double null,
            lsl double null
        );
        sql > 
        -- Insert Sample Data
        insert into round_test values ( '2017_6','NK',108.939,8258.0,-64.0 );
        insert into round_test values ( '2017_6','VX',null,8258.0,-63.0 );
        insert into round_test values ( '2017_6','EV',101.249,8258.0,-64.0 );
        insert into round_test values ( '2017_6','UA',112.307,8258.0,-64.0 );
        insert into round_test values ( '2017_6','F9',null,8409.0,-64.0 );
        insert into round_test values ( '2017_6','B6',null,8258.0,-64.0 );
        insert into round_test values ( '2017_6','OO',158.159,8258.0,-64.0 );
        insert into round_test values ( '2017_6','WN',null,8258.0,-64.0 );
        insert into round_test values ( '2017_6','AA',160.657,8258.0,-64.0 );
        insert into round_test values ( '2017_6','DL',44.279,8258.0,-63.0 );
        insert into round_test values ( '2017_6','AS',null,8258.0,-64.0 );
        insert into round_test values ( '2017_6','HA',0.0,8258.0,-64.0 );
        insert into round_test values ( '2017_6',null,null,null,null );

        -- Make sure the data is inserted properly

        sql > select * from round_test;
        +----------+---------+--------------------------+--------------------------+--------------------------+
        | category | colorby | stddev_dep_delay         | usl                      | lsl                      |
        +==========+=========+==========================+==========================+==========================+
        | 2017_6   | NK      |                  108.939 |                     8258 |                      -64 |
        | 2017_6   | VX      |                     null |                     8258 |                      -63 |
        | 2017_6   | EV      |                  101.249 |                     8258 |                      -64 |
        | 2017_6   | UA      |                  112.307 |                     8258 |                      -64 |
        | 2017_6   | F9      |                     null |                     8409 |                      -64 |
        | 2017_6   | B6      |                     null |                     8258 |                      -64 |
        | 2017_6   | OO      |                  158.159 |                     8258 |                      -64 |
        | 2017_6   | WN      |                     null |                     8258 |                      -64 |
        | 2017_6   | AA      |                  160.657 |                     8258 |                      -64 |
        | 2017_6   | DL      |                   44.279 |                     8258 |                      -63 |
        | 2017_6   | AS      |                     null |                     8258 |                      -64 |
        | 2017_6   | HA      |                        0 |                     8258 |                      -64 |
        | 2017_6   | null    |                     null |                     null |                     null |
        +----------+---------+--------------------------+--------------------------+--------------------------+
    
    2.2 Data Query Task
        sql > select a.*,
                case when stddev_dep_delay is null or stddev_dep_delay=0 
                    then -9999 
                else round(((usl - lsl) / (6 * stddev_dep_delay)), 3) end as pp_dep_delay
            from round_test a;
            
        -- Execution result 
        division by zero.
        -- **In previous version (MonetDB 5 server v11.31.13) did not have this problem**
    2.3 Other tests to validate the query
        /* 
         SUCCESS - Not use Round function
        */
        sql > select a.*,
            case when stddev_dep_delay is null or stddev_dep_delay=0 
                then -9999 
            else 
                --round( 
                    ((usl - lsl) / (6 * stddev_dep_delay)) 
                --   , 3)
                end as pp_dep_delay
        from round_test a;
        +----------+---------+--------------------------+--------------------------+--------------------------+--------------------------+
        | category | colorby | stddev_dep_delay         | usl                      | lsl                      | pp_dep_delay             |
        +==========+=========+==========================+==========================+==========================+==========================+
        | 2017_6   | NK      |                  108.939 |                     8258 |                      -64 |       12.731895831612187 |
        | 2017_6   | VX      |                     null |                     8258 |                      -63 |                    -9999 |
        | 2017_6   | EV      |                  101.249 |                     8258 |                      -64 |       13.698900729883754 |
        | 2017_6   | UA      |                  112.307 |                     8258 |                      -64 |       12.350076130606285 |
        | 2017_6   | F9      |                     null |                     8409 |                      -64 |                    -9999 |
        | 2017_6   | B6      |                     null |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | OO      |                  158.159 |                     8258 |                      -64 |        8.769655852654607 |
        | 2017_6   | WN      |                     null |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | AA      |                  160.657 |                     8258 |                      -64 |        8.633299513871167 |
        | 2017_6   | DL      |                   44.279 |                     8258 |                      -63 |        31.32033996552165 |
        | 2017_6   | AS      |                     null |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | HA      |                        0 |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | null    |                     null |                     null |                     null |                    -9999 |
        +----------+---------+--------------------------+--------------------------+--------------------------+--------------------------+

        /* 
         SUCCESS - using the round function outside the case statement
        */
        sql > select a.*, round( 
            case when stddev_dep_delay is null or stddev_dep_delay=0 
                then -9999 
            else ((usl - lsl) / (6 * stddev_dep_delay)) end , 3) as pp_dep_delay
        from round_test a;
        +----------+---------+--------------------------+--------------------------+--------------------------+--------------------------+
        | category | colorby | stddev_dep_delay         | usl                      | lsl                      | pp_dep_delay             |
        +==========+=========+==========================+==========================+==========================+==========================+
        | 2017_6   | NK      |                  108.939 |                     8258 |                      -64 |                   12.732 |
        | 2017_6   | VX      |                     null |                     8258 |                      -63 |                    -9999 |
        | 2017_6   | EV      |                  101.249 |                     8258 |                      -64 |                   13.699 |
        | 2017_6   | UA      |                  112.307 |                     8258 |                      -64 |                    12.35 |
        | 2017_6   | F9      |                     null |                     8409 |                      -64 |                    -9999 |
        | 2017_6   | B6      |                     null |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | OO      |                  158.159 |                     8258 |                      -64 |                     8.77 |
        | 2017_6   | WN      |                     null |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | AA      |                  160.657 |                     8258 |                      -64 |                    8.633 |
        | 2017_6   | DL      |                   44.279 |                     8258 |                      -63 |                    31.32 |
        | 2017_6   | AS      |                     null |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | HA      |                        0 |                     8258 |                      -64 |                    -9999 |
        | 2017_6   | null    |                     null |                     null |                     null |                    -9999 |
        +----------+---------+--------------------------+--------------------------+--------------------------+--------------------------+

**Expected behavior**
-- **In previous version (MonetDB 5 server v11.31.13)**
sql > select a.*,
                case when stddev_dep_delay is null or stddev_dep_delay=0 
                    then -9999 
                else round(((usl - lsl) / (6 * stddev_dep_delay)), 3) end as pp_dep_delay
            from round_test a;
+----------+---------+--------------------------+--------------------------+--------------------------+--------------------------+
| category | colorby | stddev_dep_delay         | usl                      | lsl                      | pp_dep_delay             |
+==========+=========+==========================+==========================+==========================+==========================+
| 2017_6   | NK      |                  108.939 |                     8258 |                      -64 |                   12.732 |
| 2017_6   | VX      |                     null |                     8258 |                      -63 |                    -9999 |
| 2017_6   | EV      |                  101.249 |                     8258 |                      -64 |                   13.699 |
| 2017_6   | UA      |                  112.307 |                     8258 |                      -64 |                    12.35 |
| 2017_6   | F9      |                     null |                     8409 |                      -64 |                    -9999 |
| 2017_6   | B6      |                     null |                     8258 |                      -64 |                    -9999 |
| 2017_6   | OO      |                  158.159 |                     8258 |                      -64 |                     8.77 |
| 2017_6   | WN      |                     null |                     8258 |                      -64 |                    -9999 |
| 2017_6   | AA      |                  160.657 |                     8258 |                      -64 |                    8.633 |
| 2017_6   | DL      |                   44.279 |                     8258 |                      -63 |                    31.32 |
| 2017_6   | AS      |                     null |                     8258 |                      -64 |                    -9999 |
| 2017_6   | HA      |                        0 |                     8258 |                      -64 |                    -9999 |
| 2017_6   | null    |                     null |                     null |                     null |                    -9999 |
+----------+---------+--------------------------+--------------------------+--------------------------+--------------------------+

        
**Screenshots**

**Software versions**
 - MonetDB version number [a milestone label] : MonetDB 5 Server 11.39.17 (Oct2020-SP5)
 - OS and version: [e.g. Ubuntu 18.04] CentOS 7.4
 - Installed from release package or self-installed and compiled : Installed from release package

**Comment by PedroTadim** [comment]
I just tested the query in Jul2021 branch and it goes fine. Can you wait until it gets released? The issue is not because of the round function, but something related to conditional execution where it shouldn't have triggered the division on 0 values from the column stddev_dep_delay.

**Comment by dnstlrsla** [comment]
Thank you for answering my question.
I understood what was the problem
