### ISSUE TITLE
Bug report: "write error on stream" that results in mclient crash

### ISSUE THREAD

**Issue by JZuming** [MonetDB/MonetDB#7127]
**Describe the bug**
I used my fuzzing tool to test monetdb , and found that a crash in mclient.

**To Reproduce**
1. monetdb destroy -f test_db
2. monetdb create test_db
3. monetdb release test_db
4. mclient -u monetdb -d test_db
5. sql>
`create table t_qh (
c_f INTEGER ,
c_y2 INTEGER ,
c_i768 INTEGER ,
c_tqx TEXT ,
c_mknkhml TEXT ,
primary key(c_f, c_y2),
unique(c_y2)
);`
6. sql>
`create table t_ckfystsc (
c_kvhq5p INTEGER ,
c_aifpl INTEGER ,
c_jf6 TEXT ,
c_f31ix TEXT NOT NULL,
c_lk0zqfa INTEGER ,
c_qotzuxn INTEGER ,
c_w_z TEXT ,
primary key(c_lk0zqfa),
unique(c_kvhq5p)
);`
7. sql>
`create table t_irwrntam7 as
select
    ref_0.c_i768 as c0,
    ref_0.c_i768 as c1,
    ref_0.c_f as c2,
    ref_0.c_i768 as c3
  from
    t_qh as ref_0
  where (ref_0.c_f in (
      select
            ref_1.c_lk0zqfa as c0
          from
            t_ckfystsc as ref_1))
    and (ref_0.c_y2 >= (
      select
            ref_0.c_y2 as c0
          from
            t_qh as ref_7
        union
        select
            ref_0.c_f as c0
          from
            t_qh as ref_9));`
8. sql> (enter a "Enter")
9. "write error on stream" occur, and mclient crash.

**Expected behavior**
Create table t_irwrntam7 successfully.

**Software versions**
 - MonetDB Oct2020_17
 - Ubuntu 18.04

**Comment by PedroTadim** [comment]
Just fixed it! Thanks for the report!
