### ISSUE TITLE
Bug report: strange error message "Subquery result missing" 

### ISSUE THREAD

**Issue by JZuming** [MonetDB/MonetDB#7128]
**Describe the bug**
I used my fuzzing tool to test monetdb , and found it return a strange error message "Subquery result missing" when processing specific sql.

**To Reproduce**
1. monetdb destroy -f test_db
2. monetdb create test_db
3. monetdb release test_db
4. mclient -u monetdb -d test_db
5. sql>
`create table t_qh (
c_f INTEGER ,
c_y2 INTEGER ,
c_i768 INTEGER ,
c_tqx TEXT ,
primary key(c_f, c_y2),
unique(c_y2)
);`
6. sql>
`select
    ref_1.c_i768 as c0
  from
    t_qh as ref_1
      cross join (select
            ref_2.c_i768 as c0
          from
            t_qh as ref_2
              inner join t_qh as ref_3
              on (1=1)
          where ref_3.c_f <> ref_3.c_y2) as subq_0
  where ref_1.c_y2 < (
      select
          ref_1.c_f as c0
        from
          t_qh as ref_4
        where (EXISTS (
                  select distinct  
                      ref_5.c_i768 as c0  
                    from 
                      t_qh as ref_5))            and (ref_1.c_i768 between ref_4.c_y2 and ref_1.c_y2));`
7. "Subquery result missing" occur!

**Expected behavior**
return select result normally.

**Software versions**
 - MonetDB Oct2020_17
 - Ubuntu 18.04

**Comment by PedroTadim** [comment]
I just fixed it. Thanks for the report!
