### ISSUE TITLE
Support deletion from several tables with the same statement

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7132]
When you're doing data cleaning, you typically apply a bunch of UPDATE and DELETE queries with a certain condition after determining those records need correction or removal.  But it is also relatively common  that you wish to apply the same criterion in other tables - possibly related ones. It would therefore be convenient, instead of writing:
```
DELETE FROM t1 WHERE cond;
DELETE FROM t2 WHERE cond;
```
to be able to write:
```
DELETE FROM t1, t2 WHERE cond;
```
and similarly for update.

The semantics of the second query would be identical to the first, assuming the condition on t1 doesn't involve t2. If it does, either this combined-deletion/update command can be discarded (easier), or it can be based on the state of both tables before the deletion/update (more convenient, and AFAICT well-defined).

This should not, AFAICT, interfere with proper SQL queries, as currently, adding the comma after the table identifier is a syntax error.

The output could be the overall number of records affected (easier) or the number of records affected in each table (more information, slightly more coding).

If this is supported, another level of this feature could be:
```
DELETE FROM schema1.* WHERE cond;
```
which is the equivalent of splicing all tables in the schema with commas.

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from source

**Comment by PedroTadim** [comment]
Ok, then can you tell me why:
start transaction;
delete from t1 where cond;
delete from t2 where cond;
commit; 
is not good enough?

**Comment by eyalroz** [comment]
@PedroTadim : Semantically, it's great, but it requires duplicating the query text. What I'm asking for is strictly a convenience feature - some syntactic sugar.

**Comment by MartinVanData** [comment]
your suggestion:
DELETE FROM t1, t2 WHERE cond;
is non standard SQL.
DELETE command only works on one table by design and specification.

Is it really a problem to copy the line:
DELETE FROM t1 WHERE cond;
text, paste it and change t1 into t2?
In many SQL GUI program such as SQuirreL or DBeaver you can easily do this, save it as a script and execute part of the script interactively.
I don't see the problem or need to support this non standard SQL syntax.

**Comment by eyalroz** [comment]
Hello Martin,

* Yes, my suggestion is not standard SQL; but - it does not interfere with the support for standard SQL. That is, no standard SQL query will be mis-interpreted if my suggestion is adopted.
* You asked whether copying-and-pasting is a problem, and the answer is: Yes, very much so! Why? Because in the example here everything is short - "t1", "t2", "cond". Suppose I actually had a long, multi-line, select query for each table, and a long condition with inner queries instead of "cond", and possibly also an initial WITH clause. Multi-line copy-and-pasting in a terminal is risky business; plus you might just exceed your scroll buffer.
* Maybe this action can be made easier using SQL GUI clients, but the typical MonetDB user uses mclient on a terminal.
