### ISSUE TITLE
Tables added without actively setting a schema shouldn't be placed in the sys schema

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7134]
Consider the following commands on an empty DB and their output:
```
sql>CREATE TABLE t1 AS SELECT 1 AS c1, 2 AS c2;
operation successful
sql>\d t1
CREATE TABLE "sys"."t1" (
	"c1" TINYINT,
	"c2" TINYINT
);
sql>\d
TABLE  sys.t1
sql>SELECT * FROM sys.t1;
+------+------+
| c1   | c2   |
+======+======+
|    1 |    2 |
+------+------+
1 tuple
```
The `t1` table is added to the `sys` schema. I believe it is not reasonable for it to be in the same schema as the actually-system-internal tables. So - please don't put it in there.

This can be done in one of two ways:

1. Allow for tables with a null or empty schema (not sure whether the SQL standard supports this).
2. Choose a default schema that is not `sys`. For example: `default`. Or perhaps the name of the database.

**Expected behavior**
```
sql>CREATE TABLE t1 AS SELECT 1 AS c1, 2 AS c2;
operation successful
sql>\d t1
CREATE TABLE "t1" (
	"c1" TINYINT,
	"c2" TINYINT
);
sql>\d
TABLE  t1
sql>SELECT * FROM sys.t1;
SELECT: no such table 'sys.t2'
```
or
```
sql>CREATE TABLE t1 AS SELECT 1 AS c1, 2 AS c2;
operation successful
sql>\d t1
CREATE TABLE "mydb"."t1" (
	"c1" TINYINT,
	"c2" TINYINT
);
sql>\d
TABLE  t1
sql>SELECT * FROM sys.t1;
SELECT: no such table 'sys.t2'
```

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from source

**Comment by swingbit** [comment]
(Just another user here, this is not necessarily the developers' opinion)

I'm not sure I'm with you on this one.
 
I think your confusion/wish comes from the concept of "no schema" . There is no such thing in MonetDB. You always are in a schema, which is `sys` by default, which means there is no "schema-less" table either.

So the table is not created in the `sys` schema, but simply in the schema you are in at the moment. That seems very reasonable to me.

Also, yes, according to `sys.tables`, it is created in `sys` (if you are there).

```
sql>set schema sys;
operation successful

sql>create table x(a int);
operation successful

sql>\d
TABLE  sys.x

sql>select * from tables where name='x';
+-------+------+-----------+-------+------+--------+---------------+--------+-----------+
| id    | name | schema_id | query | type | system | commit_action | access | temporary |
+=======+======+===========+=======+======+========+===============+========+===========+
| 18999 | x    |      2000 | null  |    0 | false  |             0 |      0 |         0 |
+-------+------+-----------+-------+------+--------+---------------+--------+-----------+
1 tuple

sql>select * from schemas where id = 2000;
+------+------+---------------+-------+--------+
| id   | name | authorization | owner | system |
+======+======+===============+=======+========+
| 2000 | sys  |             2 |     3 | true   |
+------+------+---------------+-------+--------+
1 tuple
```

On a different schema:
```
sql>set schema spinque;
operation successful

sql>create table x(a int);
operation successful

sql>\d
TABLE  spinque.x

sql>select * from sys.tables where name='x';
+-------+------+-----------+-------+------+--------+---------------+--------+-----------+
| id    | name | schema_id | query | type | system | commit_action | access | temporary |
+=======+======+===========+=======+======+========+===============+========+===========+
| 18999 | x    |      2000 | null  |    0 | false  |             0 |      0 |         0 |
| 19010 | x    |      8951 | null  |    0 | false  |             0 |      0 |         0 |
+-------+------+-----------+-------+------+--------+---------------+--------+-----------+
2 tuples

sql>select * from sys.schemas where id = 8951;
+------+---------+---------------+-------+--------+
| id   | name    | authorization | owner | system |
+======+=========+===============+=======+========+
| 8951 | spinque |          8950 |     3 | false  |
+------+---------+---------------+-------+--------+
1 tuple

```

**Comment by eyalroz** [comment]
@swingbit : You're right, in that the table is created in the sys schema. I'll rephrase my opening post.

**Comment by PedroTadim** [comment]
When the database is created, by default the "sys" schema is created, as well as the 'monetdb' user with 'monetdb' password. Then it's up to the database administrator to create other users, change the 'monetdb' user password and create schemas for data. For a user you can set his default session schema, so he doesn't have to change the schema every time he logs in. As swingbit said every table must have a schema, except for declared tables, but those only live on function/procedure scopes.

**Comment by eyalroz** [comment]
@PedroTadim : Naturally, actions can change the schema. What I'm suggesting is for the default for tables created by a user (who is not doing administrative work) to be something other than `sys`.

**Comment by PedroTadim** [comment]
But this falls in the same way that there should be another user besides 'monetdb' by default.

**Comment by yzchang** [comment]
Hai Eyal,
Just to add to what Pedro said, at the creation of a new user, you can assign this user a default schema other than `sys`, e.g.:
```
CREATE ROLE voc_role;
CREATE SCHEMA "voc" AUTHORIZATION "voc_role";
CREATE USER "voc" WITH PASSWORD 'voc' NAME 'VOC Explorer' SCHEMA "voc";
GRANT voc_role TO voc;
```

When you log in as the `voc` user:
```
$ mclient -d voc -u voc
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Oct2020-SP5)
...
sql>select current_role;
+------+
| %2   |
+======+
| voc  |
+------+
1 tuple
sql>select current_schema;
+------+
| %2   |
+======+
| voc  |
+------+
1 tuple
sql>set role voc_role;
operation successful
sql>create table t (i int);
operation successful
sql>\d
TABLE  voc.t
```

This should give you what you want.

**Comment by eyalroz** [comment]
This is all nice, but - why does it make it a better idea to default to `sys`? What's the downside of choosing another arbitrary name?

Anyway, it's only a "cosmetic" suggestion. It doesn't matter much either way. Up to you.

**Comment by njnes** [comment]
there basically is not other schema too default to, unless the user/admin created that. So for monetdb we expect the admin too setup a new user with a proper default schema.

**Comment by eyalroz** [comment]
> there basically is not other schema too default to

1. No schema/empty schema/null schema.
2. Define such a default schema - which will not be `sys`. It could be `default`. It could be `data`. It could be `tables`. It could be `_`.

I realize you guys are all used to `sys` after years of use, but for new users, the lack of separation of internal and user-defined tables is confusing.

> , unless the user/admin created that. 

It's almost always better to ship a product with useful defaults and leave less necessary work for the user...

**Comment by njnes** [comment]
I tend too agree with the lack of separation being an issue. We should identify how much work / impact this will give too the (existing) users.

**Comment by njnes** [comment]
in the september 2022 release we now try to convince users to have a seperate schema. If a user is created with out default schema, we create one. So a user never ends by default in the sys schema etc. Its afcourse a compromise between multiple ideas and (old) handeling (to not have problems with current users), so hope this is sufficiently separation of system and user content.
