### ISSUE TITLE
Monetdb Python UDF crashes because of null aggr_group_arr

### ISSUE THREAD

**Issue by tle211212** [MonetDB/MonetDB#7138]
Hi MonetDB dev,

I encounter this MonetDB crash when I try out the Python UDF.

Test data:
sql>select * from integers;
+------+
| i    |
+======+
|    1 |
|    2 |
|    3 |
|    4 |
|    5 |
|    6 |
|    7 |
|    8 |
|    9 |
|   10 |
+------+

sql> select python_sum(i) from integers where i = 1 group by i;   ==> segfault

python_sum is just a simple PYTHON_MAP function: return numpy.sum(v);

When I rebuild MonetDB with debuginfo, this is where the code fails.
pyapi3.c
      for (element_it = 0; element_it < elements; element_it++) { 
        group_counts[aggr_group_arr[element_it]]++;    ==> aggr_group_arr is null
      }

I hope you can fix it soon. Thank you.

**Comment by PedroTadim** [comment]
I already spotted the issue. The void BAT case is missing there.

**Comment by tle211212** [comment]
Thank you. I will pull the fix and test it next week.

**Comment by PedroTadim** [comment]
I am going to close it for now. If you still find any issue, please re-open. Thanks for the report!
