### ISSUE TITLE
PYTHON_MAP UDF aggr_group variable has wrong data

### ISSUE THREAD

**Issue by tle211212** [MonetDB/MonetDB#7139]
Hi MonetDB dev team,

When I tryout the Python_map UDF functionality, the PYTHON_MAP UDF aggr_group variable has wrong data. It does not contain the aggr group id of each item.

My data contains a table having 800.000 rows and a "career" column having 20 distinct values.
My query is: select career, python_aggr(id) from fhs_product_dim group by career;

In the MonetDB sql explain, python UDF call is:
|     X_29:bat[:lng] := pyapi3map.subeval_aggr(0x55d9a82aa680:ptr, "{ # My python code }":str, X_23:bat[:lng], X_25:bat[:oid], C_26:bat[:o :
: id], true:bit);                                                              :

	X_23: correctly has "id" of all rows which are what I want to do computation on.
	X_25: incorrectly has 76 items (it should have 800.000 aggr group id)

The reason it returns 76 items is because monetdb run the query in 4 parts, 3 of them return 20 and the other returns 16.

The sql explain:
sql>explain select career, python_aggr(id) from fhs_product_dim group by career;
+------------------------------------------------------------------------------+
| mal                                                                          |
+==============================================================================+
| function user.main():void;                                                   |
|     X_1:void := querylog.define("explain select career, python_sum(id) from  |
: fhs_product_dim group by career;":str, "default_pipe":str, 23:int);          :
|     X_34:bat[:str] := bat.pack("sys.fhs_product_dim":str, "sys.%1":str);     |
|     X_35:bat[:str] := bat.pack("career":str, "%1":str);                      |
|     X_36:bat[:str] := bat.pack("varchar":str, "bigint":str);                 |
|     X_37:bat[:int] := bat.pack(255:int, 64:int);                             |
|     X_38:bat[:int] := bat.pack(0:int, 0:int);                                |
|     X_4:int := sql.mvc();                                                    |

################################################################################
################################################################################
|     C_88:bat[:oid] := sql.tid(X_4:int, "sys":str, "fhs_product_dim":str, 0:i |	
: nt, 4:int);                                                                  :

################################################################################
################################################################################
|     X_107:bat[:str] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, " |	
: career":str, 0:int, 0:int, 4:int);                                           :

################################################################################
################################################################################
|     X_124:bat[:str] := algebra.projection(C_88:bat[:oid], X_107:bat[:str]);  |   	
|     (X_131:bat[:oid], C_132:bat[:oid]) := group.groupdone(X_124:bat[:str]);  |
                
################################################################################
################################################################################
|     X_134:bat[:str] := algebra.projection(C_132:bat[:oid], X_124:bat[:str]); |   	
|     C_90:bat[:oid] := sql.tid(X_4:int, "sys":str, "fhs_product_dim":str, 1:i |
: nt, 4:int);                                                                  :
|     X_108:bat[:str] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, " |
: career":str, 0:int, 1:int, 4:int);                                           :
|     X_125:bat[:str] := algebra.projection(C_90:bat[:oid], X_108:bat[:str]);  |
|     (X_135:bat[:oid], C_136:bat[:oid]) := group.groupdone(X_125:bat[:str]);  |
|     X_138:bat[:str] := algebra.projection(C_136:bat[:oid], X_125:bat[:str]); |
|     C_92:bat[:oid] := sql.tid(X_4:int, "sys":str, "fhs_product_dim":str, 2:i |
: nt, 4:int);                                                                  :
|     X_109:bat[:str] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, " |
: career":str, 0:int, 2:int, 4:int);                                           :
|     X_126:bat[:str] := algebra.projection(C_92:bat[:oid], X_109:bat[:str]);  |
|     (X_139:bat[:oid], C_140:bat[:oid]) := group.groupdone(X_126:bat[:str]);  |
|     X_142:bat[:str] := algebra.projection(C_140:bat[:oid], X_126:bat[:str]); |
|     C_94:bat[:oid] := sql.tid(X_4:int, "sys":str, "fhs_product_dim":str, 3:i |
: nt, 4:int);                                                                  :
|     X_110:bat[:str] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, " |
: career":str, 0:int, 3:int, 4:int);                                           :
|     X_127:bat[:str] := algebra.projection(C_94:bat[:oid], X_110:bat[:str]);  |
|     (X_143:bat[:oid], C_144:bat[:oid]) := group.groupdone(X_127:bat[:str]);  |
|     X_146:bat[:str] := algebra.projection(C_144:bat[:oid], X_127:bat[:str]); |
|     X_161:bat[:str] := mat.packIncrement(X_134:bat[:str], 4:int);            |
|     X_163:bat[:str] := mat.packIncrement(X_161:bat[:str], X_138:bat[:str]);  |
|     X_164:bat[:str] := mat.packIncrement(X_163:bat[:str], X_142:bat[:str]);  |
|     X_24:bat[:str] := mat.packIncrement(X_164:bat[:str], X_146:bat[:str]);   |	
|     (X_25:bat[:oid], C_26:bat[:oid]) := group.groupdone(X_24:bat[:str]);     |
|     X_28:bat[:str] := algebra.projection(C_26:bat[:oid], X_24:bat[:str]);    |
|     X_95:bat[:lng] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, "i |
: d":str, 0:int, 0:int, 4:int);                                                :
|     X_120:bat[:lng] := algebra.projection(C_88:bat[:oid], X_95:bat[:lng]);   |
|     X_96:bat[:lng] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, "i |
: d":str, 0:int, 1:int, 4:int);                                                :
|     X_121:bat[:lng] := algebra.projection(C_90:bat[:oid], X_96:bat[:lng]);   |
|     X_97:bat[:lng] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, "i |
: d":str, 0:int, 2:int, 4:int);                                                :
|     X_122:bat[:lng] := algebra.projection(C_92:bat[:oid], X_97:bat[:lng]);   |
|     X_98:bat[:lng] := sql.bind(X_4:int, "sys":str, "fhs_product_dim":str, "i |
: d":str, 0:int, 3:int, 4:int);                                                :
|     X_123:bat[:lng] := algebra.projection(C_94:bat[:oid], X_98:bat[:lng]);   |
|     X_166:bat[:lng] := mat.packIncrement(X_120:bat[:lng], 4:int);            |
|     X_167:bat[:lng] := mat.packIncrement(X_166:bat[:lng], X_121:bat[:lng]);  |
|     X_168:bat[:lng] := mat.packIncrement(X_167:bat[:lng], X_122:bat[:lng]);  |
|     X_23:bat[:lng] := mat.packIncrement(X_168:bat[:lng], X_123:bat[:lng]);   |

################################################################################
################################################################################
|     X_29:bat[:lng] := pyapi3map.subeval_aggr(0x55d9a82aa680:ptr, "{ 
  # My python code };":str, X_23:bat[:lng], X_25:bat[:oid], C_26:bat[:o :
: id], true:bit);                                                              :

|     sql.resultSet(X_34:bat[:str], X_35:bat[:str], X_36:bat[:str], X_37:bat[: |
: int], X_38:bat[:int], X_28:bat[:str], X_29:bat[:lng]);                       :
| end user.main;                                                               |

Please let me know what I should do more to assist you in resolving the bug.

Thank you.

**Comment by PedroTadim** [comment]
I didn't develop the Python UDF feature, but I guess a tseqbase is missing here.

**Comment by PedroTadim** [comment]
Can you make a fully reproducible example, so we can see it in detail?

**Comment by tle211212** [comment]
Hi Pedro, thanks for your support. Here it is.

https://app.fahasa.com/s/table.sql.gz

gzip -dc table.sql.gz | mclient test
monetdb set embedpy3=yes test
monetdb set nthreads=1 test # I set 1 thread so that it produces much smaller MAL program, easier to debug

CREATE AGGREGATE python_sum(val BIGINT) 
RETURNS BIGINT 
LANGUAGE PYTHON_MAP {   
    try:
        unique = numpy.unique(aggr_group)
        x = numpy.zeros(shape=(unique.size))
        for i in range(0, unique.size):
            x[i] = numpy.sum(val[aggr_group==unique[i]])
    except NameError:
        # aggr_group doesn't exist. no groups, aggregate on all data
        x = numpy.sum(val)
    return(x)
};

explain select career, python_sum(id) from fhs_product_dim group by career;
|     X_29:bat[:lng] := pyapi3map.subeval_aggr(0x55a75cc82070:ptr, "{   \n    try:\n        unique = numpy.unique(aggr_grou |
: p)\n        x = numpy.zeros(shape=(unique.size))\n        for i in range(0, unique.size):\n            x[i] = numpy.sum(v :
: al[aggr_group==unique[i]])\n    except NameError:\n        # aggr_group doesn't exist. no groups, aggregate on all data\n :
:         x = numpy.sum(val)\n    return(x)\n};":str, X_23:bat[:lng], X_25:bat[:oid], C_26:bat[:oid], true:bit); 

debug explain select career, python_sum(id) from fhs_product_dim group by career;
break X_29
continue
X_23: 839571 items
X_25: 76 items (wrong)

**Comment by PedroTadim** [comment]
Thanks! I will take a look when I have time.

**Comment by PedroTadim** [comment]
After looking deeper into the issue, I can say there's something missing to parallelize PYTHON_MAP aggregates. Currently the aggregate is called on the combined groups from every thread, however the aggregate computation from each thread is missing, therefore the results are wrong. In order to parallelize aggregates, different methods are needed, so I find confusing how that can be done with just the above aggregate description. I didn't develop this extension, but for sure the developer forgot to test this case.

**Comment by tle211212** [comment]
I see. I will try taking a look at how the aggregation of SUM(DISTINCT ...) works. Maybe I can get this issue solved. Thanks Pedro

**Comment by mickbiden2** [comment]
I will take a look when I have time. [Tea tv](https://teatv.ltd/dl/)  [netbanking login](https://hellodear.in/net-banking-guide/)
