### ISSUE TITLE
SQL Query Plan Non Optimal with View

### ISSUE THREAD

**Issue by gm-digitalk** [MonetDB/MonetDB#7140]
Hi, we have a legacy MonetDB 11.29.4 installation on Debian Stretch that we want to upgrade to 11.39.18. However one of our queries is suffering major performance issues due to what appears to be an incorrect ordering of select and project operations in the SQL query plan when computed columns are present in the view and used in the query.

To reproduce in an empty DB:

**Preparation**

`drop table plantest0;`
`drop table plantest1;`
`drop table plantest2;`
`drop table plantest3;`
`drop table plantest4;`
`drop table plantest5;`
`drop table plantest6;`
`drop table plantest7;`
`drop table plantest8;`
`drop table plantest9;`

`create table "sys"."plantest0" ("id" bigint);`
`create table "sys"."plantest1" ("id" bigint);`
`create table "sys"."plantest2" ("id" bigint);`
`create table "sys"."plantest3" ("id" bigint);`
`create table "sys"."plantest4" ("id" bigint);`
`create table "sys"."plantest5" ("id" bigint);`
`create table "sys"."plantest6" ("id" bigint);`
`create table "sys"."plantest7" ("id" bigint);`
`create table "sys"."plantest8" ("id" bigint);`
`create table "sys"."plantest9" ("id" bigint);`

`drop procedure plantestp;`

`create procedure plantestp()`
`begin`
`  declare rowindex bigint;`
`  set rowindex = 0;`
`  while rowindex < 10000000 do`
`    insert into sys.plantest0 (id) values (100000000 + rowindex);`
`    insert into sys.plantest1 (id) values (110000000 + rowindex);`
`    insert into sys.plantest2 (id) values (120000000 + rowindex);`
`    insert into sys.plantest3 (id) values (130000000 + rowindex);`
`    insert into sys.plantest4 (id) values (140000000 + rowindex);`
`    insert into sys.plantest5 (id) values (150000000 + rowindex);`
`    insert into sys.plantest6 (id) values (160000000 + rowindex);`
`    insert into sys.plantest7 (id) values (170000000 + rowindex);`
`    insert into sys.plantest8 (id) values (180000000 + rowindex);`
`    insert into sys.plantest9 (id) values (190000000 + rowindex);`
`    set rowindex = rowindex + 1;`
`  end while;`
`end;`

`call plantestp();`

`drop view plantestv;`

`create view plantestv as`
` select`
`  v.*, v.id / 10000000 as id_div`
` from`
`  (`
`   select * from plantest0 union all`
`   select * from plantest1 union all`
`   select * from plantest2 union all`
`   select * from plantest3 union all`
`   select * from plantest4 union all`
`   select * from plantest5 union all`
`   select * from plantest6 union all`
`   select * from plantest7 union all`
`   select * from plantest8 union all`
`   select * from plantest9`
`  ) as v;`
 
**Query 1 - No Computed Column in View Used** 

`select`
` id_r * 10000000 as id_range_base,`
` count(id_r) as nrows`
`from`
` (select`
`   id / 10000000`
`  from`
`   plantestv v`
`  where`
`   id >= 150000000`
` ) as t (id_r)`
` group by`
`  id_r`
` order by`
`  id_r asc;`
 
**Query 2 - Computed Column in View Used**

`select`
` id_r * 10000000 as id_range_base,`
` count(id_r) as nrows`
`from`
` (select`
`   id_div`
`  from`
`   plantestv v`
`  where`
`   id >= 150000000`
` ) as t (id_r)`
` group by`
`  id_r`
` order by`
`  id_r asc;`

**Results**

In 11.29.4 query 1 and 2 have essentially the same query plan and run in about the same time. In 11.39.18 query 1 has an optimal plan similar to that in 11.29.4 but in 11.39.18 query 2 has a very poor query plan where the computed column is projected before the select to narrow the query. This issue is preventing us from upgrading at the moment because we have a lot of queries like this, and with MonetDB 11.39.18 the performance is just too poor.

Thanks for your time, Graham.

**Comment by PedroTadim** [comment]
This should be fixed in the next release.
