### ISSUE TITLE
COUNT(DISTINCT col) does not calculate correctly distinct values

### ISSUE THREAD

**Issue by v-from-meiro** [MonetDB/MonetDB#7141]
**Describe the bug**
COUNT(DISTINCT col) does not calculate correctly distinct values

**To Reproduce**
```

drop table if exists test;
create table test (id int, version int);
insert into test values
(1,1),
(1,1),
(1,2),
(1,2),
(2,1),
(2,2),
(2,2),
(3,4),
(3,4);

SELECT
  id,
  version,
  COUNT(distinct version)
FROM test
GROUP BY 
  id,
  version
HAVING 
  COUNT(distinct version) > 1;
```

**Expected behavior**
The select above should return 0 rows as a result, because with group by by both id and version there is no way count(distinct version) could return anything else than 1. Also, the number reported by count(distinct version) in the result is wrong. 

**Software versions**
MonetDB v11.39.17 (Oct2020-SP5) in docker container, running on linux host

**Comment by PedroTadim** [comment]
This is an issue in the rel_groupby_distinct optimizer. Trying to find the issue there.

**Comment by PedroTadim** [comment]
We fixed the optimizer yesterday. Thanks for the report!
