### ISSUE TITLE
Aggregates returning tables should not be allowed

### ISSUE THREAD

**Issue by PedroTadim** [MonetDB/MonetDB#7142]
**Describe the bug**
The parser allows any function type to return a table, but it should be limited to regular functions only.
I am going to push the fix in the next few limits.

**To Reproduce**
Create a setting with minimal input for an external user to demonstrate the buggy behavior.
This includes the relevant part of the database schema description.
Performance trace of the rogue query (using the TRACE command)

**Expected behavior**

**Screenshots**

**Software versions**
 - MonetDB version number [a milestone label]
 - OS and version: [e.g. Ubuntu 18.04]
 - Installed from release package or self-installed and compiled

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**

**Comment by avo15** [comment]
Pedro
What is "regular function"  in this context? Will I still be able to create a function that returns table?

**Comment by kutsurak** [comment]
Yes. This bug concerns the `CREATE AGGREGATE` statement. `CREATE FUNCTION` is not affected.
