### ISSUE TITLE
Unable to connect to MonetDB on Mac Big Sur

### ISSUE THREAD

**Issue by mustafa-visokio** [MonetDB/MonetDB#7143]
Hi,

We have issues running latest version of MonetDB (MonetDB 5 server 11.39.17 (Oct2020-SP5) (64-bit, 128-bit integers)) on Mac OS (Big Sur - 11.3.1 20E241).

We installed Monetdb from archive as per the instructions: https://www.monetdb.org/wiki/MonetDB:Installing_on_OS_X

When using mclient we get: 
`server requires unknown hash`

When using JDBC driver we get: 

```
org.monetdb.mcl.MCLException: no supported hash algorithms found in PROT10,COMPRESSION_LZ4
	at org.monetdb.mcl.net.MapiSocket.getChallengeResponse(Unknown Source)
	at org.monetdb.mcl.net.MapiSocket.connect(Unknown Source)
	at org.monetdb.mcl.net.MapiSocket.connect(Unknown Source)
	at org.monetdb.jdbc.MonetConnection.<init>(Unknown Source)
	at org.monetdb.jdbc.MonetDriver.connect(Unknown Source)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:141)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:136)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.lambda$execute$0(OpenConnectionCommand.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I tried to set the hash JDBC property in the connection options, but it gives the following error:

```
Unexpected Error occurred attempting to open an SQL connection.
class org.monetdb.mcl.MCLException: 
MALException:checkCredentials:hash 'SHA512' backend not found

```

This is the output of the jdbc debug file:

```
RD 1623664713194: read final block: 55 bytes
RX 1623664713194: FKkFu9YqlV:mserver:9:PROT10,COMPRESSION_LZ4:LIT:SHA512:
RD 1623664713195: inserting prompt
TD 1623664713195: write final block: 167 bytes
TX 1623664713195: BIG:monetdb:{SHA512}faf414bf395a4587bbb9e0b2732d589a2f6c59e0f3a838b01be3e17e3c491d9e379062b0075d1473e51fbd693ed52bd46e962d5ff975af8812f5af9015c33a4b:sql:DBFarm_2021_1:
RD 1623664713195: read final block: 63 bytes
RX 1623664713196: !MALException:checkCredentials:hash 'SHA512' backend not found
RD 1623664713196: inserting prompt
```

This thread: https://stackoverflow.com/questions/65840138/monetdb-server-requires-unknown-hash suggests a problem with OpenSSL and the installation of a library. Unfortunately, neither compilation from source or the installation of a library via a package manager is applicable for our use case.

This also appears in standard error: 

`# MonetDB/SQL module loaded MonetDB was built without OpenSSL, but what you are trying to do requires it.

#2021-06-14 10:44:49: client1: createExceptionInternal: !ERROR: MALException:checkCredentials:hash 'SHA512' backend not found`

Is this behaviour intentional? Is there any solution to this problem where we can use the monetdb binary (available from your website) without the need to install OpenSSL from source or package manager? 

Any help would be greatly appreciated.

**Comment by manuelpagliaivisokio** [comment]
I think the issue is mcrypt_hashPassword in mcrypt.c.
As far as I can tell there is no way to fix it after compilation.

**Comment by PedroTadim** [comment]
Either OpenSSL or CommonCrypto library are required to connect to the server. Without them, the client cannot connect to the server.

**Comment by manuelpagliaivisokio** [comment]
Is it not a compile time dependency ? I am not a c programmer but it looks to me like even if the openssl/CommonCrypto is available at runtime, the binaries will not able to use it because of the #ifdef  conditions

If that is the case, then the mac binaries will not work  no matter what else is on the system.

**Comment by PedroTadim** [comment]
This is a leftover from the past. Back then to compile some components (eg GDK library), the OpenSSL/CommonCrypto library was not required. So I think instead of giving a compile time error, it would just give a runtime error if it was ever used by a component.

**Comment by supersteves** [comment]
We're just trying to connect via JDBC. Is it the case that MonetDB on Mac does not support JDBC any more?

**Comment by supersteves** [comment]
I think this is a build error. From the code:
```
 * This hack is dangerous because it will allow MonetDB server to be built even without openssl installed. A
 * sever like that will be incompatible with all clients because it does not implement MAPI correctly.
```
https://github.com/MonetDB/MonetDB/blob/master/common/utils/mcrypt.c

**Comment by supersteves** [comment]
I think it's this:
https://github.com/MonetDB/MonetDB/commit/d9a399f9f1f4fe3e34d718867ad40431171701de

> Apple Darwin 19 no longer supports CommonCrypto, ie lets use a brew installed openssl

**Comment by njnes** [comment]
Indeed on Apple Darwin 19 and up we need openssl (for the monetdb server version). How did you compile the mserver5?

**Comment by supersteves** [comment]
We didn't - we downloaded the official binary: https://www.monetdb.org/downloads/MacOSX/Oct2020-SP5/

**Comment by PedroTadim** [comment]
I am not a Mac OS or Homebrew expert, but maybe we have to look at this again.

**Comment by sjoerdmullender** [comment]
The version on our website was built without openssl/commoncrypto support, and that was possible because of the issue Pedro mentioned.  The only thing we actually need from openssl is the hash algorithms, and in particular the SHA512 hash algorithm.  I just pushed a change where we use the reference implementation of this hash function if openssl is not available at compile time (presumably the openssl guys have made some efficiency improvements to the algorithm, hence that's what we prefer).
The homebrew version of monetdb was compiled with an openssl dependency, so that one should work.

**Comment by supersteves** [comment]
Wow! That was fast. Thanks! Are you planning an SP6?

**Comment by sjoerdmullender** [comment]
We're planning a new feature release.  But if necessary (i.e. enough bugs have accumulated) than we could consider an SP6.  But right now that's not very likely yet.

**Comment by supersteves** [comment]
Understood. Would you by any chance know which SP's were built on the wrong environment? Is it SP5 only, or all Oct2020 releases?

**Comment by supersteves** [comment]
@sjoerdmullender I realise that you don't need a new SP to correct this problem. You might simply want to rebuild the Mac binaries for SP5 on a correct environment, in case anyone else runs into this. 

(We're good, though; we built our own from source, after encountering this. Thanks again.)

**Comment by supersteves** [comment]
Hi guys, we're struggling to successfully build Mac binaries ourselves. Is there any chance you can give us an idea of when you are likely to do a release (SP or full) which solves this? Alternatively is it possible to rebuild the Mac binaries for the existing SP5 revision, so they work?

**Comment by yzchang** [comment]
Hai Steve, getting the new feature release out next month has the highest priority at the moment.  The whole team is fully working hard on that.  Sjoerd has the final say about the releases, but afaik, there is no plan for Oct2020-SP6 in short term (if at all).

**Comment by sjoerdmullender** [comment]
Indeed, currently no plans for an SP6.  But I can give some hints about compiling on the Mac.

I use these environment variables (not sure if the CC and CXX do anything, I also use this in the old configure builds):
    export CC=clang
    export CXX=clang++
    export PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig${PKG_CONFIG_PATH+:$PKG_CONFIG_PATH}

And I use these cmake options:
	-DFITS=OFF
	-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
	-DREADLINE_ROOT=/usr/local/opt/readline

**Comment by supersteves** [comment]
Thanks all. I understand all of the above. And thanks for the help with Mac environment, we'll keep trying.

I was merely suggesting that simply rebuilding SP5 on Mac with the correct build environment might resolve the issue. Currently the Mac build for SP5 is broken for everyone, if I understand correctly.

Alternatively, I wonder if e.g. SP4 Mac build is also broken (if not we might be able to tolerate missing whatever SP5 was fixing).

Meanwhile, looking forward to next month's release!

**Comment by PedroTadim** [comment]
Jul2021 has been released
