### ISSUE TITLE
Type up-casting (INT to BIGINT) doesn't always happen automatically

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7144]
**Describe the bug**
When inserting data from a INT column into a BIGINT column, INT is automatically cast to BIGINT in some queries, but not in some other queries.

**To Reproduce**
Run the following queries:
```
create table t (i bigint, j bigint);
# works:
insert into t(i) select id from sys.functions;
# works:
insert into t(j) select id from sys.functions;
# Error "Append failed", mserver5 says: "BATappend2: !ERROR: Incompatible operands"
insert into t(i, j) select id, id from sys.functions;
# works:
insert into t(i, j) select cast(id as bigint), id from sys.functions;
# Error "Append failed", mserver5 says: "BATappend2: !ERROR: Incompatible operands"
insert into t(i, j) select id, cast(id as bigint) from sys.functions;
```

**Expected behavior**
Since MonetDB seems to do automatically up-casting, all the above queries should work.

**Software versions**
 - MonetDB version number [Oct2020-SP5]
 - OS and version: [e.g. Mac OS Catalina]
 - Installed from release package

**Comment by yzchang** [comment]
LIMIT has some but not all effect:
```
# still error:
insert into t(i, j) select id, id from sys.functions limit 1;
# works:
insert into t(i, j) select id, cast(id as bigint) from sys.functions limit 1;
```

**Comment by yzchang** [comment]
Tests added in sql/test/BugTracker-2021/Tests/type-upcasting-INT2BIGINT.Bug-7144

**Comment by PedroTadim** [comment]
Fixed

**Comment by yzchang** [comment]
@PedroTadim thanks for the fix, but is it a good idea to simply disallow duplicate column names for those queries?  Now queries used to work also produces errors.

**Comment by yzchang** [comment]
@PedroTadim thanks for the fix, but is it a good idea to simply disallow duplicate column names for those queries?  Now queries used to work also produces errors. => it can affect existing user queries

**Comment by PedroTadim** [comment]
We don't allow duplicate names in other projection cases, so this pairs with it.
