### ISSUE TITLE
Query produces this error: !ERROR: Could not find %102.%102

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7146]
**Describe the bug**
The query does not execute because an internal error (crash) occurs.

**To Reproduce**
To reproduce just run the query below:
select c, count(distinct b) from (
select 1 a, 'a' b, 'A' c
union all select 2, 'b', 'C'
union all select 3, 'c', 'C'
union all select 4, 'a', 'A'
union all select 5, 'c', 'B'
union all select 6, 'd', 'A'
union all select 7, 'a', 'B'
union all select 8, 'b', 'D'
union all select 9, null, 'D'
) T
group by rollup(c)

**Screenshots**
![image](https://user-images.githubusercontent.com/86444458/123336896-d9836680-d51c-11eb-8f6e-2d5595f578f7.png)

**Software versions**
 - MonetDB version number [MonetDB 5 server v11.39.17 (Oct2020-SP5)]
 - OS and version: [Windows 10 Pro 64 bits - 20H2]
 - Installed from release package

**Comment by PedroTadim** [comment]
I was passing a pointer instead of doing a copy. Nice catch :) It will be fixed in the next release.

**Comment by alexandresilvawek** [comment]
Thanks Pedro!
