### ISSUE TITLE
Internal error occurs and is not shown on the screen

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7147]
**Describe the bug**
When executing a certain SELECT command with syntax error through "SQuirreL SQL" (with JDBC driver), nothing appears on the screen.
But inside MonetDB server an error occurs.

**To Reproduce**
Run the SELECT command below:
select c0, sum(c2) from (select 'A' c0, 'a' c1, 1 c2 union all select 'A', 'a', 2) T

**Expected behavior**
The error message appears on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/86444458/123469915-0e99c280-d5ca-11eb-8745-92aed2ec45b5.png)
![image](https://user-images.githubusercontent.com/86444458/123470034-36892600-d5ca-11eb-8b17-003d1c39ecdb.png)

**Software versions**
 - MonetDB version number [MonetDB 5 server v11.39.17 (Oct2020-SP5)]
 - OS and version: [Windows 10 Pro 64 bits - 20H2]
 - Installed from release package

**Comment by PedroTadim** [comment]
The cardinality of the union was not set right. Fixed! Thanks for the report!
