### ISSUE TITLE
Select distinct is not working correctly

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7148]
**Describe the bug**
Select distinct is not working correctly.
It is only returning 1 record and should return 19.

**To Reproduce**
Run the command below:
select
  distinct c1, c2
from (
select 'A' c0, 'a' c1, 1 c2
union all select 'A', 'a', 2
union all select 'A', 'b', 3
union all select 'B', 'a', 4
union all select 'B', 'b', 5
union all select 'C', 'c', 6
union all select 'C', 'a', 7
union all select 'C', 'b', 8
union all select 'C', 'c', 9
union all select 'D', 'd', 0
union all select 'F', 'a', 1
union all select 'F', 'b', 2
union all select 'E', 'c', 3
union all select 'G', 'd', 4
union all select 'G', 'e', 5
union all select 'G', 'a', 6
union all select 'G', 'b', 7
union all select 'H', 'c', 8
union all select 'A', 'd', 9
union all select 'B', 'e', 0
) T

**Expected behavior**
Return 19 records, as shown below:
![image](https://user-images.githubusercontent.com/86444458/123470981-83213100-d5cb-11eb-889e-2f99d63d109a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/86444458/123471038-97652e00-d5cb-11eb-9939-6adb92f99db7.png)

**Software versions**
 - MonetDB version number [MonetDB 5 server v11.39.17 (Oct2020-SP5)]
 - OS and version: [Windows 10 Pro 64 bits - 20H2]
 - Installed from release package

**Comment by PedroTadim** [comment]
Another cardinality not set right. Fixed! Thanks for the report!
