### ISSUE TITLE
Error When trying to build MonetDB-Oct2020_SP5_release from Source

### ISSUE THREAD

**Issue by arifsaeed** [MonetDB/MonetDB#7150]
**Describe the bug**
I downloaded the following release of Monetdb: MonetDB-Oct2020_SP5_release, 
and tried to build it using cmake, however im getting the error shown below.
I am working with a fresh install of Ubuntu.
I cant figure out what I am doing wrong.  Can anyone please point out what i might be missing.
Just to be clear, I installed odbcinst by running the command: sudo apt-get install -y odbcinst

**To Reproduce**
I then created a build folder inside the MonetDB-Oct2020_SP5_release directory
When i run the following command : `cmake -DCMAKE_BUILD_TYPE=Release ..`
I get the following error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ODBCINST_LIBRARIES (ADVANCED)
    linked by target "MonetODBC" in directory /home/arif/Documents/MonetDB-Oct2020_SP5_release/clients/odbc/driver
```

**Expected behavior**
I was hoping the build to be successfule

**Screenshots**

**Software versions**
 - Monetdb: MonetDB-Oct2020_SP5_release
 - Ubuntu 20.04
 -self insalled

**Issue labeling **
Bug

**Additional context**
Im not sure what I am doing wrong.  I installed a fresh copy of Ubuntu, but cant figure out what I am doing wrong
Any help would be greatly appreciated

**Comment by sjoerdmullender** [comment]
You need to install unixodbc-dev in order to compile MonetDB with ODBC support.
Please take a look at the README.rst file in the top-level directory.

**Comment by arifsaeed** [comment]
If I am planning to only use monetdb as an embeded db, i.e. use monetdbe, does that mean i can ignore the error

**Comment by sjoerdmullender** [comment]
You could try calling cmake with the `-DODBC=OFF` option.
