### ISSUE TITLE
System UDFs lose their indentation - Python functions broken

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7153]
**Describe the bug**
System functions that are included at compile time via `create_include_object` in `CMakeLists.txt` are created when the database is first created. They appear to lose their indentation. All lines start at column 0.
The same actually happens in 11.35, when the same functionality was handled via the `createdb` subfolder.
The same functions do keep their indentation when defined via mclient.

That is harmless for pure SQL functions, but it completely breaks functions whose body is in Python.

**Software versions**
 - MonetDB version number: All releases? Found on 11.39.18
 - OS and version: CentOS 7, Fedora 34
 - compiled from sources

**Comment by PedroTadim** [comment]
Hi! Please confirm if this solves the issue: https://dev.monetdb.org/hg/MonetDB/rev/836177e8d5ff

**Comment by swingbit** [comment]
Yes, this works.
