### ISSUE TITLE
Identifiers and Keywords: problem with character case and double quotes

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7154]
**Describe the bug**
I found behavior that looks different from what is shown in the documentation.

In the documentation shows this:
Names are used to designate database objects. In that role, they are by default in-sensitive case unless encapsulated by double quotes.
Document link:
https://www.monetdb.org/Documentation/SQLReference/LexicalStructure

But in practice, something else happens.

**To Reproduce**
Create this table:
create table teste2 ("BASECOMPETENCIA" text)
And then run this command:
select BASECOMPETENCIA from teste2
This error will happen:
Error: SELECT: identifier 'basecompetencia' unknown
SQLState:  42000
ErrorCode: 0

**Expected behavior**
The command will be executed successfully (case in-sensitive).

**Software versions**
 - MonetDB version number [MonetDB 5 server v11.39.17 (Oct2020-SP5)]
- OS and version: [Windows 10 Pro 64 bits - 20H2]
- Installed from release package

**Comment by yzchang** [comment]
You should use `select “BASECOMPETENCIA” from teste2`, without the double quotes, the column name is automatically converted to lowercase

**Comment by sjoerdmullender** [comment]
I must agree that the term "case sensitive" is badly chosen.  It is not case (in)sensitive.  Case is mapped when unquoted.
Case insensitive implies, as the OP observes, that the names are matched against upper or lower case, which is not what happens.  Unquoted names are mapped to lower case.

**Comment by PedroTadim** [comment]
People have created this bug report in the past several times. I take this as a feature of SQL and people have to learn it.

**Comment by sjoerdmullender** [comment]
It is about wording of the feature, not about the feature itself.

**Comment by njnes** [comment]
The mapping too lower case is used and unlikely too change. The documentation should match that

**Comment by Giovanni-Valcarenghi** [comment]
Documentation updated.
