### ISSUE TITLE
Scalar implementation preferred to bulk implementation in table-returning UDFs

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7157]
**Describe the bug**
For a table-returning UDF, I have both a scalar and a bulk implementation, and they both work. For some reason, using a loop over the scalar implementation is preferred to using the bulk implementation. 
However, I am not even sure if this choice is fully deterministic, I have been noticing seemingly unjustified switches between the two. 
My understanding has always been that when a bulk implementation is available, then it is always preferred. But this isn't what I'm observing.

The function on which I'm observing this has many parameters, so the following is a bit verbose.
To make the context more clear, it's a tokenizer. It usually takes a whole relation with identifiers and strings and returns a longer relation, with identifiers and single tokens.

This is the SQL interface:
```
CREATE OR REPLACE FUNCTION tokenize(id integer, s string, d string, m tinyint, g tinyint, stemmer string, 
  cs boolean, asciify boolean, prob double) 
  RETURNS TABLE (id integer, token string, prob double)
  EXTERNAL NAME spinque."UTF8tokenize_v2";
```

This is the MEL definition for the bulk implementation (it expects a relation in input):
```
command("batspinque", "UTF8tokenize_v2", SPQbat_utf8_tokenize, false, "", 
  args(3, 12, batarg("",int),batarg("",str),batarg("",dbl), batarg("id",int),batarg("s",str),
  batarg("delims",str),batarg("min_tok_len",bte),batarg("grams",bte),
  batarg("stemmer",str),batarg("cs",bit),batarg("asciify",bit),batarg("prob",dbl)))
```

This is the scalar implementation, in MAL (because it only covers corner-cases, it actually redirects to the bulk implementation, with singleton bats):
```
inline function spinque.UTF8tokenize_v2(id:int,s:str,delims:str,min_tok_len:bte,grams:bte,stemmer:str,cs:bit,asciify:bit,prob:dbl)
  (:bat[:int],:bat[:str],:bat[:dbl]);
    bid := bat.single(id);
    bs := bat.single(s);
    bdelims := bat.single(delims);
    bmin_tok_len := bat.single(min_tok_len);
    bgrams := bat.single(grams);
    bstemmer := bat.single(stemmer);
    bcs := bat.single(cs);
    basciify := bat.single(asciify);
    bprob := bat.single(prob);

    (r1,r2,r3) := batspinque.UTF8tokenize_v2(bid,bs,bdelims,bmin_tok_len,bgrams,bstemmer,bcs,basciify,bprob);

    return (r1,r2,r3);
end spinque.UTF8tokenize_v2;
```

**What happens**
The scalar implementation is chosen for a relation input:
```
SELECT * FROM tokenize( (SELECT .... FROM ...) );
```
If I bind the SQL signature directly to the bulk implementation (`... EXTERNAL NAME batspinque."UTF8tokenize_v2"`) , then it works as expected. This means the bulk implementation is correct. But, AFAIK, the SQL signature should always be bound to the scalar module.

Could the fact that one is written in MAL and one in C influence the priority?

**Expected behavior**
The bulk implementation is chosen for a relation input.

**Software versions**
 - MonetDB version number 11.41.0 (but similar behaviours observed in 11.39.18)
 - Fedora 34
 - Compiled from sources

**Comment by swingbit** [comment]
Oh! 

If I remove `inline` from the scalar MAL function, then the bulk version is chosen, as expected.
Does this behaviour make sense?

BTW, an `explain` did not show the function as inlined, anyway.

**Comment by ghost** [comment]
yes. because inline is one of the first optimizer steps. there after the bulk/scalar is determined

**Comment by swingbit** [comment]
@mlkersten that makes sense. 
However, the inline optimizer was the very first one also in 11.35, and this didn't happen. The big difference between 11.35 and the current releases is that it still used MAL files instead of compiled MEL definitions.

**Comment by njnes** [comment]
do we have a simple repeating example for this (less large interface for the function)
