### ISSUE TITLE
CREATE LOCAL TEMPORARY VIEW

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7159]
**Is your feature request related to a problem? Please describe.**
Applications may need to create temporary tables and views from different sessions, and those may use the same table/view names. 
For tables, this is possible by using `CREATE LOCAL TEMPORARY  TABLE`. With this, the scope of the table is limited to the current session, with no clashes among sessions.
However, the same is not allowed for views. I don't see a reason why not.

Note that the current implementation actually creates a problem, which can be seen as a bug by itself:
I can create a `LOCAL TEMPORARY` table, then a view that uses the table, exit the session, and find an invalid view when reopening a new session:
```
sql>create local temporary table t(i int);
operation successful
sql>insert into t values(1);
1 affected row
sql>create view v as select * from t;
operation successful

-- exit mclient and re-enter

sql>select * from v;
SELECT: no such table 't'
```

Note the PostgreSQL solves this issue by forcing a view as temporary when the objects it depends on are temporary:

> If any of the tables referenced by the view are temporary, the view is created as a temporary view (whether TEMPORARY is specified or not).

**Describe the solution you'd like**
`CREATE LOCAL TEMPORARY VIEW`

**Describe alternatives you've considered**
The only alternative I can think of is that the application uses different names per session. Of course it is possible, but it requires quite some more bookkeeping. On the other hand, if this feature already exists for tables, it seems logical to have it for views as well.

**Comment by PedroTadim** [comment]
I take this as a feature request, so it gets lower priority.

**Comment by swingbit** [comment]
It is a feature request. Note however that in absence of temporary views there is also a bug (see above PostgreSQL solution for it)

**Comment by njnes** [comment]
the current dependencies are kept in one global table (dependencies). Probably temporary tables/views related dependencies need to move to a dependencies table on the tmp schema.

**Comment by njnes** [comment]
code is in default now.
