### ISSUE TITLE
LOCAL TEMPORARY table empty after insert

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7160]
**Describe the bug**
A `LOCAL TEMPORARY` table remains empty after `INSERT INTO`

**To Reproduce**
```
sql>create local temporary table t(i int);
operation successful
sql>insert into t values(1);
1 affected row
sql>select * from t;
+---+
| i |
+===+
+---+
0 tuples
```

**Expected behavior**
Table `t` should contain 1 row.

**Software versions**
 - MonetDB version number 11.39.18
 - CentOS 7
 - Compiled from sources

**Comment by PedroTadim** [comment]
Some people have faced this too.
Temporary tables have an additional specifier to tell what to do with the rows after commit. Our default is to drop them. We could  change to keep them, but I have to see the SQL specification first.

Meanwhile you can do: `create local temporary table t(i int) on commit preserve rows;`

**Comment by swingbit** [comment]
Ah, I see. Not a bug then.
I would find the `preserve rows` a more intuitive default, but that's your choice.
Thanks for the explanation.

**Comment by PedroTadim** [comment]
I can confirm the SQL default is to delete the rows.
