### ISSUE TITLE
Extend sys.var_values table

### ISSUE THREAD

**Issue by ghost** [MonetDB/MonetDB#7162]
The sys.var_values() only provide a limited view on the predefined variables.
sql>select * from sys.var_values;
+------------------+-------------------+
| var_name         | value             |
+==================+===================+
| current_role     | monetdb           |
| current_schema   | sys               |
| current_timezone | 7200.000          |
| current_user     | monetdb           |
| debug            | 0                 |
| last_id            | 0                 |
| optimizer        | default_pipe      |
| pi                     | 3.141592653589793 |
| rowcnt            | 1                 |
+------------------+-------------------+

It should also include the pseudo variables:
USER, SESSION_USER, NOW,

**Comment by njnes** [comment]
SESSION_USER is msql sql for impersonated behaviour. We don't support that. USER == CURRENT_USER. ie nothing much to add. And NOW is a function.
