### ISSUE TITLE
Multiple sql.mvc() invocations in the same query

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7163]
**Describe the bug**
A query involving multiple instances of the same view results in a MAL plan with multiple `sql.mvc()` invocations, which blows up the plan (`commonTerms` optimizer cannot de-duplicate)

**To Reproduce**
I reproduced the issue in a small script: [multiple_mvc.sql.txt](https://github.com/MonetDB/MonetDB/files/6937970/multiple_mvc.sql.txt)
The MAL plan generated by this script contains 2 `sql.mvc()` invocations, with some code duplication due to that.
Note that this is a stripped-down example. The real query where this comes from has more than 10 invocations, which generates cascades of code duplication for a MAL plan that takes 3 seconds just to be generated (in 11.35 the plan is generated in 150ms).

**Expected behavior**
Only 1 `sql.mvc()` invocation occurs in a MAL plan.

**Software versions**
 - MonetDB version number 11.39.18
 - OS and version: FC 34
 - Compiled from sources

**Comment by swingbit** [comment]
Actually, hold this.

I cannot reproduce it on the official release (11.39.17 from RPM).
So either the bug was introduced very recently in the non-released 11.39.18, or a merge went wrong in my repository.
I'll update this asap.

**Comment by swingbit** [comment]
OK, the issue was in my test script. It didn't contain any data, which simplified the plan too much.

Here is the new script, which triggers the issue also on the official release: 
[multiple_mvc.sql.txt](https://github.com/MonetDB/MonetDB/files/6937970/multiple_mvc.sql.txt)

**Comment by PedroTadim** [comment]
The culprit seems to be the generated barriers in the Oct2020 release. We have to look into that.

**Comment by swingbit** [comment]
Any chance this could be picked up? It is a bit of a blocker, we are forced to still use 11.35 in production.

**Comment by PedroTadim** [comment]
You have to understand our priorities. Open source has less priority.

**Comment by swingbit** [comment]
I understand. Only asking.

It's just that sometimes I get almost scolded for bringing up bugs on older releases, but it becomes a chicken-egg problem if I can't move forward ;-)

**Comment by yzchang** [comment]
Hai Roberto, since Jul2021 is very different than Oct2020, I quickly ran your script "multiple_mvc.sql.txt" in Jul2021 (hg id: a0e36e93f27d) and didn't find any `sql.mvc()` in the output.  Did I miss anything?

**Comment by swingbit** [comment]
Hi Jenny,
I do see them in Jul2021 (73ca5f7cff, just pulled). Did you use my second upload? The first doesn't trigger the issue.

EDIT: I updated the issue description with the original attachment, to point at the correct file.

**Comment by yzchang** [comment]
thanks.  No idea what I did wrong earlier, but now I get two `sql.mvc` in the EXPLAIN.  Is that the correct reproduction of the problem?

**Comment by swingbit** [comment]
Yes, that's correct. In real queries I get many, but in this small example you get 2.

**Comment by yzchang** [comment]
Yeap, I can image the problem is much larger in the real-world.  Is this the only problem preventing you from upgrading?  Let me ask around how difficult it is to solve this one.

**Comment by swingbit** [comment]
At the moment yes, it's the last pending issue.
Thanks Jenny, I appreciate. Of course I don't expect to change any internal priorities. As we discussed earlier on, it is mutually beneficial if we try to stay as much up to date as possible, that's why I'm pinging for help in moving forward.

**Comment by njnes** [comment]
pushed a fix on the jul branch, ie no more double mvc() calls. Not sure it has great impact jet on the mal plan.

**Comment by swingbit** [comment]
I cherry-picked it into Oct2020, it works, thanks!

**Comment by PedroTadim** [comment]
Can we close the issue?

**Comment by swingbit** [comment]
If the question was for me, yes.
