### ISSUE TITLE
CREATE OR REPLACE FUNCTION: transaction conflict detected

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7169]
**Describe the bug**
I have a system developed in Delphi that connects to MonetDB using MAPI.
This system uses multiple concurrent threads.

When I updated the MonetDB version to "11.41.5", this error here started to appear sometimes:
42000!CREATE OR REPLACE FUNCTION: transaction conflict detected

This error occurs when I connect and run this command in MonetDB:
create or replace function wk_pcre_imatch(s string, pattern string) returns BOOLEAN external name pcre.imatch

I don't know if this is a BUG or if it's something I need to change in the system to make it compatible with some change in the MonetDB version.
Can you help me?

**To Reproduce**
Create multiple threads that simultaneously connect and execute the command "create or replace function wk_pcre_imatch(s string, pattern string) returns BOOLEAN external name pcre.imatch".
I think the programming language doesn't matter. Just use MAPI.

**Software versions**
 - MonetDB version number 11.41.5
 - OS and version: Windows 10 64 bits
 - Installed from release package

**Comment by PedroTadim** [comment]
This is a missing feature. At the moment, we don't allow concurrent transactions to create functions because they can create duplicate function names in the catalog. We can lift this limitation in the future, but it's something I don't expect people to do, so it has less priority. However I have a side question, why do you need to create the same function with multiple connections at the same time?

**Comment by alexandresilvawek** [comment]
Hi Pedro,

I'll try to explain.

I develop a BI (Business Intelligence) software.
Similar to Power BI, but much smaller and simpler.

In this software I can create a dashboard with several indicators (charts, spreadsheets, gauges, etc).
When I enter the dashboard, all indicators are executed at the same time (each in a thread).
And each indicator creates a unique connection and connects to a database (which could be MonetDB).
Now imagine a dashboard with 10 indicators connecting to MonetDB at the same time.
When a connection is made to MonetDB, I need to do a few things, and one of them is to create this function.

I hope I was clear.
I'm from Brazil and my English is not good.
I use Google Translate to help me :).

Additional information:
I'm currently using this command right after connecting to MonetDB on each thread:
create or replace function wk_pcre_imatch(s string, pattern string) returns BOOLEAN external name pcre.imatch

If I could make a command similar to this one below, I think it would meet my need and this error message would no longer appear:
create function IF NOT EXISTS wk_pcre_imatch(s string, pattern string) returns BOOLEAN external name pcre.imatch
As this command would be atomic, I wouldn't have problems synchronizing with the threads.

But, from what I saw in the documentation, this is not possible.

If you have any suggestions or alternatives to help me, I appreciate it.

Thanks.

Alexandre da Silva.

**Comment by PedroTadim** [comment]
I can add a check when a function can be replaced, if every parameter (function type, input parameter names and types, body, etc) are equal, then it doesn't have to be re-added to the catalog. Tomorrow I can do it.

**Comment by alexandresilvawek** [comment]
Thanks Pedro!

**Comment by PedroTadim** [comment]
However remember that if the function doesn't exist and two connections attempt to create it, then there's a chance for a conflict to happen, and there's nothing we can do on our side. The same would apply for an IF NOT EXISTS option.

**Comment by alexandresilvawek** [comment]
I think I understand Pedro.
That is, this implementation that you made will eliminate a case where the conflict can occur, but, there is still another scenario that the conflict can occur.
Even so, thank you, because I think this will considerably decrease the chances of this conflict occurring here in my application.
