### ISSUE TITLE
Cannot install 11.39.17 on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by manuelpagliaivisokio** [MonetDB/MonetDB#7170]
As per title I am having issues getting monetdb Oct2020-SP5 Bugfix Release (11.39.17) to work on the Ubuntu 20.04.

I followed the instructions here: https://www.monetdb.org/downloads/deb/. When it comes to install the packages I specified the version explicitly via:

`sudo apt install monetdb5-sql=11.39.17 monetdb5-server=11.39.17 monetdb-client=11.39.17`

After the installation completes, when I try to start mserver5 I get this error:

`mserver5: error while loading shared libraries: libbat.so.21: cannot open shared object file: No such file or directory`

I installed the same version of monetdb before on other machines running the same OS, and mserver5 was able to start: I think something wrong might have happened to the repository after the 11.41.5 release. 

Any help might be greatly appreciated.

**Comment by sjoerdmullender** [comment]
Make sure all monetdb packages are of the same version, not just the three you mention.

**Comment by manuelpagliaivisokio** [comment]
Thank you Sjoerd, indeed if I specify the version of  libmonetdb21 it works.
