### ISSUE TITLE
Monet DB  - SQL taking time for 5minutes Plus in query we have 1000 keys in IN clause

### ISSUE THREAD

**Issue by bharaththam** [MonetDB/MonetDB#7171]
Description:
SQL query is taking time as it has only 1000 keys in IN CLAUSE.

Tested in both version:
/monet_binaries/MonetDB-11.39.17_PY/bin/monetdbd
/monet_binaries/MonetDB-11.27.13_PY/bin/monetdbd 

let us know if Details are required

Below Query Details :

SELECT DISTINCT "CN_DIM_WALGREEN_1".CONSUMER_DIM_KEY, "WALGREEN_CN_S_4_1_O".ATTR_VALUE FROM "CN_DIM_WALGREEN_1", "WALGREEN_CN_S_4_1_O" WHERE (("CN_DIM_WALGREEN_1".S_152_KEY = 2) AND ("CN_DIM_WALGREEN_1".CONSUMER_DIM_KEY IN (9247, 13947, 14237, 15499, 16953, 22325, 22975, 23080, 24344, 25307, 25924, 25950, 25969, 26032, 26056, 26469, 26940, 27780, 28167, 28853, 28910, 29690, 29827, 30011, 30404, 31949, 33586, 33866, 33944, 34154, 34507, 34649, 35245, 36114, 37037, 37134, 37856, 38046, 38981, 39069, 40026, 40315, 40838, 41322, 42148, 42155, 43016, 44067, 46021, 46632, 46883, 49054, 50396, 50469, 51572, 51956, 52462, 52663, 52978, 53006, 53626, 53971, 54365, 55538, 57869, 58164, 58506, 58612, 59792, 60074, 60106, 60372, 60767, 61046, 61425, 62053, 62445, 63661, 63694, 63785, 64208, 64316, 65112, 65385, 65803, 66159, 67129, 67165, 67323, 67356, 67556, 68312, 68877, 69068, 69331, 69973, 70135, 71706, 71783, 71864, 72200, 73201, 74933, 75475, 75525, 75603, 76396, 78121, 79465, 79617, 80172, 80356, 81171, 81241, 81599, 82217, 82253, 82506, 82527, 82615, 82888, 84108, 84347, 84875, 85038, 85554, 85874, 86045, 86074, 86894, 88015, 88276, 88804, 88845, 90111, 90250, 90282, 91056, 91182, 92965, 93727, 94505, 94596, 94773, 95162, 95633, 95754, 96098, 96183, 96394, 96960, 97809, 97874, 99856, 99868, 101492, 102548, 103427, 103878, 104072, 104105, 104724, 106241, 107142, 108536, 108878, 108889, 110467, 110832, 111818, 112041, 112117, 112468, 112591, 112850, 112970, 113677, 114735, 116345, 116988, 117116, 117587, 117739, 118372, 118760, 119248, 120179, 120659, 120851, 121352, 121558, 121953, 122263, 123124, 123574, 124067, 124913, 124997, 126542, 127138, 127381, 127436, 127523, 128712, 128833, 129861, 129960, 130443, 130685, 130824, 130865, 130904, 131067, 131118, 131641, 131710, 131869, 132062, 133030, 133205, 133291, 133409, 133470, 133733, 133898, 134129, 134625, 135056, 135179, 135495, 136116, 136158, 136265, 136353, 136359, 136375, 136580, 136622, 136659, 136717, 136866, 136903, 137218, 137389, 137395, 137436, 137576, 137654, 138179, 138473, 138630, 138675, 138850, 139288, 139338, 139757, 139802, 140083, 140269, 140767, 140990, 141257, 141567, 141597, 141878, 141952, 142137, 142238, 142309, 143550, 143818, 144429, 144481, 144539, 144684, 145326, 145700, 145811, 146331, 146411, 146658, 146725, 147001, 147146, 147153, 147162, 147243, 147274, 147566, 148601, 149179, 149270, 149734, 149973, 150003, 150028, 150098, 150275, 150319, 150464, 150582, 151098, 151207, 151219, 151750, 152786, 153066, 153366, 153825, 153879, 155402, 156533, 156613, 156671, 156831, 156834, 157220, 157762, 158201, 158337, 158362, 158480, 158820, 158916, 159000, 159178, 159301, 159972, 160852, 161216, 161217, 161450, 161616, 161751, 161971, 162106, 162423, 162866, 163152, 163325, 163984, 164678, 166199, 167031, 167142, 167448, 169155, 170322, 170569, 170703, 170756, 170810, 171903, 172160, 172734, 173666, 174021, 174105, 174408, 174697, 175035, 175292, 175602, 175615, 177730, 179476, 179952, 180222, 180643, 180868, 182320, 184100, 184482, 185231, 185277, 185366, 186154, 186201, 186419, 187845, 188350, 192499, 192790, 192960, 194343, 194381, 194504, 195074, 195281, 196479, 198606, 199923, 200106, 200929, 202284, 203076, 203214, 203928, 204352, 204597, 204967, 205032, 206008, 206240, 206275, 207747, 208731, 209595, 211458, 212086, 212555, 213883, 213940, 214294, 214740, 215378, 215768, 215801, 215842, 215991, 216051, 216088, 216605, 216697, 217212, 218927, 220001, 222019, 223093, 224226, 226273, 226518, 226665, 227187, 229436, 230337, 231405, 231680, 232127, 232786, 233315, 235048, 236114, 236532, 236755, 237499, 237860, 238802, 242567, 245309, 246077, 247707, 247862, 248174, 248328, 252574, 254782, 254959, 256332, 256953, 258169, 258263, 259144, 260040, 261176, 262256, 262335, 262484, 263588, 263887, 264095, 265147, 267130, 268421, 268969, 268986, 269389, 269820, 269932, 270282, 270715, 270779, 271167, 271578, 273379, 274932, 275882, 276118, 277241, 278377, 282698, 283321, 283777, 285093, 285995, 286107, 286266, 287262, 291896, 292099, 294518, 295195, 295379, 295575, 296064, 296431, 296730, 299146, 300272, 302418, 303217, 304194, 306410, 306837, 307001, 307687, 307996, 308426, 309032, 310091, 310127, 310685, 311013, 312498, 312789, 314041, 314443, 314831, 315034, 315852, 316170, 317291, 318362, 319781, 319975, 320207, 320442, 320833, 321858, 323041, 325753, 326974, 327407, 329673, 329777, 330344, 331863, 332398, 332538, 332942, 333446, 333472, 333537, 333821, 333866, 334848, 338293, 338481, 339483, 339639, 340502, 341357, 341725, 343321, 343508, 344572, 344643, 345769, 345958, 346290, 347532, 348468, 350664, 351168, 351231, 351485, 351854, 354351, 354549, 354870, 356105, 356487, 358930, 359449, 360257, 361048, 362809, 363355, 364086, 366744, 367293, 367791, 368356, 368735, 369680, 369995, 370786, 372102, 372933, 373893, 374939, 377880, 378391, 379803, 380905, 383584, 383847, 385342, 386512, 388553, 390074, 390790, 390792, 391353, 392997, 393032, 393632, 394483, 396624, 397175, 398013, 398576, 399559, 401610, 402163, 405914, 406823, 407090, 409400, 409935, 410718, 411225, 411892, 411954, 412538, 413415, 414037, 414051, 414293, 414550, 414608, 414905, 415547, 417064, 417378, 417962, 418026, 418663, 420478, 421574, 422327, 424049, 424286, 424530, 425027, 425280, 425654, 426107, 426685, 427053, 427304, 427541, 429904, 430844, 431491, 433390, 433741, 433782, 434941, 434949, 436027, 436762, 438994, 440594, 440678, 440758, 442166, 442568, 442756, 443133, 443423, 446319, 447989, 449625, 451193, 452325, 454419, 458042, 459943, 461104, 462866, 463038, 463202, 463430, 464377, 464877, 466237, 468657, 469925, 470715, 471163, 471361, 472017, 472536, 472853, 473621, 473889, 473950, 474202, 474373, 476742, 477619, 478702, 478885, 479291, 481431, 481879, 482263, 483058, 483164, 483178, 483560, 485934, 486463, 486488, 486525, 486559, 486897, 487082, 487160, 487202, 488324, 490005, 491157, 491783, 492724, 492892, 493682, 496395, 497331, 498098, 498336, 498837, 498942, 499637, 500555, 502292, 502630, 502737, 503283, 503603, 503687, 504087, 504217, 505020, 505283, 506093, 506569, 506717, 507028, 507259, 508241, 509861, 511144, 511541, 511955, 512363, 513278, 513570, 513835, 514321, 514600, 514978, 515693, 516339, 516583, 517093, 517348, 517492, 518720, 520258, 520709, 522162, 522273, 522647, 522671, 523995, 524999, 525038, 527317, 528066, 528447, 529939, 531946, 532574, 533448, 538278, 538469, 538626, 540452, 541348, 541958, 545372, 546578, 547171, 548552, 548559, 548680, 548832, 549455, 549669, 552066, 556290, 557641, 557719, 557899, 559868, 561423, 563190, 564442, 569089, 570513, 572781, 575613, 577068, 577474, 581300, 582432, 585013, 587170, 587822, 588545, 588676, 588898, 590873, 591757, 592272, 592607, 593707, 595130, 596765, 597727, 599649, 600942, 601116, 601819, 602602, 603187, 603332, 603845, 604716, 605094, 605187, 606535, 606975, 607063, 608488, 608691, 610501, 610973, 611091, 613375, 613385, 613769, 617118, 617246, 617353, 618101, 619449, 620092, 620132, 620324, 621127, 621201, 622422, 622601, 624274, 624984, 625153, 626490, 626788, 628072, 628642, 628651, 628678, 628807, 628969, 629495, 629599, 633769, 634208, 636573, 636614, 637680, 640619, 643820, 646737, 647891, 648268, 648684, 649206, 649282, 649421, 649892, 651276, 651524, 653838, 654060, 654465, 654608, 654669, 658297, 658731, 661115, 661887, 662268, 662572, 663541, 667541, 669201, 673656, 675435, 676134, 676628, 677972, 678222, 679000, 679805, 681482, 682712, 683298, 684340, 684471, 684579, 685153, 686323, 687148, 687937, 688354, 688504, 688651, 688679, 689801, 692565, 692954, 693810, 695024, 695223, 697200, 697863, 699263, 699591, 701402, 702678, 704279, 704489, 704601, 705075, 705546, 705581, 705613, 705956, 707833, 707864, 708951, 709253, 709474, 709974, 710466, 712279, 713069, 713255, 713419, 714161, 716358, 716961, 717372, 717746, 719639, 720391, 721575, 723128, 725950, 726551, 728305, 728374, 729343, 733168, 734221, 734401, 737569, 738021, 738025, 738431, 742870, 743203, 743574, 747446, 748813, 749428))) AND ("CN_DIM_WALGREEN_1".S_4_KEY = "WALGREEN_CN_S_4_1_O".AVP_KEY)

**Comment by PedroTadim** [comment]
"CN_DIM_WALGREEN_1", "WALGREEN_CN_S_4_1_O"  table description?

**Comment by bharaththam** [comment]
CREATE TABLE "DM_POSTX_WALGREEN_MRT_P1"."CN_DIM_WALGREEN_1" (
        "consumer_dim_key" INTEGER       NOT NULL,
        "s_4_key"          INTEGER       DEFAULT 30000,
        "s_3_key"          INTEGER       DEFAULT 30000,
        "s_7_key"          INTEGER       DEFAULT 30000,
        "s_2_key"          INTEGER       DEFAULT 30000,
        "s_8_key"          INTEGER       DEFAULT 30000,
        "s_1_key"          INTEGER       DEFAULT 30000,
        "s_12_key"         INTEGER       DEFAULT 30000,
        "s_9_key"          INTEGER       DEFAULT 30000,
        "s_13_key"         INTEGER       DEFAULT 30000,
        "s_11_key"         INTEGER       DEFAULT 30000,
        "s_15_key"         INTEGER       DEFAULT 30000,
        "s_5_key"          INTEGER       DEFAULT 30000,
        "s_6_key"          INTEGER       DEFAULT 30000,
        "s_10_key"         INTEGER       DEFAULT 30000,
        "s_14_key"         INTEGER       DEFAULT 30000,
        "s_1194_key"       INTEGER       DEFAULT 30000,
        "s_1195_key"       INTEGER       DEFAULT 30000,
        "s_1196_key"       INTEGER       DEFAULT 30000,
        "s_16_key"         INTEGER       DEFAULT 30000,
        "s_19_key"         INTEGER       DEFAULT 30000,
        "s_17_key"         INTEGER       DEFAULT 30000,
        "s_18_key"         INTEGER       DEFAULT 30000,
        "s_20_key"         INTEGER       DEFAULT 30000,
        "s_33_key"         INTEGER       DEFAULT 30000,
        "s_34_key"         INTEGER       DEFAULT 30000,
        "s_35_key"         INTEGER       DEFAULT 30000,
        "s_36_key"         INTEGER       DEFAULT 30000,
        "s_37_key"         INTEGER       DEFAULT 30000,
        "s_38_key"         INTEGER       DEFAULT 30000,
        "s_39_key"         INTEGER       DEFAULT 30000,
        "s_40_key"         INTEGER       DEFAULT 30000,
        "s_21_key"         INTEGER       DEFAULT 30000,
        "s_44_key"         INTEGER       DEFAULT 30000,
        "s_27_key"         INTEGER       DEFAULT 30000,
        "s_45_key"         INTEGER       DEFAULT 30000,
        "s_28_key"         INTEGER       DEFAULT 30000,
        "s_29_key"         INTEGER       DEFAULT 30000,
        "s_46_key"         INTEGER       DEFAULT 30000,
        "s_30_key"         INTEGER       DEFAULT 30000,
        "s_31_key"         INTEGER       DEFAULT 30000,
        "s_32_key"         INTEGER       DEFAULT 30000,
        "s_41_key"         INTEGER       DEFAULT 30000,
        "s_22_key"         INTEGER       DEFAULT 30000,
        "s_23_key"         INTEGER       DEFAULT 30000,
        "s_24_key"         INTEGER       DEFAULT 30000,
        "s_42_key"         INTEGER       DEFAULT 30000,
        "s_25_key"         INTEGER       DEFAULT 30000,
        "s_26_key"         INTEGER       DEFAULT 30000,
        "s_43_key"         INTEGER       DEFAULT 30000,
        "s_121_key"        INTEGER       DEFAULT 30000,
        "s_143_key"        INTEGER       DEFAULT 30000,
        "s_114_key"        INTEGER       DEFAULT 30000,
        "s_95_key"         INTEGER       DEFAULT 30000,
        "s_100_key"        INTEGER       DEFAULT 30000,
        "s_126_key"        INTEGER       DEFAULT 30000,
        "s_105_key"        INTEGER       DEFAULT 30000,
        "s_108_key"        INTEGER       DEFAULT 30000,
        "s_131_key"        INTEGER       DEFAULT 30000,
        "s_135_key"        INTEGER       DEFAULT 30000,
        "s_137_key"        INTEGER       DEFAULT 30000,
        "s_112_key"        INTEGER       DEFAULT 30000,
        "s_102_key"        INTEGER       DEFAULT 30000,
        "s_127_key"        INTEGER       DEFAULT 30000,
        "s_107_key"        INTEGER       DEFAULT 30000,
        "s_130_key"        INTEGER       DEFAULT 30000,
        "s_134_key"        INTEGER       DEFAULT 30000,
        "s_111_key"        INTEGER       DEFAULT 30000,
        "s_140_key"        INTEGER       DEFAULT 30000,
        "s_113_key"        INTEGER       DEFAULT 30000,
        "s_101_key"        INTEGER       DEFAULT 30000,
        "s_104_key"        INTEGER       DEFAULT 30000,
        "s_128_key"        INTEGER       DEFAULT 30000,
        "s_109_key"        INTEGER       DEFAULT 30000,
        "s_133_key"        INTEGER       DEFAULT 30000,
        "s_110_key"        INTEGER       DEFAULT 30000,
        "s_139_key"        INTEGER       DEFAULT 30000,
        "s_142_key"        INTEGER       DEFAULT 30000,
        "s_124_key"        INTEGER       DEFAULT 30000,
        "s_103_key"        INTEGER       DEFAULT 30000,
        "s_106_key"        INTEGER       DEFAULT 30000,
        "s_129_key"        INTEGER       DEFAULT 30000,
        "s_132_key"        INTEGER       DEFAULT 30000,
        "s_136_key"        INTEGER       DEFAULT 30000,
        "s_138_key"        INTEGER       DEFAULT 30000,
        "s_141_key"        INTEGER       DEFAULT 30000,
        "s_96_key"         INTEGER       DEFAULT 30000,
        "s_119_key"        INTEGER       DEFAULT 30000,
        "s_97_key"         INTEGER       DEFAULT 30000,
        "s_120_key"        INTEGER       DEFAULT 30000,
        "s_122_key"        INTEGER       DEFAULT 30000,
        "s_98_key"         INTEGER       DEFAULT 30000,
        "s_125_key"        INTEGER       DEFAULT 30000,
        "s_123_key"        INTEGER       DEFAULT 30000,
        "s_115_key"        INTEGER       DEFAULT 30000,
        "s_117_key"        INTEGER       DEFAULT 30000,
        "s_118_key"        INTEGER       DEFAULT 30000,
        "s_92_key"         INTEGER       DEFAULT 30000,
        "s_93_key"         INTEGER       DEFAULT 30000,
        "s_116_key"        INTEGER       DEFAULT 30000,
        "s_94_key"         INTEGER       DEFAULT 30000,
        "s_99_key"         INTEGER       DEFAULT 30000,
        "s_152_key"        INTEGER       DEFAULT 30000,
        "s_155_key"        INTEGER       DEFAULT 30000,
        "s_153_key"        INTEGER       DEFAULT 30000,
        "s_154_key"        INTEGER       DEFAULT 30000,
        "s_156_key"        INTEGER       DEFAULT 30000,
        "s_977_key"        INTEGER       DEFAULT 30000,
        "s_978_key"        INTEGER       DEFAULT 30000,
        "s_979_key"        INTEGER       DEFAULT 30000,
        "s_980_key"        INTEGER       DEFAULT 30000,
        "s_981_key"        INTEGER       DEFAULT 30000,
        "s_982_key"        INTEGER       DEFAULT 30000,
        "s_983_key"        INTEGER       DEFAULT 30000,
        "s_984_key"        INTEGER       DEFAULT 30000,
        "s_985_key"        INTEGER       DEFAULT 30000,
        "s_986_key"        INTEGER       DEFAULT 30000,
        "s_987_key"        INTEGER       DEFAULT 30000,
        "s_988_key"        INTEGER       DEFAULT 30000,
        "s_989_key"        INTEGER       DEFAULT 30000,
        "s_990_key"        INTEGER       DEFAULT 30000,
        "s_991_key"        INTEGER       DEFAULT 30000,
        "s_992_key"        INTEGER       DEFAULT 30000,
        "s_993_key"        INTEGER       DEFAULT 30000,
        "s_994_key"        INTEGER       DEFAULT 30000,
        "s_995_key"        INTEGER       DEFAULT 30000,
        "s_996_key"        INTEGER       DEFAULT 30000,
        "s_997_key"        INTEGER       DEFAULT 30000,
        "s_998_key"        INTEGER       DEFAULT 30000,
        "s_999_key"        INTEGER       DEFAULT 30000,
        "s_1000_key"       INTEGER       DEFAULT 30000,
        "s_1001_key"       INTEGER       DEFAULT 30000,
        "s_1002_key"       INTEGER       DEFAULT 30000,
        "s_1003_key"       INTEGER       DEFAULT 30000,
        "s_1004_key"       INTEGER       DEFAULT 30000,
        "s_1005_key"       INTEGER       DEFAULT 30000,
        "s_1006_key"       INTEGER       DEFAULT 30000,
        "s_1007_key"       INTEGER       DEFAULT 30000,
        "s_1008_key"       INTEGER       DEFAULT 30000,
        "s_1009_key"       INTEGER       DEFAULT 30000,
        "s_1010_key"       INTEGER       DEFAULT 30000,
        "s_1011_key"       INTEGER       DEFAULT 30000,
        "s_1012_key"       INTEGER       DEFAULT 30000,
        "s_1013_key"       INTEGER       DEFAULT 30000,
        "s_1014_key"       INTEGER       DEFAULT 30000,
        "s_1015_key"       INTEGER       DEFAULT 30000,
        "s_1016_key"       INTEGER       DEFAULT 30000,
        "s_1017_key"       INTEGER       DEFAULT 30000,
        "s_1018_key"       INTEGER       DEFAULT 30000,
        "s_1019_key"       INTEGER       DEFAULT 30000,
        "s_1020_key"       INTEGER       DEFAULT 30000,
        "s_1021_key"       INTEGER       DEFAULT 30000,
        "s_1022_key"       INTEGER       DEFAULT 30000,
        "s_1023_key"       INTEGER       DEFAULT 30000,
        "s_1024_key"       INTEGER       DEFAULT 30000,
        "s_1025_key"       INTEGER       DEFAULT 30000,
        "s_1026_key"       INTEGER       DEFAULT 30000,
        "s_1027_key"       INTEGER       DEFAULT 30000,
        "s_1028_key"       INTEGER       DEFAULT 30000,
        "s_1029_key"       INTEGER       DEFAULT 30000,
        "s_1030_key"       INTEGER       DEFAULT 30000,
        "s_1031_key"       INTEGER       DEFAULT 30000,
        "s_1032_key"       INTEGER       DEFAULT 30000,
        "s_1033_key"       INTEGER       DEFAULT 30000,
        "s_1034_key"       INTEGER       DEFAULT 30000,
        "s_1035_key"       INTEGER       DEFAULT 30000,
        "s_1036_key"       INTEGER       DEFAULT 30000,
        "s_1037_key"       INTEGER       DEFAULT 30000,
        "s_1038_key"       INTEGER       DEFAULT 30000,
        "s_1039_key"       INTEGER       DEFAULT 30000,
        "s_1040_key"       INTEGER       DEFAULT 30000,
        "s_1041_key"       INTEGER       DEFAULT 30000,
        "s_1042_key"       INTEGER       DEFAULT 30000,
        "s_1043_key"       INTEGER       DEFAULT 30000,
        "s_1044_key"       INTEGER       DEFAULT 30000,
        "s_1045_key"       INTEGER       DEFAULT 30000,
        "s_1046_key"       INTEGER       DEFAULT 30000,
        "s_1047_key"       INTEGER       DEFAULT 30000,
        "s_1048_key"       INTEGER       DEFAULT 30000,
        "s_1049_key"       INTEGER       DEFAULT 30000,
        "s_1050_key"       INTEGER       DEFAULT 30000,
        "s_1051_key"       INTEGER       DEFAULT 30000,
        "s_1052_key"       INTEGER       DEFAULT 30000,
        "s_1053_key"       INTEGER       DEFAULT 30000,
        "s_1054_key"       INTEGER       DEFAULT 30000,
        "s_1055_key"       INTEGER       DEFAULT 30000,
        "s_1056_key"       INTEGER       DEFAULT 30000,
        "s_1057_key"       INTEGER       DEFAULT 30000,
        "s_1058_key"       INTEGER       DEFAULT 30000,
        "s_1059_key"       INTEGER       DEFAULT 30000,
        "s_1060_key"       INTEGER       DEFAULT 30000,
        "s_1061_key"       INTEGER       DEFAULT 30000,
        "s_1062_key"       INTEGER       DEFAULT 30000,
        "s_1063_key"       INTEGER       DEFAULT 30000,
        "s_1064_key"       INTEGER       DEFAULT 30000,
        "s_1065_key"       INTEGER       DEFAULT 30000,
        "s_1066_key"       INTEGER       DEFAULT 30000,
        "s_1067_key"       INTEGER       DEFAULT 30000,
        "s_1068_key"       INTEGER       DEFAULT 30000,
        "s_1069_key"       INTEGER       DEFAULT 30000,
        "s_1070_key"       INTEGER       DEFAULT 30000,
        "s_1071_key"       INTEGER       DEFAULT 30000,
        "s_1072_key"       INTEGER       DEFAULT 30000,
        "s_1073_key"       INTEGER       DEFAULT 30000,
        "s_1074_key"       INTEGER       DEFAULT 30000,
        "s_1075_key"       INTEGER       DEFAULT 30000,
        "s_1076_key"       INTEGER       DEFAULT 30000,
        "s_1077_key"       INTEGER       DEFAULT 30000,
        "s_1078_key"       INTEGER       DEFAULT 30000,
        "s_1079_key"       INTEGER       DEFAULT 30000,
        "s_1080_key"       INTEGER       DEFAULT 30000,
        "s_1081_key"       INTEGER       DEFAULT 30000,
        "s_1082_key"       INTEGER       DEFAULT 30000,
        "s_1083_key"       INTEGER       DEFAULT 30000,
        "s_1084_key"       INTEGER       DEFAULT 30000,
        "s_1085_key"       INTEGER       DEFAULT 30000,
        "s_1086_key"       INTEGER       DEFAULT 30000,
        "s_1087_key"       INTEGER       DEFAULT 30000,
        "s_1088_key"       INTEGER       DEFAULT 30000,
        "s_1089_key"       INTEGER       DEFAULT 30000,
        "s_1090_key"       INTEGER       DEFAULT 30000,
        "s_1091_key"       INTEGER       DEFAULT 30000,
        "s_1092_key"       INTEGER       DEFAULT 30000,
        "s_1093_key"       INTEGER       DEFAULT 30000,
        "s_1094_key"       INTEGER       DEFAULT 30000,
        "s_1095_key"       INTEGER       DEFAULT 30000,
        "s_1096_key"       INTEGER       DEFAULT 30000,
        "s_1097_key"       INTEGER       DEFAULT 30000,
        "s_1098_key"       INTEGER       DEFAULT 30000,
        "s_1099_key"       INTEGER       DEFAULT 30000,
        "s_1100_key"       INTEGER       DEFAULT 30000,
        "s_1101_key"       INTEGER       DEFAULT 30000,
        "s_1102_key"       INTEGER       DEFAULT 30000,
        "s_1103_key"       INTEGER       DEFAULT 30000,
        "s_1104_key"       INTEGER       DEFAULT 30000,
        "s_1105_key"       INTEGER       DEFAULT 30000,
        "s_1106_key"       INTEGER       DEFAULT 30000,
        "s_1107_key"       INTEGER       DEFAULT 30000,
        "s_1108_key"       INTEGER       DEFAULT 30000,
        "s_1109_key"       INTEGER       DEFAULT 30000,
        "s_1110_key"       INTEGER       DEFAULT 30000,
        "s_1111_key"       INTEGER       DEFAULT 30000,
        "s_1112_key"       INTEGER       DEFAULT 30000,
        "s_1113_key"       INTEGER       DEFAULT 30000,
        "s_1114_key"       INTEGER       DEFAULT 30000,
        "s_1115_key"       INTEGER       DEFAULT 30000,
        "s_1116_key"       INTEGER       DEFAULT 30000,
        "s_1117_key"       INTEGER       DEFAULT 30000,
        "s_1118_key"       INTEGER       DEFAULT 30000,
        "s_1119_key"       INTEGER       DEFAULT 30000,
        "s_1120_key"       INTEGER       DEFAULT 30000,
        "s_1121_key"       INTEGER       DEFAULT 30000,
        "s_1122_key"       INTEGER       DEFAULT 30000,
        "s_1123_key"       INTEGER       DEFAULT 30000,
        "s_1124_key"       INTEGER       DEFAULT 30000,
        "s_1125_key"       INTEGER       DEFAULT 30000,
        "s_1126_key"       INTEGER       DEFAULT 30000,
        "s_1127_key"       INTEGER       DEFAULT 30000,
        "s_1128_key"       INTEGER       DEFAULT 30000,
        "s_1129_key"       INTEGER       DEFAULT 30000,
        "s_1130_key"       INTEGER       DEFAULT 30000,
        "s_1131_key"       INTEGER       DEFAULT 30000,
        "s_1132_key"       INTEGER       DEFAULT 30000,
        "s_1133_key"       INTEGER       DEFAULT 30000,
        "s_1134_key"       INTEGER       DEFAULT 30000,
        "s_1135_key"       INTEGER       DEFAULT 30000,
        "s_1136_key"       INTEGER       DEFAULT 30000,
        "s_1137_key"       INTEGER       DEFAULT 30000,
        "s_1138_key"       INTEGER       DEFAULT 30000,
        "s_1139_key"       INTEGER       DEFAULT 30000,
        "s_1140_key"       INTEGER       DEFAULT 30000,
        "s_1141_key"       INTEGER       DEFAULT 30000,
        "s_1142_key"       INTEGER       DEFAULT 30000,
        "s_1143_key"       INTEGER       DEFAULT 30000,
        "s_1144_key"       INTEGER       DEFAULT 30000,
        "s_1145_key"       INTEGER       DEFAULT 30000,
        "s_1146_key"       INTEGER       DEFAULT 30000,
        "s_1147_key"       INTEGER       DEFAULT 30000,
        "s_1148_key"       INTEGER       DEFAULT 30000,
        "s_1149_key"       INTEGER       DEFAULT 30000,
        "s_1150_key"       INTEGER       DEFAULT 30000,
        "s_1151_key"       INTEGER       DEFAULT 30000,
        "s_1152_key"       INTEGER       DEFAULT 30000,
        "s_1153_key"       INTEGER       DEFAULT 30000,
        "s_1154_key"       INTEGER       DEFAULT 30000,
        "s_1155_key"       INTEGER       DEFAULT 30000,
        "s_1156_key"       INTEGER       DEFAULT 30000,
        "s_1157_key"       INTEGER       DEFAULT 30000,
        "s_1158_key"       INTEGER       DEFAULT 30000,
        "s_1159_key"       INTEGER       DEFAULT 30000,
        "s_1160_key"       INTEGER       DEFAULT 30000,
        "s_1161_key"       INTEGER       DEFAULT 30000,
        "s_1162_key"       INTEGER       DEFAULT 30000,
        "s_1163_key"       INTEGER       DEFAULT 30000,
        "s_1164_key"       INTEGER       DEFAULT 30000,
        "s_1165_key"       INTEGER       DEFAULT 30000,
        "s_1166_key"       INTEGER       DEFAULT 30000,
        "s_1167_key"       INTEGER       DEFAULT 30000,
        "s_1168_key"       INTEGER       DEFAULT 30000,
        "s_1169_key"       INTEGER       DEFAULT 30000,
        "s_1170_key"       INTEGER       DEFAULT 30000,
        "s_1171_key"       INTEGER       DEFAULT 30000,
        "s_1172_key"       INTEGER       DEFAULT 30000,
        "s_1173_key"       INTEGER       DEFAULT 30000,
        "s_1174_key"       INTEGER       DEFAULT 30000,
        "s_1175_key"       INTEGER       DEFAULT 30000,
        "s_1176_key"       INTEGER       DEFAULT 30000,
        "s_1177_key"       INTEGER       DEFAULT 30000,
        "s_1178_key"       INTEGER       DEFAULT 30000,
        "s_1179_key"       INTEGER       DEFAULT 30000,
        "s_1180_key"       INTEGER       DEFAULT 30000,
        "s_1181_key"       INTEGER       DEFAULT 30000,
        "s_1182_key"       INTEGER       DEFAULT 30000,
        "s_1183_key"       INTEGER       DEFAULT 30000,
        "s_1184_key"       INTEGER       DEFAULT 30000,
        "s_1185_key"       INTEGER       DEFAULT 30000,
        "s_1186_key"       INTEGER       DEFAULT 30000,
        "s_1187_key"       INTEGER       DEFAULT 30000,
        "s_1188_key"       INTEGER       DEFAULT 30000,
        "s_1189_key"       INTEGER       DEFAULT 30000,
        "s_1190_key"       INTEGER       DEFAULT 30000,
        "s_1191_key"       INTEGER       DEFAULT 30000,
        "s_1192_key"       INTEGER       DEFAULT 30000,
        "s_1193_key"       INTEGER       DEFAULT 30000,
        "s_1197_key"       INTEGER       DEFAULT 30000,
        CONSTRAINT "CN_DIM_WALGREEN_1_consumer_dim_key_pkey" PRIMARY KEY ("consumer_dim_key")
);

**Comment by PedroTadim** [comment]
The plan looks fine. I would like to ask if you can send the query trace, so we can find the culprit. I see the IN list values being appended one by one, and we could improve this in a future release. At the moment, you could try the workaround of storing the values in a temporary table.

**Comment by bharaththam** [comment]
Could you please provide the steps to enable the Trace in MONET db

**Comment by bharaththam** [comment]
i have used sthescope to enable the query trace , so you please provide us steps as i have tried with but the connection is getting closed

**Comment by PedroTadim** [comment]
You can try TRACE SELECT DISTINCT "CN_DIM_WALGREEN_1".CONSUMER_DIM_KEY ...

**Comment by njnes** [comment]
did we test on the Jul2021 release?

**Comment by PedroTadim** [comment]
Yes, I tested the query on Jul2021, but I didn't find exactly where the performance issue is. My wild guess are the BUNappend calls done at CMDBATappend_bulk.

**Comment by njnes** [comment]
trace output would help a lot, because with empty (or close too it) we don't see any issues.

**Comment by PedroTadim** [comment]
Any update on this?

**Comment by njnes** [comment]
could you verify this on the current jan2022
