### ISSUE TITLE
Remote table not accessible and throws - only the 'monetdb' user can use non-sql languages. run mserver5 with --set mal_for_all=yes to change this.

### ISSUE THREAD

**Issue by sreejithssharma** [MonetDB/MonetDB#7174]
**Describe the bug**
When we try to access the remote table created with below statement, we end up getting an error which says - only the 'monetdb' user can use non-sql languages. run mserver5 with --set mal_for_all=yes to change this.

CREATE REMOTE TABLE "ABC" ("id" integer,"desc" varchar(100)) ON 'mapi:monetdb://xx.xx.xx.xxx:50670/DBNAME' WITH USER 'USERNAME' PASSWORD 'Password';

It works though when the server is started by hand using mserver5 and passes "--set mal_for_all=yes", but how can we enable this property by default using monetdbd start method? Can we start this using nohup in Linux platform?

**To Reproduce**
Create a remote table in secondary DB using and try to access it. For example select count(*) from "ABC";

CREATE REMOTE TABLE "ABC" ("id" integer,"desc" varchar(100)) ON 'mapi:monetdb://xx.xx.xx.xxx:50670/DBNAME' WITH USER 'USERNAME' PASSWORD 'Password';

**Expected behavior**
The above query should result in row count of table without an error.

**Screenshots**

**Software versions**
 -  MonetDB v11.41.5 (Jul2021)
 - CentOS Linux 7 (Core)
 - Installed

**Issue labeling **
Remote table feature

**Additional context**

**Comment by PedroTadim** [comment]
I see the session is started using the 'msql' scenario, which is not strictly the 'sql' scenario. However I would say any SQL user using that scenario would have the same rights. Tomorrow I will inspect further.

**Comment by kutsurak** [comment]
You can set a property `mal_for_all` on your database using `monetdb`:

```
monetdb stop DBNAME
monetdb lock DBNAME
monetdb set mal_for_all=yes DBNAME
monetdb release DBNAME
monetdb start DBNAME
```

Now you should be able to create and access a remote table from another database on DBNAME.

**Comment by sreejithssharma** [comment]
> You can set a property `mal_for_all` on your database using `monetdb`:
> 
> ```
> monetdb stop DBNAME
> monetdb lock DBNAME
> monetdb set mal_for_all=yes DBNAME
> monetdb release DBNAME
> monetdb start DBNAME
> ```
> 
> Now you should be able to create and access a remote table from another database on DBNAME.

thank you! that's of great help.

**Comment by sreejithssharma** [comment]
One more question - does it work only if it has the same schema name for both databases?

**Comment by sreejithssharma** [comment]
thanks for all your help. It worked hence closing this.
