### ISSUE TITLE
MonetDB sorted columns not working anymore?

### ISSUE THREAD

**Issue by morgana2313** [MonetDB/MonetDB#7176]
**Describe the bug**

After inserting a second item in a table the automagical storage.sorted detection is lost.

According [Hannes Mühleisen](https://stackoverflow.com/a/29168239/16876775)

> MonetDB will detect it automagically if a column is sorted on load.

This used to work in v11.33.11 (Apr2019-SP1), but not anymore in v11.41.5 (Jul2021).
This automagical detection appears to be undocumented on monetdb.org.

**To Reproduce**

```
DROP TABLE IF EXISTS test;
  CREATE TABLE test (
     number integer NOT null
  );

  select "column","sorted" from storage() where "table"='test' and column='number';
  INSERT INTO test VALUES (1);
  select "column","sorted" from storage() where "table"='test' and column='number';
  INSERT INTO test VALUES (2);
  select "column","sorted" from storage() where "table"='test' and column='number';
  INSERT INTO test VALUES (3);
  select "column","sorted" from storage() where "table"='test' and column='number';
  INSERT INTO test VALUES (2);

  SELECT * FROM test;
```

**Expected behavior**
The automagical storage.sorted detection should work

**Software versions**
 - MonetDB version v11.41.5 (Jul2021).
 - Ubuntu 18.04.4]
- Installed from https://dev.monetdb.org/downloads/deb/ bionic

**Issue labeling **
automagical storage.sorted detection

**Comment by sjoerdmullender** [comment]
Automatic detection does happen, but only when it's deemed necessary for the algorithm being used.
Keeping the sortedness information up-to-date comes at a cost, so it isn't done in all cases where it's possible, and it's certainly not done when it's expensive to do.

**Comment by morgana2313** [comment]
We have a several tables with > 2G records each and some columns with `SMALLINT` columns that are queried like this:

 `SELECT SUM(col15), SUM(col16), SUM(col17) FROM table WHERE col1=1 and col2=16 and col3=21`
 
I assumed keeping col1, col2 and col3  sorted would speed things up, but I may may be mistaken.
