### ISSUE TITLE
Remote Table Throws Error - createExceptionInternal: !ERROR: SQLException:RAstatement2:42000!The number of projections don't match between the generated plan and the expected one: 1 != 1200

### ISSUE THREAD

**Issue by sreejithssharma** [MonetDB/MonetDB#7178]
**Describe the bug**
If we create a remote table with 500+ or 1000+ columns and when try to select * from "ABC" throws an error as given below.

#client80: createExceptionInternal: !ERROR: SQLException:RAstatement2:42000!The number of projections don't match between the generated plan and the expected one: 1 != 1000

Is there any limitation in no of columns defined for a remote table?

**To Reproduce**
create a 1000 column table in primary DB, and create a remote table on secondary DB and when try to do a select * from "ABC" limit 5 it throws this error. Even if the table has or doesn't have data.

**Expected behavior**
It should return data or 0 data if no data are available.

**Screenshots**

**Software versions**
 - MonetDB v11.41.5 (Jul2021)
 - Cent OS 7 Core
 - Installed from package

**Issue labeling **
Remote Table with large columns

**Additional context**

**Comment by PedroTadim** [comment]
There was an issue with buffer reallocation on remote plans. I already fixed on the top of the source tree and it will be available on the next release.

**Comment by sreejithssharma** [comment]
> There was an issue with buffer reallocation on remote plans. I already fixed on the top of the source tree and it will be available on the next release.
 Thanks for the fix. Is this occur specific to any number of columns or this can occur randomly for any columns within select clause of the remote table?

**Comment by PedroTadim** [comment]
> > There was an issue with buffer reallocation on remote plans. I already fixed on the top of the source tree and it will be available on the next release.
> > Thanks for the fix. Is this occur specific to any number of columns or this can occur randomly for any columns within select clause of the remote table?

The issue was on the buffer reallocation when the number of projections was large enough. The crash will be random because it depends on the type of the projections.
