### ISSUE TITLE
v11.37.11 and v11.41.5 are the same SQL execution but the results are different.

### ISSUE THREAD

**Issue by PeterYangZhi** [MonetDB/MonetDB#7179]
I am inserting a batch of data by copy binary, data structure (timestamp).
This is my original data
![OriginalData](https://user-images.githubusercontent.com/53032192/134303547-1b08773c-5609-4bb0-adfb-a90929a111bc.png)
I use c#'s binarywriter to create binary files, this is my conversion program,
`public class DateTimeWriter : IColumnWriter
	{
		private const long _dt_to1970 = 352653098885316608;
		private const long _dt_secondModifier = 1000000L;
		private const long _dt_minuteModifier = 60000000L;
		private const long _dt_hourModifier = 3600000000L;
		private const long _dt_dayModifier = 137438953472L;       //38 hours 11 minutes and ...
		private const long _dt_monthModifier = 4398046511104L;    //32L * dayModifier
		private const long _dt_yearModifier = 52776558133248L;    //12L * monthModifier

		public void Write(BinaryWriter binaryWriter, object value)
		{
				binaryWriter.Write(ConvertDateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, dt.Ticks));
		}

		private static long ConvertDateTime(int year, int month, int day, int hour, int minute, int second, long ticks)
		{
			return _dt_to1970
			+ _dt_yearModifier * (year - 1970)
			+ _dt_monthModifier * (month - 1)
			+ _dt_dayModifier * (day - 1)
			+ _dt_hourModifier * hour
			+ _dt_minuteModifier * minute
			+ _dt_secondModifier * second
			+ ticks % 10000000L / 10;
		}
	}`
This is the converted binary file.
[BinaryData.zip](https://github.com/MonetDB/MonetDB/files/7208792/BinaryData.zip)

I use sql statement like this
`copy binary into table1."7ba603337693449fb73883a19c087016" from ('C:\\BinaryData\\3df5dd91-1df3-4c6c-a372-b7fe2e57a041__rowid.bin', 'C:\\BinaryData\\3df5dd91-1df3-4c6c-a372-b7fe2e57a041_0.bin') no constraint;`

There is no problem executing on v11.37.11 version.
![success](https://user-images.githubusercontent.com/53032192/134313783-5b536073-78b2-4658-9f1e-78a041f05de2.png)
But when I execute it in v11.41.5, I get the following error:
#2021-09-22 15:55:39: DFLOWworker10: createExceptionInternal: !ERROR: MALException:sql.importColumn:42000!inconsistent row count in C:\BinaryData\3df5dd91-1df3-4c6c-a372-b7fe2e57a041_0.bin: expected 4, got 2

Is there any change in the new version?

**Comment by PedroTadim** [comment]
There was a major rewrite on the copy binary into for the Jul2021 release. We have to investigate if this is a real issue or not.

**Comment by PeterYangZhi** [comment]
> There was a major rewrite on the copy binary into for the Jul2021 release. We have to investigate if this is a real issue or not.

Thank you for your investigation, and I look forward to your reply again.

**Comment by PedroTadim** [comment]
After some digging, I found out the inputs for time related types changed for the binary copy into command at the Jul2021 release. You can find the expected inputs for each time type here: https://github.com/MonetDB/MonetDB/blob/47eea1cc9b96894f01d3dd3f846034957202b462/common/utils/copybinary.h

The copy_binary_timestamp struct is the expected input for the timestamp type. For more details about changes from this command, please read the release notes:
https://monetdb.org/Downloads/ReleaseNotes

**Comment by PedroTadim** [comment]
I am going to close this because this is a feature change rather than a bug. Please re-open it if you find any other issue.

**Comment by peterZhiFate** [comment]
> I am going to close this because this is a feature change rather than a bug. Please re-open it if you find any other issue.

Thanks.
