### ISSUE TITLE
monetdb: unable to start

### ISSUE THREAD

**Issue by krimp** [MonetDB/MonetDB#7181]
**Describe the bug**
Our monetdb has been running for a very long time without issues, but suddenly we were not able to connect or log into the database.  The logfile says:

```
merovingian.log:
2021-10-04 12:44:54 MSG merovingian[6487]: Merovingian 11.41.5 (Jul2021) starting
2021-10-04 12:44:54 MSG merovingian[6487]: monitoring dbfarm /datadrive/monetdbfarm
2021-10-04 12:44:54 MSG merovingian[6487]: accepting connections on TCP socket :50000
2021-10-04 12:44:54 MSG merovingian[6487]: accepting connections on UNIX domain socket /tmp/.s.monetdb.50000
2021-10-04 12:44:54 MSG discovery[6487]: listening for UDP messages on :50000
2021-10-04 12:44:54 MSG control[6487]: accepting connections on UNIX domain socket /tmp/.s.merovingian.50000
2021-10-04 12:44:54 MSG discovery[6487]: new neighbour myDBmachine (myDBmachine.com)
2021-10-04 12:44:56 MSG discovery[6487]: new database mapi:monetdb://myDBmachine:50000/devdb (ttl=660s)
2021-10-04 12:44:57 MSG merovingian[6487]: database 'devdb' has crashed after start on 2021-10-04 12:35:02, attempting restart, up min/avg/max: 29m/1w/12w, crash average: 1.00 0.80 0.93 (78-15=63)

2021-10-04 12:44:58 MSG devdb[6497]: arguments: /usr/bin/mserver5 --dbpath=/datadrive/monetdbfarm/devdb --set merovingian_uri=mapi:monetdb://myDBmachine:50000/devdb --set mapi_listenaddr=none --set mapi_usock=/datadrive/monetdbfarm/devdb/.mapi.sock --set monet_vault_key=/datadrive/monetdbfarm/devdb/.vaultkey --set gdk_nr_threads=8 --set max_clients=64 --set sql_optimizer=default_pipe

``` 

After running 

` sudo monetdbd start /datadrive/monetdbfarm
`

mserver5 takes 100% cpu:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
6497 root      20   0 1839468 1.405g  47876 R 100.0  4.5  14:11.85 mserver5

```
Trying to log into the console using :

`sudo mclient -t performance -u aUsername-d devdb
`

results in a wait forever. No errormessages....

The same also for

`sudo monetdb start devdb
`
i.e. wait forever/ does not return to prompt.

**To Reproduce**
Unable to provide information here.

**Expected behavior**
We expected to be able to login.

**Screenshots**
-None

**Software versions**
Monetdb Jul2021: 11.41.5
Linux: ubuntu 18.04.6 , bionic, x86 64-bit

**Issue labeling **
-None

**Additional context**
The database was originally created using Oct2020 branch, and the issues happened also with the latest Oct2020. We did  a sudo apt upgrade and a reboot of the linux machine.  The monetdb was upgraded by the apt upgrade, and is hence now Jul2021. 

We have several apps using a lot of login/logout, and we wander if there are some login constraints reached or some login recourses that are locked?  A reboot of the linux machine does not solve the issue...

Any hints to what to look for, are very much appreciated.

**Comment by PedroTadim** [comment]
We did some fixes related to this after the Jul2021 release. Can you try using the tip of the source tree?

**Comment by krimp** [comment]
Thank you for your response, but I'm sorry, I do not understand what you mean...

**Comment by PedroTadim** [comment]
Compile and install the latest sources on the Jul2021 branch, otherwise you can wait for the Jul2021-SP1 which is coming soon.

**Comment by krimp** [comment]
Thanks. Will do.

**Comment by krimp** [comment]
We compiled and installed the tip of the source tree. Unfortunately it was not a success. The start of the database was still stuck in an infinite/endless loop. mserver5 took 100% cpu and no response or error messages. Also a monetdbd stop of the dbfarm leaved mserver5 running. 

Since Jul2021-SP1 was released today, we removed the tip installation and installed Jul2021-SP1. However, we were not able to start the database, since the tip installation converted our database to a newer version than the Jul2021-SP1.

Our database was/is kind of big, ~250GB on 32GB ram and 8 cores. We know for sure that our issues happened during a burst of (a faulty) insert of many identical records. I do not know if that can cause the issues we have experienced. The database status health reported 19% (which we think is not good) prior to our issues.

We judge our database as corrupt, and have initialized a new one.

**PS!** 
The tip branch has/had a bug in converting utc timestamp in ms to date, e.g CAST(sys.epoch(timestamp_ms) as DATE) gave wrong result and was very slow. Had to use CAST(sys.epoch(timestamp_ms/1000) as DATE) to get correct (and fast) conversions.

**Comment by yzchang** [comment]
Jul2021-SP1 contains important fixes, including some for db startup problems.  But without deeper investigation, there's not much we can say about your original problem.  Fortunately, you were able to start with a fresh DB, that's even safer than a patched old db.

I'm closing this issue.  Would you please file a new issue for the timestamp conversion problem?  Thanks a lot!

**Comment by PedroTadim** [comment]
Regarding the conversion issue, are you sure you tested on the Jul2021 branch or default/master branch? That's because the "epoch" function has changed on default/master for the next feature release:
https://github.com/MonetDB/MonetDB/blob/master/sql/ChangeLog#L23

**Comment by krimp** [comment]
Yes, I'm sure. The Jul2021-SP1 (installed by apt update)  accept ms as an input. The tip did not (i.e behaved as pr the change log#23).  I really hope you are not going to change this behavior. We are using ms in so many applications and have GBs with data timestamped in ms. This will be a catastrophe for us.

**Comment by yzchang** [comment]
We're digressing from the original topic, but FWIW  :)

Cleaning up the `sys.epoch` functions is one of our long-term wishes, i.e. remove the confusion between seconds and milliseconds.  Below are the `sys.epoch` functions, current vs new:
```
-- Until Jul2021:
sys.epoch(int seconds) → timestamptz
sys.epoch(bigint milliseconds) → timestamptz
sys.epoch(timestamp) → int seconds

-- After Jul2021:
sys.epoch(int seconds) → timestamp
sys.epoch(decimal(18,3) sec.millisec) → timestamp
sys.epoch(timestamp) → decimal(18,3) sec.millisec
```

Millisecond is still supported but will become a decimal.  These changes do not change the data in the database, but during the upgrade, the definition of the `sys.epoch` functions in the SQL catalogue will be automatically updated.  Applications using these functions might need to be updated to correctly interpret the values.

Currently, our tentative plan is to do a new feature release in Dec. 2021.  Hope this gives you sufficient time to adjust the application code.

PS> if you want to continue discussing sys.epoch, please open a new issue.
