### ISSUE TITLE
data files created with COPY SELECT .. INTO 'file.csv' fail to be loaded using COPY INTO .. FROM 'file.csv' when double quoted string data contains the field values delimiter character

### ISSUE THREAD

**Issue by mvdvm** [MonetDB/MonetDB#7186]
**Describe the bug**
I expect that data  exports created using  COPY SELECT .. INTO 'file.csv' ...
would be usable to restore/copy the data again using COPY 'file.csv' INTO .. 
However for certain data (in this case all data from sys.tables) this fails when the delimiter is a pipe character '|' or a comma character ','.
When I look at the generated data files they seem to be correct.
However the import does not handle the string data inside double quoted delimiters "" correctly, as it fails on the || characters (in the .psv file) or comma character (in the .csv file).

**To Reproduce**
Start mserver5

-# builtin opt 	gdk_dbpath = /home/dinther/dev/INSTALL/var/monetdb5/dbfarm/demo
-# builtin opt 	mapi_port = 50000
-# builtin opt 	sql_optimizer = default_pipe
-# builtin opt 	sql_debug = 0
-# builtin opt 	raw_strings = false
-# cmdline opt 	embedded_r = true
-# cmdline opt 	embedded_py = 3
-# cmdline opt 	embedded_c = true
-# cmdline opt 	mapi_port = 41000
-# MonetDB 5 server v11.42.0 (hg id: 38bf565fc89a)
-# This is an unreleased version
-# Serving database 'demo', using 8 threads
-# Compiled for x86_64-pc-linux-gnu/64bit with 128bit integers
-# Found 31.233 GiB available main-memory of which we use 25.455 GiB
-# Copyright (c) 1993 - July 2008 CWI.
-# Copyright (c) August 2008 - 2021 MonetDB B.V., all rights reserved
-# Visit https://www.monetdb.org/ for further information
-# Listening for connection requests on mapi:monetdb://localhost:41000/
-# MonetDB/GIS module loaded
-# MonetDB/R   module loaded
-# MonetDB/Python3 module loaded
-# MonetDB/SQL module loaded

Start mclient

Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)
Database: MonetDB v11.42.0 (hg id: 38bf565fc89a), 'demo'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>CREATE TABLE t AS SELECT * FROM tables WITH NO DATA;
operation successful
sql>\d t
CREATE TABLE "sys"."t" (
	"id"            INTEGER,
	"name"          VARCHAR(1024),
	"schema_id"     INTEGER,
	"query"         VARCHAR(1048576),
	"type"          SMALLINT,
	"system"        BOOLEAN,
	"commit_action" SMALLINT,
	"access"        SMALLINT,
	"temporary"     TINYINT
);
sql>select count(*) from t;
+------+
| %1   |
+======+
|    0 |
+------+
1 tuple

sql>COPY SELECT * FROM tables INTO 'csvfiles/tables.psv' ON CLIENT DELIMITERS '|';
sql>COPY SELECT * FROM tables INTO 'csvfiles/tables.csv' ON CLIENT DELIMITERS ',';
sql>COPY SELECT * FROM tables INTO 'csvfiles/tables.tsv' ON CLIENT DELIMITERS '\t';

sql>COPY INTO t FROM 'csvfiles/tables.psv' ON CLIENT DELIMITERS '|';
Failed to import table 't', line 105: column 11: Leftover data 'true|0|0|0'

sql>COPY INTO t FROM 'csvfiles/tables.psv' ON CLIENT DELIMITERS '|';
Failed to import table 't', line 85: column 11: Leftover data '\n sys.describe_type(c.type, c.type_digits, c.type_scale) ||\n ifthenelse(c.\"null\" = 'false', ' NOT NULL', '')\n , ', ') || ')'\n from sys._columns c\n where c.table_id = t.id) col,\n case ts.table_type_name\n when 'REMOTE TABLE' then\n sys.get_remote_table_expressions(s.name, t.name)\n when 'MERGE TABLE' then\n sys.get_merge_table_partition_expressions(t.id)\n when 'VIEW' then\n sys.schema_guard(s.name, t.name, t.query)\n else\n ''\n end opt\n from sys.schemas s, sys.table_types ts, sys.tables t\n where ts.table_type_name in ('TABLE', 'VIEW', 'MERGE TABLE', 'REMOTE TABLE', 'REPLICA TABLE')\n and t.system = false\n and s.id = t.schema_id\n and ts.table_type_id = t.type\n and s.name <> 'tmp';"|11|true|0|0|0'

sql>COPY INTO t FROM 'csvfiles/tables.psv' ON CLIENT DELIMITERS '|';
Failed to import table 't', line 43: column 11: Leftover data ' ' arg' as varchar(44)), 'sys.args', f.system from sys.args a join sys.functions f on a.func_id = f.id left outer join sys.function_types ft on f.type = ft.function_type_id union all\nselect id, name, schema_id, cast(null as int) as table_id, cast(null as varchar(124)) as table_name, 'sequence', 'sys.sequences', false from sys.sequences union all\nselect o.id, o.name, pt.schema_id, pt.id, pt.name, 'partition of merge table', 'sys.objects', false from sys.objects o join sys._tables pt on o.sub = pt.id join sys._tables mt on o.nr = mt.id where mt.type = 3 union all\nselect id, sqlname, schema_id, cast(null as int) as table_id, cast(null as varchar(124)) as table_name, 'type', 'sys.types', (sqlname in ('inet','json','url','uuid')) from sys.types where id > 2000\n order by id;"|11|true|0|0|0'

sql>COPY INTO t FROM 'csvfiles/tables.psv' ON CLIENT DELIMITERS '|';
Failed to import table 't', line 115: column 11: Leftover data ' sys.dq(col) || ' SET DEFAULT ' || def || ';' stmt,\n sch schema_name,\n tbl table_name,\n col column_name\n from sys.describe_column_defaults;"|11|true|0|0|0'

sql>select count(*) from t;
+------+
| %1   |
+======+
|    0 |
+------+
1 tuple
sql>

sql>COPY INTO t FROM 'csvfiles/tables.csv' ON CLIENT DELIMITERS ',';
Failed to import table 't', line 41: column 11: Leftover data ' ql.ship, ql.cpu, ql.io\nfrom sys.querylog_catalog() qd, sys.querylog_calls() ql\nwhere qd.id = ql.id and qd.owner = user;",11,true,0,0,0'

sql>COPY INTO t FROM 'csvfiles/tables.csv' ON CLIENT DELIMITERS ',';
Failed to import table 't', line 41: column 11: Leftover data ' ql.ship, ql.cpu, ql.io\nfrom sys.querylog_catalog() qd, sys.querylog_calls() ql\nwhere qd.id = ql.id and qd.owner = user;",11,true,0,0,0'

sql>COPY INTO t FROM 'csvfiles/tables.csv' ON CLIENT DELIMITERS ',';
Failed to import table 't', line 58: column 11: Leftover data ' c.name as column_name, dep.depend_type as depend_type\n from sys.tables as t, sys.columns as c, sys.triggers as tri, sys.dependencies as dep\n where dep.id = c.id and dep.depend_id = tri.id and c.table_id = t.id\n and dep.depend_type = 8\n order by t.schema_id, t.name, tri.name, c.name;",11,true,0,0,0'

sql>COPY INTO t FROM 'csvfiles/tables.csv' ON CLIENT DELIMITERS ',';
Failed to import table 't', line 22: column 11: Leftover data ' \"commit_action\", \"access\", CASE WHEN (NOT \"system\" AND \"commit_action\" > 0) THEN 1 ELSE 0 END AS \"temporary\" FROM \"sys\".\"_tables\" WHERE \"type\" <> 2 UNION ALL SELECT \"id\", \"name\", \"schema_id\", \"query\", CAST(\"type\" + 30 /* local temp table */ AS SMALLINT) AS \"type\", \"system\", \"commit_action\", \"access\", 1 AS \"temporary\" FROM \"tmp\".\"_tables\";",11,true,0,0,0'

sql>select count(*) from t;
+------+
| %1   |
+======+
|    0 |
+------+
1 tuple
sql>

sql>COPY INTO t FROM 'csvfiles/tables.tsv' ON CLIENT DELIMITERS '\t';
129 affected rows

sql>COPY INTO t FROM 'csvfiles/tables.tsv' ON CLIENT DELIMITERS '\t';
129 affected rows

sql>select count(*) from t;
+------+
| %1   |
+======+
|  258 |
+------+
1 tuple

sql>COPY INTO t FROM 'csvfiles/tables.tsv' ON CLIENT DELIMITERS '\t';
129 affected rows

sql>select count(*) from t;
+------+
| %1   |
+======+
|  387 |
+------+
1 tuple

sql>truncate t;
387 affected rows

sql>select count(*) from t;
+------+
| %1   |
+======+
|    0 |
+------+
1 tuple

sql>drop table t;
operation successful

sql>\d
sql>

**Expected behavior**
The import of created files tables.psv and tables.csv succeed without errors (like is the case with tables.tsv).
Also the import does not return the same error for the data file when it is executed multiple consecutive times.
This looks like mserver5 randomly processes the data file (or is this due to parallel processing the data file).
At least to the user it is not consistent and therefore confusing.

**Software versions**
I tested it using the compiled build from default branch on Fedora .
However this problem is probably also reproducable with Jul2021 or Jul2021-SP1 release

**Comment by mvdvm** [comment]
I also ran this now with ON SERVER instead of ON CLIENT. Same results as before, see below.
This implies the problem is in the mserver5 its csv data file parser, as the data files are accessed by the mserver5 and not by mclient.

sql>COPY SELECT * FROM tables INTO '/home/dinther/csvfiles/tables_os.psv' ON SERVER DELIMITERS '|';
sql>COPY SELECT * FROM tables INTO '/home/dinther/csvfiles/tables_os.csv' ON SERVER DELIMITERS ',';
sql>COPY SELECT * FROM tables INTO '/home/dinther/csvfiles/tables_os.tsv' ON SERVER DELIMITERS '\t';

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.psv' ON SERVER DELIMITERS '|';
Failed to import table 't', line 115: column 11: Leftover data ' sys.dq(col) || ' SET DEFAULT ' || def || ';' stmt,\n sch schema_name,\n tbl table_name,\n col column_name\n from sys.describe_column_defaults;"|11|true|0|0|0'

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.psv' ON SERVER DELIMITERS '|';
Failed to import table 't', line 115: column 11: Leftover data ' sys.dq(col) || ' SET DEFAULT ' || def || ';' stmt,\n sch schema_name,\n tbl table_name,\n col column_name\n from sys.describe_column_defaults;"|11|true|0|0|0'

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.psv' ON SERVER DELIMITERS '|';
Failed to import table 't', line 85: column 11: Leftover data '\n sys.describe_type(c.type, c.type_digits, c.type_scale) ||\n ifthenelse(c.\"null\" = 'false', ' NOT NULL', '')\n , ', ') || ')'\n from sys._columns c\n where c.table_id = t.id) col,\n case ts.table_type_name\n when 'REMOTE TABLE' then\n sys.get_remote_table_expressions(s.name, t.name)\n when 'MERGE TABLE' then\n sys.get_merge_table_partition_expressions(t.id)\n when 'VIEW' then\n sys.schema_guard(s.name, t.name, t.query)\n else\n ''\n end opt\n from sys.schemas s, sys.table_types ts, sys.tables t\n where ts.table_type_name in ('TABLE', 'VIEW', 'MERGE TABLE', 'REMOTE TABLE', 'REPLICA TABLE')\n and t.system = false\n and s.id = t.schema_id\n and ts.table_type_id = t.type\n and s.name <> 'tmp';"|11|true|0|0|0'

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.psv' ON SERVER DELIMITERS '|';
Failed to import table 't', line 105: column 11: Leftover data 'true|0|0|0'
sql>

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.csv' ON SERVER DELIMITERS ',';
Failed to import table 't', line 22: column 11: Leftover data ' \"commit_action\", \"access\", CASE WHEN (NOT \"system\" AND \"commit_action\" > 0) THEN 1 ELSE 0 END AS \"temporary\" FROM \"sys\".\"_tables\" WHERE \"type\" <> 2 UNION ALL SELECT \"id\", \"name\", \"schema_id\", \"query\", CAST(\"type\" + 30 /* local temp table */ AS SMALLINT) AS \"type\", \"system\", \"commit_action\", \"access\", 1 AS \"temporary\" FROM \"tmp\".\"_tables\";",11,true,0,0,0'

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.csv' ON SERVER DELIMITERS ',';
Failed to import table 't', line 41: column 11: Leftover data ' ql.ship, ql.cpu, ql.io\nfrom sys.querylog_catalog() qd, sys.querylog_calls() ql\nwhere qd.id = ql.id and qd.owner = user;",11,true,0,0,0'

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.csv' ON SERVER DELIMITERS ',';
Failed to import table 't', line 41: column 11: Leftover data ' ql.ship, ql.cpu, ql.io\nfrom sys.querylog_catalog() qd, sys.querylog_calls() ql\nwhere qd.id = ql.id and qd.owner = user;",11,true,0,0,0'

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.csv' ON SERVER DELIMITERS ',';
Failed to import table 't', line 58: column 11: Leftover data ' c.name as column_name, dep.depend_type as depend_type\n from sys.tables as t, sys.columns as c, sys.triggers as tri, sys.dependencies as dep\n where dep.id = c.id and dep.depend_id = tri.id and c.table_id = t.id\n and dep.depend_type = 8\n order by t.schema_id, t.name, tri.name, c.name;",11,true,0,0,0'
sql>

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.tsv' ON SERVER DELIMITERS '\t';
129 affected rows

sql>select count(*) from t;
+------+
| %1   |
+======+
|  129 |
+------+
1 tuple

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.tsv' ON SERVER DELIMITERS '\t';
129 affected rows
sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.tsv' ON SERVER DELIMITERS '\t';
129 affected rows

sql>select count(*) from t;
+------+
| %1   |
+======+
|  387 |
+------+
1 tuple

sql>COPY INTO t FROM '/home/dinther/csvfiles/tables_os.tsv' ON SERVER DELIMITERS '\t';
129 affected rows

sql>truncate t;
516 affected rows

sql>select count(*) from t;
+------+
| %1   |
+======+
|    0 |
+------+
1 tuple

sql>drop table t;
operation successful
sql>\d
sql>

**Comment by PedroTadim** [comment]
COPY INTO uses the double quote as the default string delimiter, while COPY FROM uses an empty string. I would say COPY INTO should change, because is used less often than COPY FROM, so less production scripts would possibly break. We will discuss about it.

**Comment by mvdvm** [comment]
Hi Pedro,

As discussed I rather would have the double quote character to be the default string delimiter.
The reason is that this is the default for csv files as used by all external tools (like LibreOffice Calc, MS Excel, PostgreSQL, etc) when reading/writing csv files.

See https://www.postgresql.org/docs/14/sql-copy.html
Search for QUOTE. This shows text: Specifies the quoting character to be used when a data value is quoted. The default is double-quote.

See https://dev.mysql.com/doc/refman/8.0/en/load-data.html
LOAD DATA can be used to read files obtained from external sources. For example, many programs can export data in comma-separated values (CSV) format, such that lines have fields separated by commas and enclosed within double quotation marks, with an initial line of column names.

We should make it users easy to successfully import & export csv files created by/for any external source/target, so assume the double quote character to be the default string delimiter for COPY INTO (this was already the case) and COPY FROM (the default needs to change).

**Comment by PedroTadim** [comment]
From the discussion yesterday, we decided that changing COPY FROM command would be dangerous. At the same time, both commands used different string delimiters for many years now and no one complained about it before, so we can take this as a feature.
