### ISSUE TITLE
MonetDB startup error

### ISSUE THREAD

**Issue by peterZhiFate** [MonetDB/MonetDB#7189]
When I start monetdb, an error appears (my operating system is Windows10 x64).
Below is the error message:
```
C:\Users\cathyma\Desktop\MonetDB5_new>M5server.bat --dbpath=wyndw --set mapi_port=50000 --set max_clients=200
MonetDB/Python Disabled: Python 3.9 installation not found.
# MonetDB 5 server v11.41.5 (Jul2021)
# Serving database 'demo', using 8 threads
# Compiled for amd64-pc-windows-msvc/64bit
# Found 15.692 GiB available main-memory of which we use 12.789 GiB
# Copyright (c) 1993 - July 2008 CWI.
# Copyright (c) August 2008 - 2021 MonetDB B.V., all rights reserved
# Visit https://www.monetdb.org/ for further information
#2021-10-22 12:07:23: main thread: createExceptionInternal: !ERROR: LoaderException:loadLibrary:Loading error failed to open library geom (from within file 'C:\Users\cathyma\Desktop\MonetDB5_new\lib\monetdb5\_geom.dll'): The specified module could not be found.
#2021-10-22 12:07:23: main thread: mal_init: !ERROR: LoaderException:loadLibrary:Loading error failed to open library geom (from within file 'C:\Users\cathyma\Desktop\MonetDB5_new\lib\monetdb5\_geom.dll'): The specified module could not be found.
```

**Comment by PedroTadim** [comment]
Did you compile and install MonetDB from sources or did you use the installer? Is the _geom.dll file on the location?

**Comment by peterZhiFate** [comment]
> Did you compile and install MonetDB from sources or did you use the installer? Is the _geom.dll file on the location?

I installed it on another machine through msi, then copied its installation file to the current machine, and then started it.

In addition, _geom.dll is in the specified directory

**Comment by PedroTadim** [comment]
This sounds like a bad installation. Can you try to install again from scratch?

**Comment by zhaoyexa** [comment]
Does it support silent installation on windows？

**Comment by PedroTadim** [comment]
We don't support silent installation on Windows at the moment. About the issue, can you confirm the directory of _geom.dll is on the PATH?

**Comment by zhaoyexa** [comment]
The _geom.dll file is in the path, it was not installed normally, but the installed file of another machine was copied to another machine

**Comment by PedroTadim** [comment]
This could be a visual studio c++ runtime version mismatch between the geom library and mserver5, but I am not a Windows expert to give a definitive answer.

**Comment by zhaoyexa** [comment]
I just compared the files in the msi with the installed files, and found that there are several .dll files in the C:\Windows\System32 directory after the normal installation. after copying these files to MonetDB/bin/, MonetDB can start normally.
