### ISSUE TITLE
Upsert clause support

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7190]
**Is your feature request related to a problem? Please describe.**
The absence of Upsert means several queries whereas Upsert means only one query. Also, that can be optimized.

**Describe the solution you'd like**
implementation of an UPSERT clause

**Describe alternatives you've considered**
writing several queries

**Comment by joerivanruth** [comment]
You can use MERGE statements for this, see https://www.monetdb.org/blog/sql2003_merge_statements_now_supported.

**Comment by simonaubertbd** [comment]
Hello @joerivanruth 
Thanks. Found the documentation on https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-manipulation/merge-statement/
