### ISSUE TITLE
Python UDFs are mapped even if they are not mappable.

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7195]
According to the documentation of monetdb/numpy pdfs, a UDF is mappable only when python_map language is defined. Otherwise is considered as a black box. According to an example it is ok to have a scalar function like this:
CREATE FUNCTION python_min(i INTEGER) RETURNS integer LANGUAGE PYTHON {
    return numpy.min(i)
};
which returns one single value in the result and expect it not to be mappable.
However, we have encountered a case that this UDF runs in parallel and returns multiple rows in the output.
If we have a merge table, with two partition tables, and run the above UDF without defining it as PYTHON_MAP, then this is mapped to the partitions and returns 2 values.

**Comment by PedroTadim** [comment]
This is an issue I found a few months back. The author of Python UDFs forgot to check the cardinality of the input and outputs must match. If I have time, I can attempt to fix this.

**Comment by johnfouf** [comment]
This solution seems to be the most valid, as this is how scalar functions are most usually defined, and I agree with this.

However, I wonder if there is existing code based on this characteristic, since according to the documentation page, this seems to have been done in purpose, and it is possible to create a non-mappable vectorized function returning different output size. If it is defined as mappable with Python_map, then it is same as traditional scalar udfs.
