### ISSUE TITLE
BATproject2: does not match always

### ISSUE THREAD

**Issue by Aceeri** [MonetDB/MonetDB#7196]
**Describe the bug**

Heyo, I was trying to test some things to make our analytics stuff more stable. Basically I create a table, start a transaction on 2 clients, one alters the table to add a new column, the other client inserts some data. Instead of rolling back it ends up corrupting the table entirely it seems like?

I've read over the optimistic concurrency control so I'm not sure if this is *actually* a bug or expected behavior here. 

**To Reproduce**

 Client 1
```
sql>create table test (id bigint);
operation successful
sql>select * from test;
+----+
| id |
+====+
+----+
0 tuples
sql>start transaction;
auto commit mode: off
sql>alter table test add column data int; # To be clear this is run BEFORE the insert in the second client.
operation successful
sql>commit;
auto commit mode: on
sql>select * from test;
GDK reported error: BATproject2: does not match always
```

Client 2
```
sql>select * from test;
+----+
| id |
+====+
+----+
0 tuples
sql>start transaction;
auto commit mode: off
sql>insert into test values (1); # This is run AFTER the alter
1 affected row
sql>commit;
auto commit mode: on
sql>select * from test;
GDK reported error: BATproject2: does not match always
```

**Expected behavior**
I know this is a violation of the OCC rules on concurrent connections but wasn't expecting the table to not be recoverable afterwards.

**Screenshots**

**Software versions**
MonetDB: MonetDB Database Server Toolkit v11.41.11 (Jul2021-SP1)
OS: Linux 839c464b9757 5.10.0-8-cloud-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 x86_64 x86_64 GNU/Linux
Using the docker image here: https://hub.docker.com/r/monetdb/monetdb

**Issue labeling **
Table corruption, concurrent transactions,

**Additional context**

**Comment by sjoerdmullender** [comment]
There is clearly a bug here.  Neither client should report "BATproject2: does not match always".
I was able to reproduce by making sure both clients had started their transactions before the ALTER and INSERT queries were done.
In this case, there is going to be a conflict between the two transactions, so at least one of them should fail (I expect).  So I think there is a problem handling this type of case.

**Comment by PedroTadim** [comment]
A dml dependency is missing I think. Let me test before and after my changes.

**Comment by bharaththam** [comment]
hi Joe mullender ,

Is the BAT project2:doesnot match always is fixed in which version i need the version because we are facing lot issues and failures we need test upgrading it to the required verison

**Comment by bharaththam** [comment]
hi pedrotadim 
any comments in which verison it is used as i am unable to get the in any of the notes

**Comment by PedroTadim** [comment]
Hi! This error message is generally thrown due to an internal bug. You may be facing another bug. Can you make a reproducible test case?

**Comment by sjoerdmullender** [comment]
> hi pedrotadim any comments in which verison it is used as i am unable to get the in any of the notes

We are experiencing nameserver resolution problems with our monetdb.org website where the release notes are normally available.  The provider has not given an ETA for their fix of this problem.
