### ISSUE TITLE
Cast query constant instead of column data for incompatible timestamp types

### ISSUE THREAD

**Issue by jpastuszek** [MonetDB/MonetDB#7197]
The database prefers to convert column data to match the query filter type instead of the way around for timestamps.

I filter the TIMESTAMP (SQL date and time) column `processed_timestamp` with timestamp calculated using `interval` statement. The resulting filter type is a UNIX timestamp and does not match the SQL date and time column type. The engine adds a cast from SQL date and time to UNIX timestamp for each column data entry which is very slow compared to just casting the UNIX timestamp to SQL date and time filter constant.

```
 -- took: 463ms
 --     X_8:bat[:timestamp] := sql.bind(X_4:int, "logs":str, "http_access_past":str, "processed_timestamp":str, 0:int);
 --     X_15:bat[:timestamp] := batcalc.timestamp(X_8:bat[:timestamp], C_5:bat[:oid], 7:int);
 --     C_28:bat[:oid] := algebra.select(X_15:bat[:timestamp], "2021-11-10 14:48:19.393693":timestamp, "2021-11-10 14:54:59.393705":timestamp, true:bit, true:bit, false:bit, true:bit);
explain
select count(*)
from logs.http_access
where processed_timestamp BETWEEN now() - interval '110' second - interval '300' second 
and now() - interval '10' second
```

Notice the `timestamp_2time_timestamp` calls during execution:

```
Overhead  Shared Object              Symbol
  56.06%  libmonetdbsql.so.11.41.11  [.] __divti3
  21.65%  libmonetdbsql.so.11.41.11  [.] timestamp_2time_timestamp
   5.86%  libbat.so.23.0.3           [.] timestamp_create
   4.29%  libbat.so.23.0.3           [.] timestamp_date
   4.18%  libbat.so.23.0.3           [.] timestamp_daytime
   2.30%  libmonetdbsql.so.11.41.11  [.] timestamp_date@plt
   1.15%  libmonetdbsql.so.11.41.11  [.] timestamp_create@plt
   1.05%  libbat.so.23.0.3           [.] BATordered
   0.36%  libmonetdbsql.so.11.41.11  [.] timestamp_daytime@plt
```

The workaround is to manually cast the result of the interval operation to TIMESTAMP - this make my query to run 10x faster:

```
-- took: 40 ms
--    X_8:bat[:timestamp] := sql.bind(X_4:int, "logs":str, "http_access_past":str, "processed_timestamp":str, 0:int);
--    C_29:bat[:oid] := algebra.select(X_8:bat[:timestamp], C_5:bat[:oid], "2021-11-19 10:42:12.604285":timestamp, "2021-11-19 10:48:52.604301":timestamp, true:bit, true:bit, false:bit, true:bit);
explain
select count(*)
from logs.http_access
where processed_timestamp BETWEEN CAST(now() - interval '110' second - interval '300' second AS TIMESTAMP) 
and CAST(now() - interval '10' second AS TIMESTAMP)
```

Ideally the database would add the cast automatically for the constant that the table is filtered by instead of casting all the column data.

This is on MonetDB Jul2021-SP1 release.

I have ended up rewriting my queries due to stricter SQL standard requirements introduced with the latest releases (I was using integer subtraction before) and I have noticed this problem. I have migrated from Apr2019-SP1 release.

**Comment by PedroTadim** [comment]
The 'now' function returns a timestamp with time zone, which requires the conversion. If possible, try using the 'localtimestamp' function which returns a timestamp without time zone, and no conversion is performed.

**Comment by jpastuszek** [comment]
Yes, I can confirm that using `localtimestamp` does avoid the overhead of type casting, I will update my queries. Thank you for the tip!
As for the issue I think it still stands that the DB may be better off casting constants in the query once rather than data in each row to match. But now this is more like a feature request I guess than a bug, as I was using wrong types...

**Comment by PedroTadim** [comment]
The reason the constants are not converted in the example it's because the difference used it's not computed during SQL optimization, but rather the backend engine, so there might be late. After computing the difference the constants are converted.

**Comment by jpastuszek** [comment]
Yeah looks like this calculation is done for each partition (perhaps in parallel execution):

```
exit X_1150:bit;
    X_899:timestamp := sql.current_timestamp();
    X_901:timestamp := mtime.timestamp_sub_msec_interval(X_899:timestamp, 110000:lng);
    X_903:timestamp := mtime.timestamp_sub_msec_interval(X_901:timestamp, 300000:lng);
    X_904:timestamp := sql.current_timestamp();
barrier X_1153:bit := language.dataflow();
    X_914:bat[:lng] := bat.new(nil:lng);
    X_913:bat[:lng] := bat.single(X_890:lng);
    X_906:timestamp := mtime.timestamp_sub_msec_interval(X_904:timestamp, 10000:lng);
    C_907:bat[:oid] := algebra.select(X_894:bat[:timestamp], C_891:bat[:oid], X_903:timestamp, X_906:timestamp, true:bit, true:bit, false:bit, true:bit);
    X_912:lng := aggr.count(C_907:bat[:oid]);
    X_916:bat[:lng] := bat.append(X_914:bat[:lng], X_913:bat[:lng], true:bit);
    X_917:bat[:lng] := bat.append(X_916:bat[:lng], X_912:lng, true:bit);
    X_921:bat[:timestamp] := sql.bind(X_4:int, "logs":str, "http_access_20211112":str, "processed_timestamp":str, 0:int);
    C_919:bat[:oid] := sql.tid(X_4:int, "logs":str, "http_access_20211112":str);
    X_918:lng := aggr.sum(X_917:bat[:lng]);
exit X_1153:bit;
    X_928:timestamp := sql.current_timestamp();
    X_931:timestamp := mtime.timestamp_sub_msec_interval(X_928:timestamp, 110000:lng);
    X_934:timestamp := mtime.timestamp_sub_msec_interval(X_931:timestamp, 300000:lng);
    X_935:timestamp := sql.current_timestamp();
barrier X_1156:bit := language.dataflow();
    X_943:bat[:lng] := bat.new(nil:lng);
    X_942:bat[:lng] := bat.single(X_918:lng);
    X_938:timestamp := mtime.timestamp_sub_msec_interval(X_935:timestamp, 10000:lng);
    C_939:bat[:oid] := algebra.select(X_921:bat[:timestamp], C_919:bat[:oid], X_934:timestamp, X_938:timestamp, true:bit, true:bit, false:bit, true:bit);
    X_941:lng := aggr.count(C_939:bat[:oid]);
    X_944:bat[:lng] := bat.append(X_943:bat[:lng], X_942:bat[:lng], true:bit);
    X_946:bat[:lng] := bat.append(X_944:bat[:lng], X_941:lng, true:bit);
    X_950:bat[:timestamp] := sql.bind(X_4:int, "logs":str, "http_access_20211119":str, "processed_timestamp":str, 0:int);
    C_948:bat[:oid] := sql.tid(X_4:int, "logs":str, "http_access_20211119":str);
    X_947:lng := aggr.sum(X_946:bat[:lng]);
```
I guess given that this is a dynamic function call and an extra calculation needed on its result that should not be surprising...

**Comment by jpastuszek** [comment]
Thank you for the information. I think I can close the issue as this is how the system works and having the types right in the query is the key here.
