### ISSUE TITLE
PRIMARY KEY unique constraint is violated with concurrent inserts

### ISSUE THREAD

**Issue by nuno-faria** [MonetDB/MonetDB#7200]
**Describe the bug**
The unique constraint imposed by the PRIMARY KEY is violated when there are concurrent inserts, resulting in multiple rows with the same key.

**To Reproduce**
- Create a table with a primary key:
  ```sql
  CREATE TABLE T (k int PRIMARY KEY, v int);
  ```

- Check that the unique constraint is working correctly:
  ```sql
  INSERT INTO T VALUES (1, 1); -- ok
  INSERT INTO T VALUES (1, 1); -- fails (INSERT INTO: PRIMARY KEY constraint 't.t_k_pkey' violated)
  DELETE FROM T; -- reset table
  ```

- Test using bash + `mclient`:
  - Create the `DOTMONETDBFILE`:
    ```bash
    cat <<EOF >> .monetdb
    user=monetdb
    password=monetdb
    EOF
    ```
  - Run concurrent inserts (make sure to run the second command immediatly after the first, e.g., by pasting the entire input in the terminal):
    ```bash
    for i in {1..1000}; do DOTMONETDBFILE=.monetdb mclient -d testdb -s "INSERT INTO T VALUES ($i, $i)"; done &
    for i in {1..1000}; do DOTMONETDBFILE=.monetdb mclient -d testdb -s "INSERT INTO T VALUES ($i, $i)"; done
    ;
    ```
  - Check the duplicate values in the table:
    ```sql
    SELECT count(*) FROM T;

    Returns (the actual value may vary):
    +------+
    | %1   |
    +======+
    | 1917 |
    +------+ 

    SELECT * FROM T LIMIT 10;

    Returns:
    +------+------+
    | k    | v    |
    +======+======+
    |    1 |    1 |
    |    1 |    1 |
    |    2 |    2 |
    |    2 |    2 |
    |    3 |    3 |
    |    3 |    3 |
    |    4 |    4 |
    |    4 |    4 |
    |    5 |    5 |
    |    5 |    5 |
    +------+------+
    ```
  - Running the script again will result in just rollbacks, so it only affects concurrent executions.

- Test using Python with `pyodbc`:
  ```python
  import pyodbc
  from multiprocessing import Pool

  def insert(_):
      conn = pyodbc.connect(f"DRIVER={{/usr/lib/x86_64-linux-gnu/libMonetODBC.so}};HOST=localhost;PORT=50000;DATABASE=testdb;UID=monetdb;PWD=monetdb")
      conn.autocommit = True
      cursor = conn.cursor()
      
      for i in range(1000):
          try:
              cursor.execute(f'INSERT INTO T values(?, ?)', i, i)
          except:
              pass

      return True

  pool = Pool(2)
  pool.map(insert, range(2))
  ```
**Expected behavior**
No rows with a duplicate primary key.

**Software versions**
- `monetdb -v`: `MonetDB Database Server Toolkit v11.41.11 (Jul2021-SP1)`.
- OS: `Ubuntu 20.04.3 LTS`;
- Monetdb installed from release packages with `apt` (packages `monetdb5-sql` and `monetdb-client`);
- `mclient -v`: `mclient, the MonetDB interactive terminal, version 11.41.11 (Jul2021-SP1)`
- ODBC driver installed with `apt` packages `unixodbc`, `unixodbc-dev`, and `libmonetdb-client-odbc`;
- `pyodbc==4.0.32`.

**Additional context**
The problem is visible with both `autocommit=True` and `autocommit=False`.

**Comment by PedroTadim** [comment]
On Jul2021 we added support for snapshot isolation, but transaction isolation levels are not correctly handled, and the storage thinks the transaction is running on the snapshot isolation level, while it should be serializable. Fix is on the way.
