### ISSUE TITLE
Continuous Queries Support

### ISSUE THREAD

**Issue by AKheli** [MonetDB/MonetDB#7204]
I am trying to evaluate the ability of MonetDB on performing continuous queries on time series data. 

Continuous queries on time series data are queries that run automatically and periodically on real-time data (and maybe store query results in a specified measurement). Some Time Series Database Systems (TSDBs) have a built-in operation that allows doing this (e.g. InfluxDB, TimescaleDB). 

I couldn't find in MonetDB's documentation a way to perform this type of query. Another alternative would be to program the frequency of queries in a separate programming language/system clock that would run the given query frequently and automatically every time length. This is however not guaranteed to be fair 1) to the system because the performance would depend on an independent factor (the third-party programming language) and 2) to the other systems because they provide an extra convenient feature that MonetDB does not. 

My question is there an efficient way that could be used for the purpose of performing continuous queries? If not, what are the alternative I have using MonetDB in order to perform the continuous queries?

Thanks!

**Comment by PedroTadim** [comment]
You are asking for the trails branch! We have implemented continuous queries there, but it's still a developmental branch, so is far from being production ready. At the same time, it is not paired with recent versions of MonetDB, and those changes include storage rewrite, MAL scripts loading, new MAL optimizers, etc. Make it accommodate these new features will take some time.

**Comment by AbdelouahabKhelifati** [comment]
That makes sense. Thanks Pedro!
