### ISSUE TITLE
Time Series Data Indexing for Performance Benchmarking

### ISSUE THREAD

**Issue by AKheli** [MonetDB/MonetDB#7207]
I know MonetDB is a self-indexing database but how does this actually work? I am benchmarking time-series database systems with data of the following format: 

```
sql>select * from datapoints limit 5; 
+----------------------------+------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+
| time                       | id_station | temperature              | discharge                | ph                       | oxygen                   | oxygen_saturation        |
+============================+============+==========================+==========================+==========================+==========================+==========================+
| 2019-03-01 00:00:00.000000 |          0 |                  407.052 |                    0.954 |                     7.79 |                    12.14 |                    12.14 |
| 2019-03-01 00:00:10.000000 |          0 |                  407.052 |                    0.954 |                     7.79 |                    12.13 |                    12.13 |
+----------------------------+------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+
```

The fields of the data are the `time`, the `station_id`, and the other sensor readings. 

I am creating a database with the `time` as a primary key, as follows: 

```
CREATE TABLE datapoints ( 
        time TIMESTAMP NOT NULL PRIMARY KEY, 
        id_station INTEGER,
        temperature DOUBLE PRECISION , 
        discharge DOUBLE PRECISION , 
        pH DOUBLE PRECISION , 
        oxygen DOUBLE PRECISION , 
        oxygen_saturation DOUBLE PRECISION
);
```

I would also like to index data on the `id_station`, since most of the queries would be using it to locate the data. 

Should I create another index on the column `id_station`? On the [documentation](https://www.monetdb.org/Documentation/SQLLanguage/DataDefinition/IndexDefinitions) it says that MonetDB would take the `create index` statements like suggestions and are often neglected.  

The following [article](https://dev.to/yugabyte/think-about-primary-key-indexes-before-anything-else-o5m) mentions that the order of columns used in the index is very important `(id_station, time)` vs `(time, id_station`). 

Does MonetDB create compound indexes as well or is it just per column? What indexing strategy is being used? How should I assert the optimal indexing strategy for my use case?

**Comment by mvdvm** [comment]
MonetDB detects when it would need an index on a column to speedup the query processing. So when you send a query it could internally build indices as part of the query processing. Those internal indices may be reused for instance if you repeat the query, which may run faster the second time. For benchmarking this makes a difference, so run your queries multiple times. Often the first (on cold data) query time is ignored, and next runs (on hot data) are used for comparison.
Tip: For optimal results you should run [ANALYZE statement](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-manipulation/analyze-statement/) to update column data statistics after loading table data and before running the benchmark queries.

A `create index` statement currently does not create a physical secondary index. So you do **not** need to do `create index`.
See [index-definitions](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-definition/index-definitions/).
Please note that manually created indices also create costs, such as: DBA or SQL tuning expert time needed, slower INSERT, UPDATE and DELETE performance, more permanent disk storage needed, etc. MonetDB will save on these costs.

Our aim is that MonetDB runs any SQL query as fast as possible, without the need to manually create indices. This is also the intention of SQL, which is a declarative language. FYI: the CREATE INDEX statement is not even part of the ISO SQL standard.

You may also read our [performance tips](https://www.monetdb.org/documentation-Jan2022/admin-guide/performance-tips/performance-tips/).

If you have queries which run slow in comparison to others, you could use the `PLAN SELECT ..` , `EXPLAIN SELECT ..` and `TRACE SELECT ..` to get details on the SQL and MAL execution plans.
When you see opportunities for improvement, please let us know by logging an enhancement request, including all the SQL statements and trace logs to reproduce the performance problem. Also include the used MonetDB version and used OS and version.
