### ISSUE TITLE
Configuration option for merovingian.log

### ISSUE THREAD

**Issue by yzchang** [MonetDB/MonetDB#7209]
Would be nice to be able to configure what is being logged in the merovingian.log. In particular, a way to not log the large amount of connection information, because they can push away more useful (error) messages in log rotation.

**Comment by swingbit** [comment]
That would be very nice!

I was writing this to the mailing list in 2018:

> merovingian.log files on our production servers are dominated by these two lines:
> 
> 2018-03-21 16:55:38 MSG merovingian[23237]: proxying client localhost.localdomain:51502 for database 'test' to mapi:monetdb://path/test/.mapi.sock?database=test
> 2018-03-21 16:55:38 MSG merovingian[23237]: target connection is on local UNIX domain socket, passing on filedescriptor instead of proxying
> 
> They account for 90% of the log. 
> 
> Is there a way to reduce verbosity? 
> 
> Maybe it would be nice to introduce the concept of logging levels in MonetDB (like ALL, DEBUG, INFO, WARN, ERROR, FATAL), so that one can then decide what to log, with a simple configuration option.
> I would argue the two lines I mention are at level DEBUG. 
>

**Comment by yzchang** [comment]
Does “tracer” provide some of those features? https://www.monetdb.org/Documentation/Tutorial/Troubleshooting/Tracer

**Comment by swingbit** [comment]
Ah look, I had missed that! :)

But, as you say, merovingian.log is bloated with connection information. It would be nice to make it more readable.

**Comment by mvdvm** [comment]
FYI, in the upcoming new Jan2022 release we will filter out connection information messages from merovingian.log such as:
2018-03-21 16:55:38 MSG merovingian[23237]: proxying client localhost.localdomain:51502 for database 'test' to mapi:monetdb://path/test/.mapi.sock?database=test
2018-03-21 16:55:38 MSG merovingian[23237]: target connection is on local UNIX domain socket, passing on filedescriptor instead of proxying

And in a future release we plan to add the suggested logging levels and possibility to set and change the log level.

**Comment by mvdvm** [comment]
For the next feature release (after Jan2022) we added "loglevel" property for monetdbd logging (to merovingian.log).
The loglevel can be set to: error or warning or information or debug.
The loglevel property can be changed dynamically via command:
  monetdbd set loglevel=warning /path/to/dbfarm
Default the loglevel is set to: information
When loglevel is error, only errors are logged.
When loglevel is warning, errors and warnings are logged.
When loglevel is information, errors and warnings and information messages are logged.
When loglevel is debug, all messages are logged.
