### ISSUE TITLE
"Failed to extend the BAT" error in MonetDB 11.41.5

### ISSUE THREAD

**Issue by llorieb** [MonetDB/MonetDB#7213]
I'm using MonetDB 11.41.5 and I'm trying to bulk upload a very large CSV file (70 Gb) to a table using COPY INTO.

After a few minutes, I get the following message:

![Error_1](https://user-images.githubusercontent.com/36425807/147571399-cc94b7ca-8088-45fa-be66-4039646f72c3.png)

The complete COPY INTO sentence is:

`COPY OFFSET 2 INTO brasil.staging_rm_fact FROM '/opt/data/import/Brasil/202108/stagings/staging_rm_fact.csv' USING DELIMITERS ';','\n','"' NULL AS '';
`

- Disk space is enough to ensure the sucess of operation (more than 600 Gb of free space).
- The problem doesn't happen using previous version of MonetDB (11.39.11). Works perfectly in exactly the same conditions: same server, same free disk space and same large CSV file.

CSV file has 225 millions of lines. In order to help to reproduce the error, I attached a reduced version of 100.000 sample lines of the same file. You can repeat the lines to create a 225 million lines file. Please, keep the header as the first line in the CSV file.

[sample.zip](https://github.com/MonetDB/MonetDB/files/7784921/sample.zip)

The target table is created with this sentence:

[table.zip](https://github.com/MonetDB/MonetDB/files/7784934/table.zip)

If you need more information, please feel free to ask me. I'm going to try to get some debug information, as you suggested in Staackoverflow using:

```
CALL logging.setcomplevel('HEAP', 'DEBUG');
CALL logging.setflushlevel('DEBUG');
```

**Comment by joerivanruth** [comment]
Link to the StackOverflow discussion: https://stackoverflow.com/questions/70352149/failed-to-extend-the-bat-error-in-monetdb-11-41-5
