### ISSUE TITLE
Update failed due to conflict with another transaction

### ISSUE THREAD

**Issue by morgana2313** [MonetDB/MonetDB#7216]
**Describe the bug**

I have multiple perl scripts running every night, one after the other, that each updating their own tables.  The scripts use transactional updates. For some reason one of the scripts brings monetdb into a state where from that point on all scripts fail with a _Update failed due to conflict with another transaction_. 

**To Reproduce**
I have not been able to narrow down the problem yet. The problem may have started with a full disk.

**Expected behavior**
I would expect that if one script fails, that session is aborted (and rolled back), but following sessions would be unaffected. Is that a misconception?

**Screenshots**
```
$ mclient
Welcome to mclient, the MonetDB/SQL interactive terminal (Jul2021)
Database: MonetDB v11.41.5 (Jul2021), 'mapi:monetdb://monet1:50000/mapfilter'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>drop table x;
Transaction conflict while dropping table sys.x
```

**Software versions**
- MonetDB Database Server Toolkit v11.41.5 (Jul2021)
 - Ubuntu 18.04]
 - Installed from release package

**Comment by PedroTadim** [comment]
I fixed a problem recently that the wrong message would be thrown if a disk full error would happen on Jan2022. Can you try to test there? Also at this point, we don't support concurrent updates on the same table.

**Comment by PedroTadim** [comment]
More recently we did another bug fix similar to this one? Can you try test it again?
