### ISSUE TITLE
monetdb sometimes hangs during copy from /abs/path 

### ISSUE THREAD

**Issue by morgana2313** [MonetDB/MonetDB#7217]
**Describe the bug**

This happens about 1 in 10 times I use a script that uses 

`
COPY {n} OFFSET 2 RECORDS INTO "sys"."{table}" FROM '{absPath}' {using_delimitors}
`
to do a big (10M+ records) import.

when this happens my Ubuntu 18.04 server goes into a strange state; `ps -auwx` shows some processes hand then hangs completely. ctrl-c doesn't work. `service monetdbd stop` brings the system back to a normal state.

**To Reproduce**
I cannot reproduce it. When i happens and I restart the server to import the same data it works ok.

**Software versions**
- MonetDB Database Server Toolkit v11.41.5 (Jul2021)
 - Ubuntu 18.04]
 - Installed from release package

**Comment by sjoerdmullender** [comment]
From the limited description, it sounds as if the server is thrashing.  The issue might be that the server is using more memory than the system has (which causes thrashing).
The immediate solution is then indeed to kill the server and try it again.
Perhaps this will alleviate the problem: add a row count to the query.  Specifically, add a count to the first COPY INTO query for the table that gives the total number of rows to be inserted, not the number of rows in the first file.
To be sure this is the problem, monitor the system using e.g. the `top` command and look at the columns for resident set size and virtual size (VIRT and RES in my copy of top).
How much memory does your system have?
