### ISSUE TITLE
what is the different between the release of GitHub and monetdb.org?

### ISSUE THREAD

**Issue by l1t1** [MonetDB/MonetDB#7220]
I found the GitHub is newer.
for example, the newest release at GitHub is
https://github.com/MonetDB/MonetDB/releases/tag/Jan2022_release
but the newest of monetdb.org is
https://www.monetdb.org/downloads/Windows/Jul2021-SP2/

**Comment by kutsurak** [comment]
If you take a look at the tags in our Mercurial repository [here](https://www.monetdb.org/hg/MonetDB/tags) where actual development happens, you will see that it has exactly the same tags. 

Currently we are in the process of creating a new release, so release candidates are being tagged as part of our release process. Usually we have to test a couple of candidates before we are happy with one and marking it as a new release publicly, but all the tags remain and they get mirrored automatically to github.

**Comment by l1t1** [comment]
I got it.  thanks
