### ISSUE TITLE
could you supply the tpcds benchmark datasets of scale 10G gz file?

### ISSUE THREAD

**Issue by l1t1** [MonetDB/MonetDB#7221]
I have problem to compile and run the data generater.  
>We run the tpcds benchmark every day and query 72 is not the slowest, still runs at a reasonable speed. Can you show the traces?

_Originally posted by @PedroTadim in https://github.com/MonetDB/MonetDB/issues/7219#issuecomment-1010848129_

**Comment by PedroTadim** [comment]
Uploading a 10 GB file will take some time, you better generate the dataset yourself. There are open source generators for TPC-DS datasets you can try.

**Comment by l1t1** [comment]
I searched the Internet. but no binary for windows was  found

**Comment by PedroTadim** [comment]
We run the benchmarks on Linux, sorry.

**Comment by yzchang** [comment]
Hai Pedro, let's discuss this internally if and how we can possibly provide this 10GB file

**Comment by l1t1** [comment]
[dsgen_win32.rar.zip](https://github.com/MonetDB/MonetDB/files/7896499/dsgen_win32.rar.zip)
[dsgen_x64.rar.zip](https://github.com/MonetDB/MonetDB/files/7896503/dsgen_x64.rar.zip)
binary compiled with vs 2005
