### ISSUE TITLE
Improve the performance of concurrent, non-conflicting INSERTS

### ISSUE THREAD

**Issue by nuno-faria** [MonetDB/MonetDB#7222]
We were hoping you could provide us (or point us to) a way to improve the performance of concurrent, non-conflicting inserts. 
Right now, we think that write performance is being bottlenecked by the sequential commit to the WAL. To test this theory, we executed a [simple benchmark](https://gist.github.com/nuno-faria/304f61c42eb100951e959f1db0a61a46) that compared the insert performance with the WAL in disk (NVMe) and in ramdisk (Google Cloud instance, 32 cores & 32 GB RAM; MonetDB branch Jan22 used). Additionally, we considered a different number of inserts per transaction (1 with autocommit=on, 5 and 10 with autocommit=off):

<img width="733" alt="image" src="https://user-images.githubusercontent.com/26089290/149510540-aada8e75-80f0-4af3-bd3e-8f076c9b4a23.png">

Even though we used an NVMe, the write performance in disk stagnates after 4 threads, unlike with ramdisk. So 1) this is a problem with the storage.
Furthermore, the throughput in disk increases when each transaction inserts more data, so 2) this is a problem with the commit.

For comparison, PostgreSQL single insert/tx achieves up to 35k inserts/s (or 15x higher than MonetDB) and linearly scales to 32 threads.

To see if we could remove the bottleneck, we commented out the `commit` lock in the commit function `sql_trans_commit`, as presented in this [file](https://gist.github.com/nuno-faria/90f62a6969a54b8b59ea8b0e01cd33a9), obtaining the following results:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/26089290/149509728-b42af01d-c87d-441c-9841-d1c3bd1e43af.png">

Without the `commit` lock, the write performance now scales up to 16 threads in disk. In addition, the table correctly displayed all data inserted, while the recently committed data is still in the WAL. However, when the flush from the WAL to the store occurs, sometimes most of the data disappears and the database crashes with the following message:

```log
2022-01-13 11:39:07 ERR testdb[23397]: !FATAL: write-ahead logging failure
2022-01-13 11:39:10 MSG merovingian[23228]: database 'testdb' (-1) has exited with exit status 1
```

We also notice that before the crash, a new log file appears while the other is still there.
Other times, the data is flushed correctly to the store, without any crash.

We believe there could be a way here to prevent the crash without compromising write performance, since our workload only requires non-conflicting inserts (e.g., READ UNCOMMITTED isolation would suffice). However, we lack the necessary knowledge about the MonetDB internals.

**Comment by nuno-faria** [comment]
With the new group commit feature (7302f87d346232618e9f663ed82fab2e8c0eaaf8) I think this issue can be finally be closed, as performance of concurrent non-conflicting inserts is now optimized and scales linearly with the number of clients.

![imagem](https://user-images.githubusercontent.com/26089290/163599355-9cbd0b29-39b0-46be-870a-ffda78804ff2.png)

**Comment by ghost** [comment]
a little more information is highly appreciated for this great work. a 1 page blog with problem description, experiment setup and great graph:):)

**Comment by swingbit** [comment]
Great work indeed!
