### ISSUE TITLE
No generator functions working in monetdbe?

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7224]
In monetdbe (embedded), none of the examples in this documentation succeed for me: https://www.monetdb.org/documentation-Jul2021/user-guide/sql-functions/generator-functions/

The first example gives: `SELECT: no such table returning function 'generate_series'(tinyint, tinyint)`

I saw something online that suggested maybe I need to try: `SELECT generate_series...`, but that gives `SELECT: no such binary operator 'generate_series'(tinyint,tinyint)`

I'm using monetdbe version `0.11`, the latest from Pypi, if I'm not mistaken

Thanks!

**Comment by PedroTadim** [comment]
I just tested with the C API and the function is found. This must be an issue while compiling the Python version. Please continue the discussion on this issue: https://github.com/MonetDBSolutions/MonetDBe-Python/issues/162
