### ISSUE TITLE
Date calculations, bug or feature

### ISSUE THREAD

**Issue by FGroot** [MonetDB/MonetDB#7227]
See date calculations below. Is it a bug or a feature?

select cast('2021-03-29' as date)  - interval '1' month;
--Result:	2021-03-01 
--Expected:	2021-02-28

select cast('2021-05-31' as date)  + interval '1' month;
--Result:	2021-07-01 
--Expected:	2021-06-30

select cast('2020-03-29' as date)  - interval '1' year;
--Result:	2019-03-01 
--Expected:	2019-02-28

select cast('2020-02-29' as date)  + interval '1' year;
--Result:	2021-03-01 
--Expected:	2021-02-28

Affects Version/s
Jul2021

**Comment by sjoerdmullender** [comment]
Misfeature is fixed for the next feature release.
