### ISSUE TITLE
Jan2022 Docker Image has wrong version

### ISSUE THREAD

**Issue by enricomariam42** [MonetDB/MonetDB#7229]
**Describe the bug**
Jan2022 Docker Image has wrong db version 11.41.13 (Jul2021-SP2)

**To Reproduce**
docker run -d --rm --name testdb monetdb/monetdb:Jan2022
docker exec -it testdb monetdb version

results in:
MonetDB Database Server Toolkit v11.41.13 (Jul2021-SP2)

**Expected behavior**
MonetDB Database Server Toolkit v11.43.5 (Jan2022)

**Software versions**
- MonetDB version number Jan2022
- Installed from release docker image

**Issue labeling**
Docker Image
Jan2022
Severe

**Comment by sjoerdmullender** [comment]
An updated images has been uploaded.
The problem was, the build of the container was accidentally based on Fedora 33, and the lastest version of MonetDB was not built for Fedora 33 (since it's end of life).   The new image is based on Fedora 35 and includes the latest version of MonetDB.
