### ISSUE TITLE
docs for "function definitions" page / no "truncate" function

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7231]
The documentation at https://www.monetdb.org/documentation-Jul2021/user-guide/sql-programming/function-definitions/ shows an example for defining an `MS_ROUND`function. When trying to follow these examples to create my own function, there was some friction, since it seems to be interpreted as the `TRUNCATE` that empties tables, and fails. I see a `truncate` for strings, and I guess you can put quotes around it to avoid this syntax issue, but I don't see one for numbers.

Changing to the predefined `ms_trunc` might be the fix?

(Smaller point: After that, users will get the error: `CREATE OR REPLACE FUNCTION: not allowed to replace system function ms_round;`. This is better; I think most users would work around that, probably just altering the name. But you all might have a better example sitting around that works on the first attempt )

To reproduce, `SELECT truncate(100.24535, 2);` gives: `syntax error, unexpected TRUNCATE in: "prepare select truncate" `
I have only run this in monetdbe (embedded)

Thank you!

**Comment by mvdvm** [comment]
documentation page has been updated.
