### ISSUE TITLE
missing/mangled text in space/splitpart function docs

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7233]
Referring to [this page](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/string-functions/)

The example calls for the `space` and `splitpart` functions seem to have had some accident. They currently say just `select 's'` and `splitpart('a`

**Comment by sjoerdmullender** [comment]
Thanks for noticing.  This should be fixed now.  There was also a problem in the `rpad` example.
