### ISSUE TITLE
sys.reverse and not_like: no such operator error

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7234]
**Describe the bug**
1) `sys.reverse` example in [string function docs](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/string-functions/) does not succeed
2) `not_like` example in [comparison function docs](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/comparison-functions/) does not succeed

(Also, while I am here, I'm not sure the `like` patterns like `'_B%'` in the docs would qualify as "pcre", as stated. That is, wouldn't that fail in `perl` or `grep -P`?)

**To Reproduce**
 - `SELECT sys.reverse('MonetDB')` gives `SELECT: no such unary operator 'sys'.'reverse'(char)`
 - `SELECT not_like('a', '%a%')` gives `SELECT: no such binary operator 'not_like'(char,char)`

**Expected behavior**
No error

**Software versions**
 - monetdbe (embedded) version 0.11

**Comment by PedroTadim** [comment]
What MonetDBe version are you using? In the C version, sys.reverse does exist. I think MonetDBe-Python is not loading the module. For not_like, the function signature changed in Jul2021 release. I am updating the documentation

**Comment by PedroTadim** [comment]
The like operator will use cheaper string comparisons if possible at runtime. Look for the traces to see which path was chosen.

**Comment by dancromartie** [comment]
Thanks Pedro - I am using MonetDBe version 0.11, from pypi.

The root issue with `not_like` here is simply that I am passing the wrong arguments, right? To clarify, I am not particularly interested in using the function, as I lean towards `NOT LIKE '%pattern%'`, or `pcre_match`, but I randomly noticed the error.

I think the only reason I tried that function was because I doubted that it actually supported "pcre" syntax, but I wasn't able to run it at all, so I didn't get to find out. Let me know if me "looking for traces" would still help you (if that's a C/C++ debugging thing, I need to do some reading first!)

**Comment by sjoerdmullender** [comment]
The sys.reverse (and also sys.fuse) function was removed from the binary distribution starting with the Jan2022 release (11.43).  They are still available in the source code, they are just not packaged in the binaries.

I have removed these functions from the relevant documentation.

**Comment by sjoerdmullender** [comment]
By the way, see the release notes that include a hint for how you can still use the `udf` module where this `reverse` function is defined.
