### ISSUE TITLE
query with system function: "index"(varchar, boolean) fails with GDK error or assertion failure.

### ISSUE THREAD

**Issue by mvdvm** [MonetDB/MonetDB#7238]
**Describe the bug**
Select query with system function "index"(name, true) produces a GDK error:
createExceptionInternal: !ERROR: MALException:algebra.projection:GDK reported error: project1_bte: does not match always

Select query with system function "index"(name, false) triggers an assertion failure:
gdk/gdk_bat.c:2537: BATassertProps: Assertion `strcmp(b->theap->filename, filename) == 0' failed.

**To Reproduce**
compile mserver5 from Jan2022 branch and start it.
start mclient and run queries:
select name, "index"(name, true) nm_idx from sys.schemas order by nm_idx;
select name, "index"(name, false) nm_idx from sys.schemas order by nm_idx;

**Expected behavior**
+----------+--------+
| name    | nm_idx |
+======+======+
| sys       |      4 |
| tmp      |     12 |
| json      |     20 |
| profiler |     32 |
| wlc       |     48 |
| wlr        |     56 |
| logging |     64 |
+----------+--------+

**Software versions**
 - MonetDB version number: MonetDB 5 server v11.43.8 (hg id: 0768335463bb)
 - OS and version: Fedora 35
 - self-compiled with assertions enabled

**Comment by PedroTadim** [comment]
We removed these functions on pushcands. We can remove them on default.

**Comment by sjoerdmullender** [comment]
Fixed in Jan2022 branch.  We should probably indeed remove these on the default branch.
