### ISSUE TITLE
Documention for lateral joins

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7239]
I was unable to find any documentation on lateral joins in the main Monet docs site. Is there any? Is it a fully-endorsed feature the team wants to publicize? There was a mention of fixing a crash related to lateral joins in the release notes, so I started looking.

I found some example on a [mailing list](https://www.monetdb.org/pipermail/users-list/2018-June/010259.html), but it took a while to find, once I tried another search engine. It was only one example, so I'm not sure if there are additional ways to use lateral joins. (Small point: this mailing list example wasn't directly usable in embedded Monet, since `generate_series` is broken). I did get something working after ~20 minutes.

I don't have any urgent need for these joins, and I'm more just playing around and taking mental inventory of what is supported by Monet vs Postgres, which I am most familiar with.

Thanks for all your help lately!

**Comment by mvdvm** [comment]
See [SELECT query FROM clause syntax](https://www.monetdb.org/documentation/user-guide/sql-manual/data-manipulation/table-expressions/#from-clause)
