### ISSUE TITLE
documentation issues for "merge table" and "merge into"

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7242]
I was revisiting table partitioning, got mixed up briefly, and took notes on the confusion.

### Incomplete syntax?

In https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-definition/merge-tables/, I think the syntax explanation for `ALTER TABLE ... ADD TABLE` is missing the `AS PARTITION` part. Should it be the following?

```
    ALTER TABLE [ IF EXISTS ] [ schema_name . ] merge_table_name
        ADD TABLE [ schema_name . ] table_name
        [ AS PARTITION  partition_spec ] 
```

### Link to examples for partitioning

Might I suggest that the [merge table](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-definition/merge-tables/) docs page links to the nice [updatable merge tables](https://www.monetdb.org/documentation-Jan2022/user-guide/blog-archive/update-mergetables/) blog post, since the former has no examples and the latter has many? Maybe just something like "for examples, see this blog post". I later saw there are other links leading there in the "SQL Summary" section, but when moving through "Data Definition", I spent much time trying to make sense of the (probably incomplete) syntax in issue 1.

### Merge statement content on merge tables page
In https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-definition/merge-tables/, there is general information and also syntax explanations for `MERGE INTO`. I assume this is meant for https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-manipulation/merge-statement/ instead. 

Perhaps it could read "Merge/partitioned tables have no relationship with the `MERGE INTO` command. For info on `MERGE INTO`, see this link"

### Wrong link, link consistency, and preferred sources

This one is a little twisty and maybe not super useful, but I'll submit it anyways. In https://www.monetdb.org/documentation-Jan2022/user-guide/sql-summary/, you could review these:

 - text `CREATE MERGE TABLE` leads to [merge statement docs](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-manipulation/merge-statement/) (wrong topic)
 - text `ALTER TABLE ADD TABLE`, leads to [alter statement docs](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-definition/alter-statement/) (see next bullet)
 - text `ALTER TABLE ADD TABLE`, leads to [merge table docs](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-definition/merge-tables/) (see previous bullet)

For bullets 2 &3, it's a question of what's preferred, but there's a 3rd option of linking to the `ALTER TABLE ADD TABLE` [section within the same page](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-summary/#alter-table-add-table). At least currently, given issue 1, this within-the-page option is the only one leading the user to the full syntax they need.

**Comment by Giovanni-Valcarenghi** [comment]
Thank you @dancromartie for noticing and reporting the issues. We have updated the pages accordingly.
