### ISSUE TITLE
documentation for soundex difference is backwards

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7243]
According to the [string function docs](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/string-functions/), the `difference` function:

> converts two strings s1 and s2 to their soundex codes and reports the number of matching code positions. Since soundex codes have four characters, the result ranges from zero to four, with zero being no match and four being an exact match

I think this should say "reports the number of differing code positions", and "zero being an exact match and four being no match"

```
-- 0 is exact match
SELECT soundex('bare') s1, soundex('bear') s2, difference('bare', 'bear') d

s1 | s2 | d
-- | -- | --
B600 | B600 | 0
```

Since this was my first time exploring soundex, I also found the example `difference('MonetDB', 'DB3')` (result=4) a tad confusing. I thought:  "these strings have some similarity, why is the score at an extreme?". Maybe `difference('frowned', 'around')` (result=1) better shows the usefulness of soundex.

**Comment by kutsurak** [comment]
fixed: https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/string-functions/
