### ISSUE TITLE
Using MonetDb\e in C#

### ISSUE THREAD

**Issue by dawningtruth** [MonetDB/MonetDB#7244]
Our app and system is running in C# on .Net Core, we would like to use the embedded version of MonetDB i.e. MonetDB\e. Essentially we would like to use MonetDB\e as an alternative to SQLite.
 
Any thoughts on how this could be accomplished?

**Comment by yzchang** [comment]
Unfortunately, there is no MonetDB/e for C#, yet.  Also, it's not on MonetDB's road map for the near future.  Some alternatives are:
* Use MonetDB/e for Python or Java
* Package a MonetDB server with your application to run it locally, then the application can connect to it using MonetDB's C# driver
* A DIY action to embed the MonetDB/e C-library in C#.
* Get MonetDB Solutions' commercial support for on-demand feature development.
