### ISSUE TITLE
monetdbe silently importing 0 rows, at random

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7245]
(I'm having a lot of fun with Monet, by the way! Seems like a great project)

**Describe the bug**

I found that one table I was I recreating repeatedly with identical data, via a cronjob, was sometimes populated and sometimes empty when I opened it back up. No errors are printed, and all scripts finish smoothly.

My conclusion is: the tables randomly appear empty to connections opened in a new process from the one that imported the table, but always return data when queried from the same process, even if the connection is closed and reopened.

See expected behavior section for some statistics.

**To Reproduce**
Reproducible via attached scripts.

There are 3 data files involved here, and I'm not sure how/if they are interacting to cause this. (It took me ~4 hours to shrink my real-world issue down to something simpler and to find a small subset of input data that would reproduce it, but I give up on determining the exact cause) I bet you all have some better debugging tools than I do!

- Unpack the `.tar.gz` file
- Run `bash create_data.sh`. This will download 1 CSV with `curl` and generate 2 other trivial files with `python` and `echo`.  (Total data ~100MB and ~700k rows). Of particular interest is the fake `query_profiling.csv`, which has 7 records
- Then run `bash loop.sh | tee loop_output.txt`. This imports the 3 tables, and counts the rows in `query_profiling` 2 different ways, 100 times. It's about 5 seconds per loop.

**Expected behavior**
After running `loop.py`, I saw these results (`loop_output_stats.txt` in the tar, produced from `loop_output_example.txt`):

```
    100 Row count from 'plain' python: 7
     78 Row count from subprocess: 0
     22 Row count from subprocess: 7
```

I expected: all 100 runs find 7 rows via both methods
Actual: only 22 of 100 "subprocess" runs find 7 rows, while 100 of 100 "plain python" runs find 7 rows

**Software versions**
 - monetdbe 0.11 from pip
 - both Ubuntu 20.04 and a derivative of 21.10

**Issue labeling **

**Additional context**
In my experiments, I believe there are 2 things that can each work around this, but I'm not sure why, and I don't have hard data on it yet.
1) closing and reopening the connection after line 24 in `make_tables.py`. That's surprsing though, since there is a `conn.close()` on the last line.
2) as mentioned above, not starting a new process, but that's not really an option in practice

[monetdbe_random_import_fail.tar.gz](https://github.com/MonetDB/MonetDB/files/8029615/monetdbe_random_import_fail.tar.gz)

**Comment by njnes** [comment]
has been fixed overtime...
