### ISSUE TITLE
Time Series Interpolation

### ISSUE THREAD

**Issue by AKheli** [MonetDB/MonetDB#7246]
I am trying to perform upsampling on time series data. This is supposed to guarantee to have one value each a given period of time. For example a value each minute, so if there's a lag in the data the query would fill it with some gap filling strategy (interpolation, last value, zero, null, etc.).

I found some reference to interpolation in a [previous release](https://www.monetdb.org/documentation-Jan2022/admin-guide/release-notes/mar2018/) but it wasn't very concrete. Is there a possibility to interpolate time series on MonetDB?

**Comment by yzchang** [comment]
Can you give an example of how the data looks like and the computation you want to do?  Some pseudo code can be very helpful.

**Comment by AKheli** [comment]
Sure. We want to perform gap filling based on the time durations and not on the number of values, because we assume that our data isn't necessarily regular. 

So for example I want a value every 5 seconds in a generally 10 second granularity time series. What I expect is that a value is inserted each 5 second gap if there's a gap. If there isn't such a gap, then the upsampling wouldn't be done. If the gap is larger (1 full minute blackout with no values for example), then the query should insert a value for each 5 seconds in the interval to fill the gap:

Example:
> ts1 = {1: 3.0, 2: 5.0, 5: -1.0}, and filler = 0.0.
> Filling with 0:{1: 3.0, 2: 5.0, 3: 0.0, 4: 0.0, 5: -1.0}
> Filling with interpolation:{1: 3.0, 2: 5.0, 3: 3.0, 4: 1.0, 5: -1.0}

**Comment by AKheli** [comment]
Hello, this is more detailed example of the upsampling query. 

The example is about a dataset where the observations are monthly and that we want the daily information. We would have to upsample the frequency from monthly to daily and use an interpolation scheme to fill in the new daily frequency.

Upsampling would have to group records when downsampling and making space for new observations when upsampling. This could be used to transform our monthly dataset into a daily dataset by calling resampling and specifying the preferred frequency of calendar day frequency or “D”.

This is what the original data looks like: 

> Month Value
> 1901-01-01 266.0
> 1901-02-01 145.9
> 1901-03-01 183.1
> 1901-04-01 119.3
> 1901-05-01 180.3

Upsampling the data to daily with filling with NULL strategy would result the following data: 

> Month Value
> 1901-01-01 266.0
> 1901-01-02 NULL
> 1901-01-03 NULL
> 1901-01-04 NULL
> 1901-01-05 NULL
> 1901-01-06 NULL
> 1901-01-07 NULL
> 1901-01-08 NULL
> 1901-01-09 NULL
> 1901-01-10 NULL
> 1901-01-11 NULL
> 1901-01-12 NULL
> 1901-01-13 NULL
> 1901-01-14 NULL
> 1901-01-15 NULL
> 1901-01-16 NULL
> 1901-01-17 NULL
> 1901-01-18 NULL
> 1901-01-19 NULL
> 1901-01-20 NULL
> 1901-01-21 NULL
> 1901-01-22 NULL
> 1901-01-23 NULL
> 1901-01-24 NULL
> 1901-01-25 NULL
> 1901-01-26 NULL
> 1901-01-27 NULL
> 1901-01-28 NULL
> 1901-01-29 NULL
> 1901-01-30 NULL
> 1901-01-31 NULL
> 1901-02-01 145.9


The upsampling function has created the rows by putting NULL values in the new values. We can see we still have the values of January and February from the original data.

We can now interpolate the missing values at this new frequency. A simple approach is the linear interpolation. This draws a straight line between available data, in this case on the first of the month, and fills in values at the chosen frequency from this line. The resulted data would something like this: 

> Month Value
> 1901-01-01 266.000000
> 1901-01-02 262.125806
> 1901-01-03 258.251613
> 1901-01-04 254.377419
> 1901-01-05 250.503226
> 1901-01-06 246.629032
> 1901-01-07 242.754839
> 1901-01-08 238.880645
> 1901-01-09 235.006452
> 1901-01-10 231.132258
> 1901-01-11 227.258065
> 1901-01-12 223.383871
> 1901-01-13 219.509677
> 1901-01-14 215.635484
> 1901-01-15 211.761290
> 1901-01-16 207.887097
> 1901-01-17 204.012903
> 1901-01-18 200.138710
> 1901-01-19 196.264516
> 1901-01-20 192.390323
> 1901-01-21 188.516129
> 1901-01-22 184.641935
> 1901-01-23 180.767742
> 1901-01-24 176.893548
> 1901-01-25 173.019355
> 1901-01-26 169.145161
> 1901-01-27 165.270968
> 1901-01-28 161.396774
> 1901-01-29 157.522581
> 1901-01-30 153.648387
> 1901-01-31 149.774194
> 1901-02-01 145.900000

We want to do something like that in MonetDB. Probably in a lesser scale, i.e. to fill the gap created by a missing values in a small window instead of upsampling the whole dataset. But I think the underlying principle is the same.

**Comment by mvdvm** [comment]
MonetDB currently has no built-in system functions or procedures to do this kind of data upsampling which synthesizes missing tuples and insert them. You will need to design and built this yourself. This is possible in SQL in MonetDB.
Your could also put the SQL statements into a user defined procedure or function for easy invocation.

I consider this as a user community question/help, not an issue of MonetDB, so closing this issue.
