### ISSUE TITLE
"Cannot use non GROUP BY column in query results without an aggregate function" when using two aggregate functions side-by-side

### ISSUE THREAD

**Issue by AKheli** [MonetDB/MonetDB#7247]
I  want to aggregate the average and the standard deviation of the same column and have them side-by-side in the results. However, this is giving me the following exception: `!SELECT: cannot use non GROUP BY column 'ph' in query results without an aggregate function`. The aggregations work fine separately but when joined in a same select statement this exception persists. 

I found a similar previous [issue](https://github.com/MonetDB/MonetDB/issues/6624) that's marked as resolved but I couldn't find my solution there. 

> sql>SELECT
>        avg(pH) ,
>        stddev(pH)
>    FROM
>        datapoints;
> MAPI  = (monetdb) /tmp/.s.monetdb.54320
> ERROR = !SELECT: cannot use non GROUP BY column 'ph' in query results without an aggregate function
> CODE  = 42000

**Comment by PedroTadim** [comment]
The aggregate 'stddev' doesn't exist. We have 'stddev_samp' and 'stddev_pop' instead. However the error message is indeed wrong. We have to fix it.

**Comment by AKheli** [comment]
Thanks @PedroTadim!
