### ISSUE TITLE
"Cannot use non GROUP BY column 'id_station' in query results without an aggregate function" when using an aggregate function is used with an attribute selection

### ISSUE THREAD

**Issue by AKheli** [MonetDB/MonetDB#7248]
I want to aggregate the average and the standard deviation of the same column and have them side-by-side in the results. However, this is giving me the following exception: `Cannot use non GROUP BY column 'id_station' in query results without an aggregate function`. The aggregations work fine separately but when joined in a same select statement this exception persists.

I found a similar previous https://github.com/MonetDB/MonetDB/issues/6624 that's marked as resolved but I couldn't find my solution there.

```
sql>SELECT
   id_station,
   avg(pH) as mean
FROM
   datapoints;
MAPI  = (monetdb) /tmp/.s.monetdb.54320
ERROR = !Cannot use non GROUP BY column 'id_station' in query results without an aggregate function
CODE  = 42000
```

**Comment by l1t1** [comment]
SELECT
   id_station,
   avg(pH) as mean
FROM
   datapoints group by id_station ;
