### ISSUE TITLE
ask before overwrite

### ISSUE THREAD

**Issue by MitchellWeg** [MonetDB/MonetDB#7251]
When importing a SQL file, the `\>` & `\<` can be mixed up, resulting in the immediate overwriting of the file. 
Mclient should ask if the user wants to overwrite the file.

Example, using the VOC example:

` \> /full/path/to/voc_dump.sql` overwrites the file, instead of reading it.

**Comment by njnes** [comment]
At best this feature could be added with a user setting. Ie I think the current behaviour is what we want, but given some user setting this could be protected with the additional question.
