### ISSUE TITLE
[Memory Issue] Memory increases rapidly when use COALESCE on where clause

### ISSUE THREAD

**Issue by merqury7** [MonetDB/MonetDB#7255]
## Describe the bug
The following phenomenon occurs when using a merge table composed of a remote table.
If the `WHERE` clause is configured using the `COALESCE` function in the SQL `SELECT` clause, the memory of the server where the merge table is located is rapidly occupied.
When query 1 below is executed, the memory increases rapidly and then comes down again as shown in Figures 1-3.

The Merge table `store.DATA_20210428_151721_190` has 113,670,794 rows

#### Query 1
``` sql
  select idx,
        '*' as category,
         COALESCE(CAST(op_unique_carrier AS TEXT),'[Null]') as colorby,
         op_unique_carrier as op_unique_carrier_colorby ,
         COALESCE(fl_date, cast('1970-01-01 00:00:00.000' as timestamp)) as xvalue,
         COALESCE(dep_delay, 0.0) as yvalue
   from store.DATA_20210428_151721_190
   where 1=1
   and COALESCE(dep_delay,50) >= 10
   and COALESCE(dep_delay,50) < 1700
```
   
   
[Figure 1- Before SQL Execution]
![image](https://user-images.githubusercontent.com/81399392/155061093-9f6679e9-7798-4e5b-9ccf-e331f91312a1.png)

[Figure 2- SQL Execution: Memory Increase]
![image](https://user-images.githubusercontent.com/81399392/155061110-742f6625-2b61-4147-ac60-9de9a2e340ed.png)

[Figure 3-After SQL execution: memory reduction]
![image](https://user-images.githubusercontent.com/81399392/155061132-080745e0-acec-4493-8fbc-369271edadd9.png)

When query 1 is executed simultaneously with different `WHERE` conditions, the server hangs due to insufficient memory as shown in Figure 4, and the MonetDB server must be restarted for the service to return to normal. However, under the same load conditions, there is no problem in the older version of MonetDB, 11.41.5 (Jul2021) As Figure 5.
In case of simultaneous load conditions, the comparison data of the two servers is attached. (They are different servers, but the memory requirements are the same.)

[Figure 4 : MonetDB 11.43.9]
<img src="https://user-images.githubusercontent.com/81399392/155061166-db478fd3-95ff-4cb9-a598-647975455824.png">

[Figure 5 : MonetDB 11.41.5]
![image](https://user-images.githubusercontent.com/81399392/155061275-2080ddc5-1a61-4ee9-9693-563ad068b149.png)

If `COALESCE` is removed from query 1 and executed as in query 2, the above phenomenon does not occur.

##### Query 2
``` sql
  select idx,
        '*' as category,
         COALESCE(CAST(op_unique_carrier AS TEXT),'[Null]') as colorby,
         op_unique_carrier as op_unique_carrier_colorby ,
         COALESCE(fl_date, cast('1970-01-01 00:00:00.000' as timestamp)) as xvalue,
         COALESCE(dep_delay, 0.0) as yvalue
   from store.DATA_20210428_151721_190
   where 1=1
   and dep_delay >= 10
   and dep_delay < 1700
```

## Reproduction
By using the `WHERE` conditional clause containing the `COALESCE` function on the merge table consisting of a remote table containing more than 100 million data

``` sql
  select idx,
        '*' as category,
         COALESCE(CAST(op_unique_carrier AS TEXT),'[Null]') as colorby,
         op_unique_carrier as op_unique_carrier_colorby ,
         COALESCE(fl_date, cast('1970-01-01 00:00:00.000' as timestamp)) as xvalue,
         COALESCE(dep_delay, 0.0) as yvalue
   from store.DATA_20210428_151721_190
   where 1=1
   and COALESCE(dep_delay,50) >= 10
   and COALESCE(dep_delay,50) < 1700

```

## Expected behavior
There should be no memory growth as in MonetDB 11.41.5 (Jul2021).

## Screenshots
All attached to the text.

## Software versions
 - MonetDB version number : MonetDB 5 server 11.43.9 (Jan2022-SP1)
 
``` bash
  [root@beestore ~]# mserver5 --version
MonetDB 5 server 11.43.9 (Jan2022-SP1) (64-bit, 128-bit integers)
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2022 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 31.2 GiB available memory, 16 available cpu cores
Libraries:
  libpcre: 8.32 2012-11-30
  libxml2: 2.9.1
Compiled by: mockbuild@14f3eb203288488dbd3f167a3ec87b16 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs =/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic
Linking: /usr/bin/ld

```
 
## OS and version
CentOS Linux release 7.4.1708 (Core)
 
## Installation from release package or self-installed and compiled
Installed from release package

## Issue labeling 
Memory Issue

**Comment by PedroTadim** [comment]
Comparing the traces of the query between the two versions could be a nice start to look for the issue.

**Comment by aris-koning** [comment]
@merqury7 I hope you don't mind that I amended your bug report a bit. You might want to try to minimize the problem somewhat.  From your top output there are multiple remote mserver5's in the mix as far as I can tell.  See if you can get this reproduced on a single machine without a remote table and/or using a simple(r) table definition and/or queries. Also please add your table definitions to the report description. The problem has to be a bit more concise and self-contained for us to work with.

**Comment by njnes** [comment]
for these kinds of problems output of the query prefixed with plan is needed. See https://www.monetdb.org/documentation-Dec2023/admin-guide/debugging-features/plan-sql-stmt/
