### ISSUE TITLE
Encrypted Password Request

### ISSUE THREAD

**Issue by maniVadlamudi** [MonetDB/MonetDB#7257]
**Is your feature request related to a problem? 
We created a user with SHA512 Hash key encrypted password, While to trying to connect the same using mclient its not taking the has password and getting invalid credentials. Please help on how the encrypted password feature works in monet.

**Describe the solution you'd like**
I need to get info about how to connect to database user using encrypted password and how the password encryption works.

**Comment by mvdvm** [comment]
See [documentation/user-guide/sql-manual/data-definition/privileges/)](https://www.monetdb.org/documentation/user-guide/sql-manual/data-definition/privileges/)
When the ENCRYPTED clause is given for PASSWORD, a hashed form of the password has to be supplied. The type of this hash depends on how the server was configured, but defaults to SHA512.

**Comment by joerivanruth** [comment]
> See [documentation/user-guide/sql-manual/data-definition/privileges/)](https://www.monetdb.org/documentation/user-guide/sql-manual/data-definition/privileges/) When the ENCRYPTED clause is given for PASSWORD, a hashed form of the password has to be supplied. The type of this hash depends on how the server was configured, but defaults to SHA512.

I agree with the above. The type of hash indeed defaults to SHA512 but can be overridden at compile time using the -DPASSWORD_BACKEND option. Nobody ever changes this of course, but if you want to be really sure you can examine the manual page monetdbd.1 included in your installation. It mentions the hash algorithm in passing in the description of the `monetdbd set passphrase=` command:

```
       passphrase
              . . .  Note that the only hash accepted is the
              one specified at configure time, which is SHA512 . . .
```

Now, as for mclient not accepting the credentials, when you compute the hash of the password you must make really sure that you're not accidentally including any spurious whitespace. For example, the bash command
```
$ echo mypassword | sha512sum 
32f73fbcf845201857499061db1d50326ce6cbce9d7b9650ad2f301a9f263d02553b5e3d08a940456e97267bc9d4c10d8903e6378803257223a84140db0ad5cc  -
```
includes the newline added by 'echo' into the hash, so the hash is wrong. What you need to do is:
```
$ echo -n mypassword | sha512sum
a336f671080fbf4f2a230f313560ddf0d0c12dfcf1741e49e8722a234673037dc493caa8d291d8025f71089d63cea809cc8ae53e5b17054806837dbe4099c4ca  -
```
The -n option suppresses the newline.

For example, the password 'mypassword' encrypted above works in the following session:
```
sql>CREATE USER myuser WITH ENCRYPTED PASSWORD 'a336f671080fbf4f2a230f313560ddf0d0c12dfcf1741e49e8722a234673037dc493caa8d291d8025f71089d63cea809cc8ae53e5b17054806837dbe4099c4ca' NAME 'My User';
operation successful
sql>
» mclient -d demo -u myuser
password: mypassword
Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)

```
