### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by HiramTheHero** [MonetDB/MonetDB#7261]
**Describe the bug**
Certain error message for CREATE TABLE query is not descriptive and doesn't explain the actual error.

**To Reproduce**
Run the following in an mclient sql shell.
```
create table some_table (
TransId bigint,
AssessorParcelNumber varchar(50),
APNIndicatorStndCode varchar(1),
TaxIDNumber varchar(50),
TaxIDIndicatorStndCode varchar(1),
UnformattedAssessorParcelNumber varchar(50),
AlternateParcelNumber varchar(50),
HawaiiCondoCPRCode varchar(4),
PropertyHouseNumber varchar(13),
PropertyHouseNumberExt varchar(10),
PropertyStreetPreDirectional varchar(2),
PropertyStreetName varchar(50),
PropertyStreetSuffix varchar(6),
PropertyStreetPostDirectional varchar(2),
PropertyBuildingNumber varchar(45),
PropertyFullStreetAddress varchar(80),
PropertyCity varchar(45),
PropertyState varchar(2),
PropertyZip varchar(15),
PropertyZip4 varchar(4),
OriginalPropertyFullStreetAddress varchar(100),
OriginalPropertyAddressLastline varchar(100),
PropertyAddressStndCode varchar(1),
LegalLot varchar(100),
LegalOtherLot varchar(100),
LegalLotCode varchar(2),
LegalBlock varchar(50),
LegalSubdivisionName varchar(200),
LegalCondoProjectPUDDevName varchar(100),
LegalBuildingNumber varchar(45),
LegalUnit varchar(100),
LegalSection varchar(100),
LegalPhase varchar(50),
LegalTract varchar(50),
LegalDistrict varchar(45),
LegalMunicipality varchar(50),
LegalCity varchar(50),
LegalTownship varchar(50),
LegalSTRSection varchar(100),
LegalSTRTownship varchar(15),
LegalSTRRange varchar(15),
LegalSTRMeridian varchar(35),
LegalSecTwnRngMer varchar(165),
LegalRecordersMapReference varchar(100),
LegalDescription varchar(2000),
LegalLotSize varchar(14),
PropertySequenceNumber int,
PropertyAddressMatchcode varchar(1),
PropertyAddressUnitDesignator varchar(10),
PropertyAddressUnitNumber varchar(25),
PropertyAddressCarrierRoute varchar(4),
PropertyAddressGeoCodeMatchCode varchar(1),
PropertyAddressLatitude varchar(15),
PropertyAddressLongitude varchar(15),
PropertyAddressCensusTractAndBlock varchar(16),
PropertyAddressConfidenceScore tinyint,
PropertyAddressCBSACode int,
PropertyAddressCBSADivisionCode int,
PropertyAddressMatchType int,
PropertyAddressDPV varchar(1),
PropertyGeocodeQualityCode varchar(50),
PropertyAddressQualityCode varchar(10),
FIPS varchar(5),
LoadID bigint,
ImportParcelID bigint,
BKFSPID int,
AssessmentRecordMatchFlag tinyint,
BatchID int,
);
```
Produces the following error text in the mclient shell.
`syntax error in: "create table junk_db (
transid bigint,
assessorparcelnumber varchar(50),
apnindi"`

**Expected behavior**
The actual error is that there is a `,` after the final item in the create statement when there shouldn't be.

**Screenshots**
<img width="1264" alt="Screen Shot 2022-03-04 at 8 58 30 AM" src="https://user-images.githubusercontent.com/22198719/156796941-4b47ff72-a26a-43ce-8483-ab944cfa3097.png">

**Software versions**
 - MonetDB version number: MonetDB Database Server Toolkit v11.43.9 (Jan2022-SP1)
 - OS and version: Mac OS Monterey
 - Installed from release package.

**Comment by sjoerdmullender** [comment]
To get a somewhat better error message from bison, we could add `%define parse.error detailed` to the sql_parser.y file (near `%define api.pure`).  I have tried that in the past, but I don't remember why I didn't commit that.  Probably because some older bison versions that we need to support don't recognize it.

**Comment by njnes** [comment]
the current error is cleaner.
syntax error, unexpected ')', expecting FOREIGN or PRIMARY or UNIQUE in: "create table some_table (
transid bigint,
assessorparcelnumber varchar(50),
apni"

We added '  %define parse.error verbose    ' .
