### ISSUE TITLE
Database Inaccessible

### ISSUE THREAD

**Issue by HiramTheHero** [MonetDB/MonetDB#7262]
**Describe the bug**
I was performing the following operation on a large table:
```
UPDATE table SET column = replace(column, '.', '');
```
Then the database was taking an extremely long time to complete the operation (far longer than it should have), and I couldn't connect another client to the database. To free up my CPU (which was being maxed out by mserver5) I had to send a SIGKILL to the process. Now, whenever I start the database:
```
monetdb start database
```
mserver5 just maxes out my CPU, and the message:
```
starting database 'database'...
```
just stays on my terminal. If I kill that command, mserver5 continues to max out my CPU usage. If I restart the server, I can't connect to the database by running the `mclient -d database` command.

These were the last lines of the mdbtrace.log file before the issues started happening:
```
2022-03-04 13:01:55    M_ERROR MAL_SERVER client1              monetdb5/mal/mal_exception.c:104               createExceptionInternal SQLException:sql.resultSet:45000!Result set construction failed: stream Server write: socket write: Broken pipe
2022-03-04 13:13:45    M_ERROR MAL_SERVER client4              monetdb5/mal/mal_exception.c:104               createExceptionInternal SQLException:sql.resultSet:45000!Result set construction failed: stream Server write: socket write: Broken pipe
```
When I start the server again this appears in the merovingian.log file (note that there isn't any output after the mserver5 command):
```
2022-03-05 13:32:42 MSG control[1522]: (local): served status list
2022-03-05 13:32:42 MSG merovingian[1522]: database 'maapl_project' has crashed after start on 2022-03-05 13:16:54, attempting restart, up min/avg/max: 26m/1h/3h, crash average: 1.00 1.00 0.60 (22-4=18)
2022-03-05 13:32:43 MSG maapl_project[1790]: arguments: /opt/homebrew/Cellar/monetdb/11.43.9/bin/mserver5 --dbpath=/Volumes/external_drive/monetdb_test/maapl_project --set merovingian_uri=mapi:monetdb://A-Computer.local:50000/maapl_project --set mapi_listenaddr=none --set mapi_usock=/Volumes/external_drive/monetdb_test/maapl_project/.mapi.sock --set monet_vault_key=/Volumes/external_drive/monetdb_test/maapl_project/.vaultkey --set gdk_nr_threads=8 --set max_clients=64 --set sql_optimizer=default_pipe
```

And mserver5 starts to max out my CPU. I can't connect to the database in any way (msqldump also doesn't work). The only way to shut down the server is by sending a SIGKILL to the process. I can send the database into maintenance mode, but it is inaccessible even then. Even from the DBA (monetdb) account.

What more information would help with addressing the bug? I can send the log files if necessary. Thank you for this product. I'm excited to keep using it. (It is a bit unfortunate that I am locked out of my data though.) 

**To Reproduce**
I have no idea how the error happened. I ran the command `UPDATE table SET column = replace(column, '.', '');` on another test database I made, but it didn't cause any issues.

**Expected behavior**
The server doesn't have any issues and I'm not locked out of using it.

**Software versions**
 - MonetDB version number [a milestone label]: MonetDB 5 server v11.43.9 (Jan2022-SP1)
 - OS and version: Mac OS (ARM/M1)
 - Installed from release package or self-installed and compiled: Obtained from Homebrew.

**Comment by aris-koning** [comment]
I have done some similar experiments with 100K to 10M records in a string column. On my system Jan2022 it seems to scale nicely. But perhaps you are reaching the limits of your memory resources with the (intermediate) results for this computation. You might prepend your query with the TRACE keyword to get the physical MAL plan and its compute times.

**Comment by yzchang** [comment]
Since you killed the server during a long-running update, the server probably has process large WAL files during the restart.  What's the output of `$ du -sh /Volumes/external_drive/monetdb_test/maapl_project/sql_logs/`?

To have a better understanding of the long-running time of the UPDATE query:
1. how many records does the `column` column contain?  How many unique strings?  What are the min, max and avg length of the strings?
2. how many CPUs and how much memory does your system have?

**Comment by HiramTheHero** [comment]
Thank you for the suggestion @aris-koning.
However, I'm not sure how that would help me regain access to my database. I can't access the database through any client service to run a TRACE command to get the compute times. Also, before I ran the `UPDATE table SET column = replace(column, '.', '');` command and the system locked up, I did the operation on the newly created column and it performed the query very quickly. (That's why in my initial post I claim that the operation was taking too long.)

Are there any suggestions on how I can reclaim access to the database?

(I also created a test database and after some time of using it I ran into the 
```
2022-03-05 22:23:06    M_ERROR MAL_SERVER client6              monetdb5/mal/mal_exception.c:104               createExceptionInternal SQLException:sql.resultSet:45000!Result set construction failed: stream Server write: socket write: Broken pipe
```
error again and that database is also inaccessible. The only error the new database shows is
```
2022-03-07 06:34:17    M_ERROR GDK      main thread          gdk/gdk_bbp.c:876                              BBPcheckbats         file /Users/a;sldfkjasldkf/test_monet/test_monet/bat/03/377.tail1 too small (expected 24806671, actual 0)
```

Is there a way to resolve the 
```
2022-03-05 22:23:06    M_ERROR MAL_SERVER client6              monetdb5/mal/mal_exception.c:104               createExceptionInternal SQLException:sql.resultSet:45000!Result set construction failed: stream Server write: socket write: Broken pipe
```
error? It seems to have happened on both of my databases.

@yzchang, when I run `du -sh /Volumes/external_drive/monetdb_test/maapl_project/sql_logs/` I get the following output:
```
12K	/Volumes/external_drive/monetdb_test/maapl_project/sql_logs/
```
I'm not sure if there is a WAL file it is trying to read from. I can't find any. As I mentioned before, the UPDATE query didn't take nearly as long (maybe around 10 seconds) when I ran it on a column I created. (I was testing to see if there was a performance difference between updating data in-place on the same column vs a newly created column on the table.)

1. There were about 158,000,000 records in the column. There were thousands of unique strings. (The column contained US census tracts and block groups in the format of `#######.####` varying in the digits on both sides of the period. There were many records that contained `null` values. Min string length was 1 character long, the max length was probably around 30 characters long, average character length was, probably, 15 characters long. The data is extremely messy. I was in the process of cleaning it up.
2. I have an M1 Macbook Pro. According to this [link](https://en.wikipedia.org/wiki/Apple_M1), it has 8 processors at 3.2 GHz. I have 16 GB of RAM. I've never seen `monetdb`,`mserver5`, nor `monetdbd` take up more than 2 - 3 GB of ram during a certain process. I am running the database on a 1 TB external drive. So storage space wasn't an issue either.

Thank you all, again, for your help. I hope I can get access to my database soon.

**Comment by yzchang** [comment]
WAL files are those log* files in sql_logs/sql.  With just 12K, an mserver5 restart shouldn't take long...

Q1. I'm a bit confused by your above reply.  What exactly do you mean with "updating data in-place on the same column vs a newly created column on the table"?

Q2. What (update) queries have you run on this column before this UPDATE?  Can you give us those queries (needed by Q3 below)?

Q3. I'd like to try to reproduce your problem (since I also have a Jan2022-SP1 installed using Homebrew).  Can you maybe upload the (anonymised) data for this column and the CREATE TABLE statement?

**Comment by sjoerdmullender** [comment]
I'm not sure there is a bug here, other than that it takes a long time.
What happens (should be happening with the current code) is that the UPDATE query runs, and at some point it has calculated the updated values.  Then it applies those values to the table.  The updates are written to the write-ahead log (WAL), and at the end of that the commit marker is written, making this a "permanent" change.  At some point after that, the bats comprising the table are updated.  If there aren't any other transactions going on, that most likely happens right away.  And here is where the problems start.  To update the bats, the so-called store lock must be held, and this can take (too) long.  This lock is also (briefly) needed by a connecting client.  And because the client has to wait for the lock, it looks as if you can't connect.
When you kill the server at this point, it will have to do basically the same update during startup, so that too will also take a long time.

**Comment by PedroTadim** [comment]
I think I got a race condition with concurrent updates some time ago, but we didn't have time to fix it back then.

**Comment by HiramTheHero** [comment]
@yzchang, thank you for the explanation of the WAL files.

**Q1. I'm a bit confused by your above reply. What exactly do you mean with "updating data in-place on the same column vs a newly created column on the table"?**

I ran the following procedure (via the mclient program) before the database crashed and it only took about 10 seconds to complete.

```
-- Added a column.
ALTER TABLE co_za_main ADD test_column varchar(100);

-- Putting New values into it.
UPDATE co_za_main SET test_column = replace(propertyaddresscensustractandblock, '.', '');
```

I then wondered if there was any time variance between putting the data into a new column (as shown above) vs updating the column that is processed by the function. So, I did the following:
```
UPDATE co_za_main SET propertyaddresscensustractandblock = replace(propertyaddresscensustractandblock, '.', '');
```

And the procedure was taking longer than several minutes.

**Q2. What (update) queries have you run on this column before this UPDATE? Can you give us those queries (needed by Q3 below)?**

I didn't run any update queries on the column before I ran the
```
UPDATE co_za_main SET propertyaddresscensustractandblock = replace(propertyaddresscensustractandblock, '.', '');
```
command.


**Q3. I'd like to try to reproduce your problem (since I also have a Jan2022-SP1 installed using Homebrew). Can you maybe upload the (anonymised) data for this column and the CREATE TABLE statement?**

I apologize, but I can't upload the data because it is proprietary data and I am under contract not to share it in any form. I did run the following on my machine and it updated the columns correctly without freezing up the server.

```
monetdbd create ~/test_monet
monetdb create db
monetdb release db

/*
In my ~/.monetdb file I have the following:
user=monetdb
password=monetdb
*/
mclient -d db

CREATE TABLE test_table (
PropertyAddressCensusTractAndBlock varchar(100)
);

COPY INTO test_table( 
PropertyAddressCensusTractAndBlock
)
FROM '/Users/person/Documents/data.csv' ON CLIENT
USING DELIMITERS '|', E'\n', '"'
NULL AS '';

UPDATE test_table SET propertyaddresscensustractandblock = replace(propertyaddresscensustractandblock, '.', '');
```

That being said, I probably have nothing else to help troubleshoot the issue.

@sjoerdmullender and @PedroTadim,

When I restart the server it maxes out my CPU and it seems that nothing is happening. The server has been running non-stop for over 30 minutes. I find it hard to believe that a procedure that normally takes less than 10 seconds is needing 30 minutes to run. It seems to be behaving as if a race condition is occurring. Unfortunately, I don't believe I have much more information to send over to help troubleshoot the issue. (Besides the merovingian.log and mdbtrace.log files.)

**Comment by yzchang** [comment]
Q1 & Q2: that clarifies. I can't think of anything immediately that might explain the time difference though.  A quick check of the physical query exec. plan shows two almost identical plans: the only difference (as expected) is where the final result is written to, the original column or the test column.

Q3: expected the data to be difficult to share, but still worth trying :) Thanks to other reports, we just found and fixed an important cause for the "... .tail1 too small (expected 24806671, actual 0)" error.  This fix should prevent this error from happening again.  We're planning a new bug-fix release soon.

There are ways to patch the .tail1 file(s) to get the database restarted, but that's not a easy task and might result in some data lose.  Is recreate your database an option?

**Comment by HiramTheHero** [comment]
Thank you @yzchang for the information.

Without going into too much detail, my databases with the issues are fine. I have a way to recreate them.

Thank you for your time and help.
