### ISSUE TITLE
Sequence value is not durable between server restarts

### ISSUE THREAD

**Issue by nuno-faria** [MonetDB/MonetDB#7264]
**Describe the bug**
The value of a sequence is not logged between sessions, causing it to reset to the initial one.
The exception is when, in addition to updating the sequence, another operation - which logs to the WAL - is executed (e.g. an insert).

**To Reproduce**
- Create a sequence and update its value:
    ```sql
    CREATE SEQUENCE test_sequence AS bigint start with 1;

    SELECT next_value_for('sys', 'test_sequence');
    SELECT next_value_for('sys', 'test_sequence');
    SELECT next_value_for('sys', 'test_sequence');
      +------+
      | %2   |
      +======+
      |    3 |
      +------+
    ```
- Restart the server
- Update the sequence value and check that it reset to the initial one:
    ```sql
    SELECT next_value_for('sys', 'test_sequence');
      +------+
      | %2   |
      +======+
      |    1 |
      +------+
    ```
- Check that the sequence is persisted when another operation is performed:
    ```sql
    CREATE TABLE Test (k int);
    SELECT next_value_for('sys', 'test_sequence');
    SELECT next_value_for('sys', 'test_sequence');
    SELECT next_value_for('sys', 'test_sequence');
      +------+
      | %2   |
      +======+
      |    3 |
      +------+
    INSERT INTO Test VALUES (1);
      1 affected row, last generated key: 3
    
    -- restart the server

    SELECT next_value_for('sys', 'test_sequence');
      +------+
      | %2   |
      +======+
      |    4 |
      +------+
    ```

**Expected behavior**
The sequence is committed to the WAL on its own.

**Software versions**
- MonetDB master branch (most recent commit)
- Ubuntu 20.04 LTS
- Self-installed and compiled

**Comment by PedroTadim** [comment]
After some looking, we consider this as a feature. The reason is, on your first example, you are using sequence numbers that aren't being store anywhere, so there's no reason to "WAL" them. We only log sequence changes when changes on tables happen. Sequences don't have strict ACID properties as other database objects, so this is plausible.
