### ISSUE TITLE
Select multiple character strings for NULL AS clause

### ISSUE THREAD

**Issue by HiramTheHero** [MonetDB/MonetDB#7266]
**Is your feature request related to a problem? Please describe.**
I'm importing data that has both empty and 'NA' strings that I would like to import as null. To my current understanding adding more than one string to the NULL AS clause throws a syntax error.

I've tried,
```
NULL AS '' AND 'NA'
-- and 
NULL AS ''
NULL AS 'NA'
```
both giving me syntax errors.

**Describe the solution you'd like**
It would be nice to have some syntax that allows multiple strings to be read in as null. Such as:
```
NULL AS '' AND 'NA'
```
I'm not too concerned about the format. Just the feature would be nice. If I've missed some documentation that explains how this behavior is possible, please let me know. 

If this possible, then having documentation about NULL AS clause explaining how this can be done would be great.

Thank you for your time and hard work on this product.

**Comment by ghost** [comment]
This feature request does not match our policy to extend SQL for corner cases. the front ends have a responsibility to provide proper organised input.
 regards Martin
