### ISSUE TITLE
Update after delete does not update some rows

### ISSUE THREAD

**Issue by kutsurak** [MonetDB/MonetDB#7267]
**Describe the bug**
Deleting `n` rows from a table and then updating the rest, leaves `n` of the remaining rows not updated.

**To Reproduce**
I have shared the reproduction privately.

**Expected behavior**
All the remaining rows should be updated.

**Software versions**
 - MonetDB Jan2022-SP1 installed on Fedora 35 using the release packages and changeset `64c356e13d86` (the current tip of Jan2022) compiled on Arch Linux.

**Comment by sjoerdmullender** [comment]
This bug has been fixed.
