### ISSUE TITLE
Missed rewrite to bulk operators in simple SQL UDF 

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7272]
**Describe the bug**
A simple SQL UDF involving function `epoch_ms` translates to a MAL loop.

**To Reproduce**
The following baseline works as expected:
```
start transaction;

create table t(d date);
insert into t values (curdate());
insert into t values (curdate());

CREATE OR REPLACE FUNCTION test(d1 date, d2 date) RETURNS decimal
BEGIN
  return epoch_ms(d1 - d2);
END;

explain select test(d, curdate()) from t;

|     X_66:bat[:lng] := batmtime.diff(X_11:bat[:date], "2022-03-20":date, nil:BAT);
|     X_67:bat[:lng] := batmtime.epoch_ms(X_66:bat[:lng]);
```

The following (only `* 1000` was added) translates to a MAL loop:
```
CREATE OR REPLACE FUNCTION test(d1 date, d2 date) RETURNS decimal
BEGIN
  return epoch_ms(d1 - d2) * 1000;
END;

explain select test(d, curdate()) from t;

|     X_77:bat[:lng] := bat.new(nil:lng, X_11:bat[:date]);
| barrier (X_80:oid, X_81:date) := iterator.new(X_11:bat[:date]);
|     X_83:lng := sql.f_23(X_81:date, "2022-03-20":date);
|     X_77:bat[:lng] := bat.append(X_77:bat[:lng], X_83:lng);
|     redo (X_80:oid, X_81:date) := iterator.next(X_11:bat[:date]);
| exit (X_80:oid, X_81:date);
```

The same happens leaving the same body as the original, but returning an `int`:
```
CREATE OR REPLACE FUNCTION test(d1 date, d2 date) RETURNS int
BEGIN
  return epoch_ms(d1 - d2);
END;
```

**Expected behavior**
All these variations should translate to a sequence of bulk operators.
This is 11.39:
```
|     X_61:bat[:lng] := batmtime.diff(X_11:bat[:date], "2022-03-20":date);
|     X_62:bat[:lng] := batmtime.epoch_ms(X_61:bat[:lng]);
|     X_63:bat[:int] := batcalc.int(X_62:bat[:lng]);
|     X_66:bat[:lng] := batcalc.*(X_63:bat[:int], 1000:sht, nil:BAT);
```

I am not sure if this happens with different functions as well - I didn't find any.
My guess: because this function was changed in 11.43, some signatures may have slipped away.

**Software versions**
 - MonetDB version number 11.43.10
 - OS and version: Fedora 35
 - self-installed and compiled

**Comment by PedroTadim** [comment]
The issue comes from missing candidate-less versions for some batcalc conversion calls. I will open a branch soon to clean this.

**Comment by swingbit** [comment]
Hi @PedroTadim , do you have any update on this?

**Comment by njnes** [comment]
Having all these extra mal api's for with and without candidate list isn't the proper solution. Its better to reduce to only the api with candidate lists. But that does require all map like functions to behave (api wise) the same. Such that injection of the right candidate list (nil:bat) is easily possible. This is however a larger project.

**Comment by swingbit** [comment]
I didn't point that out before: does it make sense to you that this happens only if that expression is in a SQL function?
If I skip the function and replicate its behaviour in one statement:
```
create table t(d date);
insert into t values (curdate());
insert into t values (curdate());

explain select cast(epoch_ms(d - curdate()) * 1000 as int) from t;
```
then it works as expected:
```
|     X_13:bat[:lng] := batmtime.diff(X_11:bat[:date], "2022-04-28":date, nil:BAT);                                                         |
|     X_16:bat[:lng] := batmtime.epoch_ms(X_13:bat[:lng]);                                                                                  |
|     X_20:bat[:hge] := batcalc.*(X_16:bat[:lng], 1000:sht, nil:BAT);                                                                       |
|     X_23:bat[:int] := batcalc.int(3:int, X_20:bat[:hge], nil:BAT);                                                                        |
```

**Comment by swingbit** [comment]
FYI, for now I solved my problem by implementing the function (which was similar to the one in the examples) as an `inline` MAL function for scalar values. Then all scalar operators used are correctly turned into bulk operators when needed.
