### ISSUE TITLE
Concurrent reads and writes causes "BATproject2: does not match always" error

### ISSUE THREAD

**Issue by nuno-faria** [MonetDB/MonetDB#7273]
**Describe the bug**
When executing concurrent reads and writes, particularly if the read query is large, the client returns the following error: `GDK reported error: BATproject2: does not match always\nBATproject2: does not match always`

This only seems to happen when the writes are updates or deletes.

Here is the log output:

```log
DFLOWworker1018: BATproject2: !ERROR: does not match always
DFLOWworker1018: BATproject2: !ERROR: does not match always
DFLOWworker1018: createExceptionInternal: !ERROR: SQLException:sql.bind:GDK reported error: BATproject2: does not match always
DFLOWworker1018: createExceptionInternal: !ERROR: !ERROR: BATproject2: does not match always
```

**To Reproduce**
The following [gist](https://gist.github.com/nuno-faria/d6ffb69cacca87e397ca779c53189813) can be used to reproduce the error. In it, there are two clients, one executes writes over a simple table (k int, v int), while the other executes the query below:
```sql
SELECT k, sum(v)
FROM Test
GROUP BY k
ORDER BY sum(v) DESC
```

**Software versions**
 - MonetDB master branch (most recent commit)
 - Ubuntu 20.04 LTS
 - Self-installed and compiled

**Comment by aris-koning** [comment]
Telepathy: we're already working on (hopefully) the same bug since last week. Fix is on the way. Thanks for reporting!

**Comment by PedroTadim** [comment]
The fix should be on default branch. Please test it.

**Comment by nuno-faria** [comment]
I cannot replicate the error anymore. Thank you all for looking into it.
