### ISSUE TITLE
Aggregate function ST_Collect crashes mserver5

### ISSUE THREAD

**Issue by smavros** [MonetDB/MonetDB#7274]
On latest 'geo-update' branch (hg id: f73972d12bf5) given a table
```
CREATE TABLE "sys"."test" (
        "id" INTEGER,
        "g"  GEOMETRY
);
```

the query
```
create table test2 as 
    select id, st_collect(g) as g 
    from test 
    where false
    group by id;
```
causes a crash to mserver5

**Comment by PedroTadim** [comment]
On default it's complaining about geom.subUnion being undefined, which really is.

**Comment by yzchang** [comment]
it doesn't crash (any more?) on my ubuntu, but gives the expected error `SELECT: cannot use non GROUP BY column 'g' in query results without an aggregate function`. `st_collect` needs to be declared as a aggr. func.

**Comment by smavros** [comment]
@PedroTadim this is due to migration. we have changed the exported SQL function and we are not managing this in the migration yet. create a new dbfarm using the `geo-update` and you will be able to see the crash.

@yzchang are you using the `geo-update` branch? if yes check if you really build the `geom` module

in general we use github tickets to keep track of any potential problems that we will solve later. they are low-priority so no worries. but thanks for trying it out! :slightly_smiling_face:

**Comment by njnes** [comment]
fixed, by handling empty result aggregate
