### ISSUE TITLE
MonetDB documentation in PDF format

### ISSUE THREAD

**Issue by HiramTheHero** [MonetDB/MonetDB#7275]
**Is your feature request related to a problem? Please describe.**
I find myself frequently referencing the MonetDB documentation. It would be nice to do so without having to use a browser.

**Describe the solution you'd like**
MonetDB documentation in PDF format would be excellent.

I've searched the website, but haven't found an area to download the documentation. I apologize if I missed the link while searching the website.

Thank you for your hard work on this project.

**Comment by yzchang** [comment]
not sure if Hugo has an easy to use option to export the whole documentation to PDF

**Comment by njnes** [comment]
hugo doesn't support it out of the box. With many hacks it maybe possible, but seems not that useful.
