### ISSUE TITLE
Unable to run count() on two distinct columns

### ISSUE THREAD

**Issue by HiramTheHero** [MonetDB/MonetDB#7276]
**Describe the bug**
Unable to run `select count(distinct col_1, col_2) from a_table;` without throwing the error `SELECT: no such binary operator 'count'(tinyint,char)`. Even though `select distinct col_1, col_2 from a_table;` can be successfully ran.

**To Reproduce**
```
create table a_table as 
select *
from ( values(0,'cero'),
(1,'uno'),
(2,'dos'),
(3,'tres'),
(4,'cuatro'),
(5,'cinco'),
(6,'seis'),
(7,'siete'),
(8,'ocho'),
(9,'nueve'),
(10,'diez'),
(10,'diez'),
(10,'diez'),
(10,'diez'),
(10,'diez'),
(10,'once')) as nr_es(nr, nm);

select * from a_table;
select distinct nr from a_table;
select distinct nm from a_table;
select distinct nr, nm from a_table;

select count(*) from a_table;
select count(distinct nr) from a_table;
select count(distinct nm) from a_table;
select count(distinct nr, nm) from a_table; -- This throws the error.

drop table a_table;
```
**Expected behavior**
When I run `select count(distinct nr, nm) from a_table;` I expect it to return 12. The tuple number result as the non-count query.

**Software versions**
 - MonetDB version number: MonetDB Database Server Toolkit v11.43.9 (Jan2022-SP1)
 - OS and version: MacOS 12
 - Installed from: Homebrew

**Comment by PedroTadim** [comment]
There's no "count" aggregate with multiple arguments. You should do `select distinct col_1, col_2 from a_table` then use `count(*)` above it.

**Comment by HiramTheHero** [comment]
This:
```
select count(*) from (select distinct nr, nm from a_table) as xxx;
```
works great.

Thank you. I apologize for the poor question. I'm still getting used to SQL syntax and subqueries.
