### ISSUE TITLE
Databases consistently become inaccessible

### ISSUE THREAD

**Issue by HiramTheHero** [MonetDB/MonetDB#7277]
**Describe the bug**
I've been using MonetDB for about a month now, and the databases I create keep becoming inaccessible. I've reported 2 out of the 10+ of these occurrences in #7268 and #7262.

With them happening so frequently I'm starting to think that I am the issue.

Here is my set up:
I'm on MacOS (ARM architecture) and I've installed monetdb via homebrew.
I have a 1 TB external drive using the APFS storage format connected via USB-C that I put the database on using the following commands:
```
monetdbd create /path/to/external_drive/dbfarm
monetdbd start /path/to/external_drive/dbfarm
monetdb create db
monetdb release db
```
I then log onto the database via the mclient program to perform operations on the database.
```
mclient -u monetdb -d db
```

When I am done using the database, need to disconnect the external drive, or put my computer to sleep with the external drive connected to it, I close all client connections to the database by exiting all mclient interfaces I have open.

Then I run the following commands:
```
monetdb stop db
monetdbd stop /path/to/external_drive/dbfarm
```

When I need to get back to the database I run the following:
```
monetdbd start /path/to/external_drive/dbfarm
monetdb start db
```

Sometimes I get lucky and the database starts with no problems. However, many times I run into the system hanging as described in #7268 and #7262. In one of the issues @sjoerdmullender asked https://github.com/MonetDB/MonetDB/issues/7268#issuecomment-1065298682:
> Do you have a large write-ahead log (WAL)? Try `du` on the `sql_logs` subdirectory of the database. My guess is, you do. And that is why startup takes long. Just let it finish.

I check for this when the database doesn't start up normally. None of these databases have any large write-ahead log files that justify the system not starting the databases under 10 minutes. (I assume a MonetDB database that is holding 60 GB of data shouldn't take longer than 10 minutes to start up. Please let me know if I am incorrect.)

My list of questions are:
- Am I starting and stopping my databases correctly?
- Is there an issue with me hosting the database on an external drive?
- What debugging tools (besides sending logs) can I use to help identify the issue?

I assume the issue isn't going to magically disappear, and I'd love to help solve it. (Especially if the issue is me. Lolz.)

I've been blown away with the performance of MonetDB on huge datasets, and I'd love to keep using the product. This issue is the only one that I've had with MonetDB, and unfortunately, it is severe.

Thank you for your time and help.

**To Reproduce**
I've described the procedure I follow when the issue occurs. It appears to happen at random.

**Expected behavior**
Not being "locked" out of the database when restarting it is the expected behavior.

**Software versions**
 - MonetDB version number: MonetDB Database Server Toolkit v11.43.9 (Jan2022-SP1)
 - OS and version: MacOS 12.3 (ARM)
 - Installed from: Homebrew

**Comment by njnes** [comment]
external drives are usualy slow (bandwidth maybe okay, but reading/writing lots of small bits is very very slow). This could explain the startup because of a small WAL files to take a long time. For debugging you could simply check the dbfarm/datbase/sql_logs/sql/* files. Once the number files are reduced too only one and that being empty, then the wal is processed.
