### ISSUE TITLE
Possibly inappropriate/incoherent behavior

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7279]
**Describe the bug** / **To Reproduce**
Imagine the following table:
Table: T
Field: num of type numeric (double);
Field: text of type text (clob). This field, despite being of the text type, has a number stored.

The following SQL works:
select sum(text) from T

The following SQL works:
select sum(text)-sum(text) from T

The following SQL works in version 11.33.3 but does not work in version 11.43.9:
select sum(num)-sum(text) from T

If I spell out a cast it works on both versions.
select sum(num)-sum(cast(text as float)) from T

Looking at it coldly I can understand that I might actually need to apply the conversion but this opens up a few questions:
Why do the first and second SQLs work? If it's correct the third one doesn't work, the others shouldn't work either.
Why did it work before and now it doesn't? This is going to be quite problematic as users update MonetDB.

If this is not allowed, then the MonetDB needs to return an appropriate message. The error currently returned is actually triggered on a subsequent operation and not on the aggregation. This is because of the type of data returned by this aggregation.
From what I've noticed, the sum(text) expression is returning a strange data type: sec_interval. And with that, it doesn't find a suitable subtraction operation.

**Expected behavior**
Or it prohibits the use of sum with text field and returns a proper error message;
Or allow this usage, but adjust the data type returned by this aggregation;

**Screenshots**
![image](https://user-images.githubusercontent.com/86444458/160832958-a91fe1cc-7ebe-4387-bc36-76be6b6cd3d0.png)
![image](https://user-images.githubusercontent.com/86444458/160833018-dde2ee56-e721-43b1-a19c-06c3cbbea2bc.png)
![image](https://user-images.githubusercontent.com/86444458/160833076-c5cb3800-dfd2-4b5a-b16d-7fb116035a63.png)
![image](https://user-images.githubusercontent.com/86444458/160833136-8d7f5261-7ba2-4b60-9638-477f89c71817.png)
![image](https://user-images.githubusercontent.com/86444458/160833356-a870cb21-02e4-4734-b8d2-7929b69af6e8.png)
![image](https://user-images.githubusercontent.com/86444458/160833568-c277a095-6833-4f80-9b9e-acfcf82ea961.png)

**Software versions**
MonetDB version number: 11.43.9
OS and version: Windows 10
Installed from release package or self-installed and compiled: release package

**Comment by PedroTadim** [comment]
On Oct2020 release we made a breakable change where interval types are not compatible with integer types because of their nature. On your examples, sum(text) doesn't exist, so MonetDB picks a type compatible with text and finds second intervals. Later to do the subtraction, if the other sum is returning an integer, then it can't be done. because of the aforementioned incompatibility. This is expected because SQL has undefined behavior for type incompatibilities.

**Comment by alexandresilvawek** [comment]
Hi Pedro,

If the sum(text) doesn't exist, wouldn't it be better to give an error at this point?

**Comment by PedroTadim** [comment]
I think SQL allows the possibility to find the same function with a compatible type if it doesn't exist for the input type, so there's nothing we can do about it.

**Comment by alexandresilvawek** [comment]
I understand.

I have another suggestion/question: Assuming that the "sum" function only accepts numeric types, wouldn't it be better to always choose a more comprehensive numeric type (double for example)?

I think it would be better than a random type that could be less comprehensive, as is the case with "interval".

**Comment by PedroTadim** [comment]
The issue with sum(interval), is that all numeric sum functions are compatible with the text type and the first of the list is picked up (they are hashed by name and all go into the same bucket). For this case is the interval type. Changing this method could break some production scripts.

**Comment by alexandresilvawek** [comment]
It's ok Pedro.
Thanks.
