### ISSUE TITLE
Outdated documentation about autoloading scripts

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7280]
Page https://www.monetdb.org/documentation-Jan2022/admin-guide/system-resources/autoloading-scripts/ is outdated since Oct2020 release.

I actually wish it this documentation were still valid. I liked that autoloading mechanism much better.

**Comment by sjoerdmullender** [comment]
The new way of doing it is using the --loadmodule option.
There is already an entry in the manual, and it is also in the current version of the MonetDB-extend repository.

But we should still fix the documentation on the website.

**Comment by mvdvm** [comment]
Documentation on old autoloading scripts has been removed from documentation.
