### ISSUE TITLE
Is DataCell (Streaming) functionality is disabled? Will i be able to use MonetDB as a streaming DB?

### ISSUE THREAD

**Issue by sreejithssharma** [MonetDB/MonetDB#7286]
**Is your feature request related to a problem? Please describe.**
I would like to know if the DataCell functionality still exists in MonetDB. In the documentation, it was mentioned this feature is disabled. Can we still use MonetDB as a streaming DB?

**Describe the solution you'd like**
Enable DataCell or feature to have MonetDB as streaming DB.

**Describe alternatives you've considered**

**Additional context**

**Comment by PedroTadim** [comment]
The DataCell extension was removed a long time ago and the code is no longer maintained (we should update the documentation). Later we started a follow-up time series project at the 'trails' branch. However, that code is now outdated and it will require some time to tune it with the latest kernel changes we did in the last few years.

**Comment by sreejithssharma** [comment]
Thanks, Pedro. Does still MonetDB support the streaming features?

**Comment by PedroTadim** [comment]
As I said, the 'trails' branch is the closest we have to streaming, but it requires some maintenance to become updated. You can try it for fun, but it's not well tested.

**Comment by sreejithssharma** [comment]
okay, thank you!
