### ISSUE TITLE
Unable to upgrade from MonetDB-MonetDB-11.31.13  to  MonetDB-11.37.11

### ISSUE THREAD

**Issue by bharaththam** [MonetDB/MonetDB#7287]
**Describe the bug**
when try to update the existing DB to new version we are getting below error.

error details:
mapi_usock=/monet_data01/DBFARM_TSVR_P2_A_BT/DB_TSVR_JR_P2_A/.mapi.sock --set monet_vault_key=/monet_data01/DBFARM_TSVR_P2_A_BT/DB_TSVR_JR_P2_A/.vaultkey --set gdk_nr_threads=128 --set max_clients=2048 --set sql_optimizer=sequential_pipe
2022-04-19 07:38:25 ERR DB_TSVR_JR_P2_A[298637]: #main thread: BBPcheckbats: !ERROR: BBPcheckbats: cannot stat file /monet_data01/DBFARM_TSVR_P2_A_BT/DB_TSVR_JR_P2_A/bat/01/46/14637.tail (expected size 1953432): No such file or directory

**To Reproduce**
upgrade from the version MonetDB-11.31.13  to  MonetDB-11.37.11 we are getting error.

**Software versions**
 - MonetDB version number [a milestone label]
  MonetDB-11.37.11

 - OS and version: [e.g. Ubuntu 18.04]
 - Linux lnx1538.ch3.qa.i.com 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Installed from release package or self-installed and compiled
 - Self installed and complied

**Comment by PedroTadim** [comment]
We no longer support version 11.31. Can you try to upgrade one feature release at a time?

**Comment by bharaththam** [comment]
There are lot of versions in between, so we need to upgrade one by one or do we have any other method  to upgrade.

**Comment by PedroTadim** [comment]
Upgrade one by one to be safe.
