### ISSUE TITLE
Monet Backup validation 

### ISSUE THREAD

**Issue by bharaththam** [MonetDB/MonetDB#7290]
Monet backup validation  - we need to know if there is any backup utility inbuilt in monet as we are taking DB level backup using rsync and we have no option to validate if the backup is successful or not.

And also please update us to take backup and validate the backup.

**Software versions**
 - MonetDB version number -  Jan 2022 monetdb 11.43.5

**Comment by yzchang** [comment]
MonetDB doesn't have built-in feature to verify the backups, yet.  So, no matter you backup your database into a CSV dump or use hot-snapshot, you need to restore your backup into a new database to validate it:

* In [this page](https://www.monetdb.org/documentation-Jan2022/admin-guide/backup-upgrade/database-upgrade/), we give some ideas about "How to validate the database after an upgrade" (see the FAQs section), but you can apply the same steps to a restored database.
* [This page](https://www.monetdb.org/documentation-Jan2022/admin-guide/backup-upgrade/hot-backup/) describes how to create and restore a hot-snapshot.
