### ISSUE TITLE
Parallel execution of Numpy UDFs hangs

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7293]
**Describe the bug**
Running multiple queries from different clients involving Numpy UDFs hangs (it seems that creates too many servers)

**To Reproduce**

Define the following function

CREATE OR REPLACE FUNCTION bug_test(total_population INTEGER)
RETURNS INTEGER
LANGUAGE PYTHON
{
        sum_ = 0
        for p in total_population:
            sum_ += p
        return sum_
};

and run the query `select bug_test(col1) from atable;` with a table containing 10K integer rows,  from multiple clients in parallel (we tested with 12 and 24)
 
**Expected behavior**
All the queries return the result

**Software versions**
 - MonetDB version 11.44.0
 - OS and version: [e.g. Ubuntu 20.04]
 - Self-installed and compiled

**Comment by kutsurak** [comment]
I think that you need to create an aggregate function for this to work (take a look at [this](https://www.monetdb.org/documentation-Jan2022/dev-guide/sql-extensions/embedded-python/) and specifically the "Aggregating Data" section) but the server should not hang in any case.

I will look into the issue, but it's a bit busy currently so this might take some time.

**Comment by johnfouf** [comment]
Thanks Panos, indeed that's an aggregate as it gets a table, and returns a single row. However, according to the docs it seems that this is allowed for aggregates without group by. For example, this function exists in the docs:

CREATE FUNCTION python_min(i INTEGER) RETURNS integer LANGUAGE PYTHON {
    return numpy.min(i)
};

and also the explanation on blocking operations (above this example):
"These are called blocking operations. An example of such a blocking operation is the quantile function, because we cannot compute the quantile of a column when we only have access to part of a column. " 

We felt that this is a supported feature. However, that's just a function to reproduce the problem which returns correct results if runs alone and hangs otherwise. I 've just asked my colleagues to examine if this is also the case with other UDFs  that follow the "standard" rules. 
 As a side note, we are note facing this issue if running the same UDF in parallel through the C udfs api with the udf written in C.

**Comment by njnes** [comment]
The hang is a result of the python interpreter. For c-udfs this indeed doesn't hold. For better performance using the direct c-api is even better than the c-udf one.
