### ISSUE TITLE
Ambiguous identifier not detected

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7294]
**Describe the bug**
Queries using an ambiguous identifier do not fail accordingly. The ambiguity is beween an actual column and an alias.

**To Reproduce**
This query:
```
create table s(a int, w int);
create table t(x int, y int);

SELECT t.x as a, s.w as b
FROM s, t
GROUP by a, b;
```
fails with:
```
SELECT: cannot use non GROUP BY column 't.x' in query results without an aggregate function
```
The intention was to group on `t.x` (aliased as `a`)
At first sight, `t.x` seems grouped. The problem is that its alias clashes with `s.a`. So I think MonetDB is silently grouping on `s.a`, hence the complaint that `t.x` is not grouped. Indeed, the query works by replacing the group-by clause with `GROUP by t.x, b`.

This second query also "works" silently, while it should fail:
```
create table s(a int, w int);
create table t(x int, y int);

SELECT t.x as a, s.w as b
FROM s, t
where a = 0;
```
Again, `a` is totally ambiguous, but MonetDB chooses one instance silently (we can't even guess which one in this case).

**Expected behavior**
Both queries should fail with an "ambiguous identifier" error

**Software versions**
 - MonetDB 11.43.14
 - OS and version: Rocky Linux 8.5
 - self-installed and compiled

**Comment by njnes** [comment]
the aliases are only used once the projection is handled, ie when the where is done, the aliases are (not jet) known. So its not ambiguous.

**Comment by njnes** [comment]
using the aliases in the group by is possible, you cannot do both, ie use alias and old name. So we require ambiguous names on the group by, ie use large strings in this case and for both the group by expresssions

**Comment by swingbit** [comment]
@njnes to be sure I understand well your answer: the ambiguity is resolved by knowing that the target list (thus the alias) is the last one being evaluated, so in both queries it is right to expect `a` to refer to `s.a` .

I agree with that. Though I find it extremely confusing and a potential source for very sneaky bugs (in queries).
Instead of allowing this silent shadowing, wouldn't it be better to make it fail?

**Comment by njnes** [comment]
I'd love clear semantics, but somehow we ended up with this unclear semantics (not sure who to blame)

**Comment by swingbit** [comment]
I remember MonetDB used not to allow to use aliases in the `GROUP BY` clause, and I think it was more correct (as you say, aliases are not known yet when evaluating `GROUP BY`).

Allowing this is actually one of the reasons why this is now confusing. How can one rely on the evaluation order (as you pointed out), if the evaluation order is broken by convenience exceptions?

**Comment by njnes** [comment]
I agree. I'll look again at the sql specs, if I can disallow this potential confusion, with some specs backing me I'd kill the feature ;-)

**Comment by njnes** [comment]
its a bit hard to remove this now. Some people like this (ugh). 
The semantics (in group by) are first look at the inner relation (ie the attributes of s and t. That succeeds for a, fails for b.
Then look at the aliases. Causing the strange result.
(second query is correct as it only can use the inner bits)
Group by, order by in this are somewhat complex, but seems users like to not type an expression twice.
