### ISSUE TITLE
Implictly cast a timestamp string to DATE when appropriate

### ISSUE THREAD

**Issue by aris-koning** [MonetDB/MonetDB#7296]
While playing around with [Apache Superset](https://superset.apache.org/) on top of MonetDB, I have noticed that Superset expects its database back-ends to be able to _**implicitly**_ cast any string that is formatted according to a valid standardized timestamp as a `DATE`.

However MonetDB does not seem to support this. The following script  runs fine in postgresql, but gives errors on monetdb Januari 2022.
```sql

START TRANSACTION;
CREATE TABLE foo (d DATE);

INSERT INTO FOO VALUES (DATE '2022-05-23 00:00:00.000000'), (DATE '2022-05-30 00:00:00.000000'); -- works in MonetDB
INSERT INTO FOO VALUES ('2022-05-23'), ('2022-05-30'); -- works in MonetDB
INSERT INTO FOO VALUES ('2022-05-23 00:00:00.000000'), ('2022-05-30 00:00:00.000000'); -- breaks in MonetDB

ROLLBACK;
```

**Comment by kutsurak** [comment]
I would argue that this is something that should be fixed on Apache Superset, i.e. it should use an explicit type.

**Comment by aris-koning** [comment]
I don't know the internals of Superset except that it uses sqlalchemy under the hood. It might be an issue with our sqlalchemy connector depending on how Superset uses sqlalchemy.

But on the other hand we try to be compatible with postgres. And if we implement the same behavior here as postgres we also have that working out of the box in Superset. So two birds with one stroke.

And as a feature, it doesn't look completely unreasonable to parse a valid timestamp string as a date when required.  For instance this DOES work in monetdb

```
INSERT INTO FOO VALUES ('2022-05-23'), ('2022-05-30'); -- works in MonetDB
```

**Comment by njnes** [comment]
indeed needs a fix on the sqlalchemy side.

**Comment by njnes** [comment]
your passing a timestamp, how shoud the parser guess that your string is a timestamp and then only use the date??

**Comment by njnes** [comment]
this behaviour seem changed in sep2022, because of the more general convert operator.
