### ISSUE TITLE
Parsing partial dates behaves unpredictable

### ISSUE THREAD

**Issue by aris-koning** [MonetDB/MonetDB#7297]
Let say we have monthly data whose records are chronologically determined by a string field that represents year/month combination like: '1995-03'. As a partial date it would be nice to parse such values as complete `DATE` values by filling in a reasonable default for the missing date fields. However on MonetDB Januari 2022 we get the following behavior:

```
$ mclient -s "select str_to_date('1995-04', '%Y-%m');"
+------------+
| %2         |
+============+
| 1995-04-30 |
+------------+
1 tuple
$ mclient -s "select str_to_date('1995-02', '%Y-%m');"
bad date '1995-02'
$ mclient -s "select str_to_date('1995-01', '%Y-%m');"
+------------+
| %2         |
+============+
| 1995-01-30 |
+------------+
1 tuple
```
And I have seen cases where all of the above queries fail or that the day field value is different then `30`.

On Postgres all of the equivalent examples work:

```
$ psql -c "select to_date('1995-04', 'YYYY-MM');"
  to_date   
------------
 1995-04-01
(1 row)

$ psql -c "select to_date('1995-02', 'YYYY-MM');"
  to_date   
------------
 1995-02-01
(1 row)

$ psql -c "select to_date('1995-01', 'YYYY-MM');"
  to_date   
------------
 1995-01-01
(1 row)

```

**Comment by sjoerdmullender** [comment]
You get a very reasonable default: today's day.  ;-)
The problem is in the strptime function which fills in the missing information.  We do not know what information is passed to this function.  It acts, as far as MonetDB is concerned, as a black box.  So we don't know either the to-be-parsed string, not the format string.  If we did, we might as well do the complete parsing and get rid of that function.  It seems, postgresql took that route.

**Comment by aris-koning** [comment]
Yeah, that is hard to solve then. Still I like to leave the ticket open for now. Just to see if it resonates with other users.

**Comment by njnes** [comment]
the passed tm is initialized with today. Therefor we get this 'today' based result. Ie probably we need not to fill this before calling (just keep it clean (0's).

**Comment by njnes** [comment]
almost. tm_mday starts from 1, ie we need to set it on 1 before.

**Comment by njnes** [comment]
pushed fix to sep2022 branch. ie now the 1st of the month / year etc is used, with missing input.
