### ISSUE TITLE
table corrupt and shows negative id, how can we remove them?

### ISSUE THREAD

**Issue by sreejithssharma** [MonetDB/MonetDB#7299]
**Describe the bug**
sql>select * from sys.tables where name='AS_XQL_LOG_INFO_29042022_RPM';
+-------------+------------------------------+-----------+-------+------+--------+---------------+--------+-----------+
| id          | name                         | schema_id | query | type | system | commit_action | access | temporary |
+=============+==============================+===========+=======+======+========+===============+========+===========+
| -1059856705 | AS_XQL_LOG_INFO_29042022_RPM |      6422 | null  |    0 | false  |             0 |      0 |         0 |
+-------------+------------------------------+-----------+-------+------+--------+---------------+--------+-----------+

**To Reproduce**
We don't have a specific way to reproduce it, yet if we check the sys.tables the ID shows a negative number.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78530412/171781646-9e461986-0428-4b04-a6c7-cd6d96564ee0.png)

**Software versions**
 - MonetDB-11.43.13 - Even in older version
 - CentOS 7
 - Compiled

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**

**Comment by njnes** [comment]
as monetdb user you should be able to delete the row, but that doesn't remove the table (if it still exists) from the storage (disk).
Any idea what steps/queries/system restarts/upgrades etc where done to end up with this broken/corrupted db?

**Comment by mvdvm** [comment]
Note that the id column is of type int and thus allows a maximum of 2^31 or 2147483648 db-catalog objects created in the whole database lifetime.

Please run queries:
 select min(id) min_id, max(id) max_id from sys.tables;
 select min(id) min_id, max(id) max_id from sys.ids;
There should not show negative ids.

 select * from sys.tables where id < 1;
 select * from sys.ids where id < 1;
These queries should return no rows.

If negative ids are reported I recommend to make an SQL dump of your database asap and create a new database and run that SQL dump script. This restarts the id sequence generator for all database objects.

**Comment by njnes** [comment]
Could you see if the Jan2022-sp4 solves also this issue?

**Comment by njnes** [comment]
It does require a clean loaded db from a sql dump.

**Comment by RoderickZuniga** [comment]
I have the same problem, in which version is it fixed?
