### ISSUE TITLE
MonetDB : Partitioning Data by Time Intervals

### ISSUE THREAD

**Issue by AKheli** [MonetDB/MonetDB#7302]
I am looking to use MonetDB for a time series data by partition the data using a given time interval, for example, by day. The aim in this case is that each partition would contain data of a particular day. 

From the [documentation](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-catalog/table-data-partitioning/), I can see that MonetDB provides partitioning as a feature, by I couldn't know how to implement it, I have tried for example: `PARTITION BY DAY`, such is implemented by other systems, by that didn't work. 

How could data be partitioned using a fixed time period interval in MonetDB? 
Thanks.

**Comment by ghost** [comment]
hi, the partitioning schemes are documented and include expressions to finetune the scheme
short cuts are not provided
