### ISSUE TITLE
Concurrent creation of remote tables.

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7304]
**Describe the bug**
Concurrent creation of remote tables does not return a concurrency conflict error, it runs, but leads to errors.

**To Reproduce**
1) Open 3 databases (db1, db2, db3) with 2 local tables to 2 of them (db1, db2)
2) Concurrently create 2 remote tables to the third database (db3).

The create queries will run, but when selecting a remote table, it connects to the wrong database and fails to find it. 
It seems a concurrency issue, however no error is returned during the create remote table queries. 

**Software versions**
 - MonetDB 11.44.0
 - Ubuntu 22.04

**Comment by aris-koning** [comment]
Hi,

Thanks for the report. If you can add the actual (SQL) reproduction scripts for setting things up, e.g. have all three servers listening on the loopback interface on different ports, schema definitions, etc, we can start playing with this on our side.

**Comment by lrpereira** [comment]
Hi @johnfouf ,
Any updates on this issue ? Were you able to solve this or the bug still persists ? In the case of the latter, can you provide what @aris-koning asked above ? This is something we would like to investigate if it's still a problem.

**Comment by johnfouf** [comment]
I have attached some scripts to reproduce the issue. 
Some instructions:

Run:
./reproducable.sh
./loadlocaldbs.sh
./notparallelscript.sh

after that open voc1 with mclient and execute `select * from local1;`
This should work.

Cleanup everything and then run again:
./reproducable.sh
./loadlocaldbs.sh
./parallelscript.sh

In this case query `select * from local1` does not work. It seems a concurrency issue with create remote table. The difference is that the second script submits the queries in parallel.
It runs without returning conflict error but the result is a corrupted remote table. 


[reproducible.tar.gz](https://github.com/MonetDB/MonetDB/files/9614842/reproducible.tar.gz)

**Comment by aris-koning** [comment]
Thanks! We will have a look at it!

**Comment by njnes** [comment]
is this reproducable with jun2023 ?

**Comment by njnes** [comment]
I cannot reproduce this on aug2024
