### ISSUE TITLE
SQL output time not being displayed by default

### ISSUE THREAD

**Issue by sreejithssharma** [MonetDB/MonetDB#7307]
By default, we used to get the timings after any SQL execution from mclient. In MonetDB-11.43.5, we no longer see that. Do we need to add a parameter or is it being removed from the default?

OLD Version -
---------------------
sql>COPY select * from "tstsql_1" INTO '/nztoexa/di_export/DATA_TO_EXPORT/tstsql_2.dat' using delimiters '|','\n','"' NULL AS '';
10 affected rows (6.822ms)  ---->>>> missing in new version mclient

New Version - 
----------------------
sql>COPY select * from "tstsql_1" INTO '/nztoexa/di_export/DATA_TO_EXPORT/tstsql_1.dat' using delimiters '|','\n','"' NULL AS '';
sql>

**Comment by sjoerdmullender** [comment]
See the `--timer` option in the mclient manual: https://www.monetdb.org/documentation-Jan2022/admin-guide/manpages/mclient/
