### ISSUE TITLE
"Getting started" is wrong

### ISSUE THREAD

**Issue by alexey-milovidov** [MonetDB/MonetDB#7310]
**Describe the bug**
```
ubuntu@ip-172-31-2-193:~$ cat $HOME/.monetdb
name=monetdb
password=monetdb
ubuntu@ip-172-31-2-193:~$ mclient -d voc
.monetdb:1: unknown property: name
user(ubuntu):
```

https://www.monetdb.org/documentation-Jan2022/user-guide/get-started/login-to-monetdb/

**Comment by lrpereira** [comment]
Hi @alexey-milovidov ,
Thanks for spotting this issue!

**Comment by lrpereira** [comment]
Hi @alexey-milovidov ,
Thanks for spotting this issue!
