### ISSUE TITLE
Missing `REGEXP_REPLACE` function.

### ISSUE THREAD

**Issue by alexey-milovidov** [MonetDB/MonetDB#7311]

**Comment by aris-koning** [comment]
Thanks,

we actually have a `replace_first` function. But I personally think we should add a dedicated `REGEX_REPLACE` amongst our SQL functions as most DB systems offer it out of the box.

However if you need an immediate workaround for it, you should be able to call:

```
select sys.replace_first('foobar', 'o+', 'aa', 'ismx');
+--------+
| %2     |
+========+
| faabar |
+--------+
````

You might even define a custom SQL function named `REGEX_REPLACE` which basically just aliases this function and uses the proper standard `pcre` flags.

**Comment by simonaubertbd** [comment]
It's a useful industry standard. :)

**Comment by aris-koning** [comment]
Yes, we are convinced about that as well. We are aiming to have a dedicated `REGEXP_REPLACE` function implemented in the next major release.

**Comment by sjoerdmullender** [comment]
A function `sys.regexp_replace` will arrive in the next feature release.

**Comment by alexey-milovidov** [comment]
@sjoerdmullender Thank you for the great work on MonetDB!
