### ISSUE TITLE
Test Button for ODBC Driver

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7312]
**Is your feature request related to a problem? Please describe.**
Once you click on ok, the ODBC window closes and you have to open an other sotfware to test the configuration. If it's wrong, we have to reopen the window
![image](https://user-images.githubusercontent.com/46959192/176832509-727f09d6-04de-4a98-a54c-007e615bd5c7.png)

**Describe the solution you'd like**
A button to test the configuration

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by simonaubertbd** [comment]
Hello @mvdvm  did you find some time on that "small but life changing" topic ?

Best regards,

Simon

**Comment by simonaubertbd** [comment]
Hello @mvdvm I just noticed you're working on the odbc these days. Do you also plan to solve this little issue? 

Best regards,

Simon

**Comment by njnes** [comment]
lots of new fields (for tls) are added indeed. Also the test became more or less needed for this. So you can start testing this..

**Comment by simonaubertbd** [comment]
Hello @njnes by "you", do you mean me? and if yes, how to ?

 Best regards,
 
 Simon

**Comment by njnes** [comment]
The release is almost there. The installers are available via https://www.monetdb.org/downloads/testing/Windows/Aug2024/.
