### ISSUE TITLE
ODBC Driver : please mask/hide password

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7314]
**Is your feature request related to a problem? Please describe.**
The ODBC driver shows the password, which is pretty unsafe if someone watches your screen

**Describe the solution you'd like**
the common dot instead of the password

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by simonaubertbd** [comment]
Hello @mvdvm  . Good for me with MonetDB-ODBC-Installer-x86_64-9ace5c9b1de1.msi

Before 
![image](https://user-images.githubusercontent.com/46959192/181777838-9a52adf9-35a6-48ec-8d31-1f7c3373a50f.png)


Now 
![image](https://user-images.githubusercontent.com/46959192/181777944-0bd89a71-9127-41ed-a04d-fba570110fc2.png)


Thanks a lot, that's much secured (at least I can share my screen)

Best regards,

Simon

PS : Can I wait to have the official release to close the Issue ?

**Comment by mvdvm** [comment]
Yes.
