### ISSUE TITLE
Hotbackup fails after lastest update 

### ISSUE THREAD

**Issue by warrenmaster** [MonetDB/MonetDB#7319]
call sys.hot_snapshot('/home/monetdb/mdb_hotbackup_20220824-1355387174998.tar.lz4');   

esults in 
:0.22000-GDK reported error: snapshot_heap: One of /home/dbFarm/trg/bat/BACKUP/6.theap and /home/dbFarm/trg/bat/6.theap must exist

**Comment by aris-koning** [comment]
Thanks for reporting. Will have a look at it in the coming time.

**Comment by warrenmaster** [comment]
> Thanks for reporting. Will have a look at it in the coming time.

Hi , checking in if there is an update to this issue

**Comment by sjoerdmullender** [comment]
Which version of MonetDB are (were) you using when this happened?

**Comment by warrenmaster** [comment]
the release just before the last feature release  or version prior to  monetdbd[13684] 11.45.7 (Sep2022) is serving this dbfarm

**Comment by njnes** [comment]
Does this still fail with later sep2022 versions?
