### ISSUE TITLE
sys.epoch_ms

### ISSUE THREAD

**Issue by gm-digitalk** [MonetDB/MonetDB#7323]
**Describe the bug**

sys.epoch_ms(timestamp) returns a decimal(18,3) in 11.43 where it previously returned a bigint in 11.41 Also there is now no way to obtain the number of milliseconds since the epoch from a timestamp directly and efficiently as a bigint.

Our use of MonetDB requires the binning of both millisecond accurate timestamps and differences between these timestamps.

On older versions of MonetDB we were using using `select cast(timestamp '1970-01-01 00:00:00.123' as bigint);`
This would yield a result of 123.

We upgraded to 11.41 and have been using the`select  sys.epoch_ms(timestamp '1970-01-01 00:00:00.123');` that again returns a bigint result of 123.

In 11.43 it seems that sys.epoch_ms now returns a **decimal(18,3)** with the fractional part as seconds.

This change to an established function (in fact the removal of any way of getting milliseconds since the epoch out of a date time stamp as a bigint) completely breaks our application. We could re-write our SQL queries to functionally achieve with 11.43 what we do with 11.41 at significant development effort. Unfortunately, testing this shows a massive and unsustainable performance penalty for our circumstances - more than doubling of the query time for our typical queries.

Can we please have sys.epoch_ms revert to its 11.41 behaviour or at least some way of getting a bigint count of milliseconds since the epoch out a date time stamp.

**To Reproduce**
In 11.41 run the SQL `sys.epoch_ms(timestamp '1970-01-01 00:00:00.123');`
Result is a bigint 123.

In 11.43 run the SQL `sys.epoch_ms(timestamp '1970-01-01 00:00:00.123');`
Result is a decimal(18,3) 0.123.

**Expected behavior**
In 11.43, the SQL : sys.epoch_ms(timestamp '1970-01-01 00:00:00.123'); should return the bigint 123

**Screenshots**
N/A

**Software versions**
 - MonetDB version number 11.43 (cf 11.41)
 - OS and version: Debian Buster
 - Installed from release package.

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**

**Comment by njnes** [comment]
small trick is to add the function like 
create function epoch_ms2(ts timestamp) returns bigint external name mtime.epoch_ms;
ie then select epoch_ms2 should function as before.
