### ISSUE TITLE
string_distance('method',str1, str2) as a generic distance function

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7324]
**Is your feature request related to a problem? Please describe.**
I would like to use several different methods to calculate distance between two strings :
-levenshtein (already exists)
-hamming
-jaro winkler
-damerau levenshtein
-...

**Describe the solution you'd like**
a generic function string_distance('method',str1, str2)  with useful error messages about methods when incorrect

**Describe alternatives you've considered**
several functions : seems too much for a simple usage

Best regards,

Simon

**Comment by mvdvm** [comment]
For extending MonetDB with more string distance functions, you can create a user defined function (in either SQL or C or Python). See [https://www.monetdb.org/documentation/user-guide/sql-programming/function-definitions/](https://www.monetdb.org/documentation/user-guide/sql-programming/function-definitions/)
This is also possible for the proposed generic function string_distance('method',str1, str2).

If you require this feature to be implemented natively in MonetDB source code (like levenshtein()), please contact [MonetDB Solutions](https://www.monetdbsolutions.com/contact)

**Comment by sjoerdmullender** [comment]
Some or all of these (or something closely related) is now in the Jun2023 releases.  See the release notes at https://www.monetdb.org/release-notes/jun2023/

**Comment by simonaubertbd** [comment]
Hello @njnes  and @sjoerdmullender First of all, thanks, that's cool to see you take users feedback into account. However, I'm a little surprised by what I read in the release notes :
"Renamed previous Levenshtein distance to Damerau-Levenshtein distance."

Levenshtein and Damerau-Levenshtein are two different things. Does it mean the old levenshstein distance function was actually a damerau-levenshtein? I'm ashamed I didn't even notice.

Best regards,

Simon

**Comment by njnes** [comment]
When I look back at the older branches I indeed see that the levenshtein function we had in that time already included transpositions, which I think is the big difference between levenshtein and Damerau-Levenshtein. So yes we use to have the incorrect (or more advanced) implementation, the rename is correct.

**Comment by simonaubertbd** [comment]
@njnes Thanks for the clarification !
