### ISSUE TITLE
SQL insert statement syntax error

### ISSUE THREAD

**Issue by faridzidan** [MonetDB/MonetDB#7327]
**Describe the bug**
I am getting sql syntax errors with insert statements into a table. The insert statements work fine in other DBMSs such as DuckDB, MS SQL Server, MySQL, PostgreSQL, etc.

The insert sql script has 822 sql insert statements, all succeed in MonetDB except for the attached 10 statements.

**To Reproduce**
1 connect to MonetDB via ODBC
2 create the table

**create table in_sync_dbms_object (
DBMS_CD              CHAR(8)                        not null,
OBJECT_TYPE_CD       CHAR(8)                        not null,
SQL_TYPE_CD          CHAR(8)                        not null,
REF_DBMS_CD          CHAR(8),
REF_OBJECT_TYPE_CD   CHAR(8),
REF_SQL_TYPE_CD      CHAR(8),
OBJECT_SQL           CHARACTER LARGE OBJECT,
OBJECT_SCRIPT        CHARACTER LARGE OBJECT,
OBJECT_SQL_CAT_COL   VARCHAR(128),
OBJECT_SQL_SCHEM_COL VARCHAR(128),
OBJECT_SQL_PARENT_NAME_COL VARCHAR(128),
OBJECT_SQL_NAME_COL  VARCHAR(128),
OBJECT_SQL_SIG_COL   VARCHAR(128),
OBJECT_SQL_SUBTYPE_COL VARCHAR(128),
OBJECT_SQL_ORD_POSITION_COL VARCHAR(128),
OBJECT_SQL_TEXT_COL  VARCHAR(128),
SIDE_EFFECT_DESC     VARCHAR(80),
CTRL_INS_DTM         TIMESTAMP                      default CURRENT_TIMESTAMP not null,
CTRL_UPD_DTM         TIMESTAMP                      not null,
CTRL_USR_ID          VARCHAR(256)                   not null,
constraint PK_IN_SYNC_DBMS_OBJECT primary key (DBMS_CD, OBJECT_TYPE_CD, SQL_TYPE_CD)
)**

3 run the attached sql script that has 10 insert statements (all fail).
(change the attached file extension from .txt to .sql as not allowed to attach .sql file).

**Expected behavior**
The 10 attached sql statements are valid sql and should execute with no error.

**Screenshots**

**Software versions**
 - MonetDB 11.43
 - Windows 10 64-bit
 - Installed from release package

**Issue labeling **
SQL parse error

**Additional context**
[parse_errors.txt](https://github.com/MonetDB/MonetDB/files/9630074/parse_errors.txt)

**Comment by sjoerdmullender** [comment]
The problem is with a legacy "feature" in monetdb.  Strings, by default, are interpreted like C strings in that the backslash has a special meaning: it either quotes or transforms the following character.  This is not according to the SQL standard.
There are two different ways you can deal with this issue:
1. change affected strings (ones that contain a backslash) and add an R in front of the string (e.g.: `select r'string with \';`).
2. alternatively, start the mserver5 process with the option `--set raw_strings=true`.

**Comment by faridzidan** [comment]
I started the server with `--set raw_strings=true` and that fixed 4 statements.
There are still 6 insert statements that fail that do not have a backslash.

**Comment by njnes** [comment]
seems your file has utf16 encoding. When converted using iconv -futf16 -tutf8 parse_error.txt > parse_error.txt2
the 10 inserts work fine (tested on the sep2022 release branch)

**Comment by faridzidan** [comment]
I get the same 6 statement errors with UTF-8 encoded file [parse_errors_utf8.txt](https://github.com/MonetDB/MonetDB/files/9685217/parse_errors_utf8.txt). All the code points in the file are 
ASCII-7 code points.
I am executing the statements via the MonetDB ODBC driver and not sure if the errors are due to the driver at this point.
Using MonetDB 11.43 server.

If this issue is fixed in the latest release branch of the server, then this issue can be closed.

**Comment by njnes** [comment]
with the correct UTF8 encoding and --set raw_strings=true. Seems to work both on the old jan2022 and newer sep2022 releases.

**Comment by faridzidan** [comment]
Are you executing the SQL from an ODBC client app using MonetDB ODBC driver?. This may be an ODBC driver issue.

**Comment by njnes** [comment]
the problem is indeed in the odbc driver. The support for the odbc {fn } seems to be at fault.

**Comment by njnes** [comment]
Also now the odbc {} escapes are handled in the server
