### ISSUE TITLE
sys.dependency_columns_on_functions view lists all table columns, not just the actually used by the function

### ISSUE THREAD

**Issue by budulinku** [MonetDB/MonetDB#7328]
The *dependency_columns_on_functions* view shows all (table's) columns. 
To demonstrate, run following example

```
CREATE TABLE mmtest01 ( id int, name text)
;
CREATE OR REPLACE FUNCTION mmtest02()
RETURNS int
BEGIN
	INSERT INTO mmtest01(id) VALUES (1);
	RETURN 1;
END
;
-- the  following SELECT returns both columns
-- not just the one actually used by the function
SELECT c.* 
FROM sys.dependency_columns_on_functions c 
WHERE c.function_name LIKE 'mmtest02'
ORDER BY table_name
; 
```
So in fact this view has no real value (looks to me but of course i may be wrong). What would be really helpfull is to get list of the columns that are really used by the function - in the example above the SELECT would return just 1 column (the _ID_). Which is btw what the view name hints.

Just as a side note - looks like the function_id is missing in the _sys.dependency_tables_on_functions_. To get table name for the column (dependency) a join condition by the function name may not help when there is an overloaded function.

thanks & best regards
budulinek dejmihrasek

**Comment by mvdvm** [comment]
I could reproduce the reported issue. It lists both the columns of table mmtest02.

A possible explanation could be that when you include an insert statement in a function with a subset of the columns (as in your example) or no columns at all, it still needs to use NULL (or the column default value or expression) for the other columns of the table during insert and the internal code therefore potentially concludes all columns of a table are needed for the insert, and thus show up in the sys.dependencies table. We will need to look into this.

Thanks for the suggestion to extend sys.dependency_tables_on_functions with column: function_id. We will add this to the enhancement list for the next feature release.

**Comment by njnes** [comment]
why do you think the function doesn't depend on all columns? The insert needs to insert a value (maybe a default or null) into the column, hence it has a dependency.

**Comment by mvdvm** [comment]
It appears to be correct output for insert statements used in a function body. It such situations it will list all the columns of the table you apply the insert statement on.

**Comment by sjoerdmullender** [comment]
This wasn't really a bug.
The `sys.dependency_tables_on_functions` and `sys.dependency_views_on_functions` views will be extended with a `function_id` column in the next feature release.
