### ISSUE TITLE
Critical Path Traversal Logs Exposed

### ISSUE THREAD

**Issue by SleepTheGod** [MonetDB/MonetDB#7329]
**Describe the bug**
Insecure Path That Leads To Critical Data Exposure

**To Reproduce**
intxturl: "/usr/local/opt/bison/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/bison/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin"

https://www.monetdb.org/testweb/logs/86580:5f17d2f9b5b0/Cla-Darwin-x86_64/MdoClient.identify

https://www.monetdb.org/testweb/logs/86580:5f17d2f9b5b0/Cla-Darwin-x86_64/

**Expected behavior**
Path Traversal

# 2022-10-12 19:08:03 -- /export/scratch1/home/monet/testweb/logs/2022-10-12_19:08/MdoServer

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda6       1.8T  281G  1.4T  17% /export/scratch1

~/testweb/source/monetdb-java ~/testweb/TestTools
updating the sources for monetdb-java
pulling from https://www.monetdb.org/hg/monetdb-java/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-java sources updated to revision 7ec8d469fd0b
~/testweb/source/monetdb-perl ~/testweb/TestTools
updating the sources for monetdb-perl
pulling from https://www.monetdb.org/hg/monetdb-perl/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-perl sources updated to revision a2a23aa2bf8e
~/testweb/source/monetdb-php ~/testweb/TestTools
updating the sources for monetdb-php
pulling from https://www.monetdb.org/hg/monetdb-php/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-php sources updated to revision 9de229e8cb8d
~/testweb/source/monetdb-ruby ~/testweb/TestTools
updating the sources for monetdb-ruby
pulling from https://www.monetdb.org/hg/monetdb-ruby/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-ruby sources updated to revision c2070750ad20
~/testweb/source/monetdb-test-data ~/testweb/TestTools
updating the sources for monetdb-test-data
pulling from https://www.monetdb.org/hgtt/monetdb-test-data/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-test-data sources updated to revision 855b4c5aa368
~/testweb/source/monetdb-external-tests ~/testweb/TestTools
updating the sources for monetdb-external-tests
pulling from https://www.monetdb.org/hgtt/monetdb-external-tests/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-external-tests sources updated to revision 1c488a273181
~/testweb/source/MonetDB ~/testweb/TestTools
updating the sources for MonetDB, switching to Jan2022
pulling from https://www.monetdb.org/hg/MonetDB/
searching for changes
no changes found
716 files updated, 0 files merged, 74 files removed, 0 files unresolved
MonetDB sources updated to revision 830c006f2c77
error: aborting MdoServer run, as a log directory for 86802:830c006f2c77 already exists: identical sources have been tested already
# 2022-10-12 19:08:57 -- /export/scratch1/home/monet/testweb/logs/2022-10-12_19:08/MdoServer

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda6       1.8T  281G  1.4T  17% /export/scratch1

~/testweb/source/monetdb-java ~/testweb/TestTools
updating the sources for monetdb-java
pulling from https://www.monetdb.org/hg/monetdb-java/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-java sources updated to revision 7ec8d469fd0b
~/testweb/source/monetdb-perl ~/testweb/TestTools
updating the sources for monetdb-perl
pulling from https://www.monetdb.org/hg/monetdb-perl/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-perl sources updated to revision a2a23aa2bf8e
~/testweb/source/monetdb-php ~/testweb/TestTools
updating the sources for monetdb-php
pulling from https://www.monetdb.org/hg/monetdb-php/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-php sources updated to revision 9de229e8cb8d
~/testweb/source/monetdb-ruby ~/testweb/TestTools
updating the sources for monetdb-ruby
pulling from https://www.monetdb.org/hg/monetdb-ruby/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-ruby sources updated to revision c2070750ad20
~/testweb/source/monetdb-test-data ~/testweb/TestTools
updating the sources for monetdb-test-data
pulling from https://www.monetdb.org/hgtt/monetdb-test-data/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-test-data sources updated to revision 855b4c5aa368
~/testweb/source/monetdb-external-tests ~/testweb/TestTools
updating the sources for monetdb-external-tests
pulling from https://www.monetdb.org/hgtt/monetdb-external-tests/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
monetdb-external-tests sources updated to revision 1c488a273181
~/testweb/source/MonetDB ~/testweb/TestTools
updating the sources for MonetDB, switching to Jul2021
pulling from https://www.monetdb.org/hg/MonetDB/
searching for changes
no changes found
1871 files updated, 0 files merged, 258 files removed, 0 files unresolved
MonetDB sources updated to revision 219c3300d4b9
finding previous run for branch Jul2021
previous run was: 86544:c8b5a0a4e270

# 2022-10-12 19:09:57 == changing logdir from /export/scratch1/home/monet/testweb/logs/2022-10-12_19:08 to /export/scratch1/home/monet/testweb/logs/86808:219c3300d4b9, delta time: 60s

storing incoming commits
~/testweb/source/MonetDB ~/testweb/TestTools
moving sources into staging area
creating MonetDB-219c3300d4b9.tar.bz2
creating monetdb-java-7ec8d469fd0b.tar.bz2
creating monetdb-test-data-855b4c5aa368.tar.bz2
creating monetdb-external-tests-1c488a273181.tar.bz2
creating TestTools-88f215894731.tar.bz2

# 2022-10-12 19:10:19 == gathering workers, delta time: 22s

in directory /export/scratch1/home/monet/testweb/TestTools/config/workers:
  lab01 (config/workers/lab01.da.cwi.nl)
  lab03 (config/workers/lab03.ins.cwi.nl)
  lab04 (config/workers/lab04.da.cwi.nl)
  lab05 (config/workers/lab05.da.cwi.nl)
    lab05 is disabled by configuration
  lab06 (config/workers/lab06.da.cwi.nl)
  macmini (config/workers/mac-mini.scilens.private)
  power8 (config/workers/power8.scilens.private)
  win2k22 (config/workers/win2k22.virt.private)

# 2022-10-12 19:10:19 == gathering targets, delta time: 0s

processing target: Int-Fedora-x86_64-assert-propcheck
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-dbfarm
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-assert-propcheck-multifarm-coverage
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-sanitize
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-undefined
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-nowal
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-assert-debug=65536
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: Cla-Fedora-x86_64
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-notint128-dbfarm
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-thrs=1-assert
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-thrs=1-propcheck
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-thrs=32-propcheck-rpm
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-x86_64-thrs=53-assert-tcmalloc
  found worker: lab01
  found worker: lab04
  found worker: lab06
processing target: GNU-Fedora-powerpc64-thrs=8-assert-propcheck-dbfarm
  found worker: power8
processing target: GNU-Fedora-powerpc64-thrs=8-notint128-assert-propcheck-dbfarm
  found worker: power8
processing target: Cla-Darwin-x86_64
  found worker: macmini
processing target: Cla-Darwin-x86_64-assert-propcheck
  found worker: macmini
processing target: Mic-Windows7-x86_64-assert-propcheck
  found worker: lab03
processing target: Mic-Windows2022-i386-installer-notest
  found worker: win2k22
processing target: Mic-Windows2022-i386-assert-propcheck
  found worker: win2k22
processing target: Mic-Windows2022-x86_64-installer
  found worker: win2k22

# 2022-10-12 19:10:19 == final workqueues for workers, delta time: 0s
(final execution based on workers themselves):
  lab01: Int-Fedora-x86_64-assert-propcheck GNU-Fedora-x86_64-dbfarm GNU-Fedora-x86_64-assert-propcheck-multifarm-coverage GNU-Fedora-x86_64-sanitize GNU-Fedora-x86_64-undefined GNU-Fedora-x86_64-nowal GNU-Fedora-x86_64-assert-debug=65536 Cla-Fedora-x86_64 GNU-Fedora-x86_64-notint128-dbfarm GNU-Fedora-x86_64-thrs=1-assert GNU-Fedora-x86_64-thrs=1-propcheck GNU-Fedora-x86_64-thrs=32-propcheck-rpm GNU-Fedora-x86_64-thrs=53-assert-tcmalloc
  lab03: Mic-Windows7-x86_64-assert-propcheck
  lab04: Int-Fedora-x86_64-assert-propcheck GNU-Fedora-x86_64-dbfarm GNU-Fedora-x86_64-assert-propcheck-multifarm-coverage GNU-Fedora-x86_64-sanitize GNU-Fedora-x86_64-undefined GNU-Fedora-x86_64-nowal GNU-Fedora-x86_64-assert-debug=65536 Cla-Fedora-x86_64 GNU-Fedora-x86_64-notint128-dbfarm GNU-Fedora-x86_64-thrs=1-assert GNU-Fedora-x86_64-thrs=1-propcheck GNU-Fedora-x86_64-thrs=32-propcheck-rpm GNU-Fedora-x86_64-thrs=53-assert-tcmalloc
  lab06: Int-Fedora-x86_64-assert-propcheck GNU-Fedora-x86_64-dbfarm GNU-Fedora-x86_64-assert-propcheck-multifarm-coverage GNU-Fedora-x86_64-sanitize GNU-Fedora-x86_64-undefined GNU-Fedora-x86_64-nowal GNU-Fedora-x86_64-assert-debug=65536 Cla-Fedora-x86_64 GNU-Fedora-x86_64-notint128-dbfarm GNU-Fedora-x86_64-thrs=1-assert GNU-Fedora-x86_64-thrs=1-propcheck GNU-Fedora-x86_64-thrs=32-propcheck-rpm GNU-Fedora-x86_64-thrs=53-assert-tcmalloc
  macmini: Cla-Darwin-x86_64 Cla-Darwin-x86_64-assert-propcheck
  power8: GNU-Fedora-powerpc64-thrs=8-assert-propcheck-dbfarm GNU-Fedora-powerpc64-thrs=8-notint128-assert-propcheck-dbfarm
  win2k22: Mic-Windows2022-i386-installer-notest Mic-Windows2022-i386-assert-propcheck Mic-Windows2022-x86_64-installer

# 2022-10-12 21:43:25 == all workers finished, delta time: 9186s

# 2022-10-12 21:43:26 -- /export/scratch1/home/monet/testweb/logs/86808:219c3300d4b9/MdoServer, elapsed time: 9269s

**Comment by lrpereira** [comment]
#7345 
(duplicated)
