### ISSUE TITLE
Support RETURNING clause

### ISSUE THREAD

**Issue by smavros** [MonetDB/MonetDB#7331]
*Non SQL standard*

Ops like `INSERT`, `UPDATE` and `DELETE` could return the same number of rows as the ones affected so a second `SELECT` query is not needed.

It is implemented by most popular dbs [postgres](https://www.postgresql.org/docs/current/dml-returning.html), [sqlite](https://www.sqlite.org/lang_returning.html), [mariadb](https://mariadb.com/kb/en/insertreturning/)... 

It is also a point of performance improvement for driver and ORM libs (see the relative discussion in SQLAlchemy 2.0 Beta [release notes](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#optimized-orm-bulk-insert-now-implemented-for-all-backends-other-than-mysql))

**Comment by aris-koning** [comment]
Implemented in the next feature release.
