### ISSUE TITLE
Support IS [NOT] DISTINCT FROM predicate

### ISSUE THREAD

**Issue by smavros** [MonetDB/MonetDB#7332]
*Non SQL standard*

To compare two datatypes treating at the same time `NULL` as a comparable value some databases implement the `IS [NOT] DISTINCT FROM`. This means that any not-null valued datatype can be safely compared with `NULL` e.g. `SELECT 3 IS DISTINCT FROM NULL -> true`. Note that `NULL` values can be compared `SELECT NULL IS DISTINCT FROM NULL -> false` and `SELECT NULL NOT DISTINCT FROM NULL -> true`

Implemented in [postgres](https://www.postgresql.org/docs/15/functions-comparison.html#FUNCTIONS-COMPARISON-PRED-TABLE), [sqlserver](https://learn.microsoft.com/en-us/sql/t-sql/queries/is-distinct-from-transact-sql?view=sql-server-ver16)

**Comment by mvdvm** [comment]
The `IS DISTINCT FROM` predicate was introduced as feature T151 “DISTINCT predicate” of SQL:1999, and its readable negation, `IS NOT DISTINCT FROM`, was added as feature T152 “DISTINCT predicate with negation” of SQL:2003.
The purpose of these predicates is to guarantee that the result of comparing two values is either True or False, never Unknown.


FYI: These SQL comparisons can also be written with a CASE statement:

foo IS NOT DISTINCT FROM bar

```
CASE
  -- Act like a normal '=' on non-null values.
  WHEN foo IS NOT NULL AND bar IS NOT NULL
    THEN foo = bar
  -- foo = 'notnull' , bar = 'null' ; then foo <> bar so false
  WHEN foo IS NOT NULL AND bar IS NULL
    THEN false
  -- foo = 'null' , bar = 'null' ; then foo = bar so true
  WHEN foo IS NULL AND bar IS NULL
    THEN true
  ELSE false
END
```

foo IS DISTINCT FROM bar

```
CASE
  -- Act like a normal '<>' on non-null values.
  WHEN foo IS NOT NULL AND bar IS NOT NULL
    THEN foo <> bar
  -- foo = 'notnull' , bar = 'null' ; then foo <> bar so true
  WHEN foo IS NOT NULL AND bar IS NULL
    THEN true
  -- foo = 'null' , bar = 'null' ; then foo = bar so false
  WHEN foo IS NULL AND bar IS NULL
    THEN false
  ELSE true
END

```

**Comment by njnes** [comment]
this feature will be part of the next Aug2024 release
