### ISSUE TITLE
DLLs fail to load on Windows with accented characters in path

### ISSUE THREAD

**Issue by supersteves** [MonetDB/MonetDB#7333]
**Describe the bug**

mserver5 fails to start when installed at a path containing accented characters on Windows.

```
#2022-11-01 09:42:03: main thread: createExceptionInternal: !ERROR: LoaderException:loadLibrary:Loading error failed to open library generator (from within file 'C:\Users\Xxxéxxx\AppData\Local\XXX\MonetDb\MonetDB5\lib\monetdb5\_generator.dll'): Le module sp?cifi? est introuvable.
```

**To Reproduce**

Install/extract MonetDb on Windows to a folder within the user profile, where the username (and the profile folder) has an accented character (in this case "é") within it.  (Also seen with Simplified Chinese characters).
Attempt to start mserver5. It will fail with an error similar to the above.

**Expected behavior**
I expect the LoadLibrary calls to be able to handle non-ASCII characters correctly.

**Software versions**
 - MonetDB version number: 11.43.21  Jan2022-SP4
 - OS and version: Windows 10 10.0 amd64
 - Installed by extracting MSI to a folder within the user profile.

**Comment by supersteves** [comment]
The workaround is to change the Monetdb installation/extraction folder.

**Comment by sjoerdmullender** [comment]
I have just pushed a fix to the Sep2022 branch so that now we use the wide character interface of LoadLibrary.  This means that accented characters in the directory name get translated first to UTF-8 (every string inside MonetDB is UTF-8), but then before the library is opened, they are translated back to wide characters.  Before, we used the narrow character interface and so the file would be attempted to be opened using the UTF-8 translation of the accented characters.

**Comment by supersteves** [comment]
Hi Sjoerd, that was super fast. You guys are awesome. I look forward to trying the next version. Thanks!

**Comment by sjoerdmullender** [comment]
A fix has been pushed, so closing this.

**Comment by supersteves** [comment]
I am guessing this will land in the first SP of Sep2022 - when is this expected?

**Comment by sjoerdmullender** [comment]
We haven't decided yet when the next SP for Sep2022 will be, but I'm guessing it won't be too long now.
In the mean time, you can get a Windows installer from https://www.monetdb.org/testweb/web/87011:63e4486232d0/ if you want to test this.  These are builds that we create in our nightly testing.

**Comment by supersteves** [comment]
Thank you Sjoerd!
