### ISSUE TITLE
Respect umask

### ISSUE THREAD

**Issue by tkorvola** [MonetDB/MonetDB#7335]
I am trying to deploy MonetDB to an OpenShift cluster. OpenShift does not run containers as root (for security reasons). It uses random uids instead, but gid is always zero (root group). File permissions must therefore be arranged via the group. So, I made my own Docker image (based on `monetdb/vesselai`) and set `umask 7` before starting MonetDB. Unfortunately MonetDB still creates its database files with mode 600, i.e., no group access. This is problematic if the pod is restarted and gets a new uid, which can no longer access the database (which is on a persistent volume).

Generally, applications are not expected to change umask.

**Comment by njnes** [comment]
"Generally, applications are not expected to change umask", but secure systems do.
Generally, applications aren't run as user root or require files to be group readable (while on the user needs access).
Ie your blaming the wrong application here. Its the docker setup, which is broken.

**Comment by tkorvola** [comment]
There should be no need to run a database server as root, and I am not doing so. What is unusual in my setup is that the uid running MonetDB varies. I found a workaround that allows fixing it, but it is a bit cumbersome because I have to look up an available uid manually. The recommended way to arrange file permissions on OpenShift is via the group, but that does not work with MonetDB. I don't think it works with PostgreSQL either (it allows giving read access to the group, but I think not write); maybe I'll take a look how people handle its OpenShift deployment.

**Comment by njnes** [comment]
i guess you should focus on podman instead of the security wise broken docker design.
