### ISSUE TITLE
Python UDF cannot have space in column names

### ISSUE THREAD

**Issue by ThanKarab** [MonetDB/MonetDB#7338]
**Describe the bug**
A python UDF cannot have space in a column name.

**To Reproduce**
Run the following queries:

```
CREATE TABLE table4("row id" INT);

INSERT INTO table4("row id") VALUES (1);

CREATE OR REPLACE FUNCTION
func1("row id" INT)
RETURNS
TABLE("transfer" CLOB)
LANGUAGE PYTHON
{   
    import json
    return json.dumps({"x":1})
};

SELECT * FROM func1((SELECT "row id" FROM table4));
```

The problem is caused from the space in the "row id" in the column name, in the signature of the udf.

**Expected behavior**
We should be able to provide a column in the udf signature that contains special characters, since it's inside double quotes.

**Software versions**
 - MonetDB version number [11.45.7]

**Comment by sjoerdmullender** [comment]
The function argument at the SQL level is available in the Python code as function argument.  The Python code cannot have spaces in variable names, so you cannot have a space in the argument name at the SQL level for Python language functions either.  The only problem I see here is therefore that the error message isn't too clear.

**Comment by ThanKarab** [comment]
Thanks a lot @sjoerdmullender , makes sense!
