### ISSUE TITLE
column which datatype is double couldn't group or aggregation in version 11.45.7

### ISSUE THREAD

**Issue by jingmhua** [MonetDB/MonetDB#7342]
**Describe the bug**
A column(data type is double) that has done four operations couldn't group by aggregation.  and pops up an error: "Query did not produce a result set."

**To Reproduce**
1) Create a table that has a column(data type is double), and insert some values into this table.
2-1) run the SQL below :
select column1  from (select column +10 as column1 from table ) tmp  group by column1
2-2) run the SQL below :
select sum(column1)  from (select column +10 as column1 from table ) tmp 

**Expected behavior**
Return the correct result set.

**Software versions**
 - MonetDB 11.45.7
 - Windows 10

**Comment by aris-koning** [comment]
Below and other variants seem to work fine on Sep2022. Are you using any special flags, builds, os/environments, etc?
```
START TRANSACTION;
CREATE TABLE foo (d DOUBLE);
INSERT INTO foo VALUES (10.0), (23.456), (3242.435);
SELECT column1 FROM (SELECT d +10 AS column1 FROM foo ) tfoo GROUP BY column1;
SELECT sum(column1) FROM (SELECT d +10 AS column1 FROM foo ) tfoo;
ROLLBACK;
```

Output:
```
auto commit mode: off
operation successful
3 affected rows
+--------------------------+
| column1                  |
+==========================+
|                       20 |
|                   33.456 |
|                 3252.435 |
+--------------------------+
3 tuples
+--------------------------+
| %1                       |
+==========================+
|                 3305.891 |
+--------------------------+
1 tuple
auto commit mode: on
```

**Comment by jingmhua** [comment]
Hi, @aris-koning 
I use the table above, which you created and inserted.
I run the SQL below:
1) SELECT distinct d +10 as column2  FROM (SELECT d, d +10 AS column1 FROM foo ) tfoo;
2) SELECT  d +10 as column2  FROM (SELECT d, d +10 AS column1 FROM foo ) tfoo group by column2;

both of them couldn't return any results.

**Comment by jingmhua** [comment]
![image](https://user-images.githubusercontent.com/48235764/205526059-7e796611-61c2-4e4f-9157-e88639939c53.png)

**Comment by njnes** [comment]
fixed was pushed on the sep2022 branch.
