### ISSUE TITLE
A bug where an exception occurs even though it is a query with normal syntax (Merge Table)

### ISSUE THREAD

**Issue by yourchikorita** [MonetDB/MonetDB#7347]
**Describe the bug**
An error occurs in the case of a merge table that contain remote tables. When executing a select query with the same column name and alias

**Server environment and version**
beestore server (server accessing remote table)
 - MonetDB 5 server 11.45.11 (Sep2022-SP1) (64-bit, 128-bit integers)

beestore1 server (server serving remote table)
 - MonetDB 5 server 11.45.11 (Sep2022-SP1) (64-bit, 128-bit integers) 

**To Reproduce**
1. DDL in beestore1 server

sql>
-- Create local table
CREATE TABLE alias_test (
dest String null,
dep_delay int null,
arr_delay String null
);

sql>
-- insert sample data
insert into alias_test values('AA', 20,5);
insert into alias_test values('AB', 30,6);
insert into alias_test values('AC', 40,7);

sql>
select
	dest as category,
	dep_delay as dep_delay,
	arr_delay as arr_delay
from alias_test  
order by dest desc limit 1

_There is no error._

2. DDL in beestore server

sql>
-- Create remote table
create remote TABLE alias_test (
dest String null,
dep_delay int null,
arr_delay String null
) on 'mapi:monetdb://beestore1:50000/bcsdb';

sql>

-- insert sample data
insert into alias_test values('AA', 20,5);
insert into alias_test values('AB', 30,6);
insert into alias_test values('AC', 40,7);

sql>
-- Checking the inserted data from remote table (same as above)
select
	dest as category,
	dep_delay as dep_delay,
	arr_delay as arr_delay
from alias_test  
order by dest desc limit 1

error occurred

>   Error: Exception occurred in the remote server, please check the log there
>    SQLState:  22000
>     ErrorCode: 0

here is the merovingian.log

> 2022-12-21 15:32:21 ERR bcsdb[40441]: #DFLOWworker1004: createExceptionInternal: ERROR: SQLException:remote.exec:(mapi:monetdb://monetdb@beestore2/bcsdb0) Identifier dep_delay doesn't exist
> 2022-12-21 15:32:21 ERR bcsdb[40441]: #DFLOWworker994: createExceptionInternal: ERROR: SQLException:remote.exec:(mapi:monetdb://monetdb@beestore3/bcsdb0) Identifier dep_delay doesn't exist
> 2022-12-21 15:32:21 ERR bcsdb[40441]: #DFLOWworker995: createExceptionInternal: ERROR: SQLException:remote.exec:(mapi:monetdb://monetdb@beestore1/bcsdb0) Identifier dep_delay doesn't exist
> 2022-12-21 15:32:21 ERR bcsdb[40441]: #DFLOWworker994: createExceptionInternal: ERROR: MALException:user.%3[37]:Exception occurred in the remote server, please check the log there
> 2022-12-21 15:32:21 ERR bcsdb[40441]: #DFLOWworker1004: createExceptionInternal: ERROR: MALException:user.%2[37]:Exception occurred in the remote server, please check the log there
> 2022-12-21 15:32:21 ERR bcsdb[40441]: #DFLOWworker995: createExceptionInternal: ERROR: MALException:user.%1[37]:Exception occurred in the remote server, please check the log there
> 

but,If the column name and alias are different, no error occurs.

select
	dest as category,
	dep_delay as dep_delay_diff,
	arr_delay as arr_delay_diff
from alias_test  
order by dest desc limit 1

**Expected behavior**
I would expect there is no error even if the column name and alias are the same in the merge table.

**Software versions**
- MonetDB 11.45.11
- OS and version:CentOS Linux release 7.4.1708
- Installed from release package or self-installed and compiled : both

**Comment by njnes** [comment]
A fix for this was added on the sep2022 branch (9fb6702e320f)
