### ISSUE TITLE
Subquery inside case always evaluated

### ISSUE THREAD

**Issue by PedroTadim** [MonetDB/MonetDB#7348]
**Describe the bug**
Hello everyone! A small optimization opportunity is missing here. In a case statement with an uncorrelated subquery, the subquery is being always evaluated when it shouldn't.

**To Reproduce**
Run the statements:

```
CREATE TABLE t0 (c0 BOOLEAN);
INSERT INTO t0(c0) VALUES (FALSE),(TRUE),(FALSE),(FALSE),(TRUE),(FALSE);
SELECT (CASE 0.0 WHEN 1.0 THEN (SELECT 1.0 FROM t0) END) FROM t0;
```
The SELECT query will trigger:
GDK reported error: BATsubcross: more than one match

**Expected behavior**
The subquery shouldn't be evaluated in this case and the query should output 6 NULL rows.

**Software versions**
 - MonetDB version number Sep2022
 - OS and version: Ubuntu 22.04
 - Installed from release package or self-installed and compiled

**Comment by aris-koning** [comment]
Hey @PedroTadim,

 I can reproduce it on Sep2022. Thanks for this Christmas present ;)

**Comment by njnes** [comment]
We now optimize the case/when statement. That doesn't reduce the left outer join to its left side jet.

**Comment by PedroTadim** [comment]
Done!
