### ISSUE TITLE
Dump only the schema of the database

### ISSUE THREAD

**Issue by MurikiGY** [MonetDB/MonetDB#7352]
In postgresql, when I need to get the schema of a database usually I use the pg_dump with the flag --schema-only to generate a short .sql file.
I searched but couldn't find anything like in monetdb and I think it wound be very usefull.

**Comment by njnes** [comment]
did you try msqldump -D ?

**Comment by MurikiGY** [comment]
Oh right, so --describe was to get the schema.
Thank you njnes.
