### ISSUE TITLE
MT_thread_del_mylock hanging in debug mode (win x64)

### ISSUE THREAD

**Issue by jmkinzer** [MonetDB/MonetDB#7354]
build: debug x64 windows from the current master branch

Running (say) example1 in the debugger results in an indefinite hang.

It is triggered by the lock owner check when in DEBUG mode:

#define LOCK_OWNER 1

I have traced the hang to the call/expansion of MT_lock_unset (MT_thread_del_mylock) made in BBPinsert per below:

gdk_bpp.c

`	i = BBP_free;
	assert(i > 0);
	BBP_free = BBP_next(i);

	if (lock) {
		MT_lock_unset(&GDKcacheLock); // hanging
	}
	/* rest of the work outside the lock */

	/* fill in basic BBP fields for the new bat */

	bn->batCacheid = i;
	bn->creator_tid = pid;
`

MT_thread_del_mylock:
...
`
			for (MT_Lock *l = w->mylocks; l; l = l->nxt) {
				if (l->nxt == lock) {
					l->nxt = lock->nxt;
					break;
				}
			}
`
...

**Comment by sjoerdmullender** [comment]
Is there a chance that not all files were compiled with the same options?  In particular, were all files compiled with debugging enabled (assertions enabled)?

**Comment by sjoerdmullender** [comment]
I am able to reproduce the problem.  I will have a closer look.

**Comment by sjoerdmullender** [comment]
Fixed in changeset [935dccb07bfd](https://www.monetdb.org/hg/MonetDB/rev/935dccb07bfd).
