### ISSUE TITLE
monetdb - monetdbd communication behaves strange when using -h <host>

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7355]
**Describe the bug**
I have 62 databases running in a docker container.

When using `monetdb status`, everything works fine.

When using `monetdb -h <host> -p <port> -P <passphrase> status` (pointing at localhost), 11 out of those 62 databases are not listed. For all the others, there is no difference.

I couldn't find anything different in the missing databases' metadata. 

When using the host explicitly on one of the problematic databases, I get a warning, for example:
```
# monetdb status demo06_default01
      name        state   health                        remarks
demo06_default01  R  1d   55%  3d  mapi:monetdb://d06bc7103e02:50000/demo06_default01

# monetdb -h localhost -p 50000 -P <passphrase> status demo06_default01
WARNING: failed to parse response from monetdbd: string does not contain scenarios: (null)
status: no such database: demo06_default01
```

With others databases I get different warnings: `string does not contain uri`, or `should not happen`.

**Software versions**
 - MonetDB v11.43.26
 - OS and version: Fedora 35
 - self-installed and compiled

**Comment by kutsurak** [comment]
Hi Roberto,

Are you using an image from monetdb's dockerhub, or something you built yourself? If it's the latter case, can you please share a version of the Dockerfile that shows more or less how you've set it up, and the command you use to startup the container?

**Comment by swingbit** [comment]
The Dockerfile is pretty simple:

```
FROM fedora:35

RUN dnf update -y
RUN dnf install -y \
    autoconf automake bison bzip2 bzip2-libs cmake coreutils file flex \
    gcc gdal-devel gdb geos-devel gettext-devel glibc-all-langpacks glibc-common hostname \
    langpacks-en less libcurl-devel libtool libuuid-devel libxml2-devel make openssl-devel \
    pcre-devel perl pip procps-ng proj-devel psmisc python python3-devel python3-numpy \
    readline readline-devel tar xz-devel zip zlib-devel zstd 

RUN pip install monetdb-pystethoscope boolean.py

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV TERM=xterm-256color
ENV LANG=en_US.utf8

COPY system-files /

RUN sh /config/compile.sh

ENTRYPOINT ["/config/bootstrap.sh"]
```

where `bootstrap.sh`  is as simple as
```
/opt/monetdb/bin/monetdbd start /var/lib/monetdb/dbfarm

sleep 2

for i in {30..0}; do
    echo 'Testing MonetDB connection ' $i
    /opt/monetdb/bin/monetdb status &> /dev/null
    if [ $? -ne 0 ] ; then
      echo 'Waiting for MonetDB to start...'
      sleep 1
    else
        echo 'MonetDB is running'
        break
    fi
done
if [ $i -eq 0 ]; then
    echo >&2 'MonetDB startup failed'
    # cleanup
    killall -9 monetdbd
    exit 1
fi

tail --pid=$(cat /var/lib/monetdb/dbfarm/merovingian.pid) -f /dev/null
```

I attached gdb and noticed that while the string sent to `monetdb` is normally something like:
```
sabdb:2:demo09_default01,mapi:monetdb://d06bc7103e02:50000/demo09_default01,0,1,mal'sql'msql,49,28,20,402278,6022951,0,1669970820,1675180575,1665487686,0,0.700000,0.433333
```
for the databases that don't show up (when using `-h`), it is truncated to 90 characters:
```
sabdb:2:demo07_default01,mapi:monetdb://d06bc7103e02:50000/demo07_default01,0,1,mal'sql'ms
```

That also explains why the error is not always the same. Depending on the length of the database name and of the hostname used (I tried `localhost`, `127.0.0.1`, `d06bc7103e02`), the string gets truncated at different positions, and it fails at different checks in `msab_deserialise`.

**Comment by swingbit** [comment]
BTW, this is not a real issue for me in practice, I'm not even sure why one of my scripts was using `-h localhost`. I'll change it to no host parameters.
