### ISSUE TITLE
Cann't create a table which has a column name starts with %

### ISSUE THREAD

**Issue by jingmhua** [MonetDB/MonetDB#7356]
**Describe the bug**
Cann't create a table which has a column name starts with %

**To Reproduce**
CREATE TABLE wyn.newtable24 ("% of Completion" varchar(100));

**Expected behavior**
create table successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/48235764/216276109-8c0b3f9f-ee43-47a2-8fe7-c49ba985880c.png)

**Software versions**
v11.45.13  
windows 10

**Comment by mvdvm** [comment]
This is a current restriction of MonetDB for double quoted identifier names, they may not start with a % character.
This also applies to identifier names for other SQL objects such as schemas, tables, users, functions, etc.

A workaround could be to add a space before the %, so:
CREATE TABLE newtable23 (" % of Completion" dec(5,2));

**Comment by mvdvm** [comment]
FYI: I have updated the documentation on identifier names with the current restrictions.
See: https://www.monetdb.org/documentation/user-guide/sql-manual/lexical-structure/

**Comment by jingmhua** [comment]
Thank you for your response.
