### ISSUE TITLE
Cyclic queries (create, select, drop) exhausting memory and throwing errors

### ISSUE THREAD

**Issue by ThanKarab** [MonetDB/MonetDB#7357]
**Describe the bug**
Running a simple cycle of queries (create, select, drop) makes MonetDB consume a lot of memory and when it reaches it's limit it starts throwing exceptions.

**To Reproduce**
I am assigning `vmmaxsize=2000000` but I don't think this is required.
Then I run the following script:
```
from time import sleep

import pymonetdb

def get_sql_queries():
    return [
        "DROP VIEW IF EXISTS temp_view1;",
        "DROP VIEW IF EXISTS temp_view2;",
        "DROP TABLE IF EXISTS temp; ",
        "CREATE TABLE IF NOT EXISTS temp (c1 INT, c2 INT, c3 INT);",
        "INSERT INTO temp (c1, c2, c3) VALUES (1, 2, 3),(1,2,3); ",
        "CREATE OR REPLACE VIEW temp_view1 AS SELECT c1, c2, c3 FROM temp;"
        "CREATE OR REPLACE VIEW temp_view2 AS SELECT c1, c2, c3 FROM temp;"
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "SELECT * FROM temp_view1, temp_view2;"
        "DROP VIEW IF EXISTS temp_view1;",
        "DROP VIEW IF EXISTS temp_view2;",
        "DROP TABLE IF EXISTS temp; ",

    ]


def create_connection():
    return pymonetdb.connect(
        hostname="localhost",
        port="50000",
        username="monetdb",
        password="monetdb",
        database="db",
    )


def execute_query(_connection, query):
    cur = _connection.cursor()
    cur.execute(query)
    cur.close()
    _connection.commit()


def execute_query_loop():
    connection = create_connection()
    for i in range(1000):
        try:
            for query in get_sql_queries():
                execute_query(connection, query)

            print(f"Done! {i}")
        except (BrokenPipeError) as exc:
            connection = create_connection()
            print(exc)
            sleep(1)
        except Exception as exc:
            print(exc)
            if connection:
                connection.rollback()
            sleep(1)
    connection.close()


if __name__ == '__main__':
    execute_query_loop()

```

**Expected behavior**
Since the queries are actually a cycle leaving no tables behind I would expect that these queries could run in a never ending cycle.

**Software versions**
 - MonetDB version number `Sep2022-SP2 Bugfix Release (11.45.13)`
 - OS and version: Ubuntu 20.04
 - Installed from release package

**Comment by sjoerdmullender** [comment]
My guess is that the log manager thread, which is responsible for cleaning up, can't run because there is basically always an active transaction making a bigger "mess".
The log manager thread wakes up every once in a while and checks if there is work to do and whether it can actually do that work (no active transactions), but if another thread is always hard at work creating and dropping tables, there is basically always another transaction busy.
This means the changes accumulate and the dropped tables remain in the system.
Also, all the BATs involved are dirty, so they don't get deleted from memory.  The lower level that would be responsible for that could do that, but only after writing the data to disk in order to saveguard it (that level doesn't know that the SQL level dropped the tables).  This is not currently done.
For now, the solution is to give the log manager a chance to clean things up, but this is something we should probably take another look at.

**Comment by swingbit** [comment]
Sorry for the intrusion, just to mention that if I read correctly this is related to #7349. Not so much about the timing aspect, but about the "no active transactions" part.

**Comment by njnes** [comment]
Seems some issue with the interplay between result sets being kept at the server and the pymonetdb not signaling the end of usages. 
Try running with the following adapted version of execute_query.

```
def execute_query(_connection, query):                                                                                                                                                      
    cur = _connection.cursor()                                                                                                                                                              
    cur.execute(query)                                                                                                                                                                      
    cur._must_close_resultset = True                                                                                                                                                        
    cur.close()                                                                                                                                                                             
    _connection.commit()   
```

**Comment by ThanKarab** [comment]
Hello @njnes , this fixes the problem. Care to explain a bit more?

**Comment by njnes** [comment]
Each query with a results set is kept on the server side. For small result a single full result is enough, ie then the server
directly removes the resources taken by the result set. For larger result the client should sent a Xclose, ie signalling that the result set can be removed. This is normally automatically done, but some how the _must_close_resultset flag isn't set correctly (probably some difference between the replysize the client/server th
inks they have.

**Comment by ThanKarab** [comment]
So should we set `_must_close_resultset` always to `True` or there is a reason sometimes it's false?

**Comment by joerivanruth** [comment]
No, it's an internal variable that should get set automatically when appropriate but apparently there is a bug in pymonetdb. I will look into this today and will release an updated pymonetdb version soon.
So you can put the `_must_close_resultset = True` in your code today to bridge that gap but please don't get into the habit of doing it all the time, forever.

A bit of context: when a query has a large result set the server only sends the first N rows, the rest are sent only when the client explicitly requests them. When the client is done it should close the result set so the server can discard it server side.
However, there is a special case, if the result set is small and everything got sent the first time, the result set is closed implicitly and the client doesn't have to. The cursor field _must_close_result keeps track of whether this was the case.
Unconditionally setting it to True will cause the client to make unnecessary roundtrips to close resultsets that were already closed. I even worry a little if it might not accidentally end up closing the wrong result set when the result set numbers are reused, so please use the workaround sparingly.

**Comment by joerivanruth** [comment]
**Sherlock Holmes and the case of the mysterious missing comma**

If you look closely at your example script, near line 23 you will see
```
        "INSERT INTO temp SELECT * FROM temp_view1;",
        "SELECT * FROM temp_view1, temp_view2;"
        "DROP VIEW IF EXISTS temp_view1;",
```
Note that the line with the `SELECT` does not end in a comma
This causes Python to concatenate it and the next line into a single string: "SELECT ...; DROP VIEW ...;". 
Executing this yields two results: a result set from the SELECT and an affected row count from the DROP VIEW.
Unfortunately pymonetdb is not great at dealing with multiple results, and it forgets to close the result set.

My plan is to improve pymonetdb to properly deal with multiple result sets, but that will take some time. In the mean time I expect that the problem will go away if you add the missing comma.
