### ISSUE TITLE
updated MonetDB jdbc driver version 3.2 (Liberica 20230221)  cant connect to server

### ISSUE THREAD

**Issue by trgwarrenmaster** [MonetDB/MonetDB#7358]
**Describe the bug**
upcon connection to server recieving "Server challenge string unusable! It contains too few (1) tokens: "

**To Reproduce**
                        final String dbUrl = "jdbc:monetdb://vuatmdb:50000/trg?so_timeout=10000";
			final String userName = "monetdb";
			final String password = "xxxxx";
                       Class.forName("org.monetdb.jdbc.MonetDriver");
	               Connection conn = DriverManager.getConnection(dbUrl, userName, password);

java.sql.SQLNonTransientConnectionException: Server challenge string unusable! It contains too few (1) tokens: 
	at org.monetdb.jdbc.MonetConnection.<init>(MonetConnection.java:354)
	at org.monetdb.jdbc.MonetDriver.connect(MonetDriver.java:152)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247

**Expected behavior**
to get a valid connection 

**Screenshots**

**Software versions**
MonetDB 5 server v11.45.13 (Sep2022-SP2)
centos 3.10.0-1160.83.1.el7.x86_64

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**

**Comment by trgwarrenmaster** [comment]
it seems it happens in the second call to connect method on MapiSocket  when makeConnection=false is passed in 

else if (u.getScheme().equals("merovingian")) {
					// reuse this connection to inline connect to the
					// right database that Merovingian proxies for us
					warns.addAll(connect(host, port, user, pass, false));

**Comment by trgwarrenmaster** [comment]
on the recursive call to connect the reader is returning [, ]

**Comment by trgwarrenmaster** [comment]
in the prev jdbc driver the second and recursive call to connect the reader is returning
ywbtxCfH6:mserver:9:RIPEMD160,SHA512,SHA384,SHA256,SHA224,SHA1,COMPRESSION_LZ4:LIT:SHA512:sql=6:

**Comment by joerivanruth** [comment]
Hi Warren! I can reproduce this and will investigate.

**Comment by joerivanruth** [comment]
Hi Warren! I could reproduce this on our default branch but not on any released version. Is it correct that you were testing the latest unreleased development version? If so, I believe I've fixed it there. If you encountered this problem in a released version, please let me know so I can do more digging.

Joeri

**Comment by trgwarrenmaster** [comment]
Yes I built from truck.. wasn’t clear which branch are latest release is it v3.2-branch?.

Warren S. Master
Chief Technology Officer
212-984-3504
***@***.***

**Comment by joerivanruth** [comment]
Yes, 3.2 is still the latest, we're working towards 3.3 now. Could you confirm that the issue is gone on the latest commit on the default branch? If so, I believe we can close this issue. Thanks for spotting this!
Joeri

**Comment by trgwarrenmaster** [comment]
So I have been pulling from GIT https://github.com/MonetDB/monetdb-java.git  - I don’t see the commit there, I do see it in https://www.monetdb.org/hg/monetdb-java/

They both seem to be getting commits.

Warren S. Master
Chief Technology Officer
212-984-3504
***@***.***

**Comment by joerivanruth** [comment]
The Mercurial repo is the master, the GitHub repo is a mirror for convenience.
I don't know exactly at which times the mirror gets updated but in due course the commit should also show up on GitHub.

**Comment by trgwarrenmaster** [comment]
Ok that clears some things up for me, I will test it thanks!

Warren S. Master
Chief Technology Officer
212-984-3504
***@***.***

**Comment by trgwarrenmaster** [comment]
Looks like it just synced with git , the fix works !  thank you!!

Warren S. Master
Chief Technology Officer
212-984-3504
***@***.***

**Comment by joerivanruth** [comment]
Thank you, I'll close this issue then.
