### ISSUE TITLE
50% performance degradation from 11.39 to 11.41

### ISSUE THREAD

**Issue by supersteves** [MonetDB/MonetDB#7359]
The following query takes approx 50% longer after upgrading from 11.39 to 11.45. I believe 11.41 introduced the regression but am not 100% sure as it has taken a huge amount of debugging/diagnostics to come to this point already.

``` sql
select "stack", "measures" from (
    select "product_subcategory_" as "stack", 
      (median("line_price_") - median(- "line_price_")) / cast(2 as double) as "measures" 
    from "311f739f527DM_FULFile___2M__"
        where (
            "product_category_" = 'Health foods' 
            and "customer_region_" = 'ANZ' and "customer_gender_" = 'M'
            and "customer_date_of_birth_" <= timestamp '1970-04-28 00:00:00.000' 
            and "customer_date_of_birth_" >= timestamp '1937-08-01 23:00:00.000' 
        )
    group by "stack" order by "measures" desc, "stack" asc limit 101
) as "q" 
order by "stack" asc, "measures" desc;
```

This is being executed on 2 million rows of "line item" (standardised/generated) data.

Diffing the TRACE outputs highlights the differences below. (Note there is a marked difference between running immediately after creating data, and subsequently restarting mserver5 then running the query on already-existing data. In each of the 4 cases below I ran the trace query several times for numbers to stabilise.)

### 11.39
```
| 28806 | C_60=[243537]:bat[:oid] := algebra.thetaselect(X_31=[2000000]:bat[:str], C_54=[1143152]:bat[:oid], "Health foods":str, "==":str); # hashselect    |
|   344 | C_64=[670]:bat[:oid] := algebra.thetaselect(X_19=[2000000]:bat[:str], C_60=[243537]:bat[:oid], "ANZ":str, "==":str); # hashselect                 |
|   254 | C_67=[381]:bat[:oid] := algebra.thetaselect(X_10=[2000000]:bat[:str], C_64=[670]:bat[:oid], "M":str, "==":str); # select: fullscan equi strelim   |
```

_Here, restarting mserver5 makes no difference; it's around 30ms to apply these 3 string filters. The Gender field consistently uses `fullscan`._

#### (a) immediately after inserting
```
|  5640 |     C_59=[243537]:bat[:oid] := algebra.thetaselect(X_29=[2000000]:bat[:str], C_53=[1143152]:bat[:oid], "Health foods":str, "==":str); # select: fullscan equi strelim  |
|   841 |     C_63=[670]:bat[:oid] := algebra.thetaselect(X_17=[2000000]:bat[:str], C_59=[243537]:bat[:oid], "ANZ":str, "==":str); # select: fullscan equi strelim               |
|    41 |     C_66=[381]:bat[:oid] := algebra.thetaselect(X_10=[2000000]:bat[:str], C_63=[670]:bat[:oid], "M":str, "==":str); # select: fullscan equi strelim                    |
```

#### (b) after restarting mserver5
```
| 31381 |     C_59=[243537]:bat[:oid] := algebra.thetaselect(X_29=[2000000]:bat[:str], C_53=[1143152]:bat[:oid], "Health foods":str, "==":str); # hashselect on parent           |
|   368 |     C_63=[670]:bat[:oid] := algebra.thetaselect(X_17=[2000000]:bat[:str], C_59=[243537]:bat[:oid], "ANZ":str, "==":str); # hashselect on parent                        |
| 28199 |     C_66=[381]:bat[:oid] := algebra.thetaselect(X_10=[2000000]:bat[:str], C_63=[670]:bat[:oid], "M":str, "==":str); # hashselect on parent                             |
```

_Before restarting, it's actually faster than 11.39, around 16ms. **But**, after restarting, it's twice as slow at around 60ms, consistently. The Gender field is now consistently using `hashselect` in the new version post-restart._

I believe this is down to the change introduced in 
https://github.com/MonetDB/MonetDB/commit/c3ef00e6d24d9dc37a49124ac6c25493aae755a2 with the wanthash/needhash logic in gdk_select.c, but I'm not sure.  I'm trying to find a way to trick Monetdb to always use fullscan as per the older version, without luck. I've tried playing with `mserver5 --set no_hash_select_fraction=1` arg (and others) to no effect.

**Comment by sjoerdmullender** [comment]
It turns out that in the current code, if there is a hash on the parent bat, it will be used for an equi-select.  This is not at all the smart thing to do if there are many duplicates, espceially not if there is a candidate list.  The hash will give us all matching rows, but for each row we then need to check whether it is a candidate.
I will try to come up with an improvement to the algorithm.

**Comment by supersteves** [comment]
OK, makes sense. If you do manage to find an improvement, I can test it running from source, via a patch or revision.
