### ISSUE TITLE
Table data is lost on DB restart, but only when a table has 2147483647 or more rows.

### ISSUE THREAD

**Issue by seanhly** [MonetDB/MonetDB#7361]
I'm working with a database that has a few very long tables (lots of rows, only 3 columns).

I copy the CSV data for these tables into their MonetDB counterpart tables, i.e. via the MonetDB `COPY` command.

After doing this, I stop MonetDB (both the DB and the dbfarm), and then when I subsequently restart the DB, something strange happens: most of the tables are fine, but for any table with >= 2147483647 rows, the data becomes lost.

Given the proximity of 2147483647 to 2 ^ 31, I assume there is a misused 32 bit variable in the codebase.

To reproduce this bug:
```
monetdbd create overflow_dataloss_example
monetdbd start overflow_dataloss_example
monetdb create db
monetdb start db
monetdb release db
mclient db <<<"create table test_table(test_column int not null);"
mkfifo /tmp/data_pipe
mclient db <<<"copy into test_table from '/tmp/data_pipe' on client using delimiters ',', E'\n', E'\x06' no escape;" &
seq 2147483647 > /tmp/data_pipe
wait
mclient db <<<"select count(1) from test_table;"
# Should print 2147483647
monetdb stop db
monetdbd stop overflow_dataloss_example
monetdbd start overflow_dataloss_example
monetdb start db
mclient db <<<"select count(1) from test_table;"
# On my machine, this now prints 0 rather than the expected 2147483647
```
To re-iterate the "expected versus actual" behaviour: In the above example, rather than the last line printing 0, the expected behaviour would be for it to continue printing 2147483647 (i.e. no data loss).

You can repeat the experiment with one less row (214748364**6**), and you'll notice that the data is not lost in that case.

What's more, if data is loaded using a chunked approach (i.e. load in 2147483646 rows, restart the server, then repeat until all your data is loaded), then this issue does not arise.  If one of those chunks passes the 2147483646 mark, however, that part of the table data is again lost after the next restart.  This is somewhat encouraging because it means large tables can still be loaded in via a hacky chunked approach, but it would be nice to avoid the issue entirely, of course.

Software version: 11.45.7
I use an Intel i7 x86_64 processor, if that's relevant.

**Comment by njnes** [comment]
indeed a field had an int where a lng was needed.
