### ISSUE TITLE
Is there a way to cancel and/or view running jobs in MonetDB?

### ISSUE THREAD

**Issue by seanhly** [MonetDB/MonetDB#7362]
I've previously had issues in MonetDB when shutting down the database mid-SELECT.  This has previously caused corruption in the DB.

I was wondering... is there a way to gracefully cancel a SELECT query before shutting down?

If not, this also doubles as a feature request.

Best,
Seán

**Comment by sjoerdmullender** [comment]
Shutting down the database at whatever stage should never cause a corrupted database.  If it does, that is a bug.

When the server is busy executing a query when it gets a stop signal (SIGINT or SIGTERM -- these are the normal ways), the query is aborted at its earliest convenience.  Long running lower-level instructions check from time to time whether they should stop (and this is one of the possible conditions) and then raise an (internal) error.  This means that the server should stop fairly quickly, but not immediately.

**Comment by seanhly** [comment]
Just out of curiosity, which signal is sent when `monetdb stop db` is called?  SIGINT or SIGTERM (or something else)?

**Comment by sjoerdmullender** [comment]
SIGTERM.

**Comment by mvdvm** [comment]
To stop a (long) running query/statement use SQL: 
 `call sys.stop(tag);`
See doc: https://www.monetdb.org/documentation/admin-guide/monitoring/sys-queue/

**Comment by mvdvm** [comment]
To view running queries use query:
`select * from sys.queue where status = 'running';`
This will show the running queries. 
The first column `tag` shows the query id which can be used to pause, resume or stop that specific query.
See also: [https://www.monetdb.org/documentation/admin-guide/monitoring/sys-queue/](https://www.monetdb.org/documentation/admin-guide/monitoring/sys-queue/)
This way you do not need to shut down the whole server to stop any long running query.
Hope this answers your questions.

For the corrupted DB issue, please enter a new issue. Also include MonetDB version and OS/platform used.

**Comment by seanhly** [comment]
This works great, thanks mvdvm!
