### ISSUE TITLE
[Upgrade Error] 11.41.5 to 11.43.23

### ISSUE THREAD

**Issue by jingmhua** [MonetDB/MonetDB#7366]
I first create a schema name test for example and create and insert some data  in version 11.41.5
after that, I install 11.43.23. It occurs an error below, In this case, how can we fix it as fast as possible? :

[ERROR]: #main thread: BBPrename: !ERROR: name is in use: 'sql_seqs_val'.
[ERROR]: #main thread: mvc_init: !ERROR: Unable to create system tables
[ERROR]: #main thread: createExceptionInternal: !ERROR: SQLException:SQLinit:42000!Catalogue initialization failed
[ERROR]: #main thread: SQLprelude: !ERROR: Fatal error during initialization: SQLException:SQLinit:42000!Catalogue initialization failed

**Comment by aris-koning** [comment]
Hi,

I have executed the sql statements below on a tip of Jul2021 then  upgrade that to the tip of Jan2022 with and without a filled Write-Ahead-log and I didn't caught any problems.
```
create schema foo;
set schema foo;
create table bar(i) as values (10);
```

You might try to first upgrade from your current Jul2021 version to the latest servicepack Jul2021-SP9 Bugfix Release (11.41.31). Then do an upgrade from there to Jan2022.
If that doesn't work, maybe you can post a more detailed reproduction description. But given the age of these versions and severity you might want to consider the commercial support channels to find more suitable help for your problem.

Regards
