### ISSUE TITLE
Is there a way to find which port my instance is using?

### ISSUE THREAD

**Issue by nevesLiliane** [MonetDB/MonetDB#7368]
**Is your feature request related to a problem? Please describe.**
I'm running two instances in monetdb, and when I start my dbfarm, they sometimes go to 50001 and 50002, and other times they go to 50000 and 50001.

I don't really care for which port the instances run, but I would like to know if there is a way to find it out without trial and error. When I run monetdbd status, it always shows both instances on port 50000. And I'm using monetdb through a container

**Comment by kutsurak** [comment]
Hi @nevesLiliane 

I am not sure I understand the question. MonetDB daemon (`monetdbd`) by default listens on port 50000, so if you have not changed it with `monetdbd set port=<port num> <dbfarm>`, all the databases it manages are accessible through port 50000. For example in my machine I get this:

```
$ monetdbd create /tmp/dbfarm
$ monetdbd start /tmp/dbfarm

$ monetdb create -p monetdb db1
created database with password for monetdb user: db1

$ monetdb create -p monetdb db2
created database with password for monetdb user: db2

$ monetdb start db1
starting database 'db1'... done

$ monetdb start db2
starting database 'db2'... done

$ monetdb status
name  state   health                       remarks
db2   R  3s  100%  1s  mapi:monetdb://panoramix:50000/db2
db1   R  5s  100%  1s  mapi:monetdb://panoramix:50000/db1

$  mclient -d db1 -p 50000
Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)
Database: MonetDB v11.46.0 (hg id: a61352a73d3d), 'mapi:monetdb://panoramix:50000/db1'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>

$ mclient -d db2 -p 50000
Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)
Database: MonetDB v11.46.0 (hg id: a61352a73d3d), 'mapi:monetdb://panoramix:50000/db2'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>
```

The container might complicate things a little bit because you might need to expose and map internal to external ports. I don't know which container engine you use, but for docker see https://docs.docker.com/engine/reference/builder/#expose and https://docs.docker.com/engine/reference/run/#expose-incoming-ports.

**Comment by nevesLiliane** [comment]
Hey, thanks for your answer. I tried running your example and it worked, but if I don't set the password in the create statement, it doesn't work. Do you have any idea why?

**Comment by nevesLiliane** [comment]
I tried extending your example doing the same thing for two more instances(`database.sif` is the container image that runs monetdb)
```
$ ./../database.sif monetdb start db2
starting database 'db2'... done

./../database.sif monetdb start dataflow_analyzer
starting database 'dataflow_analyzer'... done

$ ./../database.sif monetdb start dfa_server_db
starting database 'dfa_server_db'... done

$ ./../database.sif monetdb status
      name         state   health                           remarks
dfa_server_db      R  9s  100%  0s  mapi:monetdb://liliane-iMac20-1:50000/dfa_server_db    
db2                R 38s  100%  0s  mapi:monetdb://liliane-iMac20-1:50000/db2              
db1                R 57s  100%  0s  mapi:monetdb://liliane-iMac20-1:50000/db1              
dataflow_analyzer  R 24s  100%  0s  mapi:monetdb://liliane-iMac20-1:50000/dataflow_analyzer

$ ./../database.sif mclient -d db1 -p 50000

Welcome to mclient, the MonetDB/SQL interactive terminal (Sep2022-SP2)
Database: MonetDB v11.33.11 (Apr2019), 'mapi:monetdb://liliane-iMac20-1:50000/db1'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>\q


$ ./../database.sif mclient -d db2 -p 50000
Welcome to mclient, the MonetDB/SQL interactive terminal (Sep2022-SP2)
Database: MonetDB v11.33.11 (Apr2019), 'mapi:monetdb://liliane-iMac20-1:50000/db2'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>\q
```
But when I try `dataflow_analyzer` and `dfa_server_db` I get:
```
$ ./../database.sif mclient -d dataflow_analyzer -p 50000
monetdbd: an internal error has occurred 'cannot connect: Connection refused', refer to the logs for details, please try again later

$ ./../database.sif mclient -d dfa_server_db -p 50000
monetdbd: an internal error has occurred 'cannot connect: Connection refused', refer to the logs for details, please try again later
```

Looking at the logs for details I found an interesting thing, `dataflow_analyzer` and `dfa_server_db` have string connections that as distinct from the pattern of `db1` and `db2`, 

`dataflow_analyzer` and `dfa_server_db`  are `mapi:monetdb://127.0.0.1:50001/?database=dataflow_analyzer` and `mapi:monetdb://127.0.0.1:50002/?database=dfa_server_db`, meanwhile `db1` and `db2` are `/data/db1/.mapi.sock?database=db1` and `/data/db1/.mapi.sock?database=db2`

I have not set this thing, please help, the the log as follows:

```
2023-05-02 17:33:25 MSG merovingian[45099]: proxying client (local) for database 'db1' to mapi:monetdb:///home/liliane/Documentos/Doutorado/provdeploy/server/recipes/database/DfAnalyzer/data/db1/.mapi.sock?database=db1
2023-05-02 17:33:25 MSG merovingian[45099]: target connection is on local UNIX domain socket, passing on filedescriptor instead of proxying
2023-05-02 17:33:38 MSG merovingian[45099]: proxying client (local) for database 'db2' to mapi:monetdb:///home/liliane/Documentos/Doutorado/provdeploy/server/recipes/database/DfAnalyzer/data/db2/.mapi.sock?database=db2
2023-05-02 17:33:38 MSG merovingian[45099]: target connection is on local UNIX domain socket, passing on filedescriptor instead of proxying
2023-05-02 17:33:54 MSG merovingian[45099]: proxying client (local) for database 'dataflow_analyzer' to mapi:monetdb://127.0.0.1:50001/?database=dataflow_analyzer
2023-05-02 17:33:54 ERR control[45099]: !monetdbd: an internal error has occurred 'cannot connect: Connection refused'
2023-05-02 17:33:54 MSG merovingian[45099]: starting a proxy failed: cannot connect: Connection refused
2023-05-02 17:33:59 ERR merovingian[45099]: client error: cannot connect: Connection refused
2023-05-02 17:34:12 MSG merovingian[45099]: proxying client (local) for database 'dfa_server_db' to mapi:monetdb://127.0.0.1:50002/?database=dfa_server_db
2023-05-02 17:34:12 MSG merovingian[45099]: starting a proxy failed: cannot connect: Connection refused
2023-05-02 17:34:12 ERR control[45099]: !monetdbd: an internal error has occurred 'cannot connect: Connection refused'
2023-05-02 17:34:17 ERR merovingian[45099]: client error: cannot connect: Connection refused
```

**Comment by kutsurak** [comment]
Thank you for the extra information. I would like to know a couple of things in order to figure out what is happening:

- What is `database.sif` doing? 
- You mentioned that these are running in a container. Can you elaborate on how the container is setup? Specifically:
  + are you running just one container with all the databases?
  + are you using the official MonetDB image from [dockerhub](https://hub.docker.com/r/monetdb/monetdb/tags)?
  + if not, can you provide the Dockerfile used to build the container?

**Comment by nevesLiliane** [comment]
Hi, thanks for your time. `database.sif` is a container image that runs monetdb. I use this image to run all the databases and this image is my own, I wrote it some time ago with singularity. I did that because the official image was not working at the time. I had a dockerfile in the beginning, but now I only use singularity, the recipe is:

```

BootStrap: docker
From: ubuntu:18.04


%files

    monetdb.list                 /home
    
%environment
    
  export LC_ALL="en_US.UTF-8"
  export LANG="en_US.UTF-8"

%post
	
  apt-get update && apt-get install -y gnupg2 ca-certificates wget
  cp /home/monetdb.list /etc/apt/sources.list.d
  wget --output-document=/etc/apt/trusted.gpg.d/monetdb.gpg https://www.monetdb.org/downloads/MonetDB-GPG-KEY.gpg 

  apt update 
  apt install monetdb5-sql=11.33.3 monetdb-client  monetdb5-server=11.33.3 -y
  
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y -q software-properties-common
  apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
  
  apt update && apt-get install unzip
  
 
%runscript

    exec "$@"

%setup

  #Create a work directory inside the container
  WORKDIR="$SINGULARITY_ROOTFS/liliane"
  mkdir -p $WORKDIR
  mkdir -p $WORKDIR/home/

  if [ ! -x "$WORKDIR" ]; then
    echo "failed to create tempdir directory..."
    exit 1
  fi
  chmod -R 777 $WORKDIR
 
  exit 0
```

I don't have a dockerfile for this. Sorry

**Comment by kutsurak** [comment]
OK, I am not familiar with singularity. I actually first heard about it from your comment. From a very brief look at their documentation I don't think that it is the cause of your issue.

My best guess is that the databases that are having the issue were not created using `monetdb`, or there was some configuration peculiarity at creation time. To verify this I would execute the following command: `ps -wwfC mserver5` after all databases have been started, but I am not sure if this will work with singularity.

So, the difference between `db1`, `db2` and `dataflow_analyser`, `dfa_server_db` is that the former talk to the daemon through a unix socket, while the latter are listening for tcp connections. I am not sure how this happened. One sure way to fix it is to re-create the databases using `monetdb` as you did for `db1` and `db2` and copy the data over.
