### ISSUE TITLE
timestamp_to_str function not aware of timezone

### ISSUE THREAD

**Issue by lrpereira** [MonetDB/MonetDB#7370]
timestamp_to_str function is not outputting, defaults to server time, which is UTC.

**To Reproduce**
select timestamp_to_str(current_timestamp, '%d/%m/%Y %H:%M:%S');

**Expected behavior**
Output localtime

![image](https://user-images.githubusercontent.com/11319826/236195194-c82e3f32-44bf-4b5c-893c-a510f94650ff.png)
Kepp in mind that my time at the moment of the screenshot is 1:48 PM CEST (UTC+2) (+2 due to DST).

**Software versions**
 - MonetDB default branch
 - OS and version: Fedora 37
 - Self-installed and compiled

**Comment by sjoerdmullender** [comment]
There were no relevant changes, so this is still an issue.
I think we need to do some work on pushing the timezone information down to the correct levels so that this function does the right thing.

**Comment by njnes** [comment]
the timestamp with timezone -> timestamp conversion simply drops the tz info and does no timestamp correction.

**Comment by njnes** [comment]
this is fixed in the cleanup_types branch, to be merged into default soon.
