### ISSUE TITLE
Grouping scope issue

### ISSUE THREAD

**Issue by PedroTadim** [MonetDB/MonetDB#7371]
**Describe the bug**

A column cannot be found for GROUP BY after a join clause with USING.

**To Reproduce**

Run these queries:
```
CREATE TABLE t0 (c0 INT);
SELECT 1 FROM t0 JOIN t0 tx USING (c0) GROUP BY t0.c0;
--error, SELECT: no such column 't0.c0'
```

**Expected behavior**
The SELECT query should run successfully, instead it cannot find the column 't0.c0'

**Software versions**
 - MonetDB Jun2023
 - OS and version: Ubuntu 22.04
 - Self-installed and compiled

**Comment by njnes** [comment]
Because of the 'using' only one column c0 exists, which has no corresponding table name anymore. ie. correct query is: 
SELECT 1 FROM t0 JOIN t0 tx USING (c0) GROUP BY c0;

**Comment by PedroTadim** [comment]
Same issue happens with the projection case: `SELECT t0.c0 FROM t0 JOIN t0 tx USING (c0);` Other DBMS allow these queries, because USING is just a condition, then both relations columns should still be visible.

**Comment by njnes** [comment]
select * from t0 join t0 tx using (c0) group by c0; returns a single column c0. You probably need 
join on t0.c0 = tx.c0. The other DBMS is simply wrong here.

**Comment by PedroTadim** [comment]
Sure, we can keep it as it is :)
