### ISSUE TITLE
Inconsistent behaviour with ambiguous identifiers

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7372]
**Describe the bug**
The check for ambiguous identifiers does not seem to work consistently. In particular, its behaviour changes depending on the the number/order of joins and presence of aggregations.

**To Reproduce**
Schema:
```
create table test (a INT);
```

Ambiguous identifier `a` not identified:
```
-- a, b, c, d, e, with SUM
sql>select SUM(a) from test a, test b, test c, test d, test e;
+------+
| %1   |
+======+
| null |
+------+
1 tuple

```

Ambiguous identifier `a` correctly identified:
```
-- a, b, c, d, e (removed SUM)
sql>select a from test a, test b, test c, test d, test e;
SELECT: identifier 'a' ambiguous

-- a, c, d, e  (removed b)
sql>select SUM(a) from test a, test c, test d, test e;
SELECT: identifier 'a' ambiguous
```

**Expected behavior**
Identifier `a` is semantically ambiguous in all the queries above. The ambiguity should not depend on the specific plan generated.

**Software versions**
 - MonetDB version number 11.43.26
 - Fedora 38
 - self-installed and compiled

**Comment by njnes** [comment]
Seems fixed in the Sep2022 and Jun2023 versions

**Comment by swingbit** [comment]
ah ok. Good enough for me. It's just something I noticed but doesn't bother me that much.
