### ISSUE TITLE
Calculate the null percentage

### ISSUE THREAD

**Issue by MurikiGY** [MonetDB/MonetDB#7373]
Currently, I'm working on a project that requires me to determine the number of null values in a dataset.
I have searched through statistical tables and previous issues, but unfortunately, I haven't found any relevant information.
One possible calculation method could be taking the simple average of the column, such as (column_null_count) divided by (column_rows_count). 
This is similar to the column "null_frac" in the "pg_stats" table in PostgreSQL.

Would that information be somewhere in the database?

**Comment by lrpereira** [comment]
Hey @MurikiGY,

Follow the link below and notice in specific the predicate `IS NULL`:
https://www.monetdb.org/documentation-Sep2022/user-guide/sql-functions/comparison-functions/#comparison-predicates

You're able to compute a count based on the predicate.

ex: `select count(*) from foo where x IS NULL;`

**Comment by MurikiGY** [comment]
But `select count(*) from foo where x is NULL` will only return me the number of rows that are null and I need the percentage of NULLs from all the columns in all tables in the database.

I could make a bash script to do this query and calculate the percentage, but it would be better if the calculations were inside the DBMS, returning all the data at once.

Can Monetdb do this?

**Comment by lrpereira** [comment]
Hey @MurikiGY ,

Not out of the box as you expected.
We do have some functionality for gathering some statistics around the datasets that are in use but NULL percentage is not one of them.

**Comment by MurikiGY** [comment]
I see, so the way for now will be bash.

Thanks for the help @lrpereira

Do I close the issue? or I leave it open in case it is decided to implement the percentage.

**Comment by lrpereira** [comment]
I had a discussion with the team and this is not in the near futures plan to be implemented.
A combination of SQL and/or Python tailored to the user needs is the best way to go.
For now I'll close it and if opinions change in the future, this will be reopened.

Best regards @MurikiGY

**Comment by mvdvm** [comment]
This can be done completely in SQL using:
select cast(count(*) * 100.0 / (select count(*) from "tables") as decimal(6,3)) as query_prc_null
 from "tables" where "query" IS NULL;
This results in something like: 30.769
The decimal(6,3) can be used to control the number of decimals of the percentage, which is 3 in this example. Use decimal(3,0) if you want no decimals, so range 0 .. 100.

So no need for bash or Python.

**Comment by mvdvm** [comment]
This can be done completely in SQL using:
```
select cast(count(*) * 100.0 / (select count(*) from tables) as decimal(6,3)) as query_prc_null
 from tables where "query" IS NULL;
```
This results in something like: 30.769
The decimal(6,3) can be used to control the number of decimals of the percentage, which is 3 in this example. Use decimal(3,0) if you want no decimals, so range 0 .. 100.

So no need for bash or Python.
