### ISSUE TITLE
Concurrency Issue: Second Python UDF Awaits Completion of First UDF

### ISSUE THREAD

**Issue by KFilippopolitis** [MonetDB/MonetDB#7376]
**Describe the bug**
Currently, there is a concurrency issue with the Python UDFs where the second UDF execution is delayed until the first UDF completes. This behavior occurs when running a second Python UDF while the first UDF is still running. The second UDF appears to be waiting for the first UDF to finish before executing.

**To Reproduce**
  Provided two files containing the UDFs.
  Execute the "while_true_udf" function, which will run indefinitely.
  On a separate mclient, execute the "simple_udf" query.

**Expected behavior**
The simple_udf function should be able to run independently of the while_true_udf UDF and should not wait for its completion, although it runs in a separate process.

[while_true_udf.txt](https://github.com/MonetDB/MonetDB/files/11615417/while_true_udf.txt)
[simple_udf.txt](https://github.com/MonetDB/MonetDB/files/11615418/simple_udf.txt)

**Software versions**
 - MonetDB 11.45.13
 - Ubuntu 20.04

**Comment by njnes** [comment]
your while_true runs protected by the GIL (python global lock), ie any other python code will have to wait.
Current use of the 'default' python has these limitations.

**Comment by johnfouf** [comment]
I think in this case it is different. Mainly GIL affects python code that runs in multiple threads but in the same process. 
In this case, we have the python UDF running in a separate process but still it hangs. GIL shouldn't have to do with this.

**Comment by kutsurak** [comment]
Both UDFs are running on the monetdb server, that is in the same process using the same Python interpreter. It does not matter that they were started by different mclient processes.

I am not 100% sure that the problem is the python GIL, but I strongly suspect that @njnes is correct.

**Comment by johnfouf** [comment]
The issue is that in top I can see a second mserver5 process starting when issuing the second UDF. 
Also in pyapi3.c I see the following from line 435:

               MT_lock_set(&pyapiLock);
		gstate = Python_ObtainGIL(); // we need the GIL before forking,
									 // otherwise it can get stuck in the forked
									 // child
		if ((pid = fork()) < 0) {
			msg = createException(MAL, "pyapi3.eval", SQLSTATE(PY000) "Failed to fork process");
			MT_lock_unset(&pyapiLock);
			goto wrapup;

In my understanding, it seems that we are in this case, with the second process that finally gets stucked.

**Comment by kutsurak** [comment]
Actually, I was not able to reproduce the issue with a Debug build of mercurial changeset `e8b0e5558313` (aka version 11.45.13) on Arch Linux. I am going to try the actual release on an Ubuntu 20.04 VM, but meanwhile, can you please show me which packages you have installed?

**Comment by kutsurak** [comment]
Also, do you use the monetdb daemon to manage the databases? This specifically should not matter but I am trying to reproduce your issue. What commands do you use to run the UDFs?

**Comment by kutsurak** [comment]
Cannot reproduce on the VM either: 

Start monetdbd
create database
connect mclient 1
connect mclient 2
execute script while_true_udf.txt on mclient 1 -> waits forever
execute script simple_udf.txt on mclient 2 -> returns 1 tuple

**Comment by johnfouf** [comment]
This is strange. I am using ubuntu 20.04 with monetdb 11.45.13
Source installation with cmake, and then :

monetdbd create paralleldb
monetdbd set port=53000 paralleldb
monetdbd set listenaddr=0.0.0.0  paralleldb
monetdbd start paralleldb
monetdb  -p 53000 create voc20
monetdb -p 53000 set embedpy3=true voc20
monetdb -p 53000 release voc20
monetdb -p 53000 start voc20

mclient -u monetdb -d voc20
>> while true pdf

mclient -u monetdb -d voc20
>> simple_udf

**Comment by kutsurak** [comment]
Can you show me how you configured and compiled monetdb? I am mostly interested in cmake arguments. Also what is the version of python and the python development library installed on the system?

**Comment by johnfouf** [comment]
cmake -DCMAKE_INSTALL_PREFIX=/home/johnfouf/monetdb11_45 ../
 cmake --build .
 cmake --build . --target install
 
 python 3.10.6 
 python3-dev is already the newest version (3.10.6-1~22.04)
 
 sorry in my system I have 22.04 with these specs, we had first encounter the issue in 20.04

**Comment by johnfouf** [comment]
An other hint: It does not hangs if the while true UDF just sleeps. In this case the second UDF finishes. 
Still there is a second process that is created. This behaviour seems like GIL. Gil works this way (but while in the same process) it does not seem to be a monetdb lock. 

So, if I simply remove the lines that locking/releasing GIL at lines 440,457 of pyapi3.c and recompile, it works also for original while true UDF but I possibly broke something else.   

If not able to reproduce, we could arrange a call for this if needed to share my screen/terminal.

**Comment by w-he** [comment]
Are there any updates on this? 

I'm trying out a variation where one UDF does queries in a loop and the other just does a single query. If the UDF running a single query is started while the first UDF is still running, it never finishes. 

[loop_ops.txt](https://github.com/MonetDB/MonetDB/files/11917684/loop_ops.txt)
[single_op.txt](https://github.com/MonetDB/MonetDB/files/11917685/single_op.txt)

**Comment by njnes** [comment]
we are thinking of removing the fork case. Without it your examples work. (Tested using global replace of HAVE_FORK -> HAVE_FORK_).

**Comment by ThanKarab** [comment]
@njnes What are the consequences of removing the fork?

**Comment by njnes** [comment]
The fork was a bad idea. Fork with exec is sort of okay, but fork with lots of semaphores/mutexes etc doesn't combine correctly.  Without the fork you will not have concurrent (process level) activity on the python interpreter level. So any python code (statements) will execute sequentialy. Accessing any c-code/library level functions will however run without the gil, ie your calls to ML functions shouldn't have any issues running in parallel.

**Comment by ThanKarab** [comment]
Ok, perfect, so this is going to be changed in the master?

**Comment by njnes** [comment]
Yes

**Comment by ThanKarab** [comment]
@njnes Shouldn't this be closed when a fix is merged in the master branch?

**Comment by njnes** [comment]
its checked in on the master, ie the hg branch https://www.monetdb.org/hg
the github mirror is currently broken.
