### ISSUE TITLE
MonetDB server 11.46.0 crashes at `BLOBcmp`

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7380]
**Describe the bug**
MonetDB server 11.46.0 crashes at `BLOBcmp` after executing SQL statements through mclient.

**To Reproduce**
```sql
CREATE TABLE a (p_id INT, p_name BLOB);
INSERT INTO a VALUES (1,NULL);
TRACE select * from a where p_name='Lilu';
```

**Expected behavior**
Executing statements successfully or throwing errors, instead of breaking down the whole MonetDB server.

**Backtrace**
```
#0 0x7f2b15259d39 (BLOBcmp+0x19)
#1 0x7f2b14b2a171 (prepareMalEvent+0x541)
#2 0x7f2b14b2b10f (sqlProfilerEvent+0x6f)
#3 0x7f2b14b152ec (runtimeProfileExit+0x11c)
#4 0x7f2b14b1ab01 (runMALsequence+0x1601)
#5 0x7f2b14b1d5d4 (DFLOWworker+0x2c4)
#6 0x7f2b15254ba0 (THRstarter+0x100)
#7 0x7f2b152c4cc4 (thread_starter+0x34)
#8 0x7f2b14639609 (start_thread+0xd9)
#9 0x7f2b1455e133 (clone+0x43)
```

**Software versions**
 - MonetDB server version: 11.46.0 (hg id: 63a42c2) (pulled from the master branch)
 - MonetDB client version: mclient, version 11.48.0 (hg id: 63a42c2)
 - OS and version: ubuntu 20.04
 - Self-installed and compiled. The command line of compilation: `CC=clang-12 CXX=clang++-12 cmake /root/monetdb_master -DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Issue labeling**
bug

**Additional context**
The MonetDB here runs in-memory database. The command line of starting MonetDB server is `mserver5 --in-memory`.

**Comment by mvdvm** [comment]
Is also reproducable with MonetDB 5 server v11.45.17 (Sep2022-SP3).

**Comment by njnes** [comment]
fixed in https://www.monetdb.org/hg/MonetDB/rev/559996556804
