### ISSUE TITLE
MonetDB server 11.46.0 crashes at `log_create_delta`

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7381]
**Describe the bug**
MonetDB server 11.46.0 crashes at `log_create_delta` after executing SQL statements through mclient.

**To Reproduce**
```sql
CREATE TABLE t1(unique_constraint INT PRIMARY KEY);
START TRANSACTION;
ALTER TABLE t1 ADD COLUMN uniq_c1_c2_c3 INT;
ALTER TABLE t1 DROP COLUMN uniq_c1_c2_c3;
COMMIT;
```

**Expected behavior**
Executing statements successfully or throwing errors, instead of breaking down the whole MonetDB server.

**Backtrace**
```
#0 0x7f19dc711703 (log_create_delta+0x23)
#1 0x7f19dc7116bd (log_create_col+0x1d)
#2 0x7f19dc6e088e (sql_trans_commit+0x36e)
#3 0x7f19dc6eb353 (sql_trans_end+0x83)
#4 0x7f19dc72e10c (mvc_commit+0x4fc)
#5 0x7f19dc65532c (SQLtransaction_commit+0x9c)
#6 0x7f19dc9a9c63 (runMALsequence+0x763)
#7 0x7f19dc9a931e (runMAL+0x9e)
#8 0x7f19dc6309f9 (SQLrun+0xd9)
#9 0x7f19dc631bee (SQLengineIntern+0x4e)
#10 0x7f19dc62f8c2 (SQLengine_+0x5e2)
#11 0x7f19dc62e343 (SQLengine+0x23)
#12 0x7f19dc9bd6cf (runScenario+0x4f)
#13 0x7f19dc9be16c (MSscheduleClient+0x68c)
#14 0x7f19dca65c2b (doChallenge+0xfb)
#15 0x7f19dd0e4ba0 (THRstarter+0x100)
#16 0x7f19dd154cc4 (thread_starter+0x34)
#17 0x7f19dc4c9609 (start_thread+0xd9)
#18 0x7f19dc3ee133 (clone+0x43)
```

**Software versions**
 - MonetDB server version: 11.46.0 (hg id: 63a42c2) (pulled from the master branch)
 - MonetDB client version: mclient, version 11.48.0 (hg id: 63a42c2)
 - OS and version: ubuntu 20.04
 - Self-installed and compiled. The command line of compilation: `CC=clang-12 CXX=clang++-12 cmake /root/monetdb_master -DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Issue labeling**
bug

**Additional context**
The MonetDB here runs in-memory database. The command line of starting MonetDB server is `mserver5 --in-memory`.

**Comment by mvdvm** [comment]
Is also reproducable with MonetDB 5 server v11.45.17 (Sep2022-SP3). It crashes at statement: `COMMIT;`
Without the `START TRANSACTION;` and `COMMIT;` it works fine.

**Comment by njnes** [comment]
fixed in https://www.monetdb.org/hg/MonetDB/rev/e51271824555
