### ISSUE TITLE
MonetDB server 11.46.0 crashes in `rel_sequences`

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7387]
**Describe the bug**
MonetDB server 11.46.0 crashes in `rel_sequences` after executing SQL statements through mclient.

**To Reproduce**
```sql
ALTER SEQUENCE x INCREMENT BY 2;
```

**Expected behavior**
Executing statements successfully or throwing errors, instead of breaking down the whole MonetDB server.

**Backtrace**
```
#0 0x7ff49bdd36d0 (rel_sequences+0x830)
#1 0x7ff49bdb10c1 (rel_semantic+0xc1)
#2 0x7ff49bc8eb53 (sql_symbol2relation+0x73)
#3 0x7ff49bca810d (SQLparser+0x37d)
#4 0x7ff49bca787b (SQLengine_+0x59b)
#5 0x7ff49bca6343 (SQLengine+0x23)
#6 0x7ff49c0356cf (runScenario+0x4f)
#7 0x7ff49c03616c (MSscheduleClient+0x68c)
#8 0x7ff49c0ddc2b (doChallenge+0xfb)
#9 0x7ff49c75cba0 (THRstarter+0x100)
#10 0x7ff49c7cccc4 (thread_starter+0x34)
#11 0x7ff49bb41609 (start_thread+0xd9)
#12 0x7ff49ba66133 (clone+0x43)
```

**Software versions**
 - MonetDB server version: 11.46.0 (hg id: 63a42c2) (pulled from the master branch)
 - MonetDB client version: mclient, version 11.48.0 (hg id: 63a42c2)
 - OS and version: ubuntu 20.04
 - Self-installed and compiled. The command line of compilation: `CC=clang-12 CXX=clang++-12 cmake /root/monetdb_master -DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Issue labeling**
bug

**Additional context**
The MonetDB here runs in-memory database. The command line of starting MonetDB server is `mserver5 --in-memory`.

**Comment by mvdvm** [comment]
Is also reproducable with MonetDB 5 server v11.45.17 (Sep2022-SP3).

**Comment by njnes** [comment]
fixed in https://www.monetdb.org/hg/MonetDB/rev/1c178a0881ef
