### ISSUE TITLE
Some MonetDB Server crashes found

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7390]
**Describe the bug**
The are 40 crashes found in MonetDB (node 95dba4e85799). **Some of them may be duplicate bugs.**
You can browse them here: [https://github.com/fuboat/BugList-MonetDB-95dba4e85799](https://github.com/fuboat/BugList-MonetDB-95dba4e85799)

The SQL statements to trigger them and the corresponding backtrace are shown in files listed in the `pocs` dir of the repository (01.sql ~ 40.sql).

I am not sure whether it is an appropriate way to report these bugs; if more information needs to be provide, or there are some questions or suggestions, please tell me.

**Software versions**
 - MonetDB 5 server v11.48.0 (hg id: 95dba4e85799 88693) (download from the default branch of https://www.monetdb.org/hg/MonetDB/)
 - MonetDB client version: version 11.48.0 (hg id: 95dba4e85799 88693) 
 - OS and version: ubuntu 20.04
 - Self-installed and compiled. The full command line of compilation is as follow:
```bash
wget https://www.monetdb.org/hg/MonetDB/archive/default.zip
unzip ./default.zip
cd MonetDB-default/
mkdir build
cd build
CC=clang-12 CXX=clang++-12 cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
make install -j20
```

**To Reproduce**
 - Start the server in memory: `/usr/local/bin/mserver5 --in-memory`
 - Execute the files in the `pocs` dir of [this repository](https://github.com/fuboat/BugList-MonetDB-95dba4e85799) through mclient. For example: `/usr/local/bin/mclient < ./pocs/00.sql`
 - Check whether the server crashed: `pgrep mserver5 || echo "Server crashed."`

**Issue labeling**
bug

**Additional context**
None

**Comment by lrpereira** [comment]
Hi @fuboat ,

Thanks for the report!
I'll look into to them and get them fixed.

**Comment by lrpereira** [comment]
All queries were fixed!

Thanks for the report :smiley:
