### ISSUE TITLE
SQL 2023 : greatest/least functions with unlimited arguments (not only 2)

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7391]
**Is your feature request related to a problem? Please describe.**
As of today, greatest and least functions are limited to two arguments while in the new SQL 2023 norm, there is no limit to the number of arguments
https://sgbd.developpez.com/actu/345162/La-norme-SQL-2023-est-finalisee-et-livree-avec-de-nouvelles-fonctionnalites-pour-le-format-JSON-des-modifications-du-langage-SQL-existant-et-les-requetes-sur-les-graphes-de-proprietes/

**Describe the solution you'd like**
Obviously an unimited argument number for least and greatest

**Describe alternatives you've considered**
nested several current greatest/least but that's ugly

**Additional context**

Best regards,

Simon

**Comment by njnes** [comment]
added this to the current default.
