### ISSUE TITLE
Evaluate Profile-Guided Optimization

### ISSUE THREAD

**Issue by zamazan4ik** [MonetDB/MonetDB#7392]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem - just an idea of how to (possibly) improve the performance.

**Describe the solution you'd like**
Recently I tested a lot of software with PGO and measured the performance improvements from PGO - the results are [here](https://github.com/zamazan4ik/awesome-pgo/). Since my results show interesting improvements on a lot of databases I think it would be a good idea to measure PGO effects on MonetDB as well. If the results will show an improvement - would be great to see a note in the documentation about PGO.

I think for MonetDB the most interesting experience would be from SQLite with PGO - https://sqlite.org/forum/forumpost/7ce7a5f03d .

**Comment by njnes** [comment]
added initial cmake support via 
-DPGOTRAIN=ON
and 
-DPGOBUILD=ON 
later is expecting the training/profile-data in ../training/profile-date
(or the training data dir can be passed via -D../training , for now is relative to build directory)

(some compilation issues remain ..)

**Comment by zamazan4ik** [comment]
@njnes could you please share the results of enabling PGO on MonetDB? Did you get any measurable performance improvements with it? It would be great if you could share the results.
