### ISSUE TITLE
Can anyone give me a script to backup the monet db

### ISSUE THREAD

**Issue by garbincolorado** [MonetDB/MonetDB#7398]
Can anyone give me a script to backup the monet db, I was looking to use the sys.hot_snapshot option, does anyone use it that way? is the most suitable? If so, can you provide details of the procedure?

**Comment by njnes** [comment]
See https://www.monetdb.org/documentation-Jun2023/admin-guide/backup-upgrade/ (and pages on hotsnapshot and sql dump/restore). On the options for a back. It depends on your needs. If you can shutdown the server (ie no 24x7 application) then doing rsync/file level backups is most efficient. For small db's the ascii, sql dump/restore is a proper solution with 24x7 service. Else the hotsnapshot should be used.

**Comment by garbincolorado** [comment]
Thanks for the answer, I managed to do it using snashot, below is the description, in case anyone needs it.

--Criar relação confiança usuario senha para olap
nano ~/.monetdb

--Cole dentro arquivo monetdb editado acima
user=username
password=password


--Crie script de bkp
-Criei dentr da pasta /mnt/   
-Crie a pasta BKP_OLAP
mkdir BKP_OLAP

-Monte essa pasta BKP_OLAP no storage
Ex fstab://ip storage/Bkp_Monet /mnt/BKP_OLAP cifs username=user,password=your password  0  0
   comando direto :  mount -t cifs //ip storage/Bkp_Monet -o username=useradmin,password=your password  /mnt/BKP_OLAP    

-criando arquivo 
nano  bkp_monetdb.sh - jogue dados abaixo dentro dele
____________________________________________
#!/bin/bash

# Defina as variáveis
database="teste"
backup_dir="/mnt/BKP_OLAP/"
datestamp=$(date +"%Y_%m_%d")

# Execute a instrução sys.hot_snapshot usando mclient
mclient -d $database -s "call sys.hot_snapshot('$backup_dir/olap_backup_$datestamp.tar.lz4');"
_____________________________________________
-De permissão 
chmod 777 bkp_monetdb.sh



-- Para Descompactar o arquivo LZ4:

lz4 -d arquivo.tar.lz4
-Isso criará um arquivo chamado arquivo.tar 
-Extraia o conteúdo do arquivo tar na pasta /var/lib/monetdb  - Ele ja vai descompactar pasta olap
tar -xvf arquivo.tar
Obs: Percebi que para subir serviço monetdb com comando [monetdb start -a] , vc tem que digita antes [monetdb start /var/lib/monetdb/]

**Comment by garbincolorado** [comment]
Thanks
