### ISSUE TITLE
I am experiencing slow performance with MonetDB queries

### ISSUE THREAD

**Issue by lampt-uit** [MonetDB/MonetDB#7399]
**Describe the bug**
Queries for data often experience delays and may take a significant amount of time to provide results.

**To Reproduce**
I rely on monetdb as my data warehouse. However, when BI tools generate large crossjoin queries, monetdb tends to take a long time to process them. I have noticed that during this time, the CPUs are not being utilized. Even simple queries like mclient -dolap also experience significant delays. I have included the query generated by the BI tools below. Could you please provide an explanation or recommend ways to enhance monetdb's processing efficiency?

** Configs
<img width="518" alt="Screenshot 2023-08-10 at 20 03 53" src="https://github.com/MonetDB/MonetDB/assets/73767803/4711fc08-778a-4bf2-9fb6-3a4edb985556">

**Expected behavior**
The queries are free from congestion and can generate results promptly.

**Screenshots**
![monetdb](https://github.com/MonetDB/MonetDB/assets/73767803/3075ebe6-cc8f-4c2f-a967-ec5845003538)

**Software versions**
OS and version: Ubuntu 20.04.5 LTS (Focal Fossa)
MonetDB Database Server Toolkit v11.47.3 (Jun2023)
Installed from recompiled

[query.txt](https://github.com/MonetDB/MonetDB/files/12313045/query.txt)

**Comment by njnes** [comment]
could you include the ddl (create table) statements ?

**Comment by lampt-uit** [comment]
> could you include the ddl (create table) statements ?

Here are the related table creation files in the query I sent above. 
[DDL_CreateTable.txt](https://github.com/MonetDB/MonetDB/files/12364612/DDL_CreateTable.txt)

Size of tables
![sizeoftables](https://github.com/MonetDB/MonetDB/assets/73767803/fd58ba65-be02-483b-8ed5-d52279d79bfe)

The query uses `count distinct` , so I suspect this is the cause.

**Comment by njnes** [comment]
count distinct could be a cause if the number of distinct values is high, ie number of unique order's.

**Comment by mvdvm** [comment]
To analyse where time is spend you can use PLAN, EXPLAIN and TRACE commands before your query, see https://www.monetdb.org/documentation/admin-guide/debugging-features/
With PLAN I found that a lot of time is spend in: `# optimize_select_and_joins_bottomup     2 actions 432939 usec`
I guess the big generated query (124218 characters!) is taken a lot of time to optimize.

Maybe you can create a view on top of the tables which contains the joins and columns you need for filtering. This view can be tested and tuned first. Next use the BI tools to use this single view as the basis for selections.

Another approach is to store the repeating condition values such as `"fhs_bookstore_dim"."bookstorecode" = 'CTKHO1' and "fhs_date_dim"."day" = 4` into a conditions_table ('CTKHO1', 4) and use a `AND ("fhs_bookstore_dim"."bookstorecode", "fhs_date_dim"."day") IN (Select bookstorecode, day from conditions_table)` in the where clause. This reduces the query size enormously and speeds up the processing.

You may also contact [MonetDB Solutions ](https://www.monetdbsolutions.com/) for commercial support.
