### ISSUE TITLE
VM max memory is not check correctly for cgroups v2

### ISSUE THREAD

**Issue by sebastienPinel** [MonetDB/MonetDB#7400]
I was trying to deploy MonetDB on Azure running on Kubernetes v1.25.6 and it failed with following exception:
```
#2023-09-04 16:15:35: main thread: GDKmalloc_internal: ERROR: allocating too much memory
```
After looking deeper into the source code, it's seems to happen when initializing GDK and checking the max memory available.
In my opinion, the culprit is the following line.
https://github.com/MonetDB/MonetDB/blob/25a2a69633f2e5dc292742cf57dc8809484e2d59/gdk/gdk_utils.c#L701

We are only checking the swap max which is 0 in my case. I guess we should add memory.max and memory.swap.max to get the total of virtual memory. 
I also saw that in cgroup v1, the sum of this 2 was available in a single file called memory.memsw.limit_in_bytes but we don't have this file.
I hope my reading of C code is correct, it's been a while !

**Comment by envision-admin** [comment]
We are facing the exact same issue in GCP running Kubernetes v1.25 

Here is where we are seeing the error thrown from:
https://github.com/MonetDB/MonetDB/blob/522b784315f8f6ff0255aeb77a011b33a756d0c8/gdk/gdk_utils.c#L1721C33-L1721C33 

Any fixes or workarounds could be great help.

**Comment by monetdb-team** [comment]
A workaround is to start the server with an option to override the setting: `--set gdk_vm_maxsize=X` where X is the number of bytes.

**Comment by sebastienPinel** [comment]
Hello @monetdb-team,
I already tried this workaround but same error is thrown. 
![image](https://github.com/MonetDB/MonetDB/assets/2609460/52251c16-0450-450b-8d50-bae42b1adb42)

**Comment by sjoerdmullender** [comment]
Yes, I see the problem, and I can reproduce it.
I don't see any workaround on the monetdb side, though.
There may be two workarounds possible from outside monetdb.
Write a value in the memory.swap.max file that is large enough to get you past the initial part of the server before the override of the --set option takes effect.
Or perhaps create a sub cgroup in which to run the server.  The code in the latest release only looks in the cgroup directory itself and not in the parent directories from which it actually inherits cgroup settings.  So by creating a sub cgroup, the server doesn't find the memory.swap.max file and so doesn't impose its restriction.

**Comment by envision-admin** [comment]
Is the issue expected to be fixed by MonetDB in future releases so that it works OOTB?

**Comment by sebastienPinel** [comment]
@sjoerdmullender: I compiled your latest code changes and deploy it to Azure. I can confirm you that the fix is working correctly. 
Thank a lot for the quick fix, I hope it will be part of next SP of June2023 branch.
Erratum: On AWS, cgroups are still V1 so no issue on this cloud provider

**Comment by sjoerdmullender** [comment]
@envision-admin: yes.
@sebastienPinel thanks for testing.
