### ISSUE TITLE
Column aliases used incorrectly in UNION subqueries

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7401]
**Describe the bug**
A slightly naughty (but perfectly valid) usage of aliases in UNION subqueries causes the wrong column being picked for the result.

**To Reproduce**
```sql
create table t(a int, b int);
insert into t values (1,10);
insert into t values (2,20);

select a as a, b as b from t
UNION
select b as a, a as b from t;
```
delivers:
```
+------+------+
| a    | b    |
+======+======+
|    1 |   10 |
|    2 |   20 |
|   10 |   10 |
|   20 |   20 |
+------+------+
4 tuples
```
**Expected behavior**
```
+------+------+
| a    | b    |
+======+======+
|    1 |   10 |
|    2 |   20 |
|   10 |    1 |
|   20 |    2 |
+------+------+
4 tuples
```

**Software versions**
 - MonetDB version number v11.47.6
 - OS and version: Fedora 38
 - self-installed and compiled

**Comment by mvdvm** [comment]
Thanks for reporting the issue.
I created a test for it in our testweb.
I also tested  `select b as a, a as b from t;` which works fine.
Also when you use `UNION ALL` instead of `UNION`  it works fine.
So it is related to the UNION as you stated.

**Comment by mvdvm** [comment]
FYI: a temporary workaround for the column alias in union subqueries  bug is to use:
```
select a as a, b as b from t
UNION
select c1, c2 from (
select b as a, a as b from t
) as vt(c1,c2)
```

**Comment by njnes** [comment]
fixed in default and jun2023
