### ISSUE TITLE
Table definitions not fully maintained in `create table select as`

### ISSUE THREAD

**Issue by bartscheers** [MonetDB/MonetDB#7404]
**Describe the bug**
When creating a table using as select, the column constraints are not respected.

**To Reproduce**
```
create table t1 (i int, d double not null);
create table t2 (i int default 99, d double);
insert into t1 values (1, pi()), (2, exp(1));
insert into t2 (d) values (pi()), (exp(1));

create table u1 as select * from t1 with data;
create table v1 as select * from t2 with data;
```

**Expected behavior**
Table defintions of `u1` and `v1` should be identical to `t1` and `t2`, resp.

**Software versions**
 - Jun2023-SP2
 - Fedora 38
 - Installed from release package

**Issue labeling**
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Additional context**
I did not check more combinations for the column definitions or things like casting column to other data type

**Comment by njnes** [comment]
its always been structure only, ie columns, not indices and/or constraints.

**Comment by njnes** [comment]
this is also sql conformant.
