### ISSUE TITLE
Imprecise documentation about dates

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7405]
Just a (probably) outdated piece of documentation, on https://www.monetdb.org/documentation-Jun2023/user-guide/sql-manual/data-types/temporal-types/:

> Min and max years. The maximum and minimum dates and timestamps that can be stored are in the years 5,867,411 and -5,867,411, respectively. Interestingly, the year 0 is not a valid year. The year before 1 is called -1.

Perhaps this used to be the case? Nowadays year 0 is valid:
```
sql>select cast('0000-01-01' as date);
+------------+
| %2         |
+============+
| 0-01-01    |
+------------+
1 tuple
```

**Comment by njnes** [comment]
Roberto

Indeed the year zero used to not exist. We need to update that Indeed

Niels

**Comment by swingbit** [comment]
The year limits don't seem correct either.

The max. date that can be stored is in a `date` type is `170049-12-31`.

**Comment by njnes** [comment]
Roberto

That also changed, when we did the date/timestamp storage redesign

Niels

**Comment by njnes** [comment]
Should be better now.
