### ISSUE TITLE
Numpy table returning UDFs with variadic arguments

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7409]
**Describe the bug**

While numpy UDFs allow variadic arguments with * table returning numpy UDFs do not work properly (perhaps it is a feature request but it seems more like a bug).

**To Reproduce**
The UDF below :

CREATE FUNCTION python_table(arg2 string)
RETURNS TABLE (name STRING, country STRING, age INTEGER)
LANGUAGE PYTHON
{
    result = dict()
    result['name'] = ['Henk' , 'John' , 'Elizabeth']
    result['country'] = ['NL' , 'USA' , 'UK']
    result['age'] = [25, 30, 33]
    return result
};

works with a query like: select * from python_table((select col from table));

but if I have:

CREATE FUNCTION python_table2(*)
RETURNS TABLE (name STRING, country STRING, age INTEGER)
LANGUAGE PYTHON
{
    result = dict()
    result['name'] = ['Henk' , 'John' , 'Elizabeth']
    result['country'] = ['NL' , 'USA' , 'UK']
    result['age'] = [25, 30, 33]
    return result
};

the query 
 select * from python_table2((select col from table));

returns error: Scalar value expected

**Expected behavior**

It works when I have  select * from python_table2('value'), but I cannot create numpy table returning UDFs with variadic arguments that takes as input a subquery, while I can do it only with static defined args (for other UDF types like aggregates and scalars this also works properly). The same happens also with C UDFs (while the C code produced automatically and stored at TEMP_DATA folder of the database is exactly the same in both cases).

**Comment by johnfouf** [comment]
The above error message was with MonetDB 11.41. Using the latest from git the error is:

TypeException:user.main[42]:'batmal.multiplex' undefined in:     (X_0:bat[:str], X_1:bat[:str], X_2:bat[:int]) := batmal.multiplex(X_3:lng, "pyapi3":str, "eval":str, 0x7fa8145b6fc0:ptr, "{\nresult = dict()\nresult['name'] = ['Henk' , 'John' , 'Elizabeth']\nresult['country'] = ['NL' , 'USA' , 'UK']\nresult['age'] = [25, 30, 33]\nreturn result\n};":str, X_4:bat[:str], X_5:bat[:str], X_6:bat[:str], X_7:bat[:str], X_8:bat[:str], X_9:bat[:str], X_10:bat[:str], X_11:bat[:str], X_12:bat[:str]);

**Comment by njnes** [comment]
[py.diff.txt](https://github.com/MonetDB/MonetDB/files/13195020/py.diff.txt)

If you apply this patch you should get a single 3 row table output. Still not sure if that is what you really want. 
Table functions and table input do not mix well.

**Comment by njnes** [comment]
This patch was added to jun2023.

**Comment by johnfouf** [comment]
Another small bug similar to the previous is that variadic UDFs (also scalars) can not be accessed via a remote table:
If I have a udf 
create function myudf(*)
and another 
create function myudf2(arg2 STRING)

with exactly the same body:
and I have a remote table  
I am getting through the remote exec in the one server (master):
#DFLOWworker0014: createExceptionInternal: ERROR: SQLException:remote.exec:(mapi:monetdb://monetdb@127.0.0.1/fldb) No such function 'sys'.'mystrlen'(clob)

and in the worker server 
client0018: createExceptionInternal: ERROR: SQLException:RAstatement2:42000!No such function 'sys'.'mystrlen'(clob)

If it is not variadic, it is able to find it and it works, I am almost sure that it is very similar patch with a 'vararg &&' that is missing in a if statement, but I could not find it with a fast pass through the code.
