### ISSUE TITLE
FTBFS on Debian: no openssl-dev

### ISSUE THREAD

**Issue by tkorvola** [MonetDB/MonetDB#7411]
**Describe the bug**

MonetDB fails to build Debian packages because build dependency `openssl-dev` does not exist. Perhaps you mean `libssl-dev`.

**To Reproduce**

    git clone --depth 1 https://github.com/MonetDB/MonetDB.git
    cd MonetDB
    apt-get build-dep .

**Software versions**
 - MonetDB current master (d63db2e37d1)
 - Debian Bookworm (Docker image)

**Comment by sjoerdmullender** [comment]
I guess openssl-dev is the old name.  We hadn't used the SSL library for a while, but it is back in the default branch and so we just restored that part of the old config.  We hadn't checked the build configuration yet for Debian and Ubuntu, so thanks for reporting it.
