### ISSUE TITLE
Unexpected transaction conflict

### ISSUE THREAD

**Issue by PedroTadim** [MonetDB/MonetDB#7419]
**Describe the bug**
Hello! Today I got an unexpected error while running concurrent transactions in MonetDB. I am not sure if this is a bug. Run the following statements:

**To Reproduce**
```
CREATE TABLE t0 (c0 INT);

T1: START TRANSACTION;
T2: START TRANSACTION;
T1: INSERT INTO t0 VALUES (1);
T2: INSERT INTO t0 VALUES (2);
T1: DELETE FROM t0 WHERE c0 = 1;
T2: DELETE FROM t0 WHERE c0 = 2;
T1: COMMIT;
T2: COMMIT;  --COMMIT: transaction is aborted because of concurrency conflicts, will ROLLBACK instead
```

**Expected behavior**
I expect both transactions to succeed.

**Software versions**
 - Using the latest commit from default branch.
 - OS and version: Ubuntu 22.04
 - Self-installed and compiled

**Comment by njnes** [comment]
did you mean to say 'delete from t0'?

**Comment by PedroTadim** [comment]
> did you mean to say 'delete from t0'?

Yes, sorry for the typo (fixed it).

**Comment by njnes** [comment]
seems the transaction fails in the predicate list handling, ie the where parts of the deletes.

**Comment by PedroTadim** [comment]
> seems the transaction fails in the predicate list handling, ie the where parts of the deletes.

Now I remember when we did it :) If this is expected, then we can close the issue

**Comment by njnes** [comment]
Yes its expected, but could be improved. Somehow this didn't got higher on the priority queue ;-).

**Comment by PedroTadim** [comment]
Close the issue
