### ISSUE TITLE
Aggregate functions with variadic arguments

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7422]
**Describe the bug**
It seems that something has broken with aggregate functions with variadic arguments (both in numpy and C pdfs).

**To Reproduce**
In version v11.41.11 (hg id: 151fed075b61) the following works:

CREATE OR REPLACE AGGREGATE python_aggregate (*)
RETURNS INTEGER
LANGUAGE PYTHON
{
    try:
        unique = numpy.unique(aggr_group)
        x = numpy.zeros(shape=(unique.size))
        for i in range(0, unique.size):
            x[i] = numpy.sum(val[aggr_group==unique[i]])
    except NameError:
        # aggr_group doesn't exist. no groups, aggregate on all data
        x = numpy.sum(arg2)
    return (x)
};
select python_aggregate(5,2);

and returns --> 2 (sums the second arg). 

Generally, MonetDB allows variadic arguments and names them as argN

In version v11.48.0, the same code returns
name 'arg2' is not defined
the same happens also with C udfs.

**Comment by johnfouf** [comment]
Hello, is there any new for this issue?

**Comment by njnes** [comment]
fixed in dec2023. Default already had a different (working) implementation for this.
