### ISSUE TITLE
The last statement, execution error, is a false positive?

### ISSUE THREAD

**Issue by Nliver** [MonetDB/MonetDB#7425]
**Describe the bug**

```sql
drop table ttt;
create table ttt(id int primary key,k int NOT NULL DEFAULT '0');
insert into ttt values(1,3),(2,3),(3,3),(4,3),(5,3);
update ttt set k=k+1 where id=3;
delete from ttt where id=2;
update ttt set id = 3 where id = 3;
```
The last statement, execution error, is a false positive?

**Expected behavior**
An error was reported executing the last statement.

**Software versions**
 - MonetDB version number [a milestone label]
 - OS and version: Ubuntu 20.04
 - Self-installed and compiled

**Comment by mvdvm** [comment]
The last statement causes error: `UPDATE: PRIMARY KEY constraint 'ttt.ttt_id_pkey' violated`
while it should be allowed.
Potentially the primary key hash index is not correctly updated after the statement: `delete from ttt where id=2;`

From which branch did you compile the sources? Dec2023 or default or ???

**Comment by Nliver** [comment]
> The last statement causes error: `UPDATE: PRIMARY KEY constraint 'ttt.ttt_id_pkey' violated` while it should be allowed. Potentially the primary key hash index is not correctly updated after the statement: `delete from ttt where id=2;`
> 
> From which branch did you compile the sources? Dec2023 or default or ???

@mvdvm MonetDB version number [Jun2023 Feature Release (11.47.3)]

**Comment by njnes** [comment]
pushed a fix to the dec 2023 branch
