### ISSUE TITLE
[bug] Error code found, please confirm

### ISSUE THREAD

**Issue by Nliver** [MonetDB/MonetDB#7431]
**Describe the bug**
Error code found, please confirm ~

![8ba21b1b1cd75949ec1cec4a25b60dcf](https://github.com/MonetDB/MonetDB/assets/34496563/a7c6eb99-a65e-4813-a64b-dfec250ef6d4)

**To Reproduce**
Create a setting with minimal input for an external user to demonstrate the buggy behavior.
This includes the relevant part of the database schema description.
Performance trace of the rogue query (using the TRACE command)

**Expected behavior**

**Screenshots**

**Software versions**
 - MonetDB version number [Jun2023 Feature Release (11.47.3)]
 - OS and version: Ubuntu 20.04
 - Self-installed and compiled

**Comment by sjoerdmullender** [comment]
Thanks for finding this one.

Fixed in the Dec2023 branch.
