### ISSUE TITLE
Grafana Plugin

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7446]
**Is your feature request related to a problem? Please describe.**
Hello all. Monet DB is not supported by Grafana, which is a cool dataviz tool (and also opensource). I ask the Grafana teams for such a support and here their answer
`Thanks for opening this issue.

I searched on this and there have been some posts on integrating MonetDB with Grafana but did not find a final answer and the reason is that, MonetDB has not yet provided/created a plugin/Datasource that can be easily integrated with Grafana.

So I see the following 2 possibilities here:

1- Asking MonetDB to provide a plugin/datasource to get easily integrated in the Grafana environment. This might be a feature-request or they might have been working on it but not yet officially released it yet.

2- Create it by yourself and ask for some help and guidance from the Grafana Plugin Development using this [link](https://community.grafana.com/c/plugin-development/30)

I hope this helps.`

**Describe the solution you'd like**
A MonetDB plugin for Grafana

**Describe alternatives you've considered**
None

**Additional context**
The Grafana thread : https://github.com/grafana/grafana/issues/79922

**Comment by arjenderijke** [comment]
Hi @simonaubertbd , a plugin is being worked on. I posted a longer answer on the [grafana](https://github.com/grafana/grafana/issues/79922) issue.

**Comment by njnes** [comment]
There is progress on the grafana plugin. See https://github.com/dataspex/dataspex-monetdb-grafana-datasource

**Comment by arjenderijke** [comment]
The plugin is now published

https://grafana.com/grafana/plugins/dataspex-monetdb-datasource/

This is a first version, some improvements are planned. But is should be useful in most cases.
