### ISSUE TITLE
Cannot recover an msqldump

### ISSUE THREAD

**Issue by bartscheers** [MonetDB/MonetDB#7453]
**Describe the bug**
The msqldump cannot be recovered if a partition table has a column option.

**To Reproduce**
Create a basic database instance `dumpdb` and init the sys schema with a merge and partition table using init_db.sql.
Dump using `msqldump -ddumpdb > dumpdb.sql`.
Create another empty basic database instance `recoverdb` and load using `mclient -drecoverdb < dumpdb.sql` fails

**Expected behavior**
Recover is successful

**Screenshots**
init_db.sql:
```
CREATE MERGE TABLE runcat
  (id           INT         NOT NULL
  ,datapoints   INT         NOT NULL
  ,active       BOOLEAN     NOT NULL
  ,ra_deg       DOUBLE      NOT NULL
  ,dec_deg      DOUBLE      NOT NULL
  )
;
CREATE TABLE "rc_zone_42"
  (id           INT         NOT NULL
  ,datapoints   INT         NOT NULL
  ,active       BOOLEAN     NOT NULL DEFAULT TRUE
  ,ra_deg       DOUBLE      NOT NULL
  ,dec_deg      DOUBLE      NOT NULL
  )
;
ALTER TABLE runcat ADD TABLE "rc_zone_42";
```

**Software versions**
 - MonetDB version Dec2023 branch
 - OS and version: F38
 - self-installed and compiled

**Comment by sjoerdmullender** [comment]
@bartscheers can you test the tip of the branch?

**Comment by bartscheers** [comment]
It works
