### ISSUE TITLE
Crash when using `CONTAINS` in `ORDER BY` clause

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7459]
**Describe the bug**
Consider the test cases below. It would crash the monetdb server. The server log (`merovingian.log`) would show: `MSG merovingian[159]: database 'monetdb' (2154) has crashed with signal SIGSEGV (dumped core)`

**To Reproduce**

```sql
DROP TABLE IF EXISTS t0 CASCADE;

CREATE TABLE t0(c0 INTEGER, c1 VARCHAR(500));

SELECT * FROM t0 ORDER BY CONTAINS(((CASE '1' WHEN t0.c0 THEN '' ELSE t0.c0 END ) NOT BETWEEN 0 AND t0.c0>=t0.c1), t0.c1) DESC;  -- unexpected end of file
```

**Expected behavior**
Should return an error message, or return the correct result.

**Screenshots**
N/A

**Software versions**
Build from source:

```
> docker exec monetdb-test mserver5 --version --dbname=monetdb
MonetDB 5 server 11.50.0 (hg id: afd0b37) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 503.5GiB available memory, 128 available cpu cores
Libraries:
Compiled by: @45139603d730 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc 
Linking    : /usr/bin/ld
```

**Issue labeling**
Bug

**Additional context**
Kindly inform me if you need more information (e.g. error trace, etc.)

**Comment by njnes** [comment]
fixed on default
