### ISSUE TITLE
Crash when using `CAST` and `BETWEEN AND`

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7460]
**Describe the bug**
Consider the test cases below. It would crash the monetdb server. The server log (`merovingian.log`) would show: `merovingian[159]: database 'monetdb' (2328) has crashed with signal SIGABRT (dumped core)`

**To Reproduce**
Start command: `docker exec -it monetdb-test mclient -E UTF-8 -d monetdb`

```sql
DROP TABLE IF EXISTS t0 CASCADE;

CREATE TABLE t0( c2 BOOLEAN);
CREATE VIEW v0(c0) AS SELECT 1 FROM t0;

INSERT INTO t0(c2) VALUES (true);

SELECT * FROM t0, v0 WHERE CAST((t0.c2 BETWEEN 0 AND v0.c0) AS BOOLEAN); -- unexpected end of file
```

**Expected behavior**
Should return an error message, or return the correct result.

**Screenshots**
N/A

**Software versions**
Build from source:

```
> docker exec monetdb-test mserver5 --version --dbname=monetdb                                     
MonetDB 5 server 11.50.0 (hg id: b1a4de2) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 503.5GiB available memory, 128 available cpu cores
Libraries:
Compiled by: @dc91f6923a17 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc 
Linking    : /usr/bin/ld
```

**Issue labeling**
Bug

**Additional context**
Kindly inform me if you need more information (e.g. error trace, etc.)

**Comment by njnes** [comment]
solved in default. range expressions where pushed without one of the sides of the expression
