### ISSUE TITLE
Conversion TIMESTAMPTZ to TIME does not take session TZ into account

### ISSUE THREAD

**Issue by joerivanruth** [MonetDB/MonetDB#7467]
Under the old rules, conversion from temporal WITH TIMEZONE to naïve temporal would render the time the way it looks in UTC. For example, `10:11:12-08:00` (= `18:11:12 UTC`) would become `18:11:12`.
On the default branch, this has been changed to render it the way it looks in the session time zone, so the result might be `20:11:12` if the user is in a +2 time zone.
The issue is that the conversion TIMESTAMPTZ to TIME has not yet been updated.

To reproduce:
```
SET TIME ZONE INTERVAL '01:30' HOUR TO MINUTE;
SELECT CAST(TIMESTAMPTZ '1970-04-17 10:07:41-08:00' AS TIME)
```
On default this still yields `18:07:41` while it should have been `19:37:41`.

**Comment by njnes** [comment]
Fixed in default. The adjustment for conversions between timestamps with time zone to time was missing.
