### ISSUE TITLE
Crash when using `CONTAINS`

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7469]
**Describe the bug**
Consider the test cases below. It would crash the monetdb server. The server log (`merovingian.log`) would show: `2024-03-13 12:47:42 MSG merovingian[165]: database 'monetdb' (2297) has crashed with signal SIGABRT (dumped core)`

**To Reproduce**

```sql
DROP TABLE IF EXISTS t0 CASCADE;

CREATE TABLE t0(c0 BOOLEAN, c1 VARCHAR);
INSERT INTO t0(c0, c1) VALUES (true, 'a');
INSERT INTO t0(c0, c1) VALUES (true, 'b');
INSERT INTO t0(c0, c1) VALUES (false, 'c');

SELECT t0.c1, t0.c0 FROM t0 WHERE ((CONTAINS(t0.c1, ''))OR(t0.c0)); -- unexpected end of file
```

**Expected behavior**
Should return an error message, or return the correct result.

**Screenshots**
N/A

**Software versions**
Build from source:

```
> docker exec monetdb-test mserver5 --version --dbname=monetdb
MonetDB 5 server 11.50.0 (hg id: 5447912) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 503.5GiB available memory, 128 available cpu cores
Libraries:
Compiled by: @305ec6a4ac34 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc 
Linking    : /usr/bin/ld
```

**Issue labeling**
Bug

**Additional context**
Kindly inform me if you need more information (e.g. error trace, etc.)

**Comment by mvdvm** [comment]
Issue does **not** occur on MonetDB 5 server v11.49.6 (hg id: 7449a96702cc) , current Dec2023 branch.
Will test it also on default branch.

**Comment by mvdvm** [comment]
Issue does **not** occur on MonetDB 5 server v11.50.0 (hg id: b492ab0d8ac1), current default branch.

**Comment by suyZhong** [comment]
Hi @mvdvm, thanks for your effort. 

However, it looks like I could still reproduce this on the latest commit [bb8ded6](https://github.com/MonetDB/MonetDB/commit/bb8ded6b7e85b8829cb036378267624d7c5733d3). Not sure if it's I built with assertions enabled, or I made something wrong.

Here's how I build MonetDB (in a docker container). According to [this](https://github.com/MonetDB/MonetDB?tab=readme-ov-file#build-options), I think I have enabled it?

```
mkdir build && \
cd build && \
cmake .. && \
cmake --build . && \
cmake --build . --target install
```

Here's the most latest two logs in the `merovingian.log`

```
2024-03-15 14:52:45 ERR monetdb[176]: mserver5: /app/MonetDB/gdk/gdk_cand.c:438: canditer_init: Assertion `s->ttype == TYPE_msk|| s->tsorted' failed.
2024-03-15 14:52:50 MSG merovingian[159]: database 'monetdb' (176) has crashed with signal SIGABRT (dumped core)
```

**Comment by mvdvm** [comment]
Correct.
I also noticed that on our nightly testweb however only for 1 platform. See [contains-or-7469](https://www.monetdb.org/testweb/web/testgrid.php?serial=90509:a7cedf79228b&order=platform%2Carch%2Ccompiler&targets=Cla-Darwin-x86_64-assert-propcheck%2CCla-Darwin-x86_64%2CCla-Fedora-x86_64%2CGNU-Fedora-powerpc64-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-powerpc64-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-x86_64-assert-debug%3D65536%2CGNU-Fedora-x86_64-assert-propcheck-multifarm-coverage%2CGNU-Fedora-x86_64-dbfarm%2CGNU-Fedora-x86_64-notint128-dbfarm%2CGNU-Fedora-x86_64-nowal%2CGNU-Fedora-x86_64-sanitize%2CGNU-Fedora-x86_64-thrs%3D1-assert%2CGNU-Fedora-x86_64-thrs%3D1-propcheck%2CGNU-Fedora-x86_64-thrs%3D32-propcheck-jemalloc%2CGNU-Fedora-x86_64-thrs%3D53-assert-tcmalloc%2CGNU-Fedora-x86_64-undefined%2CMic-Windows2022-i386-installer%2CMic-Windows2022-x86_64-assert-propcheck%2CMic-Windows2022-x86_64-installer&module=sql&tstlimit=sql%2Ftest%2FBugTracker-2024)

It triggers the assertion: `gdk/gdk_cand.c:438: canditer_init: Assertion s->ttype == TYPE_msk|| s->tsorted' failed.`
