### ISSUE TITLE
MonetDB is utilizing the CPU inefficiently

### ISSUE THREAD

**Issue by lampt-uit** [MonetDB/MonetDB#7494]
**Describe the bug**
The system running MonetDB consistently experiences high CPU utilization. Below are the CPU usage statistics that I have captured in a screenshot. Please examine this issue and guide how to resolve it
This system is currently only running MonetDB

**Screenshots**
 - The statistics on the Zabbix dashboard
![image](https://github.com/MonetDB/MonetDB/assets/73767803/ac3585cc-ead9-4bca-b66c-12bf138c8bc0)

- mpstat
![image](https://github.com/MonetDB/MonetDB/assets/73767803/26a18123-351b-4067-ba24-b19ea1b960b0)
![image](https://github.com/MonetDB/MonetDB/assets/73767803/c45f4ef4-51a6-4a2c-8d83-928308172ee6)

- There are 3 mserver5 processes running on this system
![image](https://github.com/MonetDB/MonetDB/assets/73767803/e0a92d64-cb74-4562-86c2-32407680e5ec)

- pidstat (processID = 91809)
![image](https://github.com/MonetDB/MonetDB/assets/73767803/e9957260-c0c3-47c3-b62a-154da96ee657)

- strace (processID = 91809)
![image](https://github.com/MonetDB/MonetDB/assets/73767803/f4c09ef1-d874-4266-8c03-429fab0da060)

- The information of the mserver5 process with ID 91809
![image](https://github.com/MonetDB/MonetDB/assets/73767803/c3b2c3df-827d-4264-b34f-d5525120b4f1)

**Software versions**
 - MonetDB version:  v11.49.1 (Dec2023)
 - OS and version: Ubuntu 20.04.5 LTS
 - Installed from the release package

**Comment by njnes** [comment]
could you tell a bit more on what workload monetdb is handling? Or do you think there are no active clients/users and still you see high cpu usage?

**Comment by lampt-uit** [comment]
@njnes I have disabled all user connections to the database, but CPU usage remains high. If you require additional information, I can provide it

**Comment by njnes** [comment]
if you compiled with debugging symbols, you could run 'perf top' to see what the mserver is doing.

**Comment by lampt-uit** [comment]
@njnes 
perf top

![image](https://github.com/MonetDB/MonetDB/assets/73767803/1507a95b-2f4a-4068-8895-80b0f9f14f7f)

**Comment by njnes** [comment]
so the database is still computing a (range) join (and seems busy with locks and cleanup), which is very strange for a db without connections. Did a monetdbd or mserver5 restart help?
