### ISSUE TITLE
Deadlock in BATrange

### ISSUE THREAD

**Issue by bartscheers** [MonetDB/MonetDB#7498]
**Describe the bug**
Concurrent clients are trying to lock, swaplock, heaplock when bats are locked. This turned out after sockets were in CLOSE_WAIT state, no client access was allowed anymore due to max nclients (64), and the server did not clean up running mserver5 instances. monetdb status was giving "running".

**To Reproduce**
Hard to reproduce, but good chance it occurs when many concurrent clients run the same set of queries

**Expected behavior**
Running smoothly

**Software versions**
 - MonetDB Dec2023 SP1
 - Fedora 38
 - Installed from release package

**Comment by sjoerdmullender** [comment]
It turns out, this deadlock was already fixed in the Dec2023-SP2 release.
