### ISSUE TITLE
create schema + set schema inside a transaction that is rolled back causes the connection to be aborted

### ISSUE THREAD

**Issue by sjoerdmullender** [MonetDB/MonetDB#7499]
**Describe the bug**
See title

**To Reproduce**
START TRANSACTION;
CREATE SCHEMA test;
SET SCHEMA test;
ROLLBACK;
SET SCHEMA sys; -- should work but gives error and aborts the connection

**Expected behavior**
The ROLLBACK should ideally revert to the schema from before the START TRANSACTION, but I'll settle with the SET SCHEMA sys working.

**Software versions**
 - Dec2023-SP2

**Comment by njnes** [comment]
fix in dec2023
