### ISSUE TITLE
2024-04-29 00:29:44 MSG merovingian[101569]: databasehas crashed after start on 2024-04-28 17:48:46, attempting restart, up min/avg/max: 0s/4h/4d, crash average: 1.00 0.90 0.80 (16018-2105=13913)

### ISSUE THREAD

**Issue by RoderickZuniga** [MonetDB/MonetDB#7502]
LOGS:
   185 2024-04-29 00:27:45 ERR im_monet[170697]: #GDKmalloc(2690064384) fails, try to free up space [memory in use=394318426664,virtual memory in use=1334861410856]
    186 2024-04-29 00:27:51 ERR im_monet[170697]: #GDKmalloc(3101263872) fails, try to free up space [memory in use=394319013104,virtual memory in use=1337708356848]
2024-04-29 00:28:36 ERR im_monet[170697]: #GDKmalloc(1366956032) fails, try to free up space [memory in use=395876219240,virtual memory in use=1342435866984]
    220 2024-04-29 00:28:36 ERR im_monet[170697]: #GDKmalloc(2549714944) fails, try to free up space [memory in use=395876546080,virtual memory in use=1343824180768]
    221 2024-04-29 00:28:39 ERR im_monet[170697]: #GDKmalloc(3982016512) fails, try to free up space [memory in use=396128151152,virtual memory in use=1342135330416]
    222 2024-04-29 00:28:40 ERR im_monet[170697]: #GDKmalloc(2763450368) fails, try to free up space [memory in use=396488057568,virtual memory in use=1346646352608]
    223 2024-04-29 00:28:42 ERR im_monet[170697]: #GDKmalloc(3906095104) fails, try to free up space [memory in use=396759724096,virtual memory in use=1345211396160]

   property            value
hostname         im-monetdb01-ng1.txel.systems
dbfarm           /opt/monet2/monetdb
status           monetdbd[101569] 1.7 (Jul2017-SP4) is serving this dbfarm
mserver          /usr/bin/mserver5
logfile          /opt/monet2/monetdb/merovingian.log
pidfile          /opt/monet2/monetdb/merovingian.pid
sockdir          /tmp
listenaddr       0.0.0.0
port             50000
exittimeout      60
forward          proxy
discovery        yes
discoveryttl     600
control          no
passphrase       <unknown>
mapisock         /tmp/.s.monetdb.50000
controlsock      /tmp/.s.merovingian.50000
sql>SELECT name, value FROM sys.env();
+-----------------------------+-------------------------------------------------------------+
| name                        | value                                                       |
+=============================+=============================================================+
| gdk_dbpath                  | /opt/monet2/monetdb/im_monet                                |
| gdk_debug                   | 0                                                           |
| gdk_vmtrim                  | no                                                          |
| monet_prompt                | >                                                           |
| monet_daemon                | yes                                                         |
| mapi_port                   | 0                                                           |
| mapi_open                   | false                                                       |
| mapi_autosense              | false                                                       |
| sql_optimizer               | default_pipe                                                |
| sql_debug                   | 0                                                           |
| merovingian_uri             | mapi:monetdb://im-monetdb01-ng1.txel.systems:50000/im_monet |
| mapi_usock                  | /opt/monet2/monetdb/im_monet/.mapi.sock                     |
| monet_vault_key             | /opt/monet2/monetdb/im_monet/.vaultkey                      |
| gdk_nr_threads              | 56                                                          |
| max_clients                 | 64                                                          |
| gdk_dbname                  | im_monet                                                    |
| gdk_vm_maxsize              | 4398046511104                                               |
| gdk_mem_maxsize             | 440492518604                                                |
| gdk_mmap_minsize_persistent | 262144                                                      |
| gdk_mmap_minsize_transient  | 4294967296                                                  |
| gdk_mmap_pagesize           | 65536                                                       |
| monet_pid                   | 303832                                                      |
| monet_version               | 11.27.13                                                    |
| monet_release               | Jul2017-SP4                                                 |
| monet_mod_path              | /usr/lib64/monetdb5                                         |
| recovery                    | finished                                                    |
+-----------------------------+-------------------------------------------------------------+
26 tuples (4.066ms)
![monethtop](https://github.com/MonetDB/MonetDB/assets/168422873/7b155bd8-c1a8-480b-8dbc-65da82b8a0bc)
root@im-monetdb01-ng1:~|⇒  free -h
              total        used        free      shared  buff/cache   available
Mem:           503G         46G        9.3G        3.9G        448G        451G
Swap:           14G        177M         14G

**Comment by yzchang** [comment]
Jul2017-SP4 is no longer supported.
