### ISSUE TITLE
GDKmmap: requested too much virtual memory

### ISSUE THREAD

**Issue by RoderickZuniga** [MonetDB/MonetDB#7505]
LOGS:
 ERR im_monet[2317943]: #main thread: GDKmmap: ERROR: requesting virtual memory failed; memory requested: 1310720, memory in use: 4174219792, virtual memory in use: 1626303007248
➜  monetdb
 ERR im_monet[738170]: #main thread: GDKmmap: ERROR: requesting virtual memory failed; memory requested: 1048576, memory in use: 4869503448, virtual memory in use: 845784005080

➜  monetdb monetdbd get all /opt/monet2/monetdb
   property            value
hostname         im-monetpoc01-sq1
dbfarm           /opt/monet2/monetdb
status           monetdbd[3299345] 11.45.17 (Sep2022-SP3) is serving this dbfarm
mserver          /usr/bin/mserver5
logfile          /opt/monet2/monetdb/merovingian.log
pidfile          /opt/monet2/monetdb/merovingian.pid
loglevel         information
sockdir          /tmp
listenaddr       0.0.0.0
port             50000
exittimeout      60
forward          proxy
discovery        yes
discoveryttl     600
control          no
passphrase       <unset>
snapshotdir      <unset>
snapshotcompression  .tar.lz4
mapisock         /tmp/.s.monetdb.50000
controlsock      /tmp/.s.merovingian.50000

➜  monetdb hostnamectl
   Static hostname: im-monetpoc01-sq1
         Icon name: computer-server
           Chassis: server
        Machine ID: f152f98995ca4da9b7a053be4d66c3d4
           Boot ID: d2c57a001508435da7d2017e5a3dd590
  Operating System: Oracle Linux Server 8.8
       CPE OS Name: cpe:/o:oracle:linux:8:8:server
            Kernel: Linux 5.4.17-2136.319.1.4.el8uek.x86_64
      Architecture: x86-64

**Comment by njnes** [comment]
Your systems seems to be using a lot of memory before executing (this part) of the query. The 1.5TB and later 800GB virtual memory seems a lot. The open source released version is currently at Dec2023-sp2, please upgrade. 
For getting an idea on why the system uses so much memory, please include queries and related ddl statements, table cardinalities etc.

**Comment by njnes** [comment]
no new information and problem on old version. Closing bug.
