### ISSUE TITLE
BBPextend: ERROR: trying to extend BAT pool beyond the limit (163840000)

### ISSUE THREAD

**Issue by lampt-uit** [MonetDB/MonetDB#7507]
**Screenshots**
- merovingian.log
![image](https://github.com/MonetDB/MonetDB/assets/73767803/be8f9034-ecac-4bbc-affc-0863007bb19c)

**Software versions**
- MonetDB Database Server v11.49.1 (Dec2023)
- OS and version: Ubuntu 20.04.5 LTS (Focal Fossa)
- Installed from the release package

**Additional context**
- wc -l BBP.dir
![image](https://github.com/MonetDB/MonetDB/assets/73767803/bca4f526-cb32-4e41-8a7d-ea41318d3d16)

- The first ten lines in the file BBP.dir
![image](https://github.com/MonetDB/MonetDB/assets/73767803/3de66cec-b5bd-4217-a4fa-addc255fbcdd)

- The last ten lines in the file BBP.dir
![image](https://github.com/MonetDB/MonetDB/assets/73767803/0dfcce69-a48e-4d80-883e-589bb1712f14)

**Comment by njnes** [comment]
Looks like an issue which was fixed in the Sp2 release. Could you upgrade to this version?

**Comment by lampt-uit** [comment]
@njnes Is this the version Dec2023-SP2 Bugfix Release (11.49.7)?

**Comment by njnes** [comment]
Yes and I also think this cleanup issue maybe related to your other bug about in efficient cpu usage. #7494.
