### ISSUE TITLE
Monetdb recovery from crash and backup

### ISSUE THREAD

**Issue by vickytaurus** [MonetDB/MonetDB#7510]
We are using Monetdb as our BI database. Sometimes we experience crash of the database during some query execution. The data is critical and database needs to recover, but there is no way how to recover form the crash. Is there any way we recover from the crashed db without any loss of the data or a very minimal loss(in this case we can rerun the process to insert data again).

There is a way to backup the database as explained here - ([Backup][1]https://www.monetdb.org/documentation-Dec2023/admin-guide/backup-upgrade/hot-backup/

But the backup utility can still loose the data in case of crash before the backup is done.

Please guide on the strategy.

**Comment by lrpereira** [comment]
Please reply with MonetDB version, OS version, share log files etc.
If you're not in latest version (Dec2023) please upgrade.

**Comment by vickytaurus** [comment]
We are using monetdb/monetdb:Dec2023 docker image which is latest.
OS is Linux 5.10.210-201.855.amzn2.x86_64

Currently the application is in development state and we faced crashes two time couple of months back, have no logs currently, now we are heading towards production deployment.
Point is, are there any scenarios that database crashes and doesn't recover, if yes then how can we fix these kind of problems of crash. Do we need to remove some temp files or touch some data files.

We will do the periodical backup, but it will not help.

**Comment by njnes** [comment]
for a crash we need more input on what possibly caused the crash. For backups you need to keep your previous succesful backup until you have a new one...

**Comment by njnes** [comment]
Recent fixes include some fixes where a crash caused corrupted db. We didn't receive new reports/issues on corrupted dbs.

**Comment by njnes** [comment]
Anymore problems seen?
