### ISSUE TITLE
Nonexistent window function raises `ParseException:SQLparser:42000!Query too complex: running out of stack space`

### ISSUE THREAD

**Issue by peerpalo** [MonetDB/MonetDB#7514]
**Describe the bug**
Running a query with an nonexistent window function and three parameters raises `ParseException:SQLparser:42000!Query too complex: running out of stack space`. I understand that this isn't a big deal but, in my opinion, this could be related to some MAL Interpreter error and solve other problems.

**To Reproduce**
Run this query
```sql
select
	wrong_function(col1, col2, col3) over w
from
	(select 0 as col1, 1 as col2, 2 as col3) t window w as (partition by col1)
```
Please notice that this could be achieved even with _wrong_ query, e.g.
```sql
select
	wrong_function(col1, col2, wrong_column) over w
from
	(select 0 as col1, 1 as col2, 2 as col3) t window w as (partition by col1)
```

**Expected behavior**
MonetDB should respond with `ParseException:SQLparser:42000!SELECT: no such window function 'wrong_function'(tinyint, tinyint, tinyint)`

**Software versions**
 - MonetDB version number 11.49.5
 - OS and version: Ubuntu 22.04
 - Installed from release package 

**Issue labeling**
bug

**Additional context**
MonetDB was running inside a container

**Comment by lrpereira** [comment]
The parser needs cleanup. Currently it is handling number of function arguments in multiple ways. Fix for this will not be immediate.
In addition, could you give an example of a function which would fit 'wrong_function' with 3 args ?
