### ISSUE TITLE
Union by name

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7519]
**Is your feature request related to a problem? Please describe.**
Union with different columns (maybe union by name like duckdb syntax) : very often in analytics, we build « fact tables » that are union of different « facts » at different granularity and fields. It’s painful to build a SQL union in that case.
Here an example :

SELECT 
    'sales' AS source_table,
    sale_id,
    Null as invoice_id,
    sale_date as fact_date,
    customer_id,
    product_id,
    quantity,
    unit_price,
    quantity* unit_price as sales_amount,
    Null as invoice_amount
FROM 
    sales

UNION BY NAME

SELECT 
    'invoice' AS source_table,
    Null as sale_id,
    invoice_id,
    invoice_date as fact_date
    customer_id,
    Null as product_id, 
    Null as quantity,
    Null as unit_price,
    Null as sales_amount,
    invoice_amount
FROM 
    invoice;

**Describe the solution you'd like**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=FR style='tab-interval:35.4pt;word-wrap:break-word'>

<p class=MsoNormal>I would like to write something like that, lighter, easier<br>
<br>
<i>SELECT <o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp;&nbsp;'sales' AS source_table,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; sale_id,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; sale_date as fact_date,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; customer_id,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; product_id,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; quantity,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; unit_price,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; quantity* unit_price as sales_amount<o:p></o:p></i></p>

<p class=MsoNormal><i>FROM <o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp;&nbsp;sales<o:p></o:p></i></p>

<p class=MsoNormal><i><o:p>&nbsp;</o:p></i></p>

<p class=MsoNormal><i>UNION BY NAME<o:p></o:p></i></p>

<p class=MsoNormal><i><o:p>&nbsp;</o:p></i></p>

<p class=MsoNormal><i>SELECT <o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp;&nbsp;'invoice' AS source_table,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; invoice_id,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; invoice_date as fact_date<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; customer_id,<o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp; invoice_amount<o:p></o:p></i></p>

<p class=MsoNormal><i>FROM <o:p></o:p></i></p>

<p class=MsoNormal><i>&nbsp;&nbsp;&nbsp;&nbsp;invoice;<o:p></o:p></i></p>

<p class=MsoNormal><span style='color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><span style='color:#7F6000'>SAU&nbsp;:
It’s always better with an example. (It works that way with Tableau, Alteryx,
Dataiku, Qlik….). UNION BY NAME is my favorite syntax since it’s already
implemented in some DB (and yes, DuckDB again).<o:p></o:p></span></p>

Sales |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
sales_id | sale_date | customer_id | product_id | quantity | unit_price |   |   |   |  
1 | 01/01/2023 | 1000 | 101 | 10 | 2 |   |   |   |  
2 | 02/01/2023 | 1000 | 103 | 5 | 3 |   |   |   |  
3 | 03/01/2023 | 1001 | 105 | 7 | 5 |   |   |   |  
4 | 04/01/2023 | 1003 | 107 | 6 | 8 |   |   |   |  
5 | 05/01/2023 | 1002 | 109 | 125 | 7 |   |   |   |  
  |   |   |   |   |   |   |   |   |  
Invoice |   |   |   |   |   |   |   |   |  
invoice_id | invoice_date | customer_id | invoice_amount |   |   |   |   |   |  
45 | 02/01/2023 | 1000 | 40 |   |   |   |   |   |  
74 | 03/01/2023 | 1001 | 37 |   |   |   |   |   |  
103 | 04/01/2023 | 1003 | 45 |   |   |   |   |   |  
132 | 05/01/2023 | 1002 | 800 |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |  
Result   of my upper query with Union By Name |   |   |   |   |   |   |   |   |  
source_table | sales_id | fact_date | customer_id | product_id | quantity | unit_price | sales_amount | invoice_id | invoice_amount
sales | 1 | 01/01/2023 | 1000 | 101 | 10 | 2 | 20 |   |  
sales | 2 | 02/01/2023 | 1000 | 103 | 5 | 3 | 15 |   |  
sales | 3 | 03/01/2023 | 1001 | 105 | 7 | 5 | 35 |   |  
sales | 4 | 04/01/2023 | 1003 | 107 | 6 | 8 | 48 |   |  
sales | 5 | 05/01/2023 | 1002 | 109 | 125 | 7 | 875 |   |  
invoices |   | 02/01/2023 | 1000 |   |   |   |   | 45 | 40
invoices |   | 03/01/2023 | 1001 |   |   |   |   | 74 | 37
invoices |   | 04/01/2023 | 1003 |   |   |   |   | 103 | 45
invoices |   | 05/01/2023 | 1002 |   |   |   |   | 132 | 800

<p class=MsoNormal><span style='color:#7F6000'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='color:#7F6000'><o:p>&nbsp;</o:p></span></p>

</body>

</html>

**Describe alternatives you've considered**
N/A

**Additional context**
Just for your information, I wrote to the guys at ANSI in charge of SQL about this function, they will discuss it.

**Comment by njnes** [comment]
In the default we have union corresponding which is part of the sql standard. The corresponding works like a union by name, but by default requires the columns to exist on both sides of the union. If you combine this with outer you get the behaviour of the union by name. More dbs seems to support the standard, union by name isn't part of the sql standard.
