### ISSUE TITLE
Unexpected result when using `IS DISTINCT FROM`

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7521]
**Describe the bug**
The `IS DISTINCT FROM` operator in MonetDB returns unexpected results when used with `NULL`. Specifically, the negation of `NULL IS DISTINCT FROM NULL` returns `NULL` instead of `true`. 

**To Reproduce**

```sql
SELECT (NULL IS DISTINCT FROM NULL); -- false
SELECT NOT (NULL IS DISTINCT FROM NULL); -- null (unexpected)
```

**Expected behavior**
As mentioned above.

**Screenshots**
N/A

**Software versions**
Build from source:

```
> docker exec -it monetdb-test mserver5 --version         
MonetDB 5 server 11.50.0 (hg id: 6e3d6f5) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 503.5GiB available memory, 128 available cpu cores
Libraries:
Compiled by: @7094a4ca4432 (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc 
Linking    : /usr/bin/ld
```

**Issue labeling**
Bug

**Additional context**

**Comment by aris-koning** [comment]
Hi, thanks for reporting. It should be fixed on hg:3a51d8edf6af.
