### ISSUE TITLE
Related to bug #7422 (variadic arguments in aggregate UDFs)

### ISSUE THREAD

**Issue by johnfouf** [MonetDB/MonetDB#7525]
**Describe the bug**
The solution worked with numpy UDFs, but still not with C/C++ UDFs in which there is a strange behaviour:

The aggr_group argument contains the data of the first parameter of the variadic aggregate. No other data is passed to the C UDF.
 

**To Reproduce**

Use the following commands:

CREATE OR REPLACE AGGREGATE jit_sum(*)
RETURNS BIGINT
LANGUAGE C {
    // initialize one aggregate per group
    result->initialize(result, aggr_group.count);
    // zero initialize the sums
    memset(result->data, 0, result->count * sizeof(result->null_value));
    // gather the sums for each of the groups
    for(size_t i = 0; i < arg2.count; i++) {
        result->data[aggr_group.data[i]] += input.data[i];
    }
};
CREATE TABLE vals(grp INTEGER, value INTEGER);
INSERT INTO vals VALUES (1, 100), (2, 200), (1, 50), (2, 300);
SELECT grp, jit_sum(value) FROM vals group by grp;

It returns error for arg2.
The following works, which means that parameter 'value' is stored in the aggr_group var. 

CREATE OR REPLACE AGGREGATE jit_sum(*)
RETURNS BIGINT
LANGUAGE C {
    // initialize one aggregate per group
    result->initialize(result, 1);
    // zero initialize the sums
    memset(result->data, 0, result->count * sizeof(result->null_value));
    // gather the sums for each of the groups
    for(size_t i = 0; i < aggr_group.count; i++) {
        result->data[0] += aggr_group.data[i];
    }
};

SELECT grp, jit_sum(value) FROM vals;

**Comment by sjoerdmullender** [comment]
I'm not sure what is supposed to happen.  The variable `input` is not declared in the body of the function.  I'm guessing that the type and possibly name are unknown at the time the function is compiled.
In any case, here is the (slightly reformatted but otherwise exact) code that gets produced:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/*
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Copyright 2024 MonetDB Foundation;
 * Copyright August 2008 - 2023 MonetDB B.V.;
 * Copyright 1997 - July 2008 CWI.
 */
#include <stdint.h>
#include <stdbool.h>
typedef void *(*malloc_function_ptr)(size_t);
typedef void (*free_function_ptr)(void*);
typedef struct {
	unsigned char day;
	unsigned char month;
	int year;
} cudf_data_date;
typedef struct {
	unsigned int ms;
	unsigned char seconds;
	unsigned char minutes;
	unsigned char hours;
} cudf_data_time;
typedef struct {
	cudf_data_date date;
	cudf_data_time time;
} cudf_data_timestamp;
typedef struct {
	size_t size;
	void* data;
} cudf_data_blob;
#define DEFAULT_STRUCT_DEFINITION(type, typename)		\
	struct cudf_data_struct_##typename			\
	{							\
		type *data;					\
		bool alloced;					\
		bool valloced;					\
		size_t count;					\
		type null_value;				\
		double scale;					\
		int (*is_null)(type value);			\
		void (*initialize)(void *self, size_t count);	\
		void *bat;					\
	}
DEFAULT_STRUCT_DEFINITION(int8_t, bit);
DEFAULT_STRUCT_DEFINITION(int8_t, bte);
DEFAULT_STRUCT_DEFINITION(int16_t, sht);
DEFAULT_STRUCT_DEFINITION(int, int);
DEFAULT_STRUCT_DEFINITION(int64_t, lng);
DEFAULT_STRUCT_DEFINITION(float, flt);
DEFAULT_STRUCT_DEFINITION(double, dbl);
DEFAULT_STRUCT_DEFINITION(char*, str);
DEFAULT_STRUCT_DEFINITION(cudf_data_date, date);
DEFAULT_STRUCT_DEFINITION(cudf_data_time, time);
DEFAULT_STRUCT_DEFINITION(cudf_data_timestamp, timestamp);
DEFAULT_STRUCT_DEFINITION(cudf_data_blob, blob);
DEFAULT_STRUCT_DEFINITION(size_t, oid);
typedef int8_t bte;
typedef int16_t sht;
typedef int64_t lng;
typedef float flt;
typedef double dbl;
typedef char* str;
typedef size_t oid;

char* jit_sum(void** __inputs, void** __outputs, malloc_function_ptr malloc,
	      free_function_ptr free)
{
	struct cudf_data_struct_int aggr_group = *((struct cudf_data_struct_int*)__inputs[0]);
	struct cudf_data_struct_lng* result = ((struct cudf_data_struct_lng*)__outputs[0]);

	{
		// initialize one aggregate per group
		result->initialize(result, aggr_group.count);
		// zero initialize the sums
		memset(result->data, 0, result->count * sizeof(result->null_value));
		// gather the sums for each of the groups
		for(size_t i = 0; i < arg2.count; i++) {
			result->data[aggr_group.data[i]] += input.data[i];
		}
	};
	return 0;
}
```

**Comment by johnfouf** [comment]
Yes, the above example was not completely right. Following the numpy UDFs way and as was working also in C/C++ until 11.41 version the expected way for the variadic arguments is to have names like arg2, arg3,...argN.
The right code is the following (arg2 instead of input):

CREATE OR REPLACE AGGREGATE jit_sum(*)
RETURNS BIGINT
LANGUAGE C {
// initialize one aggregate per group
result->initialize(result, aggr_group.count);
// zero initialize the sums
memset(result->data, 0, result->count * sizeof(result->null_value));
// gather the sums for each of the groups
for(size_t i = 0; i < arg2.count; i++) {
result->data[aggr_group.data[i]] += input.data[i];
}
};

If you look at the example below for numpy UDFs:


CREATE AGGREGATE python_aggregate (*)
RETURNS INTEGER
LANGUAGE PYTHON
{
    try:
        unique = numpy.unique(aggr_group)
        x = numpy.zeros(shape=(unique.size))
        for i in range(0, unique.size):
            x[i] = numpy.sum(arg2[aggr_group==unique[i]])
    except NameError:
        # aggr_group doesn't exist. no groups, aggregate on all data
        x = numpy.sum(arg2)
    return (x)
};
CREATE TABLE grouped_ints(value INTEGER, groupnr INTEGER);
INSERT INTO grouped_ints VALUES (1, 0), (2, 1), (3, 0), (4, 1), (5, 0);
SELECT groupnr, python_aggregate(value) FROM grouped_ints GROUP BY groupnr;

This is working now, and the value parameter is named as 'arg2' in the UDF body. There is also the aggr_group argument in the body which contains the result of the group by (if there is a group by -- note this is not a materialised group by but an integer column that points each input value to the group that belongs to). 

In the last MonetDB versions this does not work for C/C++. 


This variable in your produced column:

struct cudf_data_struct_int aggr_group = *((struct cudf_data_struct_int*)__inputs[0]);

assignes the array with input values to the aggr_group variable (which should contain the result of the group by),
and there is not an assignment for groupby results or additional arguments if I call the UDF with more than one. 

So, I would expect one assignment to aggr_group variable with the groupby result, and multiple assignments (one for each input column) named arg2,arg3...argN

Hope that this is well explained. Hopefully, this is something simple missing, as this feature worked until old versions.

**Comment by johnfouf** [comment]
Specifically (to give some more insight on what I have find so far) in this example UDF I would expect something like this:

 struct cudf_data_struct_int arg2 = * ((struct cudf_data_struct_int*)__inputs[0]);
 struct cudf_data_struct_oid aggr_group = * ((struct cudf_data_struct_oid*)__inputs[1]);
 
 
Generally, as I have seen a little in capi.c file, inputs[0], inputs[1]...inputs[N] contain the data, and there is an additional last struct in inputs array that contains the group by result  (aggr_group)
so if I call it with 2 args I expect:

struct cudf_data_struct_int arg2 = * ((struct cudf_data_struct_int*)__inputs[0]);
struct cudf_data_struct_int (or str or whatever) arg3 = * ((struct cudf_data_struct_int (or str or whatever) *)__inputs[1]);
 struct cudf_data_struct_oid aggr_group = * ((struct cudf_data_struct_oid*)__inputs[2]);



In case of variadic functions, the function is compiled just in time, when the sql query is executed. The args are defined according to the input types at run time. Still I believe this is a small fix (possibly not easy to find) somewhere in capi.c (as it worked some versions before, works perfectly for scalars, and tables in C/C++ and it works for all UDF types with numpy UDFs, I do not expect to be outside of the UDF modules) 


Possibly look at lines 822-847 in capi.c file, it seems that for loop does not work so that arg2... are missing, and finally only lines 841-846 are executed with input_count = 0 to produce just the following code line in the UDF:

struct cudf_data_struct_int aggr_group = *((struct cudf_data_struct_int*)__inputs[0]);

(in which inputs[0] contains the values of the first input argument, and not the groupby result)


Note that I manually tried to edit the code in my UDF body and manually add something like this:

struct cudf_data_struct_int arg2 = * ((struct cudf_data_struct_int*)__inputs[0]);
 struct cudf_data_struct_oid aggr_group = * ((struct cudf_data_struct_oid*)__inputs[1]);
 
 but it seems that inputs array is not properly initiated with everything needed, I am getting segfault because inputs array contains only one struct.

**Comment by njnes** [comment]
fixed pushed to the aug2024 branch
