### ISSUE TITLE
Truncated file when dumping a table from mclient into a gzipped file

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7536]
**Describe the bug**
Dumping from `mclient` into a gzipped file seems broken.

**To Reproduce**
```sql
create table t as select rand() as i from generate_series(0,50000000);
\> t.sql.gz
\D t
```
then show the tail:
```
# zcat t.sql.gz | tail

gzip: t.sql.gz: unexpected end of file
1007802563
1245897912
1801940107
540157875
1979225340
1820213649
1808923998
1140597692
1751198525
101351# 
```

It does work correctly in these two cases:
- A non-compressed dump from `mclient`
- A compressed dump using `msqldump | gzip`

**Software versions**
 - MonetDB version number 11.49.10
 - OS and version: Fedora 40
 - self-installed and compiled

**Comment by joerivanruth** [comment]
The output file isn't being flushed so the final rows are still in gzip's buffer.
As a workaround you can do a bare `\>` after the `\D t`, this closes the file which flushes the buffer.
Mclient should also flush the file on exit, I'll look into that tomorrow.

**Comment by joerivanruth** [comment]
Thanks for spotting this!

**Comment by swingbit** [comment]
@joerivanruth thanks for the fix.

Only one question: aren't bugfixes supposed to go to the latest release branch? Officially that is still Dec2023.

At least I would expect Aug2024. Committing a bugfix to default now means it will available in the release after Aug2024, doesn't it?

PS: this is not an urgent fix for me, I 'm fine even if it stays in default - it's just about understanding the procedure.

**Comment by swingbit** [comment]
Ah never mind. This is actually in Aug2024. I thought I saw it in default, I must have been wrong.

**Comment by joerivanruth** [comment]
It should indeed have gone to Dec2023.
I'll backport it.
