### ISSUE TITLE
BUG with decimal values

### ISSUE THREAD

**Issue by djxandytche** [MonetDB/MonetDB#7538]
**Describe the bug**
The decimal value of a calculation is incorrect.

**To Reproduce**
Just do what is shown in the image below (I'm using the MonetDB client - mclient.bat):
![image](https://github.com/MonetDB/MonetDB/assets/106282409/536613c6-fbee-4dba-b974-6b7d71804cda)
The difference between the two SQL commands is only the limit clause that exists in one of them and not in the other.

**Expected behavior**
The calculation result must be the same for both SQL commands. It should be 36.200.

**Software versions**
 - MonetDB version number: 11.49.9.
 - OS and version: Windows 11 64 bits.
 - Installed from: https://www.monetdb.org/downloads/Windows/Latest/MonetDB5-SQL-Installer-x86_64.msi.

**Comment by njnes** [comment]
fixed in aug2024
