### ISSUE TITLE
Nested query triggers an assert

### ISSUE THREAD

**Issue by supersteves** [MonetDB/MonetDB#7542]
**Describe the bug**
Using 11.49.9 and the 3.3 JDBC driver, this query causes a critical error on the server and a null ResultSet in Java.

**To Reproduce**
Execute this query with JDBC. I've done it in a throwaway main class, where you can see the exception, but the same happens in SQuirreL, for example. No special connection settings or anything.

``` sql
with "e" as ( select 2 as "f" ) 

  select 3 as "z" from (

    select "b"."x" from ( select 2 as "y" from "e" ) as "a" 
    left outer join ( select 2 as "x" ) as "b" on 1 = 1

  ) as "c"

order by "z" desc limit 1
```

I don't think it matters what is in the dbfarm, as the query doesn't read any tables.

Note this query is vastly simplified from the original failing query, trimmed down as much as possible through iteration, to isolate the minimal failing query. As such it no longer makes sense as a query, but shouldn't behave like this.

Seen in `merovingian.log`:
```
2024-06-25 16:53:40 ERR xxx[3097]: #client0309: exp_bin: CRITICAL: Could not find (null).z
2024-06-25 16:53:40 ERR xxx[3097]: #client0309: exp_bin: ERROR: Query: 'with "e" as ( select 2 as "f" ) 
```

**Expected behavior**
To get a ResultSet. With a single cell with value 3. Note this is the outcome with 11.43.

**Software versions**
 - MonetDB version number 11.49.9 
 - JDBC driver 3.3 jre8
 - OS and version: Ubuntu 20.04.4 LTS
 - Installed from apt

Please let me know if there is anything I do to help.

**Comment by joerivanruth** [comment]
Before diving into the details I want to express my gratitude and appreciation for your trimming the query down to the bare minimum. That's incredibly helpful!

**Comment by joerivanruth** [comment]
I can also reproduce this with mclient.
The server prints the line mentioned in the issue, then crashes on an assert at rel_bin.c line 1680: `assert(s)`.

**Comment by supersteves** [comment]
Small related suggestion: when a crash happens on the server like this, the JDBC driver should raise an exception leading you to look at the server logs, perhaps. Currently you get "query did not produce a result set" which is a little obscure.

**Comment by supersteves** [comment]
Thank you.
