### ISSUE TITLE
Unexpected result when using `NULL` constant in comparison

### ISSUE THREAD

**Issue by suyZhong** [MonetDB/MonetDB#7552]
### Describe the bug

The third SELECT statement should return an empty table because the condition `((NULL NOT BETWEEN 1 AND 2) = (t0.c1 NOT IN (t0.c1)))` evaluates to NULL, and no rows should satisfy this condition.

### Reproduction steps

```sql
DROP TABLE IF EXISTS t0 CASCADE;

CREATE TABLE  IF NOT EXISTS t0 ( c1 INT );
INSERT INTO t0(c1) VALUES (1);

SELECT * FROM t0; -- 1
SELECT ((NULL NOT BETWEEN 1 AND 2)=(t0.c1 NOT IN (t0.c1))) FROM t0; -- null
SELECT * FROM t0 WHERE ((NULL NOT BETWEEN 1 AND 2)=(t0.c1 NOT IN (t0.c1)));
-- Expected: empty table
-- Actual: 1
```

### Expected behavior

As mentioned above.

### MonetDB release

11.52.0 6ed27ae

### Executables source

Self compiled and installed

### Operating System

Ubuntu 22.04

**Comment by njnes** [comment]
added test and fixed issue in aug2024
