### ISSUE TITLE
Query performance degradation on MacOS for queries calling large SQL UDF

### ISSUE THREAD

**Issue by mvdvm** [MonetDB/MonetDB#7557]
### Describe the bug

On testweb 3 tests for information_schema views show large performance degradation between Dec2023 and Aug2024 releases, but only for mac-mini Cla-Dar-i64 platforms.
It concerns following tests:
```
Test		Dec2023 time	Aug2024 time
columns		0.9s		12.8s
routines	0.4s		 7.6s
parameters	1.1s		21.8s
```
See [Dec2023 testweb report, look at mac-mini execution times](https://www.monetdb.org/testweb/web/testgrid.php?serial=91624:11bebf588226&order=platform%2Carch%2Ccompiler&targets=Cla-Darwin-x86_64-assert-propcheck%2CCla-Darwin-x86_64%2CCla-Fedora-x86_64%2CGNU-Fedora-powerpc64-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-powerpc64-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-x86_64-assert-debug%3D65536%2CGNU-Fedora-x86_64-assert-propcheck-multifarm-coverage%2CGNU-Fedora-x86_64-dbfarm-check%2CGNU-Fedora-x86_64-notint128-dbfarm%2CGNU-Fedora-x86_64-nowal%2CGNU-Fedora-x86_64-sanitize%2CGNU-Fedora-x86_64-thrs%3D1-assert%2CGNU-Fedora-x86_64-thrs%3D1-propcheck%2CGNU-Fedora-x86_64-thrs%3D32-propcheck-jemalloc%2CGNU-Fedora-x86_64-thrs%3D53-assert-tcmalloc%2CGNU-Fedora-x86_64-undefined%2CMic-Windows2022-i386-installer%2CMic-Windows2022-x86_64-assert-propcheck%2CMic-Windows2022-x86_64-installer&nocondense&module=sql&tstlimit=sql%2Ftest%2Finformation-schema
)
versus [Aug2024 testweb report, look at mac-mini execution times](https://www.monetdb.org/testweb/web/testgrid.php?serial=91663:9bfc47fb63b9&order=platform%2Carch%2Ccompiler&targets=Cla-Darwin-x86_64-assert-propcheck%2CCla-Darwin-x86_64%2CCla-Fedora-x86_64%2CGNU-Fedora-powerpc64-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-powerpc64-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-x86_64-assert-debug%3D65536%2CGNU-Fedora-x86_64-assert-propcheck-multifarm-coverage%2CGNU-Fedora-x86_64-dbfarm-check%2CGNU-Fedora-x86_64-notint128-dbfarm%2CGNU-Fedora-x86_64-nowal%2CGNU-Fedora-x86_64-sanitize%2CGNU-Fedora-x86_64-thrs%3D1-assert%2CGNU-Fedora-x86_64-thrs%3D1-propcheck%2CGNU-Fedora-x86_64-thrs%3D32-propcheck-jemalloc%2CGNU-Fedora-x86_64-thrs%3D53-assert-tcmalloc%2CGNU-Fedora-x86_64-undefined%2CMic-Windows2022-i386-installer%2CMic-Windows2022-x86_64-assert-propcheck%2CMic-Windows2022-x86_64-installer&nocondense&module=sql&tstlimit=sql%2Ftest%2Finformation-schema
)

### Reproduction steps

On testweb the tests for `sql/test/information-schema/Tests/` are available (recompose the testgrid to show all test results).

It appears the information_schema views queried in the 3 tests for columns, routines and parameters all call the system function sys."sql_datatype"() for the columns DATA_TYPE and INTERVAL_TYPE of the those views. This SQL function (defined in sql/scripts/52_describe.sql) is quite large, which apparently explodes the mal plan (run query with TRACE).

The performance issue can more simply be reproduced by running the queries on MacOS:
```
 SELECT DATA_TYPE, INTERVAL_TYPE FROM INFORMATION_SCHEMA.COLUMNS;
 SELECT DATA_TYPE, INTERVAL_TYPE FROM INFORMATION_SCHEMA.ROUTINES;
 SELECT DATA_TYPE, INTERVAL_TYPE FROM INFORMATION_SCHEMA.PARAMETERS ;
```
The first two queries should complete under half a second.
The last query should complete under one second.

When running the query with TRACE:
```
TRACE SELECT DATA_TYPE, INTERVAL_TYPE FROM INFORMATION_SCHEMA.COLUMNS
```
you get a very large trace result of 508567 rows.

### Expected behavior

No performance degradation on mac-mini machines for Aug2024 release

### MonetDB release

Aug2024 (11.51.0)

### Executables source

Release packages

### Operating System

Cla-Dar-i64

**Comment by sjoerdmullender** [comment]
The problem is twofold.  On the Mac, checking for out-of-band information is relatively expensive, and these queries cause a very large number of operations on very small bats.  Since the check is done both at the beginning of processing a bat and every 2**14 rows, the check happened very many times.
The fix is to skip the check at the start of processing the bat.

**Comment by mvdvm** [comment]
Good analysis and fix.
The performance figures are now again like in Dec2023 for mac-mini, see: [Aug2024 testweb report of 25-07-2024](https://www.monetdb.org/testweb/web/testgrid.php?serial=91684:124eb0314152&order=platform%2Carch%2Ccompiler&targets=Cla-Darwin-x86_64-assert-propcheck%2CCla-Darwin-x86_64%2CCla-Fedora-x86_64%2CGNU-Fedora-powerpc64-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-powerpc64-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-assert-propcheck-dbfarm%2CGNU-Fedora-ppc64le-thrs%3D8-notint128-assert-propcheck-dbfarm%2CGNU-Fedora-x86_64-assert-debug%3D65536%2CGNU-Fedora-x86_64-assert-propcheck-multifarm-coverage%2CGNU-Fedora-x86_64-dbfarm-check%2CGNU-Fedora-x86_64-notint128-dbfarm%2CGNU-Fedora-x86_64-nowal%2CGNU-Fedora-x86_64-sanitize%2CGNU-Fedora-x86_64-thrs%3D1-assert%2CGNU-Fedora-x86_64-thrs%3D1-propcheck%2CGNU-Fedora-x86_64-thrs%3D32-propcheck-jemalloc%2CGNU-Fedora-x86_64-thrs%3D53-assert-tcmalloc%2CGNU-Fedora-x86_64-undefined%2CMic-Windows2022-i386-installer%2CMic-Windows2022-x86_64-assert-propcheck%2CMic-Windows2022-x86_64-installer&nocondense&module=sql&tstlimit=sql%2Ftest%2Finformation-schema)
