### ISSUE TITLE
Alpine support + Dockerfile

### ISSUE THREAD

**Issue by SamuelMarks** [MonetDB/MonetDB#7561]
### Is your feature request related to a problem? Describe it

It'd be great to have Alpine support and a Dockerfile and maybe even you upload it officially to your hub.docker.com page. Alpine is smaller than Debian, for example I included a Debian Dockerfile and built a MonetDB of 153MB there versus Alpine's 32.9MB.

### Describe the solution you'd like to see implemented

I've done it

### Describe alternatives you've considered

Maintaining a fork

### Additional context

Where do I send the patch file? - Here's my fork and its branch with this feature implemented:
https://github.com/SamuelMarks/MonetDB/tree/alpine-and-docker

**Comment by sstalin** [comment]
Hi Samuel,
We maintain Docker related work at this repository https://github.com/MonetDBSolutions/monetdb-docker. We will be happy to accept your PR there.

**Comment by njnes** [comment]
we pushed some (updated) changes of your patch to the aug2024 branch, such that monetdb compiles on alpine.

**Comment by SamuelMarks** [comment]
Ahhhh ok I see the changes now. Darn I wanted to contribute but now you've done slightly different contributions that achieve the same ends so I wouldn't even appear on the `git blame`. Ooft, open-source is tough.

---

Oh I didn't see those Docker files before. - https://hub.docker.com/r/monetdb/monetdb/tags your images are all pretty large. - As you can see my latest commit gave the benchmarks: [153MB vs Alpine's 32.9MB](https://github.com/SamuelMarks/MonetDB/commit/68d63e299ad6532fa7fbcb5b39b6f1d4cf3189b0) - even my worst case is roughly half the size of each of your cases. - Want to take my Alpine build and upload it officially? - Maybe tweak the createdb/initdb and env var bit a tad to be conformant with your recommended approach…

**Comment by SamuelMarks** [comment]
Ahhhh ok I see the changes now. Darn I wanted to contribute but now you've done slightly different contributions that achieve the same ends so I wouldn't even appear on the `git blame`. Ooft, open-source is tough.

---

Oh I didn't see those Docker files before. - https://hub.docker.com/r/monetdb/monetdb/tags your images are all pretty large. - As you can see my latest commit gave the benchmarks: [153MB vs Alpine's 32.9MB](https://github.com/SamuelMarks/MonetDB/commit/68d63e299ad6532fa7fbcb5b39b6f1d4cf3189b0) - even my worst case is roughly half the size of each of your cases. - Want to take my Alpine build and upload it officially? - Maybe tweak the createdb/initdb, any additional libraries you prefer to build with, and env var bit a tad to be conformant with your recommended approach…

**Comment by sstalin** [comment]
I've added Dockerfile for Alpine here
https://github.com/MonetDBSolutions/monetdb-docker/commit/ba314fa0a15266ca72f1ee1464d9368155d1f195
We will include it in our future builds.

**Comment by SamuelMarks** [comment]
Ok so should I just not contribute to this project? - Is this a source-available contributions-not-accepted type of open-source project?

**Comment by sjoerdmullender** [comment]
You can definitely contribute.  We don't accept PR's at github since that is not our main repository.
This time we screwed up a little.  I implemented a number of changes for the build on Alpine Linux, but I hadn't seen your report at all.  Normally we do try to acknowledge contributions in the log messages, but I didn't since I hadn't seen yours until later.
