### ISSUE TITLE
upgrade monetdb version Nov2019-SP3 bugfix release (11.35.19) to Jul2021 Feature Release (11.41.5)

### ISSUE THREAD

**Issue by RoderickZuniga** [MonetDB/MonetDB#7564]
### Describe the bug

When I want to update monet to the Jul2021 Feature Release version (11.41.5), the package is installed and the farm is started, but when I perform the monetdb start <BD> it waits, it has been going on for more than 10 hours.

root@im-bono3-percona2-ng1:/tmp/monetdb/11.41.5|⇒  monetdb start im_monet
starting database 'im_monet'...

The log shows nothing

### Expected behavior

that the version is updated

### MonetDB release

Nov2019-SP3

### Executables source

Release packages

### Operating System

Red Hat 7.9

**Comment by sjoerdmullender** [comment]
What is the size of the `sql_logs/sql` subdirectory in the database directory?  The larger that is, the longer it takes to start up.

**Comment by RoderickZuniga** [comment]
root@im-bono3-percona2-ng1:/opt/monet2/monetdb/im_monet|⇒  du -h sql_traces
14M     sql_traces
root@im-bono3-percona2-ng1:/opt/monet2/monetdb/im_monet|⇒  du -h sql_logs
72K     sql_logs/sql
72K     sql_logs
9.8T    bat
root@im-bono3-percona2-ng1:/opt/monet2/monetdb/im_monet|⇒  du -h bat
I had been more than 13 hours without seeing any activity on either the disk or the CPU.

**Comment by lrpereira** [comment]
Nov2019-SP3 no longer has open source support.
Please upgrade to latest! Dec2023 (or soon Aug2024). If problem occurs there please let us know.

For commercial support contact [www.monetdbsolutions.com](www.monetdbsolutions.com)
