### ISSUE TITLE
id tables negative dontt drop catalog

### ISSUE THREAD

**Issue by RoderickZuniga** [MonetDB/MonetDB#7565]
### Describe the bug

Describe the bug
sql>select * from sys.tables where name='AS_XQL_LOG_INFO_29042022_RPM';
+-------------+------------------------------+-----------+-------+------+--------+---------------+--------+-----------+
| id | name | schema_id | query | type | system | commit_action | access | temporary |
+=============+==============================+===========+=======+======+========+===============+========+===========+
| -1059856705 | AS_XQL_LOG_INFO_29042022_RPM | 6422 | null | 0 | false | 0 | 0 | 0 |
+-------------+------------------------------+-----------+-------+------+--------+---------------+--------+-----------+

To Reproduce
We don't have a specific way to reproduce it, yet if we check the sys.tables the ID shows a negative number.

### MonetDB release

Jun2020-SP1 bugfix release (11.37.11)

### Executables source

Release packages

### Operating System

REDHAT 7.9

**Comment by lrpereira** [comment]
Jun2020 no longer has open source support.
Please upgrade to latest! Dec2023 (or soon Aug2024). If problem occurs there please let us know.

For commercial support contact [www.monetdbsolutions.com](www.monetdbsolutions.com)
