### ISSUE TITLE
Column of temporary table changes when another is updated

### ISSUE THREAD

**Issue by joerivanruth** [MonetDB/MonetDB#7569]
### Describe the bug

The following script creates a temporary table with two columns, x and y.
When y is updated, x changes with it.

### Reproduction steps

START TRANSACTION;

CREATE TEMPORARY TABLE nums(x INT, y INT);

INSERT INTO nums
    SELECT value AS x, value AS y
    FROM sys.generate_series(0, 1);

UPDATE nums SET y = 100;

SELECT * FROM nums;

### Expected behavior

I expect the tuple (0, 100) but I get (100,100).

### MonetDB release

Aug2024 prerelease, hg commit 979938af85701b430bda397105dd06e4d0d41525

### Executables source

Self compiled and installed

### Operating System

Debian 12

**Comment by sjoerdmullender** [comment]
Bisecting points to changeset [ed08ba0b1ffa](https://www.monetdb.org/hg/MonetDB/rev/ed08ba0b1ffa).
