### ISSUE TITLE
BUG in the "str_to_timestamp" function

### ISSUE THREAD

**Issue by djxandytche** [MonetDB/MonetDB#7570]
### Describe the bug

If I take the return of the "timestamp_to_str" function and try to do the inverse conversion, that is, call the "str_to_timestamp" function, it is not working.
The error "format '%Y%m%d%z', doesn't match timestamp '20240819-0300'" occurs.
The image below shows the problem:
![image](https://github.com/user-attachments/assets/f230e922-5045-4fd4-b7ea-646f90f84106)

### Reproduction steps

Get the return value from the "timestamp_to_str" function call and call the "str_to_timestamp" function.
Example:
![image](https://github.com/user-attachments/assets/d4b430ae-3edb-4d0b-a3f2-5e3235c7f774)

### Expected behavior

Run without error.
Return this result: 2024-08-19 00:00:00.000000-03:00.

### MonetDB release

11.49.11

### Executables source

Release packages

### Operating System

Windows 10

**Comment by lrpereira** [comment]
Your example works in Aug2024 and default branches(Lastest Fedora)
Most likely this was patched while fixing similar problems observed in recent past linked to timestamp and timezones and perhaps backporting the fix was not simple/doable.

Edit: seems to be the case -> #7370 part of cleanup types proj

**Comment by lrpereira** [comment]
#7370 
This was fixed with types cleanup project.

**Comment by sjoerdmullender** [comment]
I don't think this has anything to do with #7370.  It has everything to do with the fact that there is no `strptime` function in the Windows C library, and the version we use instead does not support `%z`.
We need to find a better version of `strptime`.
