### ISSUE TITLE
Incorrect BAT properties after mmapped BAT "leaks" to disk with restart.

### ISSUE THREAD

**Issue by sjoerdmullender** [MonetDB/MonetDB#7575]
### Describe the bug

When a BAT is memory-mapped and gets updated, the updated values "leak" to disk (it's an mmap, after all).  The internal copy of the BAT properties are updated, and all is still fine.
When the server restarts before the WAL is processed, the on-disk properties will not have been updated, but the values in the BAT were.  This may lead to a crash.

### Reproduction steps

create table foo as (select i from generate_series(1,850000000) as t(i));
update foo set i = 100000 where i between 1000 and 3001000;
-- restart mserver5
select key from sys.storage('sys', 'foo'); -- key is true but should be false
select count(*) from sys.foo where i = 1000000; -- crashes due to incorrect result size calculation

### Expected behavior

no crash, correct properties.

### MonetDB release

Aug2024

### Executables source

Self compiled and installed

### Operating System

Fedora 40

**Comment by sjoerdmullender** [comment]
The query to check for the key property should be:
`select "unique" from sys.storage('sys','foo');`
and the correct result is either false or NULL, but definitely not true.
Also, the query to crash the server is
`select i from sys.foo where i = 100000;`

**Comment by lrpereira** [comment]
To reproduce the broken properties issue for 'min' or 'max', here is relevant SQL statements plus server start instructions:
Start the server with --sql_optimizer=sequential_pipe. 
```
create table foo as select * from generate_series(0,850000000) as foo(i);
select max(i) from foo;
select * from statistics;
create table bar as select * from generate_series(0,100000000); -- this flushes WAL
update foo set i = 849999998 where i = 849999999;
update foo set i = 849999999 where i = 10;
select * from statistics; -- min and max should be null
```

At this point restart the server.

```
select * from foo where i = 849999999; -- this should give exactly one match, but it returns 0
```

**Comment by lrpereira** [comment]
A different way to trigger the problem that tries to mimic behavior of the dropping the highest column id(which would be used as max property) from the SQL catalog.
```
create table foo as select * from generate_series(0,850000000) as foo(i);
select max(i) from foo;
select * from statistics;
create table bar as select * from generate_series(0,100000000); -- this flushes WAL
delete from foo where i >= 849999989 and i <= 849999999;
update foo set i = 850000000 where i = 10;
select * from statistics; -- min and max should be null
```

At this point restart the server.

```
select * from foo where i = 850000000; -- this should give exactly one match, but it returns 0
```
