### ISSUE TITLE
SQL Query Optimiser Problem

### ISSUE THREAD

**Issue by gm-digitalk** [MonetDB/MonetDB#7579]
### Describe the bug

In our production MonetDB the data is partitioned over many tables that are combined into a union view for querying. This design was put in place long before merge tables were available. We have some complex expressions derived from real column data that we create as additional computed columns in the union view and then use throughout our queries.

We have been running MonetDB 11.45.13 (MonetDB Debian repo) and were looking to upgrade to 11.49.11 due to issue #7537

Unfortunately one of our production queries seems to be badly optimised by the query optimiser from 11.47.11 through the current 11.51.3 and crashes MonetDB with:

GDK reported error: GDKextendf: could not extend file: No space left on device
HEAPalloc: Insufficient space for HEAP of 414777344 bytes.
BATgroup_internal: cannot allocate hash table

On 11.45.13 where the query runs well, the plan of the query ends with:
`split_select                           0 actions 2 usec       `
`push_project_down                     15 actions 3119 usec    `
`merge_projects                         0 actions 51900 usec   `
`push_project_up                        0 actions 19646 usec   `
`split_project                          0 actions 21 usec      `
`simplify_math                          0 actions 93 usec      `
`optimize_exps                          0 actions 363 usec     `
`optimize_select_and_joins_bottomup     1 actions 2320 usec    `
`project_reduce_casts                   0 actions 3 usec       `
`optimize_unions_bottomup               0 actions 4894 usec    `
`optimize_projections                  14 actions 7187 usec    `
`optimize_select_and_joins_topdown     67 actions 115344 usec  `
`optimize_unions_topdown               91 actions 255414 usec  `
`dce                                    0 actions 2309 usec    `
`push_func_and_select_down              0 actions 2272 usec    `
`get_statistics                        42 actions 14690310 usec`
`final_optimization_loop                0 actions 710 usec     `

On 11.47.11 (MonetDB Debian repo), the first release where the query fails, the plan of the failing query ends with:

`split_select                           0 actions 2 usec    `
`push_project_down                     15 actions 2338 usec `
`merge_projects                         0 actions 14718 usec`
`push_project_up                        1 actions 14553 usec`
`split_project                          0 actions 21 usec   `
`simplify_math                          0 actions 90 usec   `
`optimize_exps                          0 actions 289 usec  `
`optimize_select_and_joins_bottomup     1 actions 1691 usec `
`project_reduce_casts                   0 actions 3 usec    `
`optimize_unions_bottomup               0 actions 3596 usec `
`optimize_projections                   1 actions 2278 usec `
`optimize_select_and_joins_topdown     67 actions 2572 usec `
`optimize_unions_topdown               78 actions 10449 usec`
`dce                                    0 actions 2083 usec `
`push_func_and_select_down              0 actions 1707 usec `
`get_statistics                        42 actions 53338 usec`
`final_optimization_loop                0 actions 190 usec  `

### Reproduction steps

The following repro script unfortunately doesn't actually reproduce the exact problem we are seeing in our production setup.
I spent a lot of time without success trying to repro where the planner optimisation is different between 11.45.13 and 11.47.11.
However the shape of the repro schema and queries is similar to our production, and produces an optimisation issue that I think is very similar to what is causing us problems.

There are four test queries. They only differ on one line and produce functionally identical results.

Query 1 uses the expression "id / 10000000" where id is the real data column from the plantestv view.
Query 2 uses the expression "id_div" where id_div is a computed column in the plantestv view with a value of "id / 10000000".
Query 3 uses the expression "abs(id) /  10000000" where id is the real data column from the plantestv view.
Query 4 uses the expression "id_abs_div" where id_abs_div is a computed column in the plantestv view with a value of "abs(id) / 10000000".

Queries 1 through 3 are planned similarly and run in similar time. Query 4 plans differently and takes approximately 10 times as long to run.

Is there any way to make the query planner optimise query 4 like queries 1 through 3 ?

`drop view plantestv;`
`drop procedure plantestp;`

`drop table plantest0;`
`drop table plantest1;`
`drop table plantest2;`
`drop table plantest3;`
`drop table plantest4;`
`drop table plantest5;`
`drop table plantest6;`
`drop table plantest7;`
`drop table plantest8;`
`drop table plantest9;`

`create table "sys"."plantest0" ("id" bigint);`
`create table "sys"."plantest1" ("id" bigint);`
`create table "sys"."plantest2" ("id" bigint);`
`create table "sys"."plantest3" ("id" bigint);`
`create table "sys"."plantest4" ("id" bigint);`
`create table "sys"."plantest5" ("id" bigint);`
`create table "sys"."plantest6" ("id" bigint);`
`create table "sys"."plantest7" ("id" bigint);`
`create table "sys"."plantest8" ("id" bigint);`
`create table "sys"."plantest9" ("id" bigint);`

`drop procedure plantestp;`
`create procedure plantestp()`
`begin`
`  declare rowindex bigint;`
`  set rowindex = 0;`
`  while rowindex < 10000000 do`
`    insert into sys.plantest0 (id) values (100000000 + rowindex);`
`    insert into sys.plantest1 (id) values (110000000 + rowindex);`
`    insert into sys.plantest2 (id) values (120000000 + rowindex);`
`    insert into sys.plantest3 (id) values (130000000 + rowindex);`
`    insert into sys.plantest4 (id) values (140000000 + rowindex);`
`    insert into sys.plantest5 (id) values (150000000 + rowindex);`
`    insert into sys.plantest6 (id) values (160000000 + rowindex);`
`    insert into sys.plantest7 (id) values (170000000 + rowindex);`
`    insert into sys.plantest8 (id) values (180000000 + rowindex);`
`    insert into sys.plantest9 (id) values (190000000 + rowindex);`
`    set rowindex = rowindex + 1;`
`  end while;`
`end;`

Populate the base tables with data.

`call plantestp();`

`drop view plantestv;`
`create view plantestv as`
` select`
`  v.*, v.id / 10000000 as id_div, abs(v.id) / 10000000 as id_abs_div`
` from`
`  (`
`   select * from plantest0 union all`
`   select * from plantest1 union all`
`   select * from plantest2 union all`
`   select * from plantest3 union all`
`   select * from plantest4 union all`
`   select * from plantest5 union all`
`   select * from plantest6 union all`
`   select * from plantest7 union all`
`   select * from plantest8 union all`
`   select * from plantest9`
`  ) as v;`

__Query 1__
`select`
` id_r * 10000000 as id_range_base,`
` count(id_r) as nrows`
`from`
` (select`
`   id / 10000000 -- discriminator line query 1`
`  from`
`   plantestv v`
`  where`
`   id >= 150000000`
` ) as t (id_r)`
` group by`
`  id_r`
` order by`
`  id_r asc;`

__Query 2__
`select`
` id_r * 10000000 as id_range_base,`
` count(id_r) as nrows`
`from`
` (select`
`   id_div -- discriminator line query 2`
`  from`
`   plantestv v`
`  where`
`   id >= 150000000`
` ) as t (id_r)`
` group by`
`  id_r`
` order by`
`  id_r asc;`

__Query 3__
`select`
` id_r * 10000000 as id_range_base,`
` count(id_r) as nrows`
`from`
` (select `
`   abs(id) / 10000000 -- discriminator line query 3`
`  from`
`   plantestv v`
`  where`
`   id >= 150000000`
` ) as t (id_r)`
` group by`
`  id_r`
` order by`
`  id_r asc;`

__Query 4__
`select`
` id_r * 10000000 as id_range_base,`
` count(id_r) as nrows`
`from`
` (select`
`   id_abs_div -- discriminator line query 4`
`  from`
`   plantestv v`
`  where`
`   id >= 150000000`
` ) as t (id_r)`
` group by`
`  id_r`
` order by`
`  id_r asc;`

### Expected behavior

Is there any way to make the query planner optimise query 4 like it optimises queries 1 through 3 ?

### MonetDB release

Jun2023-SP2 Bugfix Release (11.47.11)

### Executables source

Release packages

### Operating System

Debian Bullseye and Bookworm

**Comment by lrpereira** [comment]
Hey @gm-digitalk ,

Neither Jun2023 or Dec2023 have open source support since the release of Aug2024.
Please upgrade to latest and If problem occurs there please let us know.

For commercial support contact [www.monetdbsolutions.com](https://github.com/MonetDB/MonetDB/issues/www.monetdbsolutions.com)

Also, I tried your reproduction steps to see if any performance issue comes up in **Aug2024 Feature Release (11.51.3)** but all 4 queries execute in less than half a second.
Can you try on your end and report back ?

**Comment by gm-digitalk** [comment]
Hi, Sorry for not getting back on this. I can confirm that the optimization problem is corrected in 11.51.3 (and 11.51.5).

Just as an aside, in 11.51.3 some of our queries that have not failed before failed with a type conversion error in aggregate functions over group by when the source column type was decimal 8,3 and there was an implicit conversion to a bigint or hugeint. Casting the source column to a decimal(9,3) seemed to fix the this.

**Comment by lrpereira** [comment]
There was some work done on the `decimal type`.
If you can open a new issue with a reproduction script I'll have a look!
