### ISSUE TITLE
SIGSEGV when creating a SQL function with RETURN CASE WHEN EXISTS (..)

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7582]
### Describe the bug

Creating a SQL function with a `RETURN CASE WHEN EXISTS (..)` clause crashes the server.

### Reproduction steps

```sql
CREATE OR REPLACE FUNCTION test()
RETURNS boolean
BEGIN
  RETURN
    CASE
      WHEN EXISTS (select id from sys._tables)
      THEN true
      ELSE false
    END;
END;
```

### MonetDB release

Aug2024

### Executables source

Self compiled and installed

### Operating System

Fedora 40

### Additional context
Using `RETURN SELECT` instead of just `RETURN` works fine:
```sql
CREATE OR REPLACE FUNCTION test()
RETURNS boolean
BEGIN
  RETURN
    SELECT CASE
      WHEN EXISTS (select id from sys._tables)
      THEN true
      ELSE false
    END;
END;
```

**Comment by lrpereira** [comment]
Hey Roberto,
Thanks for the report.
Issue is fixed in Aug2024 and it will be available in the next SP.
