### ISSUE TITLE
Query slowdown after deleting rows from large table

### ISSUE THREAD

**Issue by wlaur** [MonetDB/MonetDB#7583]
### Describe the bug

After deleting even a single row from a large table (around 1B rows), there's a massive performance hit for all queries related to the table.

This issue is also present for smaller tables, and it becomes increasingly noticeable when the size grows.
Recreating the table with `create table ... as select * from ...` fixes the performance issue, but this procedure is prone to errors.

I have tried to use the `sys.vacuum` function, but it does not seem to do anything at all. The call finishes in 1 ms, and there does not seem to be any activity running in the background either.
Checking the table deltas shows a non-zero number in the `deletes` column when the performance issue is active.

### Reproduction steps

The issue can be reproduced using the following SQL statements.
A table with 1B rows and one column of integer data is generated and modified.
The query `select max(value) from test` is used to demonstrate the slowdown, however the issue occurs with more or less all queries that use the table.

I have added approximate execution times where relevant.

```
drop table if exists test

create table test (value int)

-- 12 sec
insert into test (value) select value from generate_series(1, 1000000000, 1)

-- normal performance, very fast
-- 50 ms
select max(value) from test 

delete from test where value > 999999998

-- degraded performance, by 2 orders of magnitude
-- 3 sec, also subsequent queries
select max(value) from test

-- if the table is recreated, the issue disappears
-- however, this is not always feasible without downtime
-- it also requires that table constraints are manually reconfigured (not relevant for this example)

-- 20 sec
create table _test as select * from test 

drop table test 

alter table _test rename to test 

-- back to normal performance
-- 50 ms
select max(value) from test 

-- if the row is added back after being deleted, the issues also disappears

delete from test where value > 999999997

-- same degraded performance as previously
-- 3 sec, also subsequent queries
select max(value) from test 

insert into test (value) values (999999998)

-- back to normal performance since the row was added back
-- 50 ms
select max(value) from test 
```

The performance traces for the normal and degraded performance cases are attached as CSV-files.

[normal.csv](https://github.com/user-attachments/files/17269605/normal.csv)
[degraded.csv](https://github.com/user-attachments/files/17269604/degraded.csv)

### Expected behavior

The expected behavior is that deleting one or more rows should not cause permanent performance degradation. A temporary slowdown is of course to be expected due to the nature of columnar storage.

The workaround of recreating the table is not ideal.
`sys.vacuum` seems like an appropriate tool here, but it does not seem to work.

### MonetDB release

Aug2024, 11.51.3

### Executables source

Release packages

### Operating System

Ubuntu

### Additional context

Tested on Ubuntu 24 with 16 cores, 64 GB RAM, SSD drive.

**Comment by lrpereira** [comment]
Thanks for the report.
Fixed the issue. It will be available in the next Aug2024 SP.

https://github.com/MonetDB/MonetDB/commit/49f347d90f8f0a596871a33ef955761a3d3a9861
