### ISSUE TITLE
Issue with Select Statement: Expected Specific Result, but Database Returns 'Unknown Identifier f1' Error

### ISSUE THREAD

**Issue by awusan125** [MonetDB/MonetDB#7586]
### Describe the bug

This select statement divides c2 into two groups: c2=1 and c2=2. The expected return result should be:
```sql
+--------+------+
| f1     | c2   |
+--------+------+
| 1.5000 |    1 |
| 6.0000 |    2 |
+--------+------+

2 rows in set (0.00 sec)
```
However, the database returns:
```sql
SELECT: identifier 'f1' unknown
```

### Reproduction steps

```sql
DROP TABLE IF EXISTS t;
CREATE TABLE t (c1 int,c2 int);
INSERT INTO t VALUES (1,1),(2,1);
INSERT INTO t VALUES (5,2),(7,2);

SELECT AVG(c1) AS f1 ,c2 
FROM t  
GROUP BY c2
HAVING f1 >0;
```

### Expected behavior

```sql
+--------+------+
| f1     | c2   |
+--------+------+
| 1.5000 |    1 |
| 6.0000 |    2 |
+--------+------+

2 rows in set (0.00 sec)
```

### MonetDB release

MonetDB 5 server 11.51.3 (Aug2024) (64-bit, 128-bit integers)

### Executables source

Release packages

### Operating System

ubuntu 20.04

**Comment by njnes** [comment]
This is not a bug but a sql execution order issue. The having should be handled before the selection, therefor the f1 alias isn't known jet.
