### ISSUE TITLE
Setting schema in connection string

### ISSUE THREAD

**Issue by vickytaurus** [MonetDB/MonetDB#7590]
### Describe your problem

i connect to Monetdb using connection string like
jdbc:monetdb://hostname:port/database

but i want to set schema name also like 
jdbc:monetdb://hostname:port/database?schema=<schemaname>

but when i hit sql queries, schema name is required as prefix with dot in the queries.
How can i avoid specifying schema in the query. it should be set in connection string once

### Describe the solution you'd like to see implemented

  h  

### Additional context

h

**Comment by njnes** [comment]
The jdbc driver currently doesn't support setting the schema like this.
if your first command is just
set schema 'schema name';
it should just work.
Else you could set a default schema for your user.

**Comment by vickytaurus** [comment]
Thanks Niels!
yes I did that way.
https://github.com/MonetDB/monetdb-java/blob/0a4f0321688b69c35c87df8206cb2e3fc3616866/src/main/java/org/monetdb/jdbc/MonetConnection.java#L1474
