### ISSUE TITLE
Float to string conversion is showing unnecessary decimals

### ISSUE THREAD

**Issue by djxandytche** [MonetDB/MonetDB#7592]
### Describe the bug

Converting a float value to a string is showing unnecessary decimals.

### Reproduction steps

Just do what is shown in the image below (I'm using the MonetDB client - mclient.bat):
![image](https://github.com/user-attachments/assets/136cfecf-9933-4586-bba7-2ed5e120ecaa)

### Expected behavior

The second column should show 202410.

### MonetDB release

11.51.3

### Executables source

Release packages

### Operating System

Windows 10

**Comment by njnes** [comment]
The constant is a decimal not a float. When doing division indeed a fixed (minimal) scale of 3 is used.

**Comment by lrpereira** [comment]
Moreover, you'll be able to change this behavior by using `division_min_scale` SQL env var in the next MonetDB suite release.
`set division_min_scale=1`.
See, https://github.com/MonetDB/MonetDB/blob/master/sql/ChangeLog
