### ISSUE TITLE
A value is being returned with unnecessary scientific notation

### ISSUE THREAD

**Issue by djxandytche** [MonetDB/MonetDB#7593]
### Describe the bug

A value is being returned with unnecessary scientific notation.

### Reproduction steps

Just do what is shown in the image below (I'm using the MonetDB client - mclient.bat):
![image](https://github.com/user-attachments/assets/0ef9a408-3884-4cde-9344-f39ce1816873)

### Expected behavior

The returned value should be 202910.

### MonetDB release

11.51.3

### Executables source

Release packages

### Operating System

Windows 10

**Comment by mvdvm** [comment]
Your last query evaluates to type double, hence you probably get the scientific notation on MS Windows, mclient.

If you want to get a decimal representation output, you need to cast the expression to a decimal explicitly. For instance:
````
select cast(timestamp_to_str(localtimestamp, '%Y%m') + 500 as Decimal(6)) asDecimal;

select cast(timestamp_to_str(localtimestamp, '%Y%m') as Decimal(6)) + 500 asDecimal;
````

Also note that the term `asDecimal` in your query is interpreted as a label for the output column. It does not do any type conversion. Maybe you expected that?

In your query use case you probably can also convert it to an integer instead of a decimal type, as there are no decimals expected. So:
````
select cast(timestamp_to_str(localtimestamp, '%Y%m') + 500 as integer) asInt;
````

I closed this issue as the query result colum type is double, hence the scientific notation for large (>= 10000) values.
Adding a cast() resolves the output problem.

**Comment by djxandytche** [comment]
Hi Martin,

About "asDecimal": I know it's just the column's label.

I understood your explanation and your suggestion to use a cast to solve it.

However, this behavior was different in previous versions. See the images below:
![11 41 11](https://github.com/user-attachments/assets/d1b4a718-efcf-4902-aa68-db0cdf91b4cf)
![11 45 11](https://github.com/user-attachments/assets/70bb15f1-af28-4fa3-8306-a2dc593cad79)
![11 49 11](https://github.com/user-attachments/assets/0beeae11-1591-48c4-84a3-dfa1ad4733b5)
![11 51 3](https://github.com/user-attachments/assets/e451bde8-ed8f-4766-969e-ead2a98d831b)

Therefore, I believe that things that worked before will probably stop working.

Wouldn't it be better to keep the same behavior in all versions?

Thanks.

Alexandre.

**Comment by mvdvm** [comment]
In v11.51 some changes have been made to timestamp_to_str() implementation, see #7370 and  #7374.
I do not know if this also includes the presentation issue of a double value in mclient program.

I tried to reproduce this issue on Linux, Fedora 40.
When I run it from mclient , I get:
```
$ mclient
Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)
Database: MonetDB v11.51.6 (hg id: 23ee6b89110b), 'demo'
FOLLOW US on https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>select timestamp_to_str(localtimestamp - INTERVAL '1' DAY, '%Y%m') + 500 asDecimal;
+--------------------------+
| asdecimal                |
+==========================+
|                   202911 |
+--------------------------+
1 tuple
sql>
```

So this happens only on MS Windows?

In mclient you can use command '\X' to enable tracing. This shows how values are received from the server.
Next run the select query.
In my Linux mclient I get:
```
sql>\X
sql>select timestamp_to_str(localtimestamp - INTERVAL '1' DAY, '%Y%m') + 500 asDecimal;
mapi_query_part:84:select timestamp_to_str(localtimestamp - INTERVAL '1' DAY, '%Y%m') + 500 asDecimal;

fetch next block: start at:350
got next block: length:105
text:&1 2 1 1 1 6831 1067 428 55
% . # table_name
% asdecimal # name
% double # type
% 24 # length
[ 202911	]

got complete block: 
text:&1 2 1 1 1 6831 1067 428 55
% . # table_name
% asdecimal # name
% double # type
% 24 # length
[ 202911	]

read_line:&1 2 1 1 1 6831 1067 428 55
allocating new result set
got complete block: 
text:% . # table_name
% asdecimal # name
% double # type
% 24 # length
[ 202911	]

read_line:% . # table_name
got complete block: 
text:% asdecimal # name
% double # type
% 24 # length
[ 202911	]

read_line:% asdecimal # name
got complete block: 
text:% double # type
% 24 # length
[ 202911	]

read_line:% double # type
got complete block: 
text:% 24 # length
[ 202911	]

read_line:% 24 # length
got complete block: 
text:[ 202911	]

read_line:[ 202911	]
+--------------------------+
| asdecimal                |
+==========================+
|                   202911 |
fetch next block: start at:455
got next block: length:0
text:
got complete block: 
text:

read_line:
+--------------------------+
1 tuple
closing result set
sql>
```

Try it in your windows mclient and let me know if you get the same or different output.
Note: Use command '\X' again to disable tracing.

**Comment by djxandytche** [comment]
Hi Martin,

I don't know if this only happens on Windows.
I didn't test it on Linux because I don't use it and I don't know Linux.

But, I did the test again now and realized that if the result is 202911 (the same as the test you did), the problem doesn't occur.
But, if I make the result 202910, then the problem occurs.
See:
```
user(win32):monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Aug2024)
Database: MonetDB v11.51.3 (Aug2024), 'weknow'
FOLLOW US on https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>select timestamp_to_str(localtimestamp - INTERVAL '1' DAY, '%Y%m') + 500 asDecimal;
+--------------------------+
| asdecimal                |
+==========================+
|                   202911 |
+--------------------------+
1 tuple
sql>select timestamp_to_str(localtimestamp - INTERVAL '12' DAY, '%Y%m') + 500 asDecimal;
+--------------------------+
| asdecimal                |
+==========================+
|               2.0291e+05 |
+--------------------------+
1 tuple
sql>
``` 

I did the test with tracing enabled.
See the result:
```
user(win32):monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Aug2024)
Database: MonetDB v11.51.3 (Aug2024), 'weknow'
FOLLOW US on https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>\X
sql>select timestamp_to_str(localtimestamp - INTERVAL '12' DAY, '%Y%m') + 500 asDecimal;
mapi_query_part:85:select timestamp_to_str(localtimestamp - INTERVAL '12' DAY, '%Y%m') + 500 asDecimal;

fetch next block: start at:235
got next block: length:101
text:&1 1 1 1 1 18 0 0 0
% . # table_name
% asdecimal # name
% double # type
% 24 # length
[ 2.0291e+05    ]

got complete block:
text:&1 1 1 1 1 18 0 0 0
% . # table_name
% asdecimal # name
% double # type
% 24 # length
[ 2.0291e+05    ]

read_line:&1 1 1 1 1 18 0 0 0
allocating new result set
got complete block:
text:% . # table_name
% asdecimal # name
% double # type
% 24 # length
[ 2.0291e+05    ]

read_line:% . # table_name
got complete block:
text:% asdecimal # name
% double # type
% 24 # length
[ 2.0291e+05    ]

read_line:% asdecimal # name
got complete block:
text:% double # type
% 24 # length
[ 2.0291e+05    ]

read_line:% double # type
got complete block:
text:% 24 # length
[ 2.0291e+05    ]

read_line:% 24 # length
got complete block:
text:[ 2.0291e+05       ]

read_line:[ 2.0291e+05  ]
+--------------------------+
| asdecimal                |
+==========================+
|               2.0291e+05 |
fetch next block: start at:336
got next block: length:0
text:
got complete block:
text:☺

read_line:☺
+--------------------------+
1 tuple
closing result set
sql>
```

**Comment by mvdvm** [comment]
I can now (on 13 nov) reproduce it also on Linux:
```
sql>select timestamp_to_str(localtimestamp - INTERVAL '14' DAY, '%Y%m') + 500 asDecimal;
+--------------------------+
| asdecimal                |
+==========================+
|               2.0291e+05 |
+--------------------------+
1 tuple
sql>
```
It appears that when the value ends with a 0 (and larger than 9999), the scientific notation is used in mclient. The scientific notation is send by the server as can be seen from the tracing info.
I tested it also for more values.
It is not related to timestamp_to_str() function, as it also happens for doubles:
```
sql>select cast(202909 as double);
+--------------------------+
| %2                       |
+==========================+
|                   202909 |
+--------------------------+
1 tuple
sql>select cast(202910 as double);
+--------------------------+
| %2                       |
+==========================+
|               2.0291e+05 |
+--------------------------+
1 tuple
sql>select cast(202911 as double);
+--------------------------+
| %2                       |
+==========================+
|                   202911 |
+--------------------------+
1 tuple
sql>select cast(20290 as double);
+--------------------------+
| %2                       |
+==========================+
|                2.029e+04 |
+--------------------------+
1 tuple
sql>select cast(2020 as double);
+--------------------------+
| %2                       |
+==========================+
|                     2020 |
+--------------------------+
1 tuple
```

An more generative way to show this:
```
sql>select cast(value as double) from generate_series(9985, 10131) where value % 10 in (9,0,1);
+--------------------------+
| %3                       |
+==========================+
|                     9989 |
|                     9990 |
|                     9991 |
|                     9999 |
|                    1e+04 |
|                    10001 |
|                    10009 |
|                1.001e+04 |
|                    10011 |
|                    10019 |
|                1.002e+04 |
|                    10021 |
|                    10029 |
|                1.003e+04 |
|                    10031 |
|                    10039 |
|                1.004e+04 |
|                    10041 |
|                    10049 |
|                1.005e+04 |
|                    10051 |
|                    10059 |
|                1.006e+04 |
|                    10061 |
|                    10069 |
|                1.007e+04 |
|                    10071 |
|                    10079 |
|                1.008e+04 |
|                    10081 |
|                    10089 |
|                1.009e+04 |
|                    10091 |
|                    10099 |
|                 1.01e+04 |
|                    10101 |
|                    10109 |
|                1.011e+04 |
|                    10111 |
|                    10119 |
|                1.012e+04 |
|                    10121 |
|                    10129 |
|                1.013e+04 |
+--------------------------+
44 tuples
```
So it starts with the scientific notation with doubles of value 10000 or higher (or -10000 or lower) which end with a 0.

**Comment by sjoerdmullender** [comment]
The actual problem is that before, `select '202411' + 500;` resulted in a value of type bigint or hugeint, but now it results in a value of type double.  It has nothing to do with the `timestamp_to_str` implementation which just returns a string (aka varchar).

**Comment by sjoerdmullender** [comment]
I am closing this issue.
There is no guarantee that adding a string and an integer should result in an integer.  In this version, it results in a double since when the choice is made what type to produce, we need to choose the most capable type.
Output produced by the server now does not use scientific notation for floating point values (i.e. REAL and DOUBLE) if the value can be represented exactly by an integer.
Note, it is up to the application to interpret the value correctly.  The output is still marked in the protocol as float or double, and as such, the application must be prepared to accept float/double in any floating point format.  If the application needs an integer, the expression should be cast to an integer explicitly.
