### ISSUE TITLE
A sqlglot monetdb dialect

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7594]
### Is your feature request related to a problem? Describe it

Hello,

While you can use pymonetdb,the implementation of monetdb in tools developed in Python is far to be satisfying. The thing is the developers of these tools use packages such as ibis that itself uses sqlglot. So right now, support of Monetdb on softwares such as SQLMesh, etc (full list https://github.com/tobymao/sqlglot#used-by  )depends on sqlglot.

### Describe the solution you'd like to see implemented

A monetdb "dialect" for sqlglot. 

### Describe alternatives you've considered

Asking sqlglot team to support it but not in their priority. However, they will accept a PR.
https://github.com/tobymao/sqlglot/issues/4314

I understand that's not your software at all but it will help the MonetDB community and expand users base.

**Comment by mvdvm** [comment]
Hi Simon,

As this is an enhancement request for sqlglot, it should be fixed it that repository, not in MonetDB.

If you want [MonetDB Solutions](https://www.monetdbsolutions.com/) developers to implement this in sqlglot, please contact them.
