### ISSUE TITLE
COPY INTO from three or more files crashes the server.

### ISSUE THREAD

**Issue by sjoerdmullender** [MonetDB/MonetDB#7603]
### Describe the bug

COPY INTO should be able to handle more than one file in a single query.  When using three or more, the server crashes due to a NULL pointer dereference.

### Reproduction steps

Create a table.  Any table.  Let's call it x.
copy into x from '/dev/null', '/dev/null', '/dev/null';

### MonetDB release

Aug2024-SP1

### Executables source

Self compiled and installed

### Operating System

Fedora 41

**Comment by njnes** [comment]
was fixed by adding proper union expressions.
