### ISSUE TITLE
file_loader() causes server crash when csv file contains too few field separators or contains empty lines

### ISSUE THREAD

**Issue by mvdvm** [MonetDB/MonetDB#7604]
### Describe the bug

file_loader(data.csv) causes segmentation fault (crash of server) when csv file contains to few field separators or contains empty lines

### Reproduction steps

With data file `cars_missing_separators.csv` containing data:
```
2000,"Ford","Focus",1994
2001,"Honda",,
2004,"Tesla","S3XY",2019
2014,"Lightyear","0",2022
2020,"Volvo"
```
Note that the last line contains only data for the first two columns and 1 comma separator instead of 3, so no commas at the end of the line.

run query:
`select * from file_loader(r'$TSTSRCDIR/cars_missing_separators.csv') as cars(id, brand, model, "year");`

This causes a Segmentation fault in:
#0  0x00007fdcb93574eb in __strcmp_avx2 () from /lib64/libc.so.6
#1  0x00007fdca8de597b in detect_bool () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#2  0x00007fdca8de5fb0 in detect_types_row () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#3  0x00007fdca8de61ab in detect_types () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#4  0x00007fdca8de6a12 in csv_relation () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#5  0x00007fdcaa5e606b in file_loader_add_table_column_types () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15
#6  0x00007fdcaa5e6279 in rel_file_loader () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15
#7  0x00007fdcaa5e6d2b in rel_named_table_function () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15
#8  0x00007fdcaa5e968b in table_ref () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15

With data file `cars_empty_line.csv` containing data:
```
2000,"Ford","Focus",1994
2001,"Honda",,

2004,"Tesla","S3XY",2019
2014,"Lightyear","0",2022

```
This file contains an empty line at line 3 and line 6.

run query:
`select * from file_loader(r'$TSTSRCDIR/cars_empty_line.csv') as cars(id, brand, model, "year");`

This causes a Segmentation fault in:
Thread 1 (Thread 0x7f87e27866c0 (LWP 73107)):
#0  0x00007f883207c45a in next_delim () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#1  0x00007f883207cf31 in detect_types_row () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#2  0x00007f883207d1ab in detect_types () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#3  0x00007f883207da12 in csv_relation () from /home/mvd/dev/INSTALL/lib64/monetdb5-11.51.6/lib_csv.so
#4  0x00007f8831de606b in file_loader_add_table_column_types () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15
#5  0x00007f8831de6279 in rel_file_loader () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15
#6  0x00007f8831de6d2b in rel_named_table_function () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15
#7  0x00007f8831de968b in table_ref () from /home/mvd/dev/INSTALL/lib64/libmonetdbsql-11.51.6.so.15

### Expected behavior

No segmentation faults of course.
Also when field separators are missing on a line, this should be treated as missing values (NULL in SQL), so the line can be accepted.
Also empty lines should be allowed, it will have NULL for each field in the tuple.

### MonetDB release

MonetDB 5 server v11.51.6

### Executables source

Self compiled and installed

### Operating System

Fedora 41

**Comment by njnes** [comment]
was fixed by more sanity checks
