### ISSUE TITLE
Adding a column of serial type fails with "Access denied for <user> to schema 'sys'"

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7607]
### Describe the bug

A user fails to add a column of serial type to an existing table in its own schema.

### Reproduction steps

The following is executed with user `spinque`:
```sql
sql>set schema spinque;
operation successful

sql>create table t(a int);
operation successful

sql>alter table t add column b int;
operation successful

sql>alter table t add column c int auto_increment;
Access denied for spinque to schema 'sys'

sql>alter table t add column c serial;
Access denied for spinque to schema 'sys'
```

Note that this only fails when adding the column, not when the column is within the `create` statement:
```sql
sql>create table t(a int, b int auto_increment);
operation successful
```

### Expected behavior

The operation should be allowed

### MonetDB release

Aug2024

### Executables source

Self compiled and installed

### Operating System

Fedora 41

**Comment by swingbit** [comment]
I guess it tries to `create sequence` in schema `sys` ?

**Comment by sjoerdmullender** [comment]
The EXPLAIN is interesting:
```
    X_13:void := sqlcatalog.create_seq("spinque":str, "seq_7902":str, 0x7efe801948b0:ptr, 0:int);
...
    X_26:bat[:lng] := batsql.next_value(X_25:lng, "sys":str, "seq_7902":str);
```
It creates the sequence in the "spinque" schema but then uses it from the "sys" schema.

**Comment by njnes** [comment]
pushed a fix on aug2024.
